// Code generated by mockery v1.0.0. DO NOT EDIT.

package supervisord

import mock "github.com/stretchr/testify/mock"

// mockAlertFlagsProvider is an autogenerated mock type for the alertFlagsProvider type
type mockAlertFlagsProvider struct {
	mock.Mock
}

// ListAlertFlags provides a mock function with given fields:
func (_m *mockAlertFlagsProvider) ListAlertFlags() []string {
	ret := _m.Called()

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}
