// Code generated by go-swagger; DO NOT EDIT.

package metrics_names

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewMetricsNamesGetMetricsNamesParams creates a new MetricsNamesGetMetricsNamesParams object
// with the default values initialized.
func NewMetricsNamesGetMetricsNamesParams() *MetricsNamesGetMetricsNamesParams {
	var ()
	return &MetricsNamesGetMetricsNamesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewMetricsNamesGetMetricsNamesParamsWithTimeout creates a new MetricsNamesGetMetricsNamesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewMetricsNamesGetMetricsNamesParamsWithTimeout(timeout time.Duration) *MetricsNamesGetMetricsNamesParams {
	var ()
	return &MetricsNamesGetMetricsNamesParams{

		timeout: timeout,
	}
}

// NewMetricsNamesGetMetricsNamesParamsWithContext creates a new MetricsNamesGetMetricsNamesParams object
// with the default values initialized, and the ability to set a context for a request
func NewMetricsNamesGetMetricsNamesParamsWithContext(ctx context.Context) *MetricsNamesGetMetricsNamesParams {
	var ()
	return &MetricsNamesGetMetricsNamesParams{

		Context: ctx,
	}
}

// NewMetricsNamesGetMetricsNamesParamsWithHTTPClient creates a new MetricsNamesGetMetricsNamesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewMetricsNamesGetMetricsNamesParamsWithHTTPClient(client *http.Client) *MetricsNamesGetMetricsNamesParams {
	var ()
	return &MetricsNamesGetMetricsNamesParams{
		HTTPClient: client,
	}
}

/*MetricsNamesGetMetricsNamesParams contains all the parameters to send to the API endpoint
for the metrics names get metrics names operation typically these are written to a http.Request
*/
type MetricsNamesGetMetricsNamesParams struct {

	/*Body*/
	Body interface{}

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the metrics names get metrics names params
func (o *MetricsNamesGetMetricsNamesParams) WithTimeout(timeout time.Duration) *MetricsNamesGetMetricsNamesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the metrics names get metrics names params
func (o *MetricsNamesGetMetricsNamesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the metrics names get metrics names params
func (o *MetricsNamesGetMetricsNamesParams) WithContext(ctx context.Context) *MetricsNamesGetMetricsNamesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the metrics names get metrics names params
func (o *MetricsNamesGetMetricsNamesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the metrics names get metrics names params
func (o *MetricsNamesGetMetricsNamesParams) WithHTTPClient(client *http.Client) *MetricsNamesGetMetricsNamesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the metrics names get metrics names params
func (o *MetricsNamesGetMetricsNamesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the metrics names get metrics names params
func (o *MetricsNamesGetMetricsNamesParams) WithBody(body interface{}) *MetricsNamesGetMetricsNamesParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the metrics names get metrics names params
func (o *MetricsNamesGetMetricsNamesParams) SetBody(body interface{}) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *MetricsNamesGetMetricsNamesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
