{
 "title": "Disk Details",
 "tags": [
  "OS",
  "Percona"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "region",
    "label": "Region",
    "query": {
     "query": "label_values(node_load1{node_type=~\"generic|remote_rds|container|remote\"}, region)"
    }
   },
   {
    "name": "node_type",
    "label": "Type",
    "query": {
     "query": "label_values(up{region=~\"$region\"}, node_type)"
    }
   },
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values({region=~\"$region\",node_type=~\"$node_type\",__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions|up\"}, environment)"
    }
   },
   {
    "name": "node_name",
    "label": "Node Name",
    "query": {
     "query": "label_values(up{region=~\"$region\",node_type=~\"$node_type\",environment=~\"$environment\"}, node_name)"
    }
   },
   {
    "name": "device",
    "label": "Device",
    "query": {
     "query": "label_values({__name__=~\"node_disk_reads_completed_total|rdsosmetrics_diskIO_util\",node_name=~\"$node_name\", device!~\"dm-.+\"}, device)"
    }
   },
   {
    "name": "username",
    "label": "Username",
    "query": {
     "query": "label_values(mysql_info_schema_user_statistics_connected_time_seconds_total{service_name=\"$service_name\"},user)"
    }
   },
   {
    "name": "mountpoint",
    "label": "Mountpoint",
    "query": {
     "query": "label_values(node_filesystem_avail_bytes{node_name=~\"$node_name\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"}, mountpoint)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Disk Space", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Mountpoint Usage",
   "type": "timeseries",
   "description": "Shows the percentage of disk space utilization for every mountpoint defined on the system. Having some of the mountpoints close to 100% space utilization is not good because of the risk to have a “disk full” error that can block one of the services or even cause a crash of the entire system.\n\nIn case when the mountpoint is close to 100% consider to remove unused files or to expand the space allocated to the mountpoint.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by (node_name,mountpoint) (1 - (max_over_time(node_filesystem_free_bytes{node_name=~\"$node_name\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"}[$interval]) or max_over_time(node_filesystem_free_bytes{node_name=~\"$node_name\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"}[5m])) / \n(max_over_time(node_filesystem_size_bytes{node_name=~\"$node_name\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"}[$interval]) or\nmax_over_time(node_filesystem_size_bytes{node_name=~\"$node_name\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"}[5m])))",
     "legendFormat": "{{mountpoint}}"
    },
    {
     "expr": "avg by (node_name) (azure_storage_percent_average{node_name=~\"$node_name\"}/100)",
     "legendFormat": "Azure Storage"
    }
   ]
  },
  {
   "title": "Mountpoint $mountpoint",
   "type": "timeseries",
   "description": "Shows information about the disk space usage of the specified mountpoint.\n\n**Used** is the amount of space used.\n\n**Free** is the amount of space not in use.\n\n**Used+Free** is the total disk space allocated to the mountpoint.\n\nHaving *Free* close to 0 B is not good because of the risk to have a “disk full” error that can block one of the services or even cause a crash of the entire system.\n\nIn case Free is close to 0 B consider to remove unused files or to expand the space allocated to the mountpoint.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "repeat": "mountpoint",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (node_name,device,fstype,mountpoint) ((max_over_time(node_filesystem_size_bytes{node_name=~\"$node_name\",mountpoint=~\"$mountpoint\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"}[$interval]) or max_over_time(node_filesystem_size_bytes{node_name=~\"$node_name\",mountpoint=~\"$mountpoint\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"}[5m])) - (max_over_time(node_filesystem_free_bytes{node_name=~\"$node_name\",mountpoint=~\"$mountpoint\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"}[$interval]) or max_over_time(node_filesystem_free_bytes{node_name=~\"$node_name\",mountpoint=~\"$mountpoint\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"}[5m])))",
     "legendFormat": "Used (device {{ device }}, {{ fstype }})"
    },
    {
     "expr": "avg by (node_name,device,fstype,mountpoint) (max_over_time(node_filesystem_free_bytes{node_name=~\"$node_name\", mountpoint=\"$mountpoint\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"}[$interval]) or max_over_time(node_filesystem_free_bytes{node_name=~\"$node_name\", mountpoint=\"$mountpoint\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"}[5m]) or (storage_limit_bytes_average{node_name=~\"$node_name\"} - azure_storage_used_bytes_average{node_name=~\"$node_name\"}))",
     "legendFormat": "Free (device {{ device }}, {{ fstype }})"
    },
    {
     "expr": "avg by (node_name,device,fstype,mountpoint) ((max_over_time(node_filesystem_size_bytes{node_name=~\"$node_name\",mountpoint=~\"$mountpoint\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"}[$interval]) or max_over_time(node_filesystem_size_bytes{node_name=~\"$node_name\",mountpoint=~\"$mountpoint\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"}[5m])))",
     "legendFormat": "Total (device {{ device }}, {{ fstype }})"
    },
    {
     "expr": "avg by (node_name) (node_filesystem_size_bytes{node_name=~\"$node_name\"} - azure_storage_used_bytes_average{node_name=~\"$node_name\"})",
     "legendFormat": "Free (Azure Storage)"
    },
    {
     "expr": "avg by (node_name) (azure_storage_used_bytes_average{node_name=~\"$node_name\"})",
     "legendFormat": "Used (Azure Storage)"
    }
   ]
  },
  { "title": "Total Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Disk Latency",
   "type": "timeseries",
   "description": "Shows average latency for Reads and Writes IO Devices.  Higher than typical latency for highly loaded storage indicates saturation (overload) and is frequent cause of performance problems.  Higher than normal latency also can indicate internal storage problems.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum(\n(rate(node_disk_read_time_seconds_total{device=~\"$device\", node_name=\"$node_name\"}[$interval]) / \nrate(node_disk_reads_completed_total{device=~\"$device\", node_name=\"$node_name\"}[$interval])) > 0 or \n(irate(node_disk_read_time_seconds_total{device=~\"$device\", node_name=\"$node_name\"}[5m]) / \nirate(node_disk_reads_completed_total{device=~\"$device\", node_name=\"$node_name\"}[5m])) > 0 or\navg_over_time(aws_rds_read_latency_average{node_name=\"$node_name\"}[$interval])/1000 or \navg_over_time(aws_rds_read_latency_average{node_name=\"$node_name\"}[5m])/1000 or\navg_over_time(rdsosmetrics_diskIO_readLatency{node_name=\"$node_name\"}[$interval])/1000 or \navg_over_time(rdsosmetrics_diskIO_readLatency{node_name=\"$node_name\"}[5m])/1000 or vector(0)\n)",
     "legendFormat": "Read"
    },
    {
     "calculatedInterval": "2m",
     "expr": "sum(\n(rate(node_disk_write_time_seconds_total{device=~\"$device\", node_name=\"$node_name\"}[$interval]) / \nrate(node_disk_writes_completed_total{device=~\"$device\", node_name=\"$node_name\"}[$interval])) > 0 or \n(irate(node_disk_write_time_seconds_total{device=~\"$device\", node_name=\"$node_name\"}[5m]) / \nirate(node_disk_writes_completed_total{device=~\"$device\", node_name=\"$node_name\"}[5m])) > 0 or \n(avg_over_time(aws_rds_write_latency_average{node_name=\"$node_name\"}[$interval])/1000 or \navg_over_time(aws_rds_write_latency_average{node_name=\"$node_name\"}[5m])/1000) or\n(avg_over_time(rdsosmetrics_diskIO_writeLatency{node_name=\"$node_name\"}[$interval])/1000 or \navg_over_time(rdsosmetrics_diskIO_writeLatency{node_name=\"$node_name\"}[5m])/1000)\n)",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Disk Operations",
   "type": "timeseries",
   "description": "Shows amount of physical IOs (reads and writes) different devices are serving. Spikes in number of IOs served often corresponds to performance problems due to IO subsystem overload.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (node_name) (sum(\n(rate(node_disk_reads_completed_total{device=~\"$device\", node_name=\"$node_name\"}[$interval]) or \nirate(node_disk_reads_completed_total{device=~\"$device\", node_name=\"$node_name\"}[5m])) or\n(max_over_time(rdsosmetrics_diskIO_readIOsPS{node_name=\"$node_name\"}[$interval]) or\nmax_over_time(rdsosmetrics_diskIO_readIOsPS{node_name=\"$node_name\"}[5m])) \n))",
     "legendFormat": "Read"
    },
    {
     "calculatedInterval": "2m",
     "expr": "avg by (node_name) (sum(\n(rate(node_disk_writes_completed_total{device=~\"$device\", node_name=\"$node_name\"}[$interval])) or \nirate(node_disk_writes_completed_total{device=~\"$device\", node_name=\"$node_name\"}[5m])) or\n(max_over_time(rdsosmetrics_diskIO_writeIOsPS{node_name=\"$node_name\"}[$interval]) or\nmax_over_time(rdsosmetrics_diskIO_writeIOsPS{node_name=\"$node_name\"}[5m]) \n))",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Disk Bandwidth",
   "type": "timeseries",
   "description": "Shows volume of reads and writes the storage is handling. This can be better measure of IO capacity usage for network attached and SSD storage as it is often bandwidth limited.  Amount of data being written to the disk can be used to estimate Flash storage life time.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum(rate(node_disk_written_bytes_total{node_name=~\"$node_name\",device=~\"$device\"}[$interval]) or \nirate(node_disk_written_bytes_total{node_name=~\"$node_name\",device=~\"$device\"}[5m]) or\nrate(node_disk_written_bytes_total{node_name=~\"$node_name\",node_type=\"remote_rds\"}[$interval]) or \nirate(node_disk_written_bytes_total{node_name=~\"$node_name\",node_type=\"remote_rds\"}[5m]))",
     "legendFormat": "Write"
    },
    {
     "expr": "sum(rate(node_disk_read_bytes_total{node_name=~\"$node_name\",device=~\"$device\"}[$interval]) or \nirate(node_disk_read_bytes_total{node_name=~\"$node_name\",device=~\"$device\"}[5m]) or\nrate(node_disk_read_bytes_total{node_name=~\"$node_name\",node_type=\"remote_rds\"}[$interval]) or \nirate(node_disk_read_bytes_total{node_name=~\"$node_name\",node_type=\"remote_rds\"}[5m]))",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "Average Queue Depth",
   "type": "timeseries",
   "description": "This indicates the average number of operations waiting to be serviced. Note that some devices, like SSDs, need to have multiple outstanding requests in order to achieve maximum throughput",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum(rate(node_disk_io_time_weighted_seconds_total{node_name=~\"$node_name\",device=~\"$device\"}[$interval]) or \nirate(node_disk_io_time_weighted_seconds_total{node_name=~\"$node_name\",device=~\"$device\"}[5m]) or\nrate(rdsosmetrics_diskIO_diskQueueDepth{node_name=~\"$node_name\"}[$interval]) or \nirate(rdsosmetrics_diskIO_diskQueueDepth{node_name=~\"$node_name\"}[5m]))",
     "legendFormat": "Operations"
    }
   ]
  },
  {
   "title": "Disk IO Utilization",
   "type": "timeseries",
   "description": "Shows disk Utilization as a percentage of the time when there was at least one IO request in flight. It is designed to match utilization available in iostat tool. The graph augments the IO latency and Disk Load Graphs, allowing to determine if the disk load was evenly distributed in time or consuming the IO momentarily. Higher utilization increases the likeliness of IO queuing. Always consider this metric along with response time and IO queue depth.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (node_name) (rate(node_disk_io_time_seconds_total{device=~\"$device\",node_name=~\"$node_name\"}[$interval]) or irate(node_disk_io_time_seconds_total{device=~\"$device\",node_name=~\"$node_name\"}[5m]) or\n(max_over_time(rdsosmetrics_diskIO_util{device=~\"$device\",node_name=~\"$node_name\"}[$interval]) or max_over_time(rdsosmetrics_diskIO_util{device=~\"$device\",node_name=~\"$node_name\"}[5m]))/100)",
     "legendFormat": "Util"
    }
   ]
  },
  {
   "title": "Disk Load",
   "type": "timeseries",
   "description": "Shows how much disk was loaded for reads or writes as average number of outstanding requests at different period of time.  High disk load is a good measure of actual storage utilization. Different storage types handle load differently - some will show latency increases on low loads others can handle higher load with no problems.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum(\nrate(node_disk_write_time_seconds_total{device=~\"$device\",node_name=~\"$node_name\"}[$interval]) or \nirate(node_disk_write_time_seconds_total{device=~\"$device\",node_name=~\"$node_name\"}[5m]) or\nmax_over_time(rdsosmetrics_diskIO_writeIOsPS{node_name=~\"$node_name\"}[$interval]) or \nmax_over_time(rdsosmetrics_diskIO_writeIOsPS{node_name=~\"$node_name\"}[5m])\n)",
     "legendFormat": "Write"
    },
    {
     "expr": "sum(rate(node_disk_read_time_seconds_total{device=~\"$device\",node_name=~\"$node_name\"}[$interval]) or \nirate(node_disk_read_time_seconds_total{device=~\"$device\",node_name=~\"$node_name\"}[5m]) or\nmax_over_time(rdsosmetrics_diskIO_readIOsPS{node_name=~\"$node_name\"}[$interval]) or \nmax_over_time(rdsosmetrics_diskIO_readIOsPS{node_name=~\"$node_name\"}[5m]))",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "Disk IO Size",
   "type": "timeseries",
   "description": "Shows average size of a single disk operation.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum(\n(rate(node_disk_read_bytes_total{node_name=\"$node_name\", device=~\"$device\"}[$interval]) / \nrate(node_disk_reads_completed_total{node_name=\"$node_name\", device=~\"$device\"}[$interval])) > 0 or \n(irate(node_disk_read_bytes_total{node_name=\"$node_name\", device=~\"$device\"}[5m]) / \nirate(node_disk_reads_completed_total{node_name=\"$node_name\", device=~\"$device\"}[5m])) > 0\n) ",
     "legendFormat": "Read size"
    },
    {
     "calculatedInterval": "2m",
     "expr": "sum(\n(rate(node_disk_written_bytes_total{node_name=\"$node_name\", device=~\"$device\"}[$interval]) / \nrate(node_disk_writes_completed_total{node_name=\"$node_name\", device=~\"$device\"}[$interval])) > 0 or \n(irate(node_disk_written_bytes_total{node_name=\"$node_name\", device=~\"$device\"}[5m]) / \nirate(node_disk_writes_completed_total{node_name=\"$node_name\", device=~\"$device\"}[5m])) > 0\n) ",
     "legendFormat": "Write size"
    }
   ]
  },
  {
   "title": "Avg Disks Operations Merge Ratio",
   "type": "timeseries",
   "description": "Shows how effectively Operating System is able to merge logical IO requests into physical requests.  This is a good measure of the IO locality which can be used for workload characterization.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg(\n(1 + rate(node_disk_reads_merged_total{device=~\"$device\", node_name=\"$node_name\"}[$interval]) / rate(node_disk_reads_completed_total{device=~\"$device\", node_name=\"$node_name\"}[$interval])) > 0 or (1 + irate(node_disk_reads_merged_total{device=~\"$device\", node_name=\"$node_name\"}[5m]) / irate(node_disk_reads_completed_total{device=~\"$device\", node_name=\"$node_name\"}[5m])) > 0\n)",
     "legendFormat": "Read Ratio"
    },
    {
     "calculatedInterval": "2m",
     "expr": "avg(\n(1 + rate(node_disk_writes_merged_total{device=~\"$device\", node_name=\"$node_name\"}[$interval]) / rate(node_disk_writes_completed_total{device=~\"$device\", node_name=\"$node_name\"}[$interval])) > 0 or (1 + irate(node_disk_writes_merged_total{device=~\"$device\", node_name=\"$node_name\"}[5m]) / irate(node_disk_writes_completed_total{device=~\"$device\", node_name=\"$node_name\"}[5m])) > 0\n)",
     "legendFormat": "Write Ratio"
    }
   ]
  },
  {
   "title": "Device $device",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "repeat": "device",
   "collapsed": true,
   "panels": [
    {
     "title": "$device - Disk Latency",
     "type": "timeseries",
     "description": "Shows average latency for Reads and Writes IO Devices.  Higher than typical latency for highly loaded storage indicates saturation (overload) and is frequent cause of performance problems.  Higher than normal latency also can indicate internal storage problems.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (node_name,device) ((rate(node_disk_read_time_seconds_total{device=~\"$device\", node_name=\"$node_name\"}[$interval]) / \nrate(node_disk_reads_completed_total{device=~\"$device\", node_name=\"$node_name\"}[$interval])) > 0 or \n(irate(node_disk_read_time_seconds_total{device=~\"$device\", node_name=\"$node_name\"}[5m]) / \nirate(node_disk_reads_completed_total{device=~\"$device\", node_name=\"$node_name\"}[5m])) > 0 or\navg_over_time(aws_rds_read_latency_average{node_name=\"$node_name\"}[$interval])/1000 or \navg_over_time(aws_rds_read_latency_average{node_name=\"$node_name\"}[5m])/1000 or\navg_over_time(rdsosmetrics_diskIO_readLatency{node_name=\"$node_name\"}[$interval])/1000 or \navg_over_time(rdsosmetrics_diskIO_readLatency{node_name=\"$node_name\"}[5m])/1000)",
       "legendFormat": "Read: {{device}}"
      },
      {
       "calculatedInterval": "2m",
       "expr": "avg by (node_name,device) ((rate(node_disk_write_time_seconds_total{device=~\"$device\", node_name=\"$node_name\"}[$interval]) / \nrate(node_disk_writes_completed_total{device=~\"$device\", node_name=\"$node_name\"}[$interval])) > 0 or \n(irate(node_disk_write_time_seconds_total{device=~\"$device\", node_name=\"$node_name\"}[5m]) / \nirate(node_disk_writes_completed_total{device=~\"$device\", node_name=\"$node_name\"}[5m])) > 0 or \n(avg_over_time(aws_rds_write_latency_average{node_name=\"$node_name\"}[$interval])/1000 or \navg_over_time(aws_rds_write_latency_average{node_name=\"$node_name\"}[5m])/1000) or\n(avg_over_time(rdsosmetrics_diskIO_writeLatency{node_name=\"$node_name\"}[$interval])/1000 or \navg_over_time(rdsosmetrics_diskIO_writeLatency{node_name=\"$node_name\"}[5m])/1000))",
       "legendFormat": "Write: {{device}}"
      }
     ]
    },
    {
     "title": "$device - Disk Operations",
     "type": "timeseries",
     "description": "Shows amount of physical IOs (reads and writes) different devices are serving. Spikes in number of IOs served often corresponds to performance problems due to IO subsystem overload.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (node_name,device) ((rate(node_disk_reads_completed_total{device=~\"$device\", node_name=\"$node_name\"}[$interval]) or \nirate(node_disk_reads_completed_total{device=~\"$device\", node_name=\"$node_name\"}[5m])) or\n(max_over_time(rdsosmetrics_diskIO_readIOsPS{device=~\"$device\",node_name=\"$node_name\"}[$interval]) or\nmax_over_time(rdsosmetrics_diskIO_readIOsPS{device=~\"$device\",node_name=\"$node_name\"}[5m]))) ",
       "legendFormat": "Read: {{ device }}"
      },
      {
       "calculatedInterval": "2m",
       "expr": "avg by (node_name,device) ((rate(node_disk_writes_completed_total{device=~\"$device\", node_name=\"$node_name\"}[$interval]) or \nirate(node_disk_writes_completed_total{device=~\"$device\", node_name=\"$node_name\"}[5m])) or\n(max_over_time(rdsosmetrics_diskIO_writeIOsPS{device=~\"$device\",node_name=\"$node_name\"}[$interval]) or\nmax_over_time(rdsosmetrics_diskIO_writeIOsPS{device=~\"$device\",node_name=\"$node_name\"}[5m]))) ",
       "legendFormat": "Write: {{ device }}"
      }
     ]
    },
    {
     "title": "$device - Disk Bandwidth",
     "type": "timeseries",
     "description": "Shows volume of reads and writes the storage is handling. This can be better measure of IO capacity usage for network attached and SSD storage as it is often bandwidth limited.  Amount of data being written to the disk can be used to estimate Flash storage life time.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (node_name,device) ((rate(node_disk_read_bytes_total{device=~\"$device\", node_name=\"$node_name\"}[$interval]) or \nirate(node_disk_read_bytes_total{device=~\"$device\", node_name=\"$node_name\"}[5m])) or\n(rate(rdsosmetrics_diskIO_readThroughput{device=~\"$device\",node_name=\"$node_name\"}[$interval]) or\nirate(rdsosmetrics_diskIO_readThroughput{device=~\"$device\",node_name=\"$node_name\"}[5m])))",
       "legendFormat": "Read: {{ device }}"
      },
      {
       "calculatedInterval": "2m",
       "expr": "avg by (node_name,device) (rate(node_disk_written_bytes_total{device=~\"$device\", node_name=\"$node_name\"}[$interval]) or \nirate(node_disk_written_bytes_total{device=~\"$device\", node_name=\"$node_name\"}[5m]) or\n(rate(rdsosmetrics_diskIO_writeThroughput{device=~\"$device\",node_name=\"$node_name\"}[$interval]) or\nirate(rdsosmetrics_diskIO_writeThroughput{device=~\"$device\",node_name=\"$node_name\"}[5m])))",
       "legendFormat": "Write: {{ device }}"
      }
     ]
    },
    {
     "title": "$device - Average Queue Depth",
     "type": "timeseries",
     "description": "This indicates the average number of operations waiting to be serviced. Note that some devices, like SSDs, need to have multiple outstanding requests in order to achieve maximum throughput",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (node_name,device) ((rate(node_disk_io_time_weighted_seconds_total{device=~\"$device\", node_name=\"$node_name\"}[$interval]) or \nirate(node_disk_io_time_weighted_seconds_total{device=~\"$device\", node_name=\"$node_name\"}[5m])) or\n(rate(rdsosmetrics_diskIO_diskQueueDepth{device=~\"$device\", node_name=\"$node_name\"}[$interval]) or\nirate(rdsosmetrics_diskIO_diskQueueDepth{device=~\"$device\", node_name=\"$node_name\"}[5m])))",
       "legendFormat": "Operations: {{ device }}"
      }
     ]
    },
    {
     "title": "$device - Disk IO Utilization",
     "type": "timeseries",
     "description": "Shows disk Utilization as a percentage of the time when there was at least one IO request in flight. It is designed to match utilization available in iostat tool. The graph augments the IO latency and Disk Load Graphs, allowing to determine if the disk load was evenly distributed in time or consuming the IO momentarily. Higher utilization increases the likeliness of IO queuing. Always consider this metric along with response time and IO queue depth.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (node_name,device) (rate(node_disk_io_time_seconds_total{device=~\"$device\",node_name=~\"$node_name\"}[$interval]) or irate(node_disk_io_time_seconds_total{device=~\"$device\",node_name=~\"$node_name\"}[5m]) or\n(max_over_time(rdsosmetrics_diskIO_util{device=~\"$device\",node_name=~\"$node_name\"}[$interval]) or max_over_time(rdsosmetrics_diskIO_util{device=~\"$device\",node_name=~\"$node_name\"}[5m]))/100)",
       "legendFormat": "Util: {{ device }}"
      }
     ]
    },
    {
     "title": "$device - Disk Load",
     "type": "timeseries",
     "description": "Shows how much disk was loaded for reads or writes as average number of outstanding requests at different period of time.  High disk load is a good measure of actual storage utilization. Different storage types handle load differently - some will show latency increases on low loads others can handle higher load with no problems.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (node_name,device) (rate(node_disk_read_time_seconds_total{device=~\"$device\",node_name=~\"$node_name\"}[$interval]) or \nirate(node_disk_read_time_seconds_total{device=~\"$device\",node_name=~\"$node_name\"}[5m]) or\nmax_over_time(rdsosmetrics_diskIO_readIOsPS{device=~\"$device\",node_name=~\"$node_name\"}[$interval]) or \nmax_over_time(rdsosmetrics_diskIO_readIOsPS{device=~\"$device\",node_name=~\"$node_name\"}[5m]))",
       "legendFormat": "Read: {{ device }}"
      },
      {
       "calculatedInterval": "2m",
       "expr": "avg by (node_name,device) (rate(node_disk_write_time_seconds_total{device=~\"$device\",node_name=~\"$node_name\"}[$interval]) or \nirate(node_disk_write_time_seconds_total{device=~\"$device\",node_name=~\"$node_name\"}[5m]) or\nmax_over_time(rdsosmetrics_diskIO_writeIOsPS{device=~\"$device\",node_name=~\"$node_name\"}[$interval]) or \nmax_over_time(rdsosmetrics_diskIO_writeIOsPS{device=~\"$device\",node_name=~\"$node_name\"}[5m]))",
       "legendFormat": "Write: {{ device }}"
      }
     ]
    },
    {
     "title": "$device - Disk IO Size",
     "type": "timeseries",
     "description": "Shows average size of a single disk operation.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (node_name,device) (\n(rate(node_disk_read_bytes_total{node_name=\"$node_name\", device=~\"$device\"}[$interval]) / rate(node_disk_reads_completed_total{node_name=\"$node_name\", device=~\"$device\"}[$interval])) > 0 or (irate(node_disk_read_bytes_total{node_name=\"$node_name\", device=~\"$device\"}[5m]) / irate(node_disk_reads_completed_total{node_name=\"$node_name\", device=~\"$device\"}[5m])) > 0\n) ",
       "legendFormat": "Read size: {{ device }}"
      },
      {
       "calculatedInterval": "2m",
       "expr": "avg by (node_name,device) (\n(rate(node_disk_written_bytes_total{node_name=\"$node_name\", device=~\"$device\"}[$interval]) / rate(node_disk_writes_completed_total{node_name=\"$node_name\", device=~\"$device\"}[$interval])) > 0 or (irate(node_disk_written_bytes_total{node_name=\"$node_name\", device=~\"$device\"}[5m]) / irate(node_disk_writes_completed_total{node_name=\"$node_name\", device=~\"$device\"}[5m])) > 0\n) ",
       "legendFormat": "Write size: {{ device }}"
      }
     ]
    },
    {
     "title": "$device - Disk Operations Merge Ratio",
     "type": "timeseries",
     "description": "Shows how effectively Operating System is able to merge logical IO requests into physical requests.  This is a good measure of the IO locality which can be used for workload characterization.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (node_name,device) (\n(1 + rate(node_disk_reads_merged_total{device=~\"$device\", node_name=\"$node_name\"}[$interval]) / rate(node_disk_reads_completed_total{device=~\"$device\", node_name=\"$node_name\"}[$interval])) > 0 or (1 + irate(node_disk_reads_merged_total{device=~\"$device\", node_name=\"$node_name\"}[5m]) / irate(node_disk_reads_completed_total{device=~\"$device\", node_name=\"$node_name\"}[5m])) > 0 \n)",
       "legendFormat": "Read Ratio: {{ device }}"
      },
      {
       "calculatedInterval": "2m",
       "expr": "avg by (node_name,device) (\n(1 + rate(node_disk_writes_merged_total{device=~\"$device\", node_name=\"$node_name\"}[$interval]) / rate(node_disk_writes_completed_total{device=~\"$device\", node_name=\"$node_name\"}[$interval])) > 0 or (1 + irate(node_disk_writes_merged_total{device=~\"$device\", node_name=\"$node_name\"}[5m]) / irate(node_disk_writes_completed_total{device=~\"$device\", node_name=\"$node_name\"}[5m])) > 0\n)",
       "legendFormat": "Write Ratio: {{ device }}"
      }
     ]
    }
   ]
  }
 ]
}