// Code generated by gopkg.in/reform.v1. DO NOT EDIT.

package models

import (
	"fmt"
	"strings"

	"gopkg.in/reform.v1"
	"gopkg.in/reform.v1/parse"
)

type userRolesViewType struct {
	s parse.StructInfo
	z []interface{}
}

// Schema returns a schema name in SQL database ("").
func (v *userRolesViewType) Schema() string {
	return v.s.SQLSchema
}

// Name returns a view or table name in SQL database ("user_roles").
func (v *userRolesViewType) Name() string {
	return v.s.SQLName
}

// Columns returns a new slice of column names for that view or table in SQL database.
func (v *userRolesViewType) Columns() []string {
	return []string{
		"user_id",
		"role_id",
		"created_at",
		"updated_at",
	}
}

// NewStruct makes a new struct for that view or table.
func (v *userRolesViewType) NewStruct() reform.Struct {
	return new(UserRoles)
}

// UserRolesView represents user_roles view or table in SQL database.
var UserRolesView = &userRolesViewType{
	s: parse.StructInfo{
		Type:    "UserRoles",
		SQLName: "user_roles",
		Fields: []parse.FieldInfo{
			{Name: "UserID", Type: "int", Column: "user_id"},
			{Name: "RoleID", Type: "uint32", Column: "role_id"},
			{Name: "CreatedAt", Type: "time.Time", Column: "created_at"},
			{Name: "UpdatedAt", Type: "time.Time", Column: "updated_at"},
		},
		PKFieldIndex: -1,
	},
	z: new(UserRoles).Values(),
}

// String returns a string representation of this struct or record.
func (s UserRoles) String() string {
	res := make([]string, 4)
	res[0] = "UserID: " + reform.Inspect(s.UserID, true)
	res[1] = "RoleID: " + reform.Inspect(s.RoleID, true)
	res[2] = "CreatedAt: " + reform.Inspect(s.CreatedAt, true)
	res[3] = "UpdatedAt: " + reform.Inspect(s.UpdatedAt, true)
	return strings.Join(res, ", ")
}

// Values returns a slice of struct or record field values.
// Returned interface{} values are never untyped nils.
func (s *UserRoles) Values() []interface{} {
	return []interface{}{
		s.UserID,
		s.RoleID,
		s.CreatedAt,
		s.UpdatedAt,
	}
}

// Pointers returns a slice of pointers to struct or record fields.
// Returned interface{} values are never untyped nils.
func (s *UserRoles) Pointers() []interface{} {
	return []interface{}{
		&s.UserID,
		&s.RoleID,
		&s.CreatedAt,
		&s.UpdatedAt,
	}
}

// View returns View object for that struct.
func (s *UserRoles) View() reform.View {
	return UserRolesView
}

// check interfaces
var (
	_ reform.View   = UserRolesView
	_ reform.Struct = (*UserRoles)(nil)
	_ fmt.Stringer  = (*UserRoles)(nil)
)

func init() {
	parse.AssertUpToDate(&UserRolesView.s, new(UserRoles))
}
