// Code generated by go-swagger; DO NOT EDIT.

package user_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewSnoozeUpdateParams creates a new SnoozeUpdateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSnoozeUpdateParams() *SnoozeUpdateParams {
	return &SnoozeUpdateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSnoozeUpdateParamsWithTimeout creates a new SnoozeUpdateParams object
// with the ability to set a timeout on a request.
func NewSnoozeUpdateParamsWithTimeout(timeout time.Duration) *SnoozeUpdateParams {
	return &SnoozeUpdateParams{
		timeout: timeout,
	}
}

// NewSnoozeUpdateParamsWithContext creates a new SnoozeUpdateParams object
// with the ability to set a context for a request.
func NewSnoozeUpdateParamsWithContext(ctx context.Context) *SnoozeUpdateParams {
	return &SnoozeUpdateParams{
		Context: ctx,
	}
}

// NewSnoozeUpdateParamsWithHTTPClient creates a new SnoozeUpdateParams object
// with the ability to set a custom HTTPClient for a request.
func NewSnoozeUpdateParamsWithHTTPClient(client *http.Client) *SnoozeUpdateParams {
	return &SnoozeUpdateParams{
		HTTPClient: client,
	}
}

/*
SnoozeUpdateParams contains all the parameters to send to the API endpoint

	for the snooze update operation.

	Typically these are written to a http.Request.
*/
type SnoozeUpdateParams struct {
	// Body.
	Body SnoozeUpdateBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the snooze update params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SnoozeUpdateParams) WithDefaults() *SnoozeUpdateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the snooze update params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SnoozeUpdateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the snooze update params
func (o *SnoozeUpdateParams) WithTimeout(timeout time.Duration) *SnoozeUpdateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the snooze update params
func (o *SnoozeUpdateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the snooze update params
func (o *SnoozeUpdateParams) WithContext(ctx context.Context) *SnoozeUpdateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the snooze update params
func (o *SnoozeUpdateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the snooze update params
func (o *SnoozeUpdateParams) WithHTTPClient(client *http.Client) *SnoozeUpdateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the snooze update params
func (o *SnoozeUpdateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the snooze update params
func (o *SnoozeUpdateParams) WithBody(body SnoozeUpdateBody) *SnoozeUpdateParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the snooze update params
func (o *SnoozeUpdateParams) SetBody(body SnoozeUpdateBody) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *SnoozeUpdateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
