---
# See usage instructions in the root docker-compose.yml.
services:

  pmm-server:
    profiles:
      - pmm    
    container_name: pmm-server
    image: perconalab/pmm-server:3-dev-latest
    restart: always
    depends_on:
      clickhouse:
        condition: service_healthy    
    environment:
      - PMM_CLICKHOUSE_ADDR=clickhouse:9000
      - PMM_CLICKHOUSE_DATABASE=pmm
      - PMM_CLICKHOUSE_USER=default
      - PMM_CLICKHOUSE_PASSWORD=clickhouse
      - PMM_DISABLE_BUILTIN_CLICKHOUSE=1

  clickhouse:
    profiles:
      - pmm    
    image: clickhouse/clickhouse-server:25.3.6.56
    container_name: clickhouse
    environment:
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8123/ping"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    ports:
      - 9000:9000
