apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pmm-headless.fullname" . }}-perses-provisioning
  labels:
    {{- include "pmm-headless.labels" . | nindent 4 }}
data:
  project.json: |
    {
      "kind": "Project",
      "metadata": { "name": "default" }
    }
  datasource.json: |
    {
      "kind": "Datasource",
      "metadata": {
        "name": "VictoriaMetrics",
        "project": "default"
      },
      "spec": {
        "default": true,
        "plugin": {
          "kind": "PrometheusDatasource",
          "spec": {
            "proxy": {
              "kind": "HTTPProxy",
              "spec": {
                "url": "http://{{ include "pmm-headless.fullname" . }}.{{ .Release.Namespace }}/prometheus"
              }
            }
          }
        }
      }
    }
