apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "pmm-headless.fullname" . }}-clickhouse-data
  labels:
    {{- include "pmm-headless.labels" . | nindent 4 }}
    component: clickhouse
spec:
  accessModes:
    - ReadWriteOnce
  {{- include "pmm-headless.storageClass" (dict "component" .Values.pmmServer.persistence.clickhouse "global" .Values.global) | nindent 2 }}
  resources:
    requests:
      storage: {{ .Values.pmmServer.persistence.clickhouse.size }}
