name: SBOM Assets
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*
      
jobs:
  vmproxy:
    runs-on: ubuntu-latest
    steps:
      - name: create vmproxy SBOM
        uses: anchore/sbom-action@v0
        with:
          path: ./vmproxy
          artifact-name: vmproxy-sbom.spdx

      - name: publish vmproxy SBOM
        uses: anchore/sbom-action/publish-sbom@v0
        with:
          sbom-artifact-match: ".*\\.spdx$"
