export const DYNAMIC_ICON_IMPORT_MAP = {
  account: () => import('icons/account.svg?react'),
  alerts: () => import('icons/alerts.svg?react'),
  backups: () => import('icons/backups.svg?react'),
  'browse-dashboards': () => import('icons/browse-dashboards.svg?react'),
  configuration: () => import('icons/configuration.svg?react'),
  dashboards: () => import('icons/dashboards.svg?react'),
  encrypted: () => import('icons/users-and-access.svg?react'),
  explore: () => import('icons/explore.svg?react'),
  haproxy: () => import('icons/haproxy.svg?react'),
  help: () => import('icons/help.svg?react'),
  'help-fill': () => import('icons/help-fill.svg?react'),
  'high-availability': () => import('icons/high-availability.svg?react'),
  home: () => import('icons/home.svg?react'),
  intelligence: () => import('icons/percona-intelligence.svg?react'),
  inventory: () => import('icons/inventory.svg?react'),
  mongo: () => import('icons/mongo.svg?react'),
  mysql: () => import('icons/mysql.svg?react'),
  node: () => import('icons/home.svg?react'),
  overview: () => import('icons/overview.svg?react'),
  postgresql: () => import('icons/postgresql.svg?react'),
  'pmm-titled': () => import('icons/pmm-titled.svg?react'),
  'pmm-rounded': () => import('icons/pmm-rounded.svg?react'),
  proxysql: () => import('icons/proxysql.svg?react'),
  qan: () => import('icons/qan.svg?react'),
  'operating-system': () => import('icons/operating-system.svg?react'),
  'sign-out': () => import('icons/sign-out.svg?react'),
  summary: () => import('icons/summary.svg?react'),
  'theme-dark': () => import('icons/theme-dark.svg?react'),
  'theme-light': () => import('icons/theme-light.svg?react'),
  'graph-6': () => import('icons/graph-6.svg?react'),
  percona: () => import('icons/percona.svg?react'),
  check: () => import('icons/check.svg?react'),
  'knowledge-base': () => import('icons/knowledge-base.svg?react'),
};

export const VIEWBOX_MAP: Partial<
  Record<keyof typeof DYNAMIC_ICON_IMPORT_MAP, string>
> = {
  percona: '0 0 180 155',
  'knowledge-base': '0 0 28 28',
  'pmm-rounded': '0 0 160 160',
  'pmm-titled': '0 0 363 128',
};
