---
linters-settings:
  exhaustive:
    default-signifies-exhaustive: true

  depguard:
    list-type: blacklist
    include-go-root: true
    packages:
      # use "github.com/pkg/errors" instead
      - errors
      # use "github.com/golang/protobuf/proto" instead
      - github.com/gogo/protobuf/proto
      # use only forked parser
      - github.com/percona/go-mysql/log/slow
      # use "gopkg.in/yaml.v3" instead
      - gopkg.in/yaml.v2
      # use "github.com/percona-platform/saas" instead
      - github.com/percona-platform/platform

  goimports:
    local-prefixes: github.com/percona/pmm

  gci:
    sections:
      - standard # Captures all standard packages if they do not match another section.
      - default # Contains all imports that could not be matched to another section type.
      - prefix(github.com/percona/pmm) # Groups all local imports.

  gomoddirectives:
    replace-allow-list:
      - github.com/percona-platform/dbaas-api 
  
linters:
  disable-all: true
  enable:
    # keep sorted
    - depguard
    - exhaustive
    - gci
    - goimports
    - govet
    - ineffassign
    - nolintlint
    - staticcheck

run:
  timeout: 5m
  skip-dirs:
    - agent/agents/mongodb/internal/

issues:
  exclude-use-default: false
