---
linters-settings:
  depguard:
    list-type: blacklist
    include-go-root: true
    packages:
      # use "github.com/pkg/errors" instead
      - errors
      # use "github.com/golang/protobuf/proto" instead
      - github.com/gogo/protobuf/proto
      # use only forked parser
      - github.com/percona/go-mysql/log/slow

  goimports:
    local-prefixes: github.com/percona/pmm-agent

  lll:
    line-length: 170
    tab-width: 4

  unused:
    check-exported: true

  unparam:
    check-exported: true

linters:
  enable-all: true
  disable:
    - scopelint         # too many false positives
    - gochecknoglobals  # mostly useless
    - wsl               # too annoying
    - gomodguard        # we are not using modules

run:
  skip-dirs:
    - agents/mongodb/internal/

issues:
  exclude-use-default: false
  exclude:
    # gas: Duplicated errcheck checks
    - 'G104: Errors unhandled'
