---
# The most valuable linters; they are required to pass for PR to be merged.

linters-settings:
  depguard:
    list-type: blacklist
    include-go-root: true
    packages:
      # use "github.com/pkg/errors" instead
      - errors
      # we use "github.com/golang/protobuf/proto" for now
      - github.com/gogo/protobuf/proto
      - google.golang.org/protobuf/proto
      # use only forked parser
      - github.com/percona/go-mysql/log/slow
      # use "gopkg.in/yaml.v3" instead
      - gopkg.in/yaml.v2

  goimports:
    local-prefixes: github.com/percona/pmm-agent

linters:
  disable-all: true
  enable:
    # keep sorted
    - depguard
    - goimports
    - govet
    - ineffassign
    - nolintlint
    - staticcheck

run:
  skip-dirs:
    - agents/mongodb/internal/

issues:
  exclude-use-default: false
