---
linters-settings:
  depguard:
    list-type: blacklist
    include-go-root: true
    packages:
      # use "github.com/pkg/errors" instead
      - errors
      # use "github.com/golang/protobuf/proto" instead
      - github.com/gogo/protobuf/proto
      # use "github.com/percona-platform/saas" instead
      - github.com/percona-platform/platform

  goimports:
    local-prefixes: github.com/percona/pmm-managed

  lll:
    line-length: 170
    tab-width: 4

  unused:
    check-exported: true

  unparam:
    check-exported: true

linters:
  enable-all: true
  disable:
    - scopelint         # too many false positives
    - gochecknoglobals  # mostly useless
    - wsl               # too annoying
    - gomodguard        # we are not using modules

issues:
  exclude-use-default: false
  exclude:
    # gas: duplicated errcheck checks
    - 'G104: Errors unhandled'
  exclude-rules:
    # gomnd: tests are full of magic numbers
    # funlen: tests may be long
    # unused: very annoying false positive: https://github.com/golangci/golangci-lint/issues/791
    # testpackage: senseless
    - path: _test\.go
      linters:
        - gomnd
        - funlen
        - unused
        - testpackage
