---
# The most valuable linters; they are required to pass for PR to be merged.

linters-settings:
  depguard:
    list-type: blacklist
    include-go-root: true
    packages:
      # use "github.com/pkg/errors" instead
      - errors
      # use "github.com/golang/protobuf/proto" instead
      - github.com/gogo/protobuf/proto

  goimports:
    local-prefixes: github.com/percona/pmm-update

  gci:
    sections:
      - standard # Captures all standard packages if they do not match another section.
      - default # Contains all imports that could not be matched to another section type.
      - prefix(github.com/percona/pmm-update) # Groups all local imports.

linters:
  disable-all: true
  enable:
    # keep sorted
    - depguard
    - gci
    - goimports
    - govet
    - ineffassign
    - staticcheck

issues:
  exclude-use-default: false
