---
linters-settings:
  depguard:
    list-type: blacklist
    include-go-root: true
    packages:
      # use "github.com/pkg/errors" instead
      - errors
      # use "github.com/golang/protobuf/proto" instead
      - github.com/gogo/protobuf/proto

  goimports:
    local-prefixes: github.com/percona/pmm

  gci:
    sections:
      - standard # Captures all standard packages if they do not match another section.
      - default # Contains all imports that could not be matched to another section type.
      - prefix(github.com/percona/pmm) # Groups all local imports.

  lll:
    line-length: 170
    tab-width: 4

  unused:
    check-exported: false

  unparam:
    check-exported: true

linters:
  disable-all: true
  enable:
    # keep sorted
    - depguard
    - goimports
    - govet
    - ineffassign
    - nolintlint
    - staticcheck
    - gci

issues:
  exclude-use-default: false
  exclude:
    # gas: Duplicated errcheck checks
    - 'G104: Errors unhandled'
    # golint: Methods for implementing interfaces are not documented
    - 'exported method `.+` should have comment or be unexported'
    - 'comment on exported method `.+` should be of the form `.+ ...`'
    # golint: We have to return unexported types due to oneof implementation
    - 'exported method .+ returns unexported type .+, which can be annoying to use'
