---
linters-settings:
  depguard:
    list-type: blacklist
    include-go-root: true
    packages:
      # use "github.com/pkg/errors" instead
      - errors
      # use "github.com/golang/protobuf/proto" instead
      - github.com/gogo/protobuf/proto
      # use only forked parser
      - github.com/percona/go-mysql/log/slow
      # use "github.com/percona-platform/saas" instead
      - github.com/percona-platform/platform
      # use "gopkg.in/yaml.v3" instead
      - gopkg.in/yaml.v2

  godot:
    capital: true

  goimports:
    local-prefixes: github.com/percona/pmm

  gci:
    sections:
      - standard # Captures all standard packages if they do not match another section.
      - default # Contains all imports that could not be matched to another section type.
      - prefix(github.com/percona/pmm) # Groups all local imports.

  lll:
    line-length: 170
    tab-width: 4

  unused:
    check-exported: false #TODO: set true for agent

  unparam:
    check-exported: true

  exhaustive:
    default-signifies-exhaustive: true

  gomoddirectives:
    replace-allow-list:
      - github.com/percona-platform/dbaas-api

linters:
  enable-all: true
  disable:
    # keep sorted
    - exhaustivestruct  # too annoying
    - funlen            # useless
    - gochecknoglobals  # mostly useless
    - gochecknoinits    # we use init functions
    - gomnd             # we are using numbers in many cases
    - gomoddirectives   # we use replace directives
    - gomodguard        # we are not using modules
    - ifshort           # a lot of false positives
    - interfacer        # deprecated
    - maligned          # deprecated
    - nlreturn          # too annoying
    - scopelint         # too many false positives
    - varnamelen        # useless
    - wrapcheck         # we do not use wrapping everywhere
    - wsl               # too annoying

run:
  timeout: 5m
  skip-dirs:
    - agent/agents/mongodb/internal/

issues:
  exclude-use-default: false
  exclude:
    # gas: Duplicated errcheck checks
    - 'G104: Errors unhandled'
    # golint: Methods for implementing interfaces are not documented
    - 'exported method `.+` should have comment or be unexported'
    - 'comment on exported method `.+` should be of the form `.+ ...`'
    # golint: We have to return unexported types due to oneof implementation
    - 'exported method .+ returns unexported type .+, which can be annoying to use'
  exclude-rules:
    - path: _test\.go
      linters:
        # keep sorted
        - exhaustivestruct # very annoying
        - funlen           # tests may be long
        - gocognit         # triggered by subtests
        - gomnd            # tests are full of magic numbers
        - testpackage      # senseless
        - unused           # very annoying false positive: https://github.com/golangci/golangci-lint/issues/791

