header:
  - paths:
      - "**/*.go"
    paths-ignore:
      - "agent/**"
      - "admin/**"
      - "**/mock_*"
      - "**/*.pb.go"
      - "**/*.pb.gw.go"
      - "**/*.pb.validate.go"
      - "**/*_reform.go"
      - "**/json/client/**"
      - "**/amclient/**"
      - "**/ammodels/**"
      - "qan-api2/migrations/**"
      - "managed/services/dbaas/kubernetes/client/kubeclient_interface.go"
      - "managed/services/dbaas/olm/operator_service_interface.go"
      - "managed/services/dbaas/kubernetes/operator_service_interface.go"
    license:
      spdx-id: AGPL-3.0-or-later
      copyright-owner: Percona LLC
      copyright-year: 2023

  - paths:
      - "agent/**/*.go"
      - "admin/**/*.go"
    paths-ignore:
      - "**/*_reform.go"
      - "**/mock_*"
      - "**/json/client/**"
    license:
      spdx-id: Apache-2.0
      copyright-owner: Percona LLC
      copyright-year: 2023
