coverage:
  range: "60...80"
  status:
    default_rules:
      flag_coverage_not_uploaded_behavior: exclude
    
    # disabled for now until we agree on the thresholds
    patch: off

    project:
      default:
        flag_coverage_not_uploaded_behavior: pass
        threshold: 1%
      
      admin:
        threshold: 1%
        paths:
          - admin/

      agent:
        threshold: 1%
        paths:
          - agent/

      managed:
        threshold: 1%
        paths:
          - managed/

      qan-api2:
        threshold: 1%
        paths:
          - qan-api2/

      vmproxy:
        threshold: 1%
        paths:
          - vmproxy/

ignore:
  - "**/fuzzdata"

flag_management:
  default_rules:
    carryforward: true
