---
services:
  pmm-server:
    profiles:
      - pmm
    image: ${PMM_SERVER_IMAGE:-percona/pmm-server:3}
    platform: linux/amd64
    container_name: pmm-server
    hostname: pmm-server
    environment:
      - GF_SECURITY_ADMIN_USER=${PMM_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${PMM_ADMIN_PASSWORD:-admin}
      - PMM_ENABLE_ACCESS_CONTROL=${PMM_ENABLE_ACCESS_CONTROL:-1}
      - PMM_PUBLIC_ADDRESS=${PMM_PUBLIC_ADDRESS:-localhost}
      - PMM_ENABLE_INTERNAL_PG_QAN=${PMM_ENABLE_INTERNAL_PG_QAN:-0}
      - PMM_DEBUG=${PMM_DEBUG:-0}
      # - PMM_CLICKHOUSE_ADDR=127.0.0.1:9000
      # - PMM_CLICKHOUSE_DATABASE=pmm
      # - PMM_CLICKHOUSE_USER=default
      # - PMM_CLICKHOUSE_PASSWORD=<password>
      # - PMM_DISABLE_BUILTIN_CLICKHOUSE=1
      # - PMM_POSTGRES_ADDR=pg
      # - PMM_POSTGRES_DBNAME=pmm-managed
      # - PMM_POSTGRES_USERNAME=pmm-managed
      # - PMM_POSTGRES_DBPASSWORD=<password>
      # - PMM_DISABLE_BUILTIN_POSTGRES=1
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY:-}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY:-}
    ports:
      - ${PMM_PORT_HTTPS:-443}:8443
    volumes:
      - pmm-data:/srv
    networks:
      - ${PMM_NETWORK:-default}

  pmm-client:
    profiles:
      - pmm
    image: percona/pmm-client:3
    container_name: pmm-client
    depends_on:
      pmm-server:
        condition: service_healthy
      sysbench-ps:
        condition: service_started
    environment:
      PMM_AGENT_SERVER_ADDRESS: pmm-server:8443
      PMM_AGENT_SERVER_USERNAME: admin
      PMM_AGENT_SERVER_PASSWORD: admin
      PMM_AGENT_SERVER_INSECURE_TLS: 1
      PMM_AGENT_CONFIG_FILE: config/pmm-agent.yaml
      PMM_AGENT_SETUP: 1
      PMM_AGENT_SETUP_FORCE: 1
      PMM_AGENT_SIDECAR: 1
      PMM_AGENT_PRERUN_SCRIPT: |
        pmm-admin status --wait=10s
        pmm-admin add mysql --cluster=cl1 --environment=dev --custom-labels='app=wp1' --username=root --password=secret --query-source=slowlog MySQLSlowLog ps:3306
        pmm-admin add mysql --cluster=cl2 --environment=prod --custom-labels='app=wp2' --username=root --password=secret --query-source=perfschema MySQLPerfSchema ps:3306
    volumes:
      - logs-directory:/var/log/mysql:ro
    networks:
      - ${PMM_NETWORK:-default}

  logs-init:
    profiles:
      - pmm
    image: percona/percona-server:latest
    container_name: logs-init
    user: root
    volumes:
      - logs-directory:/var/log/mysql
    command: chown mysql:mysql /var/log/mysql
    networks:
      - ${PMM_NETWORK:-default}

  ps:
    profiles:
      - pmm
    image: percona/percona-server:latest
    container_name: ps
    depends_on:
      logs-init:
        condition: service_completed_successfully
    environment:
     - MYSQL_ROOT_PASSWORD=secret
    ports:
     - 3306:3306
    volumes:
      - ./dev/my.cnf:/etc/my.cnf
      - ./dev/mysql.logrotate:/etc/logrotate.d/mysql
      - logs-directory:/var/log/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-psecret"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - ${PMM_NETWORK:-default}

  postgres:
    profiles:
      - pmm
    image: postgres
    container_name: postgres
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=secret
    ports:
     - 5432:5432
    networks:
      - ${PMM_NETWORK:-default}

  mongo:
    profiles:
      - pmm
    image: mongo
    container_name: mongo
    environment:
     - MONGO_INITDB_ROOT_USERNAME=mongo
     - MONGO_INITDB_ROOT_PASSWORD=secret
    ports:
     - 27017:27017
    networks:
      - ${PMM_NETWORK:-default}

  ps-init:
    profiles:
      - pmm
    image: percona/percona-server:latest
    container_name: ps-init
    depends_on:
      ps:
        condition: service_healthy
    command: mysql -h ps -u root -psecret -e "CREATE DATABASE IF NOT EXISTS sbtest;"
    networks:
      - ${PMM_NETWORK:-default}

  sysbench-ps:
    profiles:
      - pmm
    image: perconalab/sysbench
    platform: linux/amd64
    container_name: sysbench-ps
    depends_on:
      ps-init:
        condition: service_completed_successfully
      pmm-server:
        condition: service_healthy
    command: bash /sysbench-ps.sh
    networks:
      - ${PMM_NETWORK:-default}
    volumes:
      - ./dev/sysbench-ps.sh:/sysbench-ps.sh

volumes:
  pmm-data:
    name: pmm-data
  logs-directory:
    name: logs-directory
