---
services:
  pmm-server:
    profiles:
      - pmm
    image: ${PMM_SERVER_IMAGE:-percona/pmm-server:3}
    platform: linux/amd64
    container_name: pmm-server
    hostname: pmm-server
    networks:
      - ${PMM_NETWORK:-default}
    environment:
      - GF_SECURITY_ADMIN_USER=${PMM_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${PMM_ADMIN_PASSWORD:-admin}
      - GF_EMAILS_WELCOME_EMAIL_ON_SIGN_UP=1
      - GF_SMTP_ENABLED=1
      - GF_SMTP_HOST=mail-server:1025
      - GF_SMTP_FROM_NAME=${GF_SMTP_FROM_NAME:-Percona}
      - GF_SMTP_FROM_ADDRESS=${GF_SMTP_FROM_ADDRESS:-admin@percona.com}
      - PMM_ENABLE_ACCESS_CONTROL=${PMM_ENABLE_ACCESS_CONTROL:-1}
      - PMM_PUBLIC_ADDRESS=${PMM_PUBLIC_ADDRESS:-localhost}
      - PMM_ENABLE_INTERNAL_PG_QAN=${PMM_ENABLE_INTERNAL_PG_QAN:-0}
      - PMM_DEBUG=${PMM_DEBUG:-0}
      # - PMM_CLICKHOUSE_ADDR=127.0.0.1:9000
      # - PMM_CLICKHOUSE_DATABASE=pmm
      # - PMM_CLICKHOUSE_USER=default
      # - PMM_CLICKHOUSE_PASSWORD=<password>
      # - PMM_DISABLE_BUILTIN_CLICKHOUSE=1
      # - PMM_POSTGRES_ADDR=pg
      # - PMM_POSTGRES_DBNAME=pmm-managed
      # - PMM_POSTGRES_USERNAME=pmm-managed
      # - PMM_POSTGRES_DBPASSWORD=<password>
      # - PMM_DISABLE_BUILTIN_POSTGRES=1
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY:-}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY:-}
      # - GF_RENDERING_SERVER_URL=http://renderer:8081/render
      # - GF_RENDERING_CALLBACK_URL=https://pmm-server:8443/graph/
    ports:
      - ${PMM_PORT_HTTPS:-443}:8443
    volumes:
      - pmm-data:/srv

  mail-server:
    profiles:
      - pmm
    image: axllent/mailpit
    container_name: mail-server
    hostname: mail-server
    ports:
      - 8025:8025 # Web UI - http://localhost:8025
    networks:
      - ${PMM_NETWORK:-default}

  renderer:
    profiles:
      - renderer
    image: grafana/grafana-image-renderer:latest
    container_name: renderer
    environment:
      - RENDERING_VERBOSE_LOGGING=true
      - RENDERING_DUMPIO=true
      - IGNORE_HTTPS_ERRORS=true
      - LOG_LEVEL=debug
    ports:
      - 8081:8081
    networks:
      - ${PMM_NETWORK:-default}

volumes:
  pmm-data:
    name: pmm-data
