@ck=a38cf742a42385d717ba1635c7370310
###
{{
request.headers.cookie = 'grafana_session='+ck
}}
PUT http://localhost/v1/management/Role HTTP/1.1
Content-type: application/json; charset=utf8
Accept: application/json

{
    "title": "Role B",
    "filter": "{env=\"prod\"}"
}

###
{{
request.headers.cookie = 'grafana_session='+ck
}}
GET http://localhost/v1/management/Role/List
Content-type: application/json; charset=utf8
Accept: application/json

###
POST http://localhost/v1/management/Role/Assign
Content-type: application/json; charset=utf8
Accept: application/json

{
    "user_id": 1,
    "role_id": 3
}

POST http://localhost/v1/management/Role/SetDefault
Content-type: application/json; charset=utf8
Accept: application/json

{
    "role_id": 2
}


GET http://localhost/prometheus/api/v1/
Content-type: application/json; charset=utf8
Accept: application/json

###
{{
request.headers.cookie = 'grafana_session='+ck
}}
@serviceID=/service_id/190febc8-1d15-46d7-a3b2-e1117e428c42
POST http://localhost/v1/management/Service/CustomLabels/Add
Content-type: application/json; charset=utf8
Accept: application/json

{
    "service_id": "{{serviceID}}",
    "custom_labels": {
        "key1": "val1"
    }
}

POST http://localhost/v1/management/Service/CustomLabels/Remove
Content-type: application/json; charset=utf8
Accept: application/json

{
    "service_id": "{{serviceID}}",
    "custom_label_keys": ["key1"]
}
