ALTER TABLE metrics
  ADD COLUMN `m_read_rows_cnt` Float32,
  ADD COLUMN `m_read_rows_sum` Float32 COMMENT 'ClickHouse: total number of rows read from all tables and table functions while running the query.',
  ADD COLUMN `m_read_rows_min` Float32,
  ADD COLUMN `m_read_rows_max` Float32,
  ADD COLUMN `m_read_rows_p99` Float32,
  ADD COLUMN `m_read_bytes_cnt` Float32,
  ADD COLUMN `m_read_bytes_sum` Float32 COMMENT 'ClickHouse: total number of bytes read from all tables and table functions while running the query.',
  ADD COLUMN `m_read_bytes_min` Float32,
  ADD COLUMN `m_read_bytes_max` Float32,
  ADD COLUMN `m_read_bytes_p99` Float32,
  ADD COLUMN `m_result_rows_cnt` Float32,
  ADD COLUMN `m_result_rows_sum` Float32 COMMENT 'ClickHouse: number of rows in the query result.',
  ADD COLUMN `m_result_rows_min` Float32,
  ADD COLUMN `m_result_rows_max` Float32,
  ADD COLUMN `m_result_rows_p99` Float32,
  ADD COLUMN `m_result_bytes_cnt` Float32,
  ADD COLUMN `m_result_bytes_sum` Float32 COMMENT 'ClickHouse: RAM volume in bytes used to store the query result.',
  ADD COLUMN `m_result_bytes_min` Float32,
  ADD COLUMN `m_result_bytes_max` Float32,
  ADD COLUMN `m_result_bytes_p99` Float32,
  ADD COLUMN `m_memory_usage_cnt` Float32,
  ADD COLUMN `m_memory_usage_sum` Float32 COMMENT 'ClickHouse: amount of RAM in bytes used by the query.',
  ADD COLUMN `m_memory_usage_min` Float32,
  ADD COLUMN `m_memory_usage_max` Float32,
  ADD COLUMN `m_memory_usage_p99` Float32,
  ADD COLUMN `m_written_rows_cnt` Float32,
  ADD COLUMN `m_written_rows_sum` Float32 COMMENT 'ClickHouse: number of rows written to all tables while running the query.',
  ADD COLUMN `m_written_rows_min` Float32,
  ADD COLUMN `m_written_rows_max` Float32,
  ADD COLUMN `m_written_rows_p99` Float32,
  ADD COLUMN `m_written_bytes_cnt` Float32,
  ADD COLUMN `m_written_bytes_sum` Float32 COMMENT 'ClickHouse: number of bytes written to all tables while running the query.',
  ADD COLUMN `m_written_bytes_min` Float32,
  ADD COLUMN `m_written_bytes_max` Float32,
  ADD COLUMN `m_written_bytes_p99` Float32,
  ADD COLUMN `query_kind` LowCardinality(String) COMMENT 'ClickHouse: query kind (Select, Insert, etc.) reported by system.query_log.'
  ;
