{
 "title": "VictoriaMetrics Agents Overview",
 "description": "Overview for VictoriaMetrics vmagent v1.40.0 or higher",
 "tags": [
  "Percona",
  "Insight"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   { "name": "ds", "query": "prometheus" },
   {
    "name": "node_name",
    "label": "Node Name",
    "query": {
     "query": "label_values(vm_app_version{agent_type=\"vmagent\"}, node_name)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(vm_app_version{job=~\"$job\"}, instance)"
    }
   },
   {
    "name": "job",
    "label": "Node name",
    "query": {
     "query": "label_values(vm_app_version{agent_type=\"vmagent\"}, job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current Uptime",
   "type": "table",
   "description": "Agent is restated if a new service is added for monitoring ",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "time() - (max_over_time(vm_app_start_timestamp{node_name=~\"$node_name\"}[5m]) and on (node_name) group by (node_name) (vm_app_version{agent_type=\"vmagent\"}))",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Scraped Targets UP",
   "type": "stat",
   "description": "Shows total number of all configured scrape targets in state \"up\" and \"push\" mode.",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(max_over_time((vm_promscrape_targets{node_name=~\"$node_name\", status=\"up\"} and on (node_name) group by (node_name) (vm_app_version{agent_type=\"vmagent\"})))[5m])",
     "legendFormat": "up"
    }
   ]
  },
  {
   "title": "Scraped Samples",
   "type": "stat",
   "description": "Shows total number of all samples ",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sum by (node_name) ((increase(vm_promscrape_scraped_samples_sum{node_name=~\"$node_name\"}[$__range]) and on (node_name) group by (node_name) (vm_app_version{agent_type=\"vmagent\"})))\n+ sum by (node_name) ((increase(vmagent_rows_inserted_total{node_name=~\"$node_name\"}[$__range]) and on (node_name) group by (node_name) (vm_app_version{agent_type=\"vmagent\"}))))"
    }
   ]
  },
  {
   "title": "Dropped Samples",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum((increase(vm_persistentqueue_bytes_dropped_total{node_name=~\"$node_name\"}[$__range]) and on (node_name) group by (node_name) (vm_app_version{agent_type=\"vmagent\"}))) + sum((increase(vmagent_remotewrite_global_relabel_metrics_dropped_total{node_name=~\"$node_name\"}[$__range]) and on (node_name) group by (node_name) (vm_app_version{agent_type=\"vmagent\"}))) + sum((increase(vmagent_remotewrite_relabel_metrics_dropped_total{node_name=~\"$node_name\"}[$__range]) and on (node_name) group by (node_name) (vm_app_version{agent_type=\"vmagent\"})))",
     "legendFormat": "up"
    }
   ]
  },
  {
   "title": "Logged Errors",
   "type": "stat",
   "description": "Shows number of generated  error messages in  logs. Non-zero value may be a sign of connectivity or missconfiguration errors.",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum((increase(vm_log_messages_total{node_name=~\"$node_name\", agent_type=\"vmagent\", level!=\"info\", level!=\"warn\"}[$__range]) and on (node_name) group by (node_name) (vm_app_version{agent_type=\"vmagent\"})))"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "state-timeline",
   "description": "vmagent status per node over the selected time range. Nodes that are down are listed first. Use the pagination controls at the bottom of the panel when many nodes are selected.",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sort(sum((up{node_name=~\"$node_name\",agent_type=\"vmagent\"} offset 3s and on (node_name) group by (node_name) (vm_app_version{agent_type=\"vmagent\"}))) by (node_name))",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Scraped Samples",
   "type": "graph",
   "description": "Shows scraped samples rate including push and pull models. \n\nThe out-rate could be different to in-rate because of replication or additional timeseries added by vmagent for every scraped target.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "sum by (node_name) ((rate(vm_promscrape_scraped_samples_sum{node_name=~\"$node_name\"}[$interval]) and on (node_name) group by (node_name) (vm_app_version{agent_type=\"vmagent\"})))\n+ sum by (node_name) ((rate(vmagent_rows_inserted_total{node_name=~\"$node_name\"}[$interval]) and on (node_name) group by (node_name) (vm_app_version{agent_type=\"vmagent\"})))",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Remotely  Written Samples",
   "type": "graph",
   "description": "Shows out samples rate including push and pull models. \n\nThe out-rate could be different to in-rate because of replication or additional timeseries added by vmagent for every scraped target.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "sum by (node_name) ((rate(vmagent_remotewrite_block_size_rows_sum{node_name=~\"$node_name\"}[$interval]) and on (node_name) group by (node_name) (vm_app_version{agent_type=\"vmagent\"})))",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Dropped Samples (Persistent Queue)",
   "type": "graph",
   "description": "Shows rate of dropped samples from persistent queue. VMagent drops samples from queue if in-memory and on-disk queues are full and it is unable to flush them to remote storage.\nThe max size of on-disk queue is configured by `-remoteWrite.maxDiskUsagePerURL` flag.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum((increase(vm_persistentqueue_bytes_dropped_total{node_name=~\"$node_name\"}[$interval]) and on (node_name) group by (node_name) (vm_app_version{agent_type=\"vmagent\"}))) by (node_name)",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Persistent Queue Size",
   "type": "graph",
   "description": "Shows the persistent queue size of pending samples in bytes which hasn't been flushed to remote storage yet. \n\nIncreasing of value might be a sign of connectivity issues. In such cases, vmagent starts to flush pending data on disk with attempt to send it later once connection is restored.\n\nRemote write URLs are hidden by default but might be unveiled once `-remoteWrite.showURL` is set to true.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum((vmagent_remotewrite_pending_data_bytes{node_name=~\"$node_name\"} and on (node_name) group by (node_name) (vm_app_version{agent_type=\"vmagent\"}))) by (node_name)",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Dropped Samples (Relabeling)",
   "type": "graph",
   "description": "Shows the rate of dropped samples due to relabeling. \nMetric tracks drops for `-remoteWrite.relabelConfig` configuration only.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum((rate(vmagent_remotewrite_global_relabel_metrics_dropped_total{node_name=~\"$node_name\"}[$interval]) and on (node_name) group by (node_name) (vm_app_version{agent_type=\"vmagent\"})))",
     "legendFormat": "global"
    },
    {
     "expr": "sum((rate(vmagent_remotewrite_relabel_metrics_dropped_total{node_name=~\"$node_name\"}[$interval]) and on (node_name) group by (node_name) (vm_app_version{agent_type=\"vmagent\"}))) by(url)",
     "legendFormat": "{{url}}"
    }
   ]
  },
  {
   "title": "HTTP Requests",
   "type": "graph",
   "description": "Shows the rate of requests served by vmagent HTTP server.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum((rate(vmagent_http_requests_total{node_name=~\"$node_name\"}[$__interval]) and on (node_name) group by (node_name) (vm_app_version{agent_type=\"vmagent\"}))) by(node_name)",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  { "title": "Logged Errors/Warnings Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Logged Errors/Warnings - $node_name",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
   "repeat": "node_name",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(increase(vm_log_messages_total{level!=\"info\",node_name=~\"$node_name\"}[$interval]) and on (node_name) group by (node_name) (vm_app_version{agent_type=\"vmagent\"})) or (increase(vm_log_messages_total{level!=\"info\",node_name=~\"$node_name\"}[5m]) and on (node_name) group by (node_name) (vm_app_version{agent_type=\"vmagent\"}))",
     "legendFormat": "{{level}} - {{location}}"
    },
    {
     "expr": "sum by (node_name) ((increase(vm_log_messages_total{level=\"info\",node_name=~\"$node_name\"}[$interval]) and on (node_name) group by (node_name) (vm_app_version{agent_type=\"vmagent\"})) or (increase(vm_log_messages_total{level=\"info\",node_name=~\"$node_name\"}[5m]) and on (node_name) group by (node_name) (vm_app_version{agent_type=\"vmagent\"})))",
     "legendFormat": "info"
    }
   ]
  },
  { "title": "HTTP Requests/Errors Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 } },
  {
   "title": "HTTP Requests Details - $node_name",
   "type": "graph",
   "description": "Shows the rate of requests served by vmagent HTTP server.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 86 },
   "repeat": "node_name",
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum((rate(vmagent_http_requests_total{node_name=~\"$node_name\"}[$interval]) and on (node_name) group by (node_name) (vm_app_version{agent_type=\"vmagent\"}))) by(path, protocol)",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "HTTP Errors - $node_name",
   "type": "graph",
   "description": "Errors rate shows rate for multiple metrics that track possible errors in vmagent, such as network or parsing errors.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 94 },
   "repeat": "node_name",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum((rate(vmagent_http_request_errors_total{node_name=~\"$node_name\"}[$interval]) and on (node_name) group by (node_name) (vm_app_version{agent_type=\"vmagent\"}))) by(protocol)",
     "legendFormat": "{{protocol}} (request)"
    },
    {
     "expr": "sum((rate(vm_protoparser_read_errors_total{node_name=~\"$node_name\"}[$interval]) and on (node_name) group by (node_name) (vm_app_version{agent_type=\"vmagent\"}))) by(type)",
     "legendFormat": "{{type}} (parse)"
    },
    {
     "expr": "sum((rate(vm_ingestserver_request_errors_total{node_name=~\"$node_name\"}[$interval]) and on (node_name) group by (node_name) (vm_app_version{agent_type=\"vmagent\"}))) by(type)",
     "legendFormat": "{{type}} (ingest)"
    },
    {
     "expr": "sum((rate(vm_protoparser_unmarshal_errors_total{node_name=~\"$node_name\"}[$interval]) and on (node_name) group by (node_name) (vm_app_version{agent_type=\"vmagent\"}))) by(type)",
     "legendFormat": "{{type}} (unmarshal)"
    },
    {
     "expr": "sum((rate(vm_promscrape_dial_errors_total{node_name=~\"$node_name\"}[$interval]) and on (node_name) group by (node_name) (vm_app_version{agent_type=\"vmagent\"})))",
     "legendFormat": "scrape dial"
    }
   ]
  },
  { "title": "Scraping", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 102 } },
  {
   "title": "Scrapes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 103 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum((rate(vm_promscrape_scrapes_total{node_name=~\"$node_name\"}[$interval]) and on (node_name) group by (node_name) (vm_app_version{agent_type=\"vmagent\"})) or (irate(vm_promscrape_scrapes_total{node_name=~\"$node_name\"}[5m]) and on (node_name) group by (node_name) (vm_app_version{agent_type=\"vmagent\"}))) by (node_name)",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Samples",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 103 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum((rate(vm_promscrape_scraped_samples_sum{node_name=~\"$node_name\"}[$interval]) and on (node_name) group by (node_name) (vm_app_version{agent_type=\"vmagent\"})) or (irate(vm_promscrape_scraped_samples_sum{node_name=~\"$node_name\"}[5m]) and on (node_name) group by (node_name) (vm_app_version{agent_type=\"vmagent\"}))) by (node_name)",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Scrapes p0.95 Response Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 111 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum((rate(vm_promscrape_scrape_response_size_bytes_bucket{node_name=~\"$node_name\"}[$interval]) and on (node_name) group by (node_name) (vm_app_version{agent_type=\"vmagent\"})) or (irate(vm_promscrape_scrape_response_size_bytes_bucket{node_name=~\"$node_name\"}[5m]) and on (node_name) group by (node_name) (vm_app_version{agent_type=\"vmagent\"}))) by(vmrange,node_name))  ",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Scrapes p0.5 Response Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 111 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum((rate(vm_promscrape_scrape_response_size_bytes_bucket{node_name=~\"$node_name\"}[$interval]) and on (node_name) group by (node_name) (vm_app_version{agent_type=\"vmagent\"})) or (irate(vm_promscrape_scrape_response_size_bytes_bucket{node_name=~\"$node_name\"}[5m]) and on (node_name) group by (node_name) (vm_app_version{agent_type=\"vmagent\"}))) by(vmrange,node_name)) ",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Timeout Scrapes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 119 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum((rate(vm_promscrape_scrapes_timed_out_total{node_name=~\"$node_name\"}[$interval]) and on (node_name) group by (node_name) (vm_app_version{agent_type=\"vmagent\"})) or (irate(vm_promscrape_scrapes_timed_out_total{node_name=~\"$node_name\"}[5m]) and on (node_name) group by (node_name) (vm_app_version{agent_type=\"vmagent\"}))) by (node_name)",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Failed Scrapes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 119 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum((rate(vm_promscrape_scrapes_failed_total{node_name=~\"$node_name\"}[$interval]) and on (node_name) group by (node_name) (vm_app_version{agent_type=\"vmagent\"})) or (irate(vm_promscrape_scrapes_failed_total{node_name=~\"$node_name\"}[5m]) and on (node_name) group by (node_name) (vm_app_version{agent_type=\"vmagent\"}))) by (node_name)",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Dial Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 127 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum((rate(vm_promscrape_dial_errors_total{node_name=~\"$node_name\"}[$interval]) and on (node_name) group by (node_name) (vm_app_version{agent_type=\"vmagent\"})) or (irate(vm_promscrape_dial_errors_total{node_name=~\"$node_name\"}[5m]) and on (node_name) group by (node_name) (vm_app_version{agent_type=\"vmagent\"}))) by (node_name)",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Gunzip Failed Scrapes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 127 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum((rate(vm_promscrape_scrapes_gunzip_failed_total{node_name=~\"$node_name\"}[$interval]) and on (node_name) group by (node_name) (vm_app_version{agent_type=\"vmagent\"})) or (irate(vm_promscrape_scrapes_gunzip_failed_total{node_name=~\"$node_name\"}[5m]) and on (node_name) group by (node_name) (vm_app_version{agent_type=\"vmagent\"}))) by (node_name)",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Scrapes Duration - $node_name",
   "type": "heatmap",
   "description": "It works in VM only disclaimer",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 135 },
   "repeat": "node_name",
   "targets": [
    {
     "expr": "buckets_limit(12, prometheus_buckets(sum((rate(vm_promscrape_scrape_duration_seconds_bucket{node_name=~\"$node_name\"}[$interval]) and on (node_name) group by (node_name) (vm_app_version{agent_type=\"vmagent\"}))) by(vmrange)))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Ingestion", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 183 } },
  {
   "title": "Write Requests",
   "type": "graph",
   "description": "Shows the rate of write requests served by ingestserver (UDP, TCP connections) and HTTP server.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 184 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vm_ingestserver_requests_total{job=~\"$job\", instance=~\"$instance\", path!~\"/favicon.ico\"}[$interval]) or irate(vm_ingestserver_requests_total{job=~\"$job\", instance=~\"$instance\", path!~\"/favicon.ico\"}[5m])) by(type, net)",
     "legendFormat": "{{ type }} ({{net}})"
    },
    {
     "expr": "sum(rate(vmagent_http_requests_total{job=~\"$job\", instance=~\"$instance\", protocol!=\"\"}[$__interval])) by(protocol)",
     "legendFormat": "{{ protocol }} (http)"
    }
   ]
  },
  {
   "title": "Write Errors",
   "type": "graph",
   "description": "Shows the rate of write errors in ingestserver (UDP, TCP connections) and HTTP server.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 184 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vm_ingestserver_request_errors_total{job=~\"$job\", instance=~\"$instance\", path!~\"/favicon.ico\"}[$interval]) or irate(vm_ingestserver_request_errors_total{job=~\"$job\", instance=~\"$instance\", path!~\"/favicon.ico\"}[5m])) by(type, net)",
     "legendFormat": "{{ type }} ({{net}})"
    },
    {
     "expr": "sum(rate(vmagent_http_request_errors_total{job=~\"$job\", instance=~\"$instance\", protocol!=\"\"}[$__interval])) by(protocol)",
     "legendFormat": "{{ protocol }} (http)"
    }
   ]
  },
  {
   "title": "Parsed Rows",
   "type": "graph",
   "description": "Shows the rate of parsed rows from write or scrape requests.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 192 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vm_protoparser_rows_read_total{job=~\"$job\", instance=~\"$instance\"}[$interval]) or irate(vm_protoparser_rows_read_total{job=~\"$job\", instance=~\"$instance\"}[5m])) by(type)",
     "legendFormat": "{{ type }} ({{net}})"
    }
   ]
  },
  {
   "title": "Dropped Invalid Rows",
   "type": "graph",
   "description": "Tracks the rate of dropped invalid rows because of errors while unmarshaling write requests. The exact errors messages will be printed in logs.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 192 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vm_rows_invalid_total{job=~\"$job\", instance=~\"$instance\"}[$interval]) or irate(vm_rows_invalid_total{job=~\"$job\", instance=~\"$instance\"}[5m])) by(type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "Remote Write", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 200 } },
  {
   "title": "Remote Write Requests",
   "type": "graph",
   "description": "Shows the rate of requests to configured remote write endpoints by url and status code.\n\nRemote write URLs are hidden by default but might be unveiled once `-remoteWrite.showURL` is set to true.\n\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 201 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum((rate(vmagent_remotewrite_requests_total{node_name=~\"$node_name\"}[$interval]) and on (node_name) group by (node_name) (vm_app_version{agent_type=\"vmagent\"})) or (irate(vmagent_remotewrite_requests_total{node_name=~\"$node_name\"}[5m]) and on (node_name) group by (node_name) (vm_app_version{agent_type=\"vmagent\"}))) by(node_name, url, status_code)",
     "legendFormat": "{{node_name}} - {{url}} - {{status_code}}"
    }
   ]
  },
  {
   "title": "Remote Write Size",
   "type": "graph",
   "description": "Shows the global rate for number of written bytes via remote write connections.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 201 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum((rate(vmagent_remotewrite_conn_bytes_written_total{node_name=~\"$node_name\"}[$interval]) and on (node_name) group by (node_name) (vm_app_version{agent_type=\"vmagent\"})) or (irate(vmagent_remotewrite_conn_bytes_written_total{node_name=~\"$node_name\"}[5m]) and on (node_name) group by (node_name) (vm_app_version{agent_type=\"vmagent\"}))) by(node_name)",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Block Size Rows",
   "type": "heatmap",
   "description": "Shows the remote write request block size distribution in rows.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 209 },
   "targets": [
    {
     "expr": "buckets_limit(12, prometheus_buckets(sum((rate(vmagent_remotewrite_block_size_rows_bucket{node_name=~\"$node_name\"}[$interval]) and on (node_name) group by (node_name) (vm_app_version{agent_type=\"vmagent\"})) or (irate(vmagent_remotewrite_block_size_rows_bucket{node_name=~\"$node_name\"}[5m]) and on (node_name) group by (node_name) (vm_app_version{agent_type=\"vmagent\"}))) by(vmrange)))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Block Size in Bytes",
   "type": "heatmap",
   "description": "Shows the remote write request block size distribution in bytes.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 209 },
   "targets": [
    {
     "expr": "buckets_limit(12, prometheus_buckets(sum((rate(vmagent_remotewrite_block_size_bytes_bucket{node_name=~\"$node_name\"}[$interval]) and on (node_name) group by (node_name) (vm_app_version{agent_type=\"vmagent\"})) or (irate(vmagent_remotewrite_block_size_bytes_bucket{node_name=~\"$node_name\"}[5m]) and on (node_name) group by (node_name) (vm_app_version{agent_type=\"vmagent\"}))) by(vmrange)))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Requests Retry Rate",
   "type": "graph",
   "description": "Shows requests retry rate by url. Number of retries is unlimited but protected with delays up to 1m between attempts.\n\nRemote write URLs are hidden by default but might be unveiled once `-remoteWrite.showURL` is set to true.\n\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 217 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum((rate(vmagent_remotewrite_retries_count_total{node_name=~\"$node_name\"}[$interval]) and on (node_name) group by (node_name) (vm_app_version{agent_type=\"vmagent\"})) or (irate(vmagent_remotewrite_retries_count_total{node_name=~\"$node_name\"}[5m]) and on (node_name) group by (node_name) (vm_app_version{agent_type=\"vmagent\"}))) by(url,node_name)",
     "legendFormat": "{{node_name}} - {{ url }}"
    }
   ]
  },
  {
   "title": "Established Connections",
   "type": "graph",
   "description": "Shows current number of established connections to remote write endpoints.\n\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 217 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum((vmagent_remotewrite_conns{node_name=~\"$node_name\"} and on (node_name) group by (node_name) (vm_app_version{agent_type=\"vmagent\"}))) by (node_name)",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Remote Write Duration - $node_name",
   "type": "heatmap",
   "description": "Shows the remote write request duration distribution in seconds. Value depends on block size, network quality and remote storage performance.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 225 },
   "repeat": "node_name",
   "targets": [
    {
     "expr": "buckets_limit(12, prometheus_buckets(sum((rate(vmagent_remotewrite_duration_seconds_bucket{node_name=~\"$node_name\"}[$interval]) and on (node_name) group by (node_name) (vm_app_version{agent_type=\"vmagent\"}))) by(vmrange)))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Resource usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 279 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "description": "Shows the CPU usage per vmagent instance. \nIf you think that usage is abnormal or unexpected pls file an issue and attach CPU profile if possible.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 280 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum((rate(process_cpu_seconds_total{node_name=~\"$node_name\"}[$interval]) and on (node_name) group by (node_name) (vm_app_version{agent_type=\"vmagent\"}))) by(node_name)",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "description": "Amount of used memory (resident)\n\nIf you think that usage is abnormal or unexpected pls file an issue and attach memory profile if possible.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 280 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum((process_resident_memory_bytes{node_name=~\"$node_name\"} and on (node_name) group by (node_name) (vm_app_version{agent_type=\"vmagent\"}))) by (node_name)",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 288 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum((process_num_threads{node_name=~\"$node_name\"} and on (node_name) group by (node_name) (vm_app_version{agent_type=\"vmagent\"}))) by(node_name)",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Network  Usage",
   "type": "graph",
   "description": "Network usage shows the bytes rate for data accepted by vmagent and pushed via remotewrite protocol.\nDiscrepancies are possible because of different protocols used for ingesting, scraping and writing data.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 288 },
   "yaxes": [
    { "format": "Bps", "label": "Outbound (-) / Inbound (+)" }
   ],
   "targets": [
    {
     "expr": "sum((rate(vm_tcplistener_read_bytes_total{node_name=~\"$node_name\"}[$interval]) and on (node_name) group by (node_name) (vm_app_version{agent_type=\"vmagent\"})) or (irate(vm_tcplistener_read_bytes_total{node_name=~\"$node_name\"}[5m]) and on (node_name) group by (node_name) (vm_app_version{agent_type=\"vmagent\"}))) by (node_name)\n+ sum((rate(vm_promscrape_conn_bytes_read_total{node_name=~\"$node_name\"}[$interval]) and on (node_name) group by (node_name) (vm_app_version{agent_type=\"vmagent\"})) or (irate(vm_promscrape_conn_bytes_read_total{node_name=~\"$node_name\"}[5m]) and on (node_name) group by (node_name) (vm_app_version{agent_type=\"vmagent\"}))) by (node_name)",
     "legendFormat": "Inbound - {{node_name}}"
    },
    {
     "expr": "sum((rate(vmagent_remotewrite_conn_bytes_written_total{node_name=~\"$node_name\"}[$interval]) and on (node_name) group by (node_name) (vm_app_version{agent_type=\"vmagent\"})) or (irate(vmagent_remotewrite_conn_bytes_written_total{node_name=~\"$node_name\"}[5m]) and on (node_name) group by (node_name) (vm_app_version{agent_type=\"vmagent\"}))) by (node_name)",
     "legendFormat": "Outbound - {{node_name}}"
    }
   ]
  }
 ]
}