' High-level context C4 Model diagram
' Automatically rendered by MkDocs using PlantUML
' See https://c4model.com and https://github.com/plantuml-stdlib/C4-PlantUML
@startuml "1 - PMM Context"
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!include _resources/diagrams/plantuml_styles.puml
HIDE_STEREOTYPE()
'title PMM Context
caption PMM's client/server architecture
Person_Ext(user, "User")
System_Ext(monitored, "Monitored systems", "Servers, databases, services or applications")
System(pmm_client, "PMM Client", "Runs on every monitored host to extract metrics data from databases and services and forwards it to PMM Server")
System(pmm_server, "PMM Server", "Receives, stores and organizes metrics data from PMM Clients, presents it in web UI as graphs, charts, and tables")
System_Ext(platform, "Percona Platform", "Value-added services:\n- Security Threat Tool\n- DBaaS (Coming soon)")
Lay_D(user, pmm_client)
Lay_D(user, pmm_server)
Rel_R(monitored, pmm_client, "Metrics")
BiRel_R(pmm_client, pmm_server, " ")
BiRel_R(pmm_server, platform, " ")
Rel(user, pmm_server, " ")
Rel(user, pmm_client, " ")
@enduml
