' Map of documentation using PlantUML
' References:
' Syntax: https://plantuml.com/mindmap-diagram
' Icons: https://plantuml.com/openiconic
' Colour: https://plantuml.com/color
' Text: https://plantuml.com/creole
@startwbs "PMM_Documentation_Map"
!include _resources/diagrams/plantuml_styles.puml
<style>
wbsDiagram {
  node {
	BackgroundColor #cce6ff
    Padding 5
    Margin 5
  }
}
</style>

' Absolute links - can be useful for exporting map as stand-alone image
' relative links make testing easier but must be changed for local vs hosting' Hosted
!$base = "https://www.percona.com/doc/percona-monitoring-and-management/2.x"
'!$base = "../2.x"
' !$base = ".."

+ <&home> [[$base/index.html Welcome]]
	+ <&power-standby> [[$base/setting-up/ Setting up]]
		- <&heart> [[$base/setting-up/server/ Server]]
			-_ [[$base/setting-up/server/docker.html Docker]]
			-_ [[$base/setting-up/server/virtual-appliance.html Virtual\nAppliance]]
			-_ [[$base/setting-up/server/aws.html AWS\nMarketplace]]

		+ <&laptop> [[$base/setting-up/client/ Client]]
			+_ [[$base/setting-up/client/docker.html Docker]]
			+_ [[$base/setting-up/client/mysql.html MySQL]]
			+_ [[$base/setting-up/client/percona-server.html Percona\nServer]]
			+_ [[$base/setting-up/client/mongodb.html MongoDB]]
			+_ [[$base/setting-up/client/postgresql.html PostgreSQL]]
			+_ [[$base/setting-up/client/proxysql.html ProxySQL]]
			+_ [[$base/setting-up/client/aws.html Amazon RDS]]
			+_ [[$base/setting-up/client/azure.html Microsoft Azure]]
			+_ [[$base/setting-up/client/google.html Google Cloud Platform]]
			+_ [[$base/setting-up/client/linux.html Linux]]
			+_ [[$base/setting-up/client/external.html External\nServices]]
			+_ [[$base/setting-up/client/haproxy.html HAProxy]]

	+ <&wrench> [[$base/using/ Using]]
		+_ [[$base/using/interface.html User\ninterface]]
		+_ [[$base/using/alerting.html Integrated\nAlerting]]
		+_ [[$base/using/query-analytics.html Query\nAnalytics]]
		+ [[$base/using/platform/index.html Percona\nPlatform]]
			+_ [[$base/using/platform/security-threat-tool.html Security\nThreat Tool]]

	+ <&task> [[$base/how-to/ How to]]
		+_ [[$base/how-to/configure.html Configure]]
		+_ [[$base/how-to/upgrade.html Upgrade]]
		+_ [[$base/how-to/secure.html Secure]]
		+_ [[$base/how-to/optimize.html Optimize]]
		+_ [[$base/how-to/render-dashboard-images.html Render\ndashboard\nimages]]
		+_ [[$base/how-to/troubleshoot.html Troubleshoot]]

	+ <&magnifying-glass> [[$base/details/ Details]]
		+_ [[$base/details/architecture.html Architecture]]
		+_ [[$base/details/interface.html User Interface\ncomponents]]
		- <&graph> [[$base/details/dashboards/ Dashboards]]
			-_ [[$base/details/dashboards/index.html#insight Insight]]
			-_ [[$base/details/dashboards/index.html#pmm PMM]]
			-_ [[$base/details/dashboards/index.html#os-dashboards OS]]
			-_ [[$base/details/dashboards/index.html#prometheus-dashboards Prometheus]]
			-_ [[$base/details/dashboards/index.html#mysql-dashboards MySQL]]
			-_ [[$base/details/dashboards/index.html#mongodb-dashboards MongoDB]]
			-_ [[$base/details/dashboards/index.html#postgresql-dashboards PostgreSQL]]
			-_ [[$base/details/dashboards/index.html#proxysql-dashboards ProxySQL]]
			-_ [[$base/details/dashboards/index.html#ha-dashboards HA]]
		+ <&code> [[$base/details/commands/ Commands]]
			+_ [[$base/details/commands/pmm-admin.html pmm-admin]]
			+_ [[$base/details/commands/pmm-agent.html pmm-agent]]
		+_ [[$base/details/api.html API]]
		+_ [[$base/details/victoria-metrics.html VictoriaMetrics]]
		+_ [[$base/details/glossary.html Glossary]]
@endwbs
