' Map of documentation (without links for PDF)
' To export as PNG:
'
' A) Using Visual Studio Code:
' 1. install PlantUML extension (https://marketplace.visualstudio.com/items?itemName=jebbs.plantuml)
' 2. Right click and choose 'Export current diagram'
' 3. Select 'png' type
' 3. Copy out/resources/Map/PMM_Documentation_Map.svg to docs/_images
'
' B) Command line:
' 1. Download PlantUML jar file: https://sourceforge.net/projects/plantuml/files/plantuml.jar/download
' 2. cat _resources/diagrams/Map_PDF.puml | java -jar ~/Downloads/plantuml.jar -tsvg -pipe > docs/_images/PMM_Documentation_Map_PDF.svg
'
' For icons see https://plantuml.com/openiconic

@startmindmap "PMM_Documentation_Map_PDF"
title PMM Documentation Map
skinparam Shadowing false
<style>
mindmapDiagram {
  node {
    FontSize 12
    BackgroundColor Orange
    RoundCorner 10
    Padding 5
    Margin 3
  }
}
</style>

*[#GreenYellow] <&home> Welcome
	* <&power-standby> Setting up
		* <&heart> Server
			*_ Setting up PMM Server: Overview
			*_ Docker
			*_ Virtual Appliance
			*_ AWS Marketplace
		* <&laptop> Client
			*_ Setting up PMM Clients
			*_ Docker
			*_ MySQL
			*_ Percona Server
			*_ MongoDB
			*_ PostgreSQL
			*_ ProxySQL
			*_ Amazon RDS
			*_ Linux
			*_ External Services
	* <&wrench> Using
		*_ User interface
		*_ Integrated Alerting
		*_ Query Analytics
		*  Percona\nEnterprise\nPlatform
			*_ Security Threat Tool
	* <&task> How to
		*_ Configure
		*_ Upgrade
		*_ Secure
		*_ Optimize

left side

	* <&magnifying-glass> Details
		*_ Architecture
		* <&graph> Dashboards
			*_ Insight
			*_ PMM
			*_ OS
			*_ Prometheus
			*_ MySQL
			*_ MongoDB
			*_ PostgreSQL
			*_ ProxySQL
			*_ HA
		* <&code> Commands
			*_ pmm-admin
			*_ pmm-agent
		*_ API
		*_ VictoriaMetrics
		*_ Glossary
	* <&question-mark> FAQ
	* <&bug> Release Notes
		*_ 2.14.0 (LATEST)
		*_ 2.13.0
		*_ 2.12.0
		*_ 2.11.0
			*_ 2.11.1
		*_ 2.10.0
			*_ 2.10.1
		*_ 2.9.0
			*_ 2.9.1
		*_ 2.8.0
		*_ 2.7.0
		*_ 2.6.0
		*_ 2.5.0
		*_ 2.4.0
		*_ 2.3.0
		*_ 2.2.0
			*_ 2.2.1
			*_ 2.2.2
		*_ 2.1.0
		*_ 2.0.0
@endmindmap
