' Topic/role map of PMM documentation
' References:
' Syntax: https://plantuml.com/mindmap-diagram
' Icons: https://plantuml.com/openiconic
' Colour: https://plantuml.com/color
' Text: https://plantuml.com/creole
@startmindmap "PMM_DOC_TOPICS"
skinparam svgLinkTarget _blank
skinparam defaultFontName Chivo
skinparam defaultFontSize 11
<style>
mindmapDiagram {
  node {
    ' Gap within nodes
    Padding 7
    ' Gap between nodes
    Margin 5
  }
}
</style>
' Absolute links - can be useful for exporting map as stand-alone image
' relative links make testing easier but must be changed for local vs hosting' Hosted
!$base = "https://www.percona.com/doc/percona-monitoring-and-management/2.x"
'!$base = "../2.x"
'!$base = "."
+[#lightblue] For Users <<user>>
++[#goldenrod] For Sys Admins<<admin>>
+++_ [[$base/setting-up/ Setting up]]
+++_ [[$base/how-to/configure.html Configure]]
+++_ [[$base/how-to/upgrade.html Upgrade]]
+++_ [[$base/details/commands/ Command-line tools]]
+++_ [[$base/how-to/secure.html Secure]]
+++_ [[$base/how-to/optimize.html Optimize]]
+++_ [[$base/details/architecture.html Architecture]]
--_ [[$base/using/interface.html User interface]]
--_ [[$base/details/interface.html UI components]]
--_ [[$base/details/dashboards/ Dashboards]]
--_ [[$base/using/alerting.html Alerting]]
--_ [[$base/using/query-analytics.html Query Analytics]]
--_ [[$base/using/platform/index.html Percona Platform]]
@endmindmap
