' Styles for PlantUML created diagrams
skinparam {
  roundcorner 15
  defaultFontName Chivo
  defaultFontSize 14
  defaultTextAlignment center
  ArrowHeadColor none
  BackgroundColor #fff
  ActivityBackgroundColor #cce6ff
  activityDiamondBackgroundColor #cce6ff
  legendBackgroundColor #0000
}
