' C4 Model diagram (Not published - WIP)
' Automatically rendered by MkDocs using PlantUML
' See https://c4model.com and https://github.com/plantuml-stdlib/C4-PlantUML
@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Deployment.puml
!include _resources/diagrams/plantuml_styles.puml
HIDE_STEREOTYPE()
LAYOUT_AS_SKETCH()

title pmm-managed - PMM manage daemon
caption WIP

Deployment_Node(pmm_managed, "pmm-managed", " "){

    Container(debug, "Debug server", "/debug/metrics, /debug/vars")
    ContainerDb(postgres, "PostgreSQL", " ")
}



@enduml
