' C4 Model diagram (Not published - WIP)
' Automatically rendered by MkDocs using PlantUML
' See https://c4model.com and https://github.com/plantuml-stdlib/C4-PlantUML
@startuml PMM_context2
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

LAYOUT_WITH_LEGEND()
' LAYOUT_TOP_DOWN()
LAYOUT_LEFT_RIGHT()

Enterprise_Boundary(platform, "Percona Platform") {
    System(stt, "Security Threat Tool")
    System(dbaas, "DB as a Service")
}

Enterprise_Boundary(enterprise, "Customer Systems") {
    Person_Ext(user, "User")

    System_Boundary(server_host, "Server host") {
        System(pmm_server, "PMM Server")
    }
    System_Boundary(enterprise1, "Customer system 1") {
        System(client1, "PMM Client (A)")
        System_Ext(monitored1, "Monitored database", "(MySQL)")
        Rel(monitored1, client1, "Metrics")
    }
    System_Boundary(enterprise2, "Customer system 2") {
        System(client2, "PMM Client (B)")
        System_Ext(monitored2, "Monitored database", "(PostgreSQL)")
        System_Ext(monitored3, "Monitored database", "(MongoDB)")
        Rel(monitored2, client2, "Metrics")
        Rel(monitored3, client2, "Metrics")
    }
    System_Boundary(enterprise3, "Customer system N") {
        System(client3, "PMM Client (X)")
        System_Ext(monitored4, "Monitored service")
        Rel(monitored4, client3, "Metrics")
    }
}

Rel(user, pmm_server, " ")
BiRel(client1, pmm_server, " ")
BiRel(client2, pmm_server, " ")
BiRel(client3, pmm_server, " ")

BiRel(pmm_server, stt, " ")
BiRel(pmm_server, dbaas, " ")

@enduml
