' Diagram showing sequence of tasks to set up PMM Client as a Docker container
' Syntax: https://plantuml.com/activity-diagram-beta
' Icons: https://plantuml.com/openiconic
' Colour: https://plantuml.com/color
' Text: https://plantuml.com/creole
@startuml "setting-up_client_docker"
!include _resources/diagrams/plantuml_styles.puml

title Running PMM Client\nOverview of options\n

split
    -[hidden]->
    split
        -[hidden]->
        partition "Package manager" {
            split
                -[hidden]->
                (1)
                :Set up ""percona-release"";
                :""apt install pmm-client"";
            split again
                -[hidden]->
                (2)
                :Download "".deb""/"".rpm"";
                :""dpkg -i *.deb""\n""dnf localinstall *.rpm"";
            end split
        }
    split again
        partition "Binary package" {
        -[hidden]->
        (3)
        :Download & verify;
        :Unpack;
        :Install;
        :Set ""$PATH"";
        }
    end split
    :Set up pmm-agent;
split again
    -[hidden]->
    partition "Docker" {
        split
            -[hidden]->
            (4)
            :""docker pull percona/pmm-client:2"";
            :Create persistent data store;
            :""docker run ..."";
        split again
            -[hidden]->
            (5)
            :Create ""docker-compose.yml"";
            :""docker-compose up"";
        end split
    }
end split
:Register node;
:Configure and add services;
@enduml
