' Diagram showing sequence of tasks to set up PMM
' Syntax: https://plantuml.com/activity-diagram-beta
' Icons: https://plantuml.com/openiconic
' Colour: https://plantuml.com/color
' Text: https://plantuml.com/creole
@startuml "setting-up"
!include _resources/diagrams/plantuml_styles.puml
skinparam partitionWidth 400

title Setting up PMM\nOverview\n

partition "1. Set up PMM Server as one of: " {
	split
		-[hidden]->
		:Docker container;
	split again
		-[hidden]->
		:Virtual appliance;
	split again
		-[hidden]->
		:Amazon AWS marketplace;
	end split
}
partition "2. Set up PMM Client for each node " {
	split
		partition "Package manager" {
			:Set up ""percona-release"";
			:""apt/yum install pmm2-client"";
		}
	split again
		partition "Manual package install" {
			:Download "".deb""/"".rpm"";
			:Install
			<code>
			dpkg -i *.deb # Debian
			dnf localinstall *.rpm # RHEL
			</code>;
		}
	split again
		partition "Binary package install" {
			:Download "".tar.gz"";
			:<code>
			tar xfz ...
			pmm-agent setup ...
			</code>;
		}
	split again
		partition "Docker" {
			:<code>
			docker pull
			percona/pmm-client:2
			</code>;
		}
	end split
}
:3. Configure and add service;
@enduml
