' Diagram showing sequence of tasks to set up Virtual Appliance
' Syntax: https://plantuml.com/activity-diagram-beta
' Icons: https://plantuml.com/openiconic
' Colour: https://plantuml.com/color
' Text: https://plantuml.com/creole
@startuml "setting-up_server_virtual-appliance"
!include _resources/diagrams/plantuml_styles.puml

title Running PMM Server as a virtual appliance\nOverview\n
:Download;
:Verify;
split
partition "VMware" {
	:Import;
	:Reconfigure interface;
	:Start guest and get IP address;
}
split again
partition "VirtualBox" {
	:Import;
	:Reconfigure interface;
	:Start guest and get IP address;
}
end split
:Log in to PMM user interface;
#lightgrey:(Optional) Change root password;
#lightgrey:(Optional) Set up SSH;
#lightgrey:(Optional) Set up static IP;
@enduml
