' Diagram showing sequence of tasks to set up PMM Client as a Docker container
' Syntax: https://plantuml.com/activity-diagram-beta
' Icons: https://plantuml.com/openiconic
' Colour: https://plantuml.com/color
' Text: https://plantuml.com/creole
@startuml "setting-up_client_docker"
!include _resources/diagrams/plantuml_styles.puml

title Running PMM Client as a Docker container\nOverview\n
:1. Pull Docker image;
:2. Create persistent data store;
:3. Run the image;
:4. Check status;
@enduml
