// Code generated by protoc-gen-go. DO NOT EDIT.
// source: managementpb/mysql.proto

package managementpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "github.com/mwitkow/go-proto-validators"
	inventorypb "github.com/percona/pmm/api/inventorypb"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AddMySQLRequest struct {
	// Node identifier on which a service is been running. Required.
	NodeId string `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// Unique across all Services user-defined name. Required.
	ServiceName string `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	// Node and Service access address (DNS name or IP). Required.
	Address string `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	// Service Access port. Required.
	Port uint32 `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	// The "pmm-agent" identifier which should run agents. Required.
	PmmAgentId string `protobuf:"bytes,5,opt,name=pmm_agent_id,json=pmmAgentId,proto3" json:"pmm_agent_id,omitempty"`
	// Environment name.
	Environment string `protobuf:"bytes,6,opt,name=environment,proto3" json:"environment,omitempty"`
	// Cluster name.
	Cluster string `protobuf:"bytes,7,opt,name=cluster,proto3" json:"cluster,omitempty"`
	// Replication set name.
	ReplicationSet string `protobuf:"bytes,8,opt,name=replication_set,json=replicationSet,proto3" json:"replication_set,omitempty"`
	// MySQL username for scraping metrics.
	Username string `protobuf:"bytes,9,opt,name=username,proto3" json:"username,omitempty"`
	// MySQL password for scraping metrics.
	Password string `protobuf:"bytes,10,opt,name=password,proto3" json:"password,omitempty"`
	// FIXME remove
	QanUsername string `protobuf:"bytes,11,opt,name=qan_username,json=qanUsername,proto3" json:"qan_username,omitempty"`
	// FIXME remove
	QanPassword string `protobuf:"bytes,12,opt,name=qan_password,json=qanPassword,proto3" json:"qan_password,omitempty"`
	// If true, adds mysqld_exporter for provided service.
	MysqldExporter bool `protobuf:"varint,13,opt,name=mysqld_exporter,json=mysqldExporter,proto3" json:"mysqld_exporter,omitempty"`
	// If true, adds qan-mysql-perfschema-agent for provided service.
	QanMysqlPerfschema bool `protobuf:"varint,14,opt,name=qan_mysql_perfschema,json=qanMysqlPerfschema,proto3" json:"qan_mysql_perfschema,omitempty"`
	// If true, adds qan-mysql-slowlog-agent for provided service.
	QanMysqlSlowlog      bool     `protobuf:"varint,15,opt,name=qan_mysql_slowlog,json=qanMysqlSlowlog,proto3" json:"qan_mysql_slowlog,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddMySQLRequest) Reset()         { *m = AddMySQLRequest{} }
func (m *AddMySQLRequest) String() string { return proto.CompactTextString(m) }
func (*AddMySQLRequest) ProtoMessage()    {}
func (*AddMySQLRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab81470951176953, []int{0}
}

func (m *AddMySQLRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddMySQLRequest.Unmarshal(m, b)
}
func (m *AddMySQLRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddMySQLRequest.Marshal(b, m, deterministic)
}
func (m *AddMySQLRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddMySQLRequest.Merge(m, src)
}
func (m *AddMySQLRequest) XXX_Size() int {
	return xxx_messageInfo_AddMySQLRequest.Size(m)
}
func (m *AddMySQLRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddMySQLRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddMySQLRequest proto.InternalMessageInfo

func (m *AddMySQLRequest) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *AddMySQLRequest) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *AddMySQLRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *AddMySQLRequest) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *AddMySQLRequest) GetPmmAgentId() string {
	if m != nil {
		return m.PmmAgentId
	}
	return ""
}

func (m *AddMySQLRequest) GetEnvironment() string {
	if m != nil {
		return m.Environment
	}
	return ""
}

func (m *AddMySQLRequest) GetCluster() string {
	if m != nil {
		return m.Cluster
	}
	return ""
}

func (m *AddMySQLRequest) GetReplicationSet() string {
	if m != nil {
		return m.ReplicationSet
	}
	return ""
}

func (m *AddMySQLRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *AddMySQLRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *AddMySQLRequest) GetQanUsername() string {
	if m != nil {
		return m.QanUsername
	}
	return ""
}

func (m *AddMySQLRequest) GetQanPassword() string {
	if m != nil {
		return m.QanPassword
	}
	return ""
}

func (m *AddMySQLRequest) GetMysqldExporter() bool {
	if m != nil {
		return m.MysqldExporter
	}
	return false
}

func (m *AddMySQLRequest) GetQanMysqlPerfschema() bool {
	if m != nil {
		return m.QanMysqlPerfschema
	}
	return false
}

func (m *AddMySQLRequest) GetQanMysqlSlowlog() bool {
	if m != nil {
		return m.QanMysqlSlowlog
	}
	return false
}

type AddMySQLResponse struct {
	Service              *inventorypb.MySQLService            `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	MysqldExporter       *inventorypb.MySQLdExporter          `protobuf:"bytes,2,opt,name=mysqld_exporter,json=mysqldExporter,proto3" json:"mysqld_exporter,omitempty"`
	QanMysqlPerfschema   *inventorypb.QANMySQLPerfSchemaAgent `protobuf:"bytes,3,opt,name=qan_mysql_perfschema,json=qanMysqlPerfschema,proto3" json:"qan_mysql_perfschema,omitempty"`
	QanMysqlSlowlog      *inventorypb.QANMySQLSlowlogAgent    `protobuf:"bytes,4,opt,name=qan_mysql_slowlog,json=qanMysqlSlowlog,proto3" json:"qan_mysql_slowlog,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                             `json:"-"`
	XXX_unrecognized     []byte                               `json:"-"`
	XXX_sizecache        int32                                `json:"-"`
}

func (m *AddMySQLResponse) Reset()         { *m = AddMySQLResponse{} }
func (m *AddMySQLResponse) String() string { return proto.CompactTextString(m) }
func (*AddMySQLResponse) ProtoMessage()    {}
func (*AddMySQLResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab81470951176953, []int{1}
}

func (m *AddMySQLResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddMySQLResponse.Unmarshal(m, b)
}
func (m *AddMySQLResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddMySQLResponse.Marshal(b, m, deterministic)
}
func (m *AddMySQLResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddMySQLResponse.Merge(m, src)
}
func (m *AddMySQLResponse) XXX_Size() int {
	return xxx_messageInfo_AddMySQLResponse.Size(m)
}
func (m *AddMySQLResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddMySQLResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddMySQLResponse proto.InternalMessageInfo

func (m *AddMySQLResponse) GetService() *inventorypb.MySQLService {
	if m != nil {
		return m.Service
	}
	return nil
}

func (m *AddMySQLResponse) GetMysqldExporter() *inventorypb.MySQLdExporter {
	if m != nil {
		return m.MysqldExporter
	}
	return nil
}

func (m *AddMySQLResponse) GetQanMysqlPerfschema() *inventorypb.QANMySQLPerfSchemaAgent {
	if m != nil {
		return m.QanMysqlPerfschema
	}
	return nil
}

func (m *AddMySQLResponse) GetQanMysqlSlowlog() *inventorypb.QANMySQLSlowlogAgent {
	if m != nil {
		return m.QanMysqlSlowlog
	}
	return nil
}

func init() {
	proto.RegisterType((*AddMySQLRequest)(nil), "management.AddMySQLRequest")
	proto.RegisterType((*AddMySQLResponse)(nil), "management.AddMySQLResponse")
}

func init() { proto.RegisterFile("managementpb/mysql.proto", fileDescriptor_ab81470951176953) }

var fileDescriptor_ab81470951176953 = []byte{
	// 667 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x94, 0xdf, 0x6e, 0xd3, 0x3c,
	0x18, 0xc6, 0xbf, 0x76, 0x5d, 0xdb, 0xb9, 0xdd, 0xba, 0xcf, 0x42, 0xc2, 0x94, 0xa1, 0x95, 0xee,
	0x60, 0xdd, 0xa0, 0x09, 0x1b, 0x12, 0x07, 0x9c, 0x65, 0xd2, 0x0e, 0x26, 0xb6, 0x69, 0x4b, 0x41,
	0x42, 0x9c, 0x44, 0x6e, 0xfd, 0x2e, 0x0b, 0x24, 0x76, 0x6a, 0xbb, 0x2d, 0x3b, 0xe5, 0x12, 0xe0,
	0x36, 0x90, 0xb8, 0x18, 0x2e, 0x00, 0x09, 0x71, 0x21, 0x28, 0xce, 0x9f, 0x76, 0x5b, 0x39, 0x6a,
	0xfd, 0x3c, 0x3f, 0x3f, 0xce, 0xfb, 0xe6, 0x8d, 0x11, 0x89, 0x28, 0xa7, 0x3e, 0x44, 0xc0, 0x75,
	0x3c, 0xb4, 0xa3, 0x1b, 0x35, 0x0e, 0xad, 0x58, 0x0a, 0x2d, 0x30, 0x9a, 0x3b, 0xed, 0x57, 0x7e,
	0xa0, 0xaf, 0x27, 0x43, 0x6b, 0x24, 0x22, 0x3b, 0x9a, 0x05, 0xfa, 0x93, 0x98, 0xd9, 0xbe, 0xe8,
	0x1b, 0xb0, 0x3f, 0xa5, 0x61, 0xc0, 0xa8, 0x16, 0x52, 0xd9, 0xc5, 0xdf, 0x34, 0xa3, 0xbd, 0xe5,
	0x0b, 0xe1, 0x87, 0x60, 0xd3, 0x38, 0xb0, 0x29, 0xe7, 0x42, 0x53, 0x1d, 0x08, 0xae, 0x32, 0x97,
	0x04, 0x7c, 0x0a, 0x5c, 0x0b, 0x79, 0x13, 0x0f, 0x6d, 0xea, 0x03, 0xd7, 0xb9, 0xd3, 0x5e, 0x74,
	0x14, 0xc8, 0x69, 0x30, 0x82, 0xdc, 0x7b, 0x6e, 0x7e, 0x46, 0x7d, 0x1f, 0x78, 0x5f, 0xcd, 0xa8,
	0xef, 0x83, 0xb4, 0x45, 0x6c, 0x72, 0xef, 0x9f, 0xd1, 0xfd, 0x51, 0x41, 0x2d, 0x87, 0xb1, 0xb3,
	0x9b, 0xc1, 0xe5, 0xa9, 0x0b, 0xe3, 0x09, 0x28, 0x8d, 0xb7, 0x51, 0x8d, 0x0b, 0x06, 0x5e, 0xc0,
	0x48, 0xa9, 0x53, 0xea, 0xad, 0x1d, 0x55, 0x7f, 0xff, 0xda, 0x2e, 0xbf, 0x2f, 0xb9, 0xd5, 0x44,
	0x3e, 0x61, 0x78, 0x0f, 0x35, 0xb3, 0x43, 0x3d, 0x4e, 0x23, 0x20, 0xe5, 0x5b, 0x54, 0x23, 0xf3,
	0xce, 0x69, 0x04, 0xb8, 0x83, 0x6a, 0x94, 0x31, 0x09, 0x4a, 0x91, 0x95, 0x5b, 0x54, 0x2e, 0xe3,
	0x36, 0xaa, 0xc4, 0x42, 0x6a, 0x52, 0xe9, 0x94, 0x7a, 0xeb, 0xa9, 0xbd, 0xf9, 0x9f, 0x6b, 0x34,
	0xdc, 0x43, 0xcd, 0x38, 0x8a, 0x3c, 0x53, 0x7b, 0xf2, 0x38, 0xab, 0xb7, 0x22, 0x50, 0x1c, 0x45,
	0x4e, 0x62, 0x9d, 0x30, 0xdc, 0x41, 0x0d, 0xe0, 0xd3, 0x40, 0x0a, 0x9e, 0xbc, 0x10, 0x52, 0x4d,
	0x40, 0x77, 0x51, 0xc2, 0x04, 0xd5, 0x46, 0xe1, 0x44, 0x69, 0x90, 0xa4, 0x66, 0xdc, 0x7c, 0x89,
	0x77, 0x51, 0x4b, 0x42, 0x1c, 0x06, 0x23, 0xd3, 0x19, 0x4f, 0x81, 0x26, 0x75, 0x43, 0x6c, 0x2c,
	0xc8, 0x03, 0xd0, 0xb8, 0x8d, 0xea, 0x13, 0x05, 0xd2, 0xd4, 0xbc, 0x66, 0x88, 0x62, 0x9d, 0x78,
	0x31, 0x55, 0x6a, 0x26, 0x24, 0x23, 0x28, 0xf5, 0xf2, 0x35, 0x7e, 0x8a, 0x9a, 0x63, 0xca, 0xbd,
	0x62, 0x6f, 0x23, 0x7d, 0xba, 0x31, 0xe5, 0xef, 0xf2, 0xed, 0x19, 0x52, 0x44, 0x34, 0x0b, 0xe4,
	0x22, 0x4f, 0xd9, 0x45, 0x2d, 0x33, 0x7f, 0xcc, 0x83, 0xcf, 0x49, 0x77, 0x40, 0x92, 0xf5, 0x4e,
	0xa9, 0x57, 0x77, 0x37, 0x52, 0xf9, 0x38, 0x53, 0xf1, 0x0b, 0xf4, 0x20, 0xc9, 0x32, 0xaa, 0x17,
	0x83, 0xbc, 0x52, 0xa3, 0x6b, 0x88, 0x28, 0xd9, 0x30, 0x34, 0x1e, 0x53, 0x7e, 0x96, 0x58, 0x17,
	0x85, 0x83, 0xf7, 0xd1, 0xff, 0xf3, 0x1d, 0x2a, 0x14, 0xb3, 0x50, 0xf8, 0xa4, 0x65, 0xf0, 0x56,
	0x8e, 0x0f, 0x52, 0xb9, 0xfb, 0xbd, 0x8c, 0x36, 0xe7, 0x13, 0xa3, 0x62, 0xc1, 0x15, 0xe0, 0x03,
	0x54, 0xcb, 0xde, 0xba, 0x19, 0x99, 0xc6, 0xe1, 0x43, 0xab, 0x18, 0x51, 0xcb, 0xa0, 0x83, 0xd4,
	0x76, 0x73, 0x0e, 0x1f, 0xdd, 0x2f, 0xa7, 0x6c, 0xb6, 0x3e, 0xba, 0xbb, 0xb5, 0xa8, 0xec, 0x5e,
	0xa5, 0x6f, 0xff, 0x51, 0xe9, 0x8a, 0x09, 0xea, 0x2e, 0x04, 0x5d, 0x3a, 0xe7, 0x26, 0x2b, 0x29,
	0x7a, 0x60, 0x20, 0x33, 0x39, 0x4b, 0xbb, 0xf1, 0x66, 0x59, 0x37, 0x2a, 0x26, 0x72, 0x7b, 0x49,
	0x64, 0xd6, 0x98, 0x34, 0xef, 0x6e, 0xbb, 0x0e, 0x15, 0x5a, 0x35, 0x14, 0xfe, 0x88, 0xea, 0x79,
	0xdb, 0xf0, 0x63, 0x6b, 0x7e, 0x79, 0x58, 0x77, 0x3e, 0xbf, 0xf6, 0xd6, 0x72, 0x33, 0xed, 0x74,
	0x77, 0xe7, 0xcb, 0xcf, 0x3f, 0xdf, 0xca, 0x4f, 0xba, 0xc4, 0x9e, 0x1e, 0xd8, 0x73, 0xd0, 0x36,
	0x94, 0xed, 0x30, 0xf6, 0xba, 0xb4, 0x7f, 0xe4, 0x7d, 0x75, 0xce, 0xdd, 0x53, 0x54, 0x63, 0x70,
	0x45, 0x27, 0xa1, 0xc6, 0x0e, 0xc2, 0x0e, 0xef, 0x80, 0x94, 0x42, 0x76, 0x64, 0x96, 0x64, 0xe1,
	0x67, 0x68, 0xaf, 0xbd, 0xbb, 0x63, 0x33, 0xb8, 0x0a, 0x78, 0x90, 0x5e, 0x10, 0x8b, 0xb7, 0xdd,
	0x71, 0x82, 0xe7, 0xe7, 0x7e, 0x68, 0x2e, 0x5a, 0xc3, 0xaa, 0xb9, 0x3d, 0x5e, 0xfe, 0x0d, 0x00,
	0x00, 0xff, 0xff, 0xee, 0xa5, 0xee, 0x54, 0x1f, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MySQLClient is the client API for MySQL service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MySQLClient interface {
	// AddMySQL adds MySQL Service and starts several Agents.
	// It automatically adds a service to inventory, which is running on provided "node_id",
	// then adds "mysqld_exporter", and "qan_mysql_perfschema" agents
	// with provided "pmm_agent_id" and other parameters.
	AddMySQL(ctx context.Context, in *AddMySQLRequest, opts ...grpc.CallOption) (*AddMySQLResponse, error)
}

type mySQLClient struct {
	cc *grpc.ClientConn
}

func NewMySQLClient(cc *grpc.ClientConn) MySQLClient {
	return &mySQLClient{cc}
}

func (c *mySQLClient) AddMySQL(ctx context.Context, in *AddMySQLRequest, opts ...grpc.CallOption) (*AddMySQLResponse, error) {
	out := new(AddMySQLResponse)
	err := c.cc.Invoke(ctx, "/management.MySQL/AddMySQL", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MySQLServer is the server API for MySQL service.
type MySQLServer interface {
	// AddMySQL adds MySQL Service and starts several Agents.
	// It automatically adds a service to inventory, which is running on provided "node_id",
	// then adds "mysqld_exporter", and "qan_mysql_perfschema" agents
	// with provided "pmm_agent_id" and other parameters.
	AddMySQL(context.Context, *AddMySQLRequest) (*AddMySQLResponse, error)
}

func RegisterMySQLServer(s *grpc.Server, srv MySQLServer) {
	s.RegisterService(&_MySQL_serviceDesc, srv)
}

func _MySQL_AddMySQL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddMySQLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MySQLServer).AddMySQL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/management.MySQL/AddMySQL",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MySQLServer).AddMySQL(ctx, req.(*AddMySQLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MySQL_serviceDesc = grpc.ServiceDesc{
	ServiceName: "management.MySQL",
	HandlerType: (*MySQLServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddMySQL",
			Handler:    _MySQL_AddMySQL_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "managementpb/mysql.proto",
}
