{
 "title": "VictoriaMetrics",
 "description": "Overview for single node VictoriaMetrics v1.40.0 or higher",
 "tags": [
  "Percona",
  "Insight"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   { "name": "ds", "query": "prometheus" },
   {
    "name": "job",
    "query": {
     "query": "label_values(vm_app_version{version=~\"victoria-metrics-.*\"},job)"
    }
   },
   {
    "name": "version",
    "label": "/.*-tags-(v\\d+\\.\\d+\\.\\d+)/",
    "query": {
     "query": "label_values(vm_app_version{job=\"$job\", instance=\"$instance\"},  short_version)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(vm_app_version{job=~\"$job\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "VictoriaMetrics Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vm_app_uptime_seconds{job=\"$job\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Version",
   "type": "text",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 1 },
   "options": {
    "content": "<h4 style='color:#e68a00;font-weight:bold;text-align:center'>$version</h5>"
   }
  },
  {
   "title": "CPU Usage",
   "type": "stat",
   "description": "CPU Usage by VictoriaMetrics Process Only",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(process_cpu_seconds_total{job=\"$job\", instance=\"$instance\"}[$interval])) by () or sum(irate(process_cpu_seconds_total{job=\"$job\", instance=\"$instance\"}[5m])) by ()) / count(node_cpu_seconds_total{mode=\"user\", node_name=\"pmm-server\"})*100"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "description": "Memory Allocated and In use by VictoriaMetrics Process Only",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100*sum(go_memstats_alloc_bytes{job=\"$job\", instance=\"$instance\"}+go_memstats_stack_inuse_bytes{job=\"$job\", instance=\"$instance\"}) by () / \nsum(node_memory_MemTotal_bytes{node_name=\"pmm-server\"}) by ()"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "stat",
   "description": "Shows percent of occupied disk space by data points on the remaining disk space at `-storageDataPath`",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vm_data_size_bytes{job=\"$job\", instance=~\"$instance\"}) / (sum(vm_data_size_bytes{job=\"$job\", instance=~\"$instance\"}) + vm_free_disk_space_bytes{job=\"$job\", instance=\"$instance\"})",
     "legendFormat": "Value"
    }
   ]
  },
  {
   "title": "Total Datapoints",
   "type": "stat",
   "description": "How many datapoints are in storage",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vm_rows{job=\"$job\", instance=~\"$instance\", type!=\"indexdb\"})"
    }
   ]
  },
  {
   "title": "Index Size",
   "type": "stat",
   "description": "How many entries inverted index contains. This value is proportional to the number of unique timeseries in storage(cardinality).",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vm_rows{job=\"$job\", instance=~\"$instance\", type=~\"indexdb.*\"})"
    }
   ]
  },
  {
   "title": "Concurrent Inserts",
   "type": "stat",
   "description": "Shows how many ongoing insertions are taking place.\n* `max` - equal to number of CPU * 2\n* `current` - current number of goroutines busy with inserting rows into storage\n\nWhen `current` hits `max` constantly, it means storage is overloaded and require more CPU.",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vm_concurrent_insert_current{job=\"$job\", instance=\"$instance\"})/sum(vm_concurrent_insert_capacity{job=\"$job\", instance=\"$instance\"})",
     "legendFormat": "%"
    }
   ]
  },
  {
   "title": "Cache Memory Usage",
   "type": "stat",
   "description": "VictoriaMetrics stores various caches in RAM. Memory size for these caches may be limited with -`memory.allowedPercent` flag. Line `max allowed` shows max allowed memory size for cache.",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vm_cache_size_bytes{job=\"$job\", instance=\"$instance\"}) / max(vm_allowed_memory_bytes{job=\"$job\", instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Time before run out of space",
   "type": "stat",
   "description": "Estimated time of Disk usage based on trend",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_free_bytes{node_name=\"pmm-server\",mountpoint=~\"/srv|/\",fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"})/\nclamp_min(sum(node_filesystem_free_bytes{node_name=\"pmm-server\",mountpoint=~\"/srv|/\",fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"} - \npredict_linear(node_filesystem_free_bytes{node_name=\"pmm-server\", mountpoint=~\"/srv|/\",fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"}[1h], 1 * 3600)),0)"
    }
   ]
  },
  { "title": "Scraping", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Requests",
   "type": "graph",
   "description": "* `*` - unsupported query path\n* `/write` - insert into VM\n* `/metrics` - query VM system metrics\n* `/query` - query instant values\n* `/query_range` - query over a range of time\n* `/series` - match a certain label set\n* `/label/{}/values` - query a list of label values (variables mostly)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vm_http_requests_total{job=\"$job\", instance=~\"$instance\", path!~\"/favicon.ico\"}[$interval]) or irate(vm_http_requests_total{job=\"$job\", instance=~\"$instance\", path!~\"/favicon.ico\"}[5m])) by (path)",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Active Time Series Changes",
   "type": "graph",
   "description": "Shows increase/decrease of active time series with new data points inserted during the last hour. High value may result in ingestion slowdown. \n\nSee following link for details:",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(vm_cache_entries{job=\"$job\", instance=~\"$instance\", type=\"storage/hour_metric_ids\"}[$interval]) or increase(vm_cache_entries{job=\"$job\", instance=~\"$instance\", type=\"storage/hour_metric_ids\"}[5m])",
     "legendFormat": "Time Series"
    }
   ]
  },
  {
   "title": "Queries Duration",
   "type": "graph",
   "description": "The less time it takes is better.\n* `*` - unsupported query path\n* `/write` - insert into VM\n* `/metrics` - query VM system metrics\n* `/query` - query instant values\n* `/query_range` - query over a range of time\n* `/series` - match a certain label set\n* `/label/{}/values` - query a list of label values (variables mostly)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (path) (max(vm_request_duration_seconds{job=\"$job\", instance=~\"$instance\"}) by (path, quantile) > 0)",
     "legendFormat": "{{quantile}} ({{path}})"
    }
   ]
  },
  {
   "title": "Queries Duration Details",
   "type": "graph",
   "description": "The less time it takes is better.\n* `*` - unsupported query path\n* `/write` - insert into VM\n* `/metrics` - query VM system metrics\n* `/query` - query instant values\n* `/query_range` - query over a range of time\n* `/series` - match a certain label set\n* `/label/{}/values` - query a list of label values (variables mostly)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(vm_request_duration_seconds{job=\"$job\", instance=~\"$instance\"}) by (path, quantile) > 0",
     "legendFormat": "{{quantile}} ({{path}})"
    }
   ]
  },
  {
   "title": "Cache Memory Usage",
   "type": "graph",
   "description": "VictoriaMetrics stores various caches in RAM. Memory size for these caches may be limited with -`memory.allowedPercent` flag. Line `max allowed` shows max allowed memory size for cache.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(vm_cache_size_bytes{job=\"$job\", instance=\"$instance\"}) / max(vm_allowed_memory_bytes{job=\"$job\", instance=\"$instance\"})",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "Cache Size",
   "type": "graph",
   "description": "VictoriaMetrics stores various caches in RAM. Memory size for these caches may be limited with -`memory.allowedPercent` flag. Line `max allowed` shows max allowed memory size for cache.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(vm_cache_size_bytes{job=\"$job\", instance=\"$instance\"})",
     "legendFormat": "Size"
    },
    {
     "expr": "max(vm_allowed_memory_bytes{job=\"$job\", instance=\"$instance\"})",
     "legendFormat": "Max Allowed"
    }
   ]
  },
  {
   "title": "Concurrent Inserts",
   "type": "graph",
   "description": "Shows how many ongoing insertions are taking place.\n* `max` - equal to number of CPU * 2\n* `current` - current number of goroutines busy with inserting rows into storage\n\nWhen `current` hits `max` constantly, it means storage is overloaded and require more CPU.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(vm_concurrent_insert_capacity{job=\"$job\", instance=\"$instance\"})",
     "legendFormat": "Max"
    },
    {
     "expr": "sum(vm_concurrent_insert_current{job=\"$job\", instance=\"$instance\"})",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Error Requests",
   "type": "graph",
   "description": "* `*` - unsupported query path\n* `/write` - insert into VM\n* `/metrics` - query VM system metrics\n* `/query` - query instant values\n* `/query_range` - query over a range of time\n* `/series` - match a certain label set\n* `/label/{}/values` - query a list of label values (variables mostly)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vm_http_request_errors_total{job=\"$job\", instance=\"$instance\"}[$interval]) or irate(vm_http_request_errors_total{job=\"$job\", instance=\"$instance\"}[5m])) by (path)",
     "legendFormat": "{{path}}"
    }
   ]
  },
  { "title": "Storage Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Disk Space Usage - Datapoints",
   "type": "graph",
   "description": "Shows amount of on-disk space occupied by data points and the remaining disk space at `-storageDataPath`",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "vm_data_size_bytes{job=\"$job\", instance=~\"$instance\", type!=\"indexdb\"}",
     "legendFormat": "Used - {{type}}"
    },
    {
     "expr": "vm_free_disk_space_bytes{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Disk Space Usage - Index",
   "type": "graph",
   "description": "Shows amount of on-disk space occupied by inverted index.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "vm_data_size_bytes{job=\"$job\", instance=~\"$instance\", type=~\"indexdb.*\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Datapoints Ingestions",
   "type": "graph",
   "description": "How many datapoints are inserted into storage per second",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vm_rows_inserted_total{job=\"$job\", instance=\"$instance\"}[$interval])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Pending Datapoints",
   "type": "graph",
   "description": "How many datapoints are in RAM queue waiting to be written into storage. The number of pending data points should be in the range from 0 to `2*<ingestion_rate>`, since VictoriaMetrics pushes pending data to persistent storage every second.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vm_pending_rows{job=\"$job\", instance=~\"$instance\", type=\"storage\"}",
     "legendFormat": "Datapoints"
    },
    {
     "expr": "vm_pending_rows{job=\"$job\", instance=~\"$instance\", type=\"indexdb\"}",
     "legendFormat": "Index Entries"
    }
   ]
  },
  {
   "title": "Datapoints",
   "type": "graph",
   "description": "Shows how many datapoints are in the storage and what is average disk usage per datapoint.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(vm_rows{job=\"$job\", instance=~\"$instance\", type != \"indexdb\"})",
     "legendFormat": "Total Datapoints"
    },
    {
     "expr": "sum(vm_data_size_bytes{job=\"$job\", instance=~\"$instance\", type!=\"indexdb\"}) / sum(vm_rows{job=\"$job\", instance=~\"$instance\", type != \"indexdb\"})",
     "legendFormat": "Datapoint Size"
    }
   ]
  },
  {
   "title": "LSM Parts",
   "type": "graph",
   "description": "Data parts of LSM tree.\nHigh number of parts could be an evidence of slow merge performance - check the resource utilization.\n* `indexdb` - inverted index\n* `storage/small` - recently added parts of data ingested into storage(hot data)\n* `storage/big` -  small parts gradually merged into big parts (cold data)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(vm_parts{job=\"$job\", instance=\"$instance\"}) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Active Merges",
   "type": "graph",
   "description": "The number of on-going merges in storage nodes.  It is expected to have high numbers for `storage/small` metric.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(vm_active_merges{job=\"$job\", instance=\"$instance\"}) by(type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Merge speed",
   "type": "graph",
   "description": "The number of rows merged per second by storage nodes.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vm_rows_merged_total{job=\"$job\", instance=\"$instance\"}[$interval])) by(type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 } },
  {
   "title": "TCP Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vm_tcplistener_conns{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Troubleshooting", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 } },
  {
   "title": "Ignored Rows",
   "type": "graph",
   "description": "Shows how many rows were ignored on insertion due to corrupted or out of retention timestamps.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(vm_rows_ignored_total{job=\"$job\", instance=\"$instance\"}) by (reason)",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Logging Messages",
   "type": "graph",
   "description": "Shows the rate of logging the messages by their level. Unexpected spike in rate is a good reason to check logs.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vm_log_messages_total{job=\"$job\", instance=\"$instance\"}[$interval]) or irate(vm_log_messages_total{job=\"$job\", instance=\"$instance\"}[5m])) by (level) ",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Churn Rate",
   "type": "graph",
   "description": "Shows how many of new time-series are created every second.  High churn rate tightly connected with database performance and may result in unexpected OOM's or slow queries. It is recommended to always keep an eye on this metric to avoid unexpected cardinality \"explosions\".\n\nGood references to read:\n* https://www.robustperception.io/cardinality-is-key\n* https://www.robustperception.io/using-tsdb-analyze-to-investigate-churn-and-cardinality",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vm_new_timeseries_created_total{job=\"$job\", instance=\"$instance\"}[$interval]))",
     "legendFormat": "Churn Rate"
    }
   ]
  },
  {
   "title": "Slow Queries",
   "type": "graph",
   "description": "Slow queries rate according to `search.logSlowQueryDuration` flag, which is `5s` by default.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 91 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(increase(vm_slow_queries_total{job=\"$job\", instance=\"$instance\"}[$interval]) or increase(vm_slow_queries_total{job=\"$job\", instance=\"$instance\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Slow Inserts",
   "type": "graph",
   "description": "The percentage of slow inserts comparing to total insertion rate.\n\nThe less value is better. If percentage remains high (>50%) during extended periods of time, then it is likely more RAM is needed for optimal handling of the current number of active time series. \n\nIn general, VictoriaMetrics requires ~1KB or RAM per active time series, so it should be easy calculating the required amounts of RAM for the current workload according to capacity planning docs. But the resulting number may be far from the real number because the required amounts of memory depends on may other factors such as the number of labels per time series and the length of label values.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 99 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vm_slow_row_inserts_total{job=\"$job\", instance=\"$instance\"}[$interval])) by (job) / sum(rate(vm_rows_inserted_total{job=\"$job\", instance=\"$instance\"}[$interval])) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 99 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(go_memstats_sys_bytes{job=\"$job\", instance=\"$instance\"}) + sum(vm_cache_size_bytes{job=\"$job\", instance=\"$instance\"})",
     "legendFormat": "requested from system"
    },
    {
     "expr": "sum(go_memstats_heap_inuse_bytes{job=\"$job\", instance=\"$instance\"}) + sum(vm_cache_size_bytes{job=\"$job\", instance=\"$instance\"})",
     "legendFormat": "heap inuse"
    },
    {
     "expr": "sum(go_memstats_stack_inuse_bytes{job=\"$job\", instance=\"$instance\"})",
     "legendFormat": "stack inuse"
    }
   ]
  },
  {
   "title": "Time Series",
   "type": "graph",
   "description": "Shows the number of active time series. High value may result in ingestion slowdown. ",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 107 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vm_cache_entries{job=\"$job\", instance=~\"$instance\"} > 0",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "Time Series Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 115 } },
  {
   "title": "Top 10 metrics by time series count",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 116 },
   "targets": [
    {
     "expr": "topk(10, count({__name__=~\".+\"})  by (__name__))",
     "legendFormat": "Metrics"
    }
   ]
  },
  {
   "title": "Top 10 hosts by time series count",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 116 },
   "targets": [
    {
     "expr": "topk(10, sum by (node_name) (count({__name__=~\".+\",instance!=\"pmm-server\"})  by (node_name) or \nlabel_replace(\nlabel_join(count({__name__=~\".+\",instance=\"pmm-server\"})  by (instance,node_name), \"node_name\", \",\",\"instance\"),\n\"node_name\", \"pmm-server\", \"node_name\", \"pmm-server\")\n))",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  { "title": "VictoriaMetrics Settings", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 128 } },
  {
   "title": "Flags",
   "type": "table-old",
   "description": "Run VM with `-help` flag to see all the available flags with description and default values",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 129 },
   "targets": [
    {
     "expr": "flag{job=\"$job\", instance=~\"$instance\", value!=\"secret\", value!=\"\"}"
    }
   ]
  },
  { "title": "System Level Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 139 } },
  {
   "title": "CPU Busy",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 140 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(clamp_max(sum by () (avg by (mode)((clamp_max(rate(node_cpu_seconds_total{node_name=~\"pmm-server\",mode!=\"idle\",mode!=\"iowait\",mode!=\"steal\"}[$interval]),1)))*100),100))"
    }
   ]
  },
  {
   "title": "Mem Avail",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 140 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg by (node_name) ((node_memory_MemAvailable_bytes{node_name=\"pmm-server\"} or (node_memory_MemFree_bytes{node_name=\"pmm-server\"} + node_memory_Buffers_bytes{node_name=\"pmm-server\"} + node_memory_Cached_bytes{node_name=\"pmm-server\"})) / node_memory_MemTotal_bytes{node_name=\"pmm-server\"} * 100)"
    }
   ]
  },
  {
   "title": "Disk Reads",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 140 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg by (node_name) (rate(node_vmstat_pgpgin{node_name=\"pmm-server\"}[$interval]) * 1024 or irate(node_vmstat_pgpgin{node_name=\"pmm-server\"}[5m]) * 1024)"
    }
   ]
  },
  {
   "title": "Disk Writes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 140 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg by (node_name) (rate(node_vmstat_pgpgout{node_name=\"pmm-server\"}[$interval]) * 1024 or irate(node_vmstat_pgpgout{node_name=\"pmm-server\"}[5m]) * 1024)"
    }
   ]
  },
  {
   "title": "Network IO",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 140 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg by (node_name) ((sum(rate(node_network_receive_bytes_total{node_name=\"pmm-server\", device!=\"lo\"}[$interval]) or irate(node_network_receive_bytes_total{node_name=\"pmm-server\", device!=\"lo\"}[5m]))) + (sum(rate(node_network_transmit_bytes_total{node_name=\"pmm-server\", device!=\"lo\"}[$interval]) or irate(node_network_transmit_bytes_total{node_name=\"pmm-server\", device!=\"lo\"}[5m]))))"
    }
   ]
  },
  {
   "title": "Sys Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 140 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg by (node_name) (node_time_seconds{node_name=\"pmm-server\"} - node_boot_time_seconds{node_name=\"pmm-server\"})"
    }
   ]
  }
 ]
}