@startuml "2 - PMM Containers"
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include resources/plantuml_styles.puml
HIDE_STEREOTYPE()
'title
caption PMM Client/PMM Server connections

System_Ext(monitored, "Monitored system", "Database, node or service")

Boundary(pmm_client, "PMM Client") {
    System(exporters, "exporters", "Collection of programs, one for each monitored system type")
    System(pmm_agent, "pmm-agent", "Invokes appropriate exporter on command")
    System(vmagent, "vmagent", "VictoriaMetrics agent")
}

Person_Ext(user, "User")

Boundary(pmm_server, "PMM Server") {
    System(pmm_managed, "pmm-managed", "Manages configuration, exposes API for other components")
    System(query_analytics, "Query Analytics", "Detailed database query data application")
    System(victoriametrics, "VictoriaMetrics", "Receives and stores metrics data (Prometheus-compatible)")
    System(grafana, "Grafana", "Data presentation")
}

Rel(user, grafana, "Uses")
Rel_R(monitored, pmm_agent, "Query Analytics metrics")
Rel(monitored, exporters, "Metrics")
BiRel_R(pmm_agent, pmm_managed, "Control API")
Rel(exporters, vmagent, " ")
Rel(pmm_agent, exporters, "Runs")
Rel(pmm_managed, query_analytics, " ")
Rel(pmm_managed, victoriametrics, " ")
Rel(query_analytics, grafana, " ")
Rel(victoriametrics, exporters, "Pulls from")
Rel(vmagent, victoriametrics, "Pushes to")

Lay_D(grafana, query_analytics)
Lay_R(pmm_managed, grafana)

@enduml
