' Map of documentation
' To export as image with clickable links:
'
' A) Using Visual Studio Code:
' 1. install PlantUML extension (https://marketplace.visualstudio.com/items?itemName=jebbs.plantuml)
' 2. Right click and choose 'Export current diagram'
' 3. Select 'svg' type
' 3. Copy out/resources/Map/PMM_Documentation_Map.svg to docs/_images
'
' B) Command line:
' 1. Download PlantUML jar file: https://sourceforge.net/projects/plantuml/files/plantuml.jar/download
' 2. cat resources/Map.puml | java -jar ~/Downloads/plantuml.jar -tsvg -pipe > docs/_images/PMM_Documentation_Map.svg
'
' For icons see https://plantuml.com/openiconic



@startmindmap "PMM_Documentation_Map"
title PMM Documentation Map
caption Click a link to jump to that section
skinparam Shadowing false
<style>
mindmapDiagram {
  node {
    FontSize 12
    BackgroundColor Orange
    RoundCorner 10
    Padding 5
    Margin 3
  }
}
</style>

*[#GreenYellow] <&home> [[index.html Welcome]]
** <&power-standby> [[setting-up/ Setting up]]
'*** [[setting-up/index.html Setting up: Overview]]
*** <&heart> [[setting-up/server/ Server]]
'****_ [[setting-up/server/ Setting up PMM Server: Overview]]
****_ [[setting-up/server/docker.html Docker]]
****_ [[setting-up/server/virtual-appliance.html Virtual Appliance]]
****_ [[setting-up/server/aws.html AWS Marketplace]]
*** <&laptop> [[setting-up/client/ Client]]
'****_ [[setting-up/client/ Setting up PMM Clients]]
****_ [[setting-up/client/docker.html Docker]]
****_ [[setting-up/client/mysql.html MySQL]]
****_ [[setting-up/client/percona-server.html Percona Server]]
****_ [[setting-up/client/mongodb.html MongoDB]]
****_ [[setting-up/client/postgresql.html PostgreSQL]]
****_ [[setting-up/client/proxysql.html ProxySQL]]
****_ [[setting-up/client/aws.html Amazon RDS]]
****_ [[setting-up/client/linux.html Linux]]
****_ [[setting-up/client/external.html External Services]]

** <&wrench> [[using/ Using]]
'***_ [[using/ Using: Overview]]
***_ [[using/interface.html User interface]]
***_ [[using/alerting.html Integrated Alerting]]
***_ [[using/query-analytics.html Query Analytics]]
*** [[using/platform/  Percona\nEnterprise\nPlatform]]
'***_ [[using/platform/ About Percona Enterprise Platform]]
****_ [[using/platform/security-threat-tool.html Security Threat Tool]]

** <&task> [[how-to/ How to]]
'***_ [[how-to/ How to: Overview]]
***_ [[how-to/configure.html Configure]]
***_ [[how-to/upgrade.html Upgrade]]
***_ [[how-to/secure.html Secure]]
***_ [[how-to/optimize.html Optimize]]

left side


** <&magnifying-glass> [[details/ Details]]
'***_ [[details/ Details: Overview]]
***_ [[details/architecture.html Architecture]]
*** <&graph> [[details/dashboards/ Dashboards]]
****_ [[details/dashboards/index.html#insight Insight]]
****_ [[details/dashboards/index.html#pmm PMM]]
****_ [[details/dashboards/index.html#os-dashboards OS]]
****_ [[details/dashboards/index.html#prometheus-dashboards Prometheus]]
****_ [[details/dashboards/index.html#mysql-dashboards MySQL]]
****_ [[details/dashboards/index.html#mongodb-dashboards MongoDB]]
****_ [[details/dashboards/index.html#postgresql-dashboards PostgreSQL]]
****_ [[details/dashboards/index.html#proxysql-dashboards ProxySQL]]
****_ [[details/dashboards/index.html#ha-dashboards HA]]

*** <&code> Commands
****_ [[details/commands/pmm-admin.html pmm-admin]]
****_ [[details/commands/pmm-agent.html pmm-agent]]
***_ [[details/api.html API]]
***_ [[details/victoria-metrics.html VictoriaMetrics]]
***_ [[details/glossary.html Glossary]]

** <&question-mark> [[faq.html FAQ]]

** <&bug> [[https://www.percona.com/doc/percona-monitoring-and-management/2.x/release-notes/ Release Notes]]
***_ [[https://www.percona.com/doc/percona-monitoring-and-management/2.x/release-notes/2.14.0.html 2.14.0 (LATEST)]]
***_ [[https://www.percona.com/doc/percona-monitoring-and-management/2.x/release-notes/2.13.0.html 2.13.0]]
***_ [[https://www.percona.com/doc/percona-monitoring-and-management/2.x/release-notes/2.12.0.html 2.12.0]]
***_ [[https://www.percona.com/doc/percona-monitoring-and-management/2.x/release-notes/2.11.0.html 2.11.0]]
****_ [[https://www.percona.com/doc/percona-monitoring-and-management/2.x/release-notes/2.11.1.html 2.11.1]]
***_ [[https://www.percona.com/doc/percona-monitoring-and-management/2.x/release-notes/2.10.0.html 2.10.0]]
****_ [[https://www.percona.com/doc/percona-monitoring-and-management/2.x/release-notes/2.10.1.html 2.10.1]]
***_ [[https://www.percona.com/doc/percona-monitoring-and-management/2.x/release-notes/2.9.0.html 2.9.0]]
****_ [[https://www.percona.com/doc/percona-monitoring-and-management/2.x/release-notes/2.9.1.html 2.9.1]]
***_ [[https://www.percona.com/doc/percona-monitoring-and-management/2.x/release-notes/2.8.0.html 2.8.0]]
***_ [[https://www.percona.com/doc/percona-monitoring-and-management/2.x/release-notes/2.7.0.html 2.7.0]]
***_ [[https://www.percona.com/doc/percona-monitoring-and-management/2.x/release-notes/2.6.0.html 2.6.0]]
***_ [[https://www.percona.com/doc/percona-monitoring-and-management/2.x/release-notes/2.5.0.html 2.5.0]]
***_ [[https://www.percona.com/doc/percona-monitoring-and-management/2.x/release-notes/2.4.0.html 2.4.0]]
***_ [[https://www.percona.com/doc/percona-monitoring-and-management/2.x/release-notes/2.3.0.html 2.3.0]]
***_ [[https://www.percona.com/doc/percona-monitoring-and-management/2.x/release-notes/2.2.0.html 2.2.0]]
****_ [[https://www.percona.com/doc/percona-monitoring-and-management/2.x/release-notes/2.2.1.html 2.2.1]]
****_ [[https://www.percona.com/doc/percona-monitoring-and-management/2.x/release-notes/2.2.2.html 2.2.2]]
***_ [[https://www.percona.com/doc/percona-monitoring-and-management/2.x/release-notes/2.1.0.html 2.1.0]]
***_ [[https://www.percona.com/doc/percona-monitoring-and-management/2.x/release-notes/2.0.0.html 2.0.0]]
@endmindmap
