@startuml "PMM components - server"
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
!include resources/plantuml_styles.puml
HIDE_STEREOTYPE()
'LAYOUT_LEFT_RIGHT()
'title
caption PMM Server components

System_Ext(pmm_client, "PMM Client")

Boundary(pmm_server, "PMM Server") {

    System(pmm_managed, "pmm-managed", "")
    Boundary(query_analytics, "Query Analytics") {
        ComponentDb(clickhouse, "Storage", "clickhouse")
        System(qan_api, "API", "")
        System(qan_app, "Application", "")

    }
    Boundary(victoriametrics, "VictoriaMetrics") {
        ComponentDb(vmdb, "VictoriaMetrics", "")
    }
    System_Ext(grafana, "Grafana", "Data presentation")
    System_Ext(web_server, "Web server", "Nginx")
}

'Lay_R(pmm_managed, qan_api)
'Lay_D(pmm_managed, vmdb)
'Lay_R(monitored, pmm_client)
'Lay_R(pmm_client, pmm_server)
'Lay_R(victoriametrics, grafana)
'Lay_R(grafana, web_server)
'Lay_D(query_analytics, grafana)

'Rel(web_server, pmm_client, "")

Rel(pmm_client, victoriametrics, " ")
Rel(pmm_managed, victoriametrics, " ")
Rel(pmm_managed, qan_api, " ")
Rel(qan_api, clickhouse, " ")
Rel(grafana, qan_app, " ")
Rel(qan_app, qan_api, " ")
Rel(grafana, web_server, " ")
'BiRel_L(pmm_managed, pmm_client, " ")
BiRel(pmm_client, pmm_managed, " ")

@enduml
