@startuml "PMM components - client"
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
!include resources/plantuml_styles.puml
HIDE_STEREOTYPE()
LAYOUT_LEFT_RIGHT()
'title PMM Client/PMM Server connections
caption PMM Client components

Boundary(pmm_client, "PMM Client") {
    Container_Boundary(exporters, "exporters") {
        Component(rds_exporter, "rds_exporter", "")
        Component(node_exporter, "node_exporter", "")
        Component(mysqld_exporter, "mysqld_exporter", "")
        Component(mongodb_exporter, "mongodb_exporter", "")
        Component(postgres_exporter, "postgres_exporter", "")
        Component(proxysql_exporter, "proxysql_exporter", "")
    }
    System(pmm_admin, "pmm-admin", "Command-line administration tool")
    System(pmm_agent, "pmm-agent", "Agent invokes relevant exporter when instructed")
    System(vmagent, "vmagent", "VictoriaMetrics agent pushes data to PMM Server")
}
System_Ext(pmm_server, "PMM Server")

Rel(rds_exporter, vmagent, " ")
Rel(mysqld_exporter, vmagent, " ")
Rel(mongodb_exporter, vmagent, " ")
Rel(postgres_exporter, vmagent, " ")
Rel(proxysql_exporter, vmagent, " ")
Rel(node_exporter, vmagent, " ")

Rel(pmm_agent, rds_exporter, " ")
Rel(pmm_agent, mysqld_exporter, " ")
Rel(pmm_agent, mongodb_exporter, " ")
Rel(pmm_agent, postgres_exporter, " ")
Rel(pmm_agent, proxysql_exporter, " ")
Rel(pmm_agent, node_exporter, " ")

Rel(pmm_agent, pmm_server, " ")
Rel(vmagent, pmm_server, "Push")
Rel(pmm_server, exporters, "Pull")

Rel(pmm_admin, pmm_agent, " ")
@enduml
