' Diagram showing sequence of tasks to set up Integrated Alerting
' Not published (WIP)
@startuml
skinparam Shadowing false
skinparam ConditionEndStyle hline

|//PMM Settings//|
start
:Activate //Integrated Alerting//;

if (//Communication// settings) then
    :Email;
else
    :Slack;
endif

|//Integrated Alerting//|
:Add //Notification Channel//;

if (Alert Rule Template?) then
    :Select;
else
    |Server|
    -[dashed]->
    :Create;
    note right
        Edit on filesystem
    end note

    -[dashed]->
endif

|//Integrated Alerting//|


:Add //Alert Rule//;




stop
@enduml
