CREATE USER IF NOT EXISTS 'pmm'@'%' IDENTIFIED BY 'pmm';

GRANT SELECT, PROCESS, RELOAD, LOCK TABLES, REPLICATION CLIENT, BACKUP_ADMIN ON *.* TO 'pmm'@'%';
GRANT SELECT ON performance_schema.* TO 'pmm'@'%';

ALTER USER 'pmm'@'%' WITH MAX_USER_CONNECTIONS 10;
FLUSH PRIVILEGES;
