---
# We already have nginx package in epel repo
- name: Add Nginx repository
  yum_repository:
    name: nginx
    description: nginx repo
    baseurl: http://nginx.org/packages/centos/7/$basearch/
    gpgcheck: no
    enabled: no

- name: Create directories for nginx
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - /usr/share/pmm-server/static/
    - /etc/nginx/conf.d/
    - /etc/nginx/ssl/

- name: Install nginx rpm          | Install nginx rpm
  yum:
    name: nginx-1.20.1
    state: installed

- name: Add ssl-related files and scripts
  copy:
    src: "ssl/{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: '{{ item.mode }}'
  loop:
    - { src: ca-certs.pem, dest:  /etc/nginx/ssl/ca-certs.pem, mode: 'u=rw,g=r,o=r' }
    - { src: certificate.conf, dest:  /etc/nginx/ssl/certificate.conf, mode: 'u=rw,g=r,o=r' }
    - { src: dhparam.pem, dest:  /etc/nginx/ssl/dhparam.pem, mode: 'u=rw,g=r,o=r' }
    - { src: generate-ssl-certificate, dest: /var/lib/cloud/scripts/per-boot/generate-ssl-certificate, mode: 'u=rwx,g=rx,o=rx' }
    - { src: upgrade-certificate, dest: /var/lib/cloud/scripts/per-boot/upgrade-certificate, mode: 'u=rwx,g=rx,o=rx' }

- name: NGINX                       | Copy nginx configs
  copy:
    src: "{{ item }}"
    dest: "/etc/nginx/{{ item }}"
    mode: 0644
  loop:
    - "nginx.conf"
    - "conf.d/pmm-ssl.conf"
    - "conf.d/pmm.conf"

- name: NGINX SSL Certificate      | Check certificate file
  stat:
    path: /srv/nginx/certificate.crt
  register: certificate_file

- name: NGINX SSL Certificate      | Generate certificate
  when: not certificate_file.stat.exists
  command: /var/lib/cloud/scripts/per-boot/generate-ssl-certificate

- name: Remove default.conf
  file:
    path: /etc/nginx/conf.d/default.conf
    state: absent

- name: Check nginx configuration
  command: nginx -t
  changed_when: False

- name: Copy local-rss.xml file
  copy:
    src: local-rss.xml
    dest: /usr/share/pmm-server/static/
    mode: 0644

- name: Restart nginx
  command: supervisorctl {{ item }} nginx
  changed_when: True
  loop:
    - "stop"
    - "remove"
    - "add"
