{
 "title": "PostgreSQL Instance",
 "tags": [
  "Percona",
  "PostgreSQL"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "node_name",
    "label": "Node Name",
    "query": {
     "query": "label_values(pg_up{service_name=~\"$service_name\"},node_name)"
    }
   },
   {
    "name": "service_name",
    "label": "Service Name",
    "query": {
     "query": "label_values(pg_up, service_name)"
    }
   },
   {
    "name": "database",
    "label": "DB",
    "query": {
     "query": "label_values(pg_stat_database_tup_fetched{service_name=~\"$service_name\",datname!~\"template.*\"},datname)"
    }
   },
   {
    "name": "version",
    "query": {
     "query": "label_values(pg_static{service_name=~\"$service_name\"},version)"
    }
   },
   {
    "name": "service_type",
    "label": "Type",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, service_type)"
    }
   },
   {
    "name": "uptime",
    "query": {
     "query": "query_result(pg_postmaster_uptime_seconds{service_name=~\"$service_name\"}/60/60/24)"
    }
   },
   {
    "name": "slowq",
    "label": "slowq",
    "query": "SELECT count(*)\n   FROM pmm.metrics\n   WHERE service_name = '${service_name}'\n     AND ( period_start  >= $__fromTime AND period_start <= $__toTime )\n    AND m_query_time_sum/m_query_time_cnt > ${qthres}"
   },
   { "name": "qthres", "label": "Query Time", "query": "0.001,0.010,0.100,1,10" },
   {
    "name": "rangeCustom",
    "query": "select ($__toTime - $__fromTime)/60"
   },
   {
    "name": "currentConn",
    "query": {
     "query": "query_result(sum(pg_stat_activity_count{service_name=\"$service_name\"}))"
    }
   },
   {
    "name": "activeConn",
    "query": {
     "query": "query_result(sum(pg_stat_activity_count{service_name=\"$service_name\",state=\"active\"}))"
    }
   },
   {
    "name": "node_id",
    "label": "Node ID",
    "query": {
     "query": "label_values(pg_up{service_name=~\"$service_name\"},node_id)"
    }
   },
   { "name": "uptimedecimal", "query": "select round($uptime, 2)" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "options": {
    "content": " <div style=\"\n          color: white; \n          font-family: -apple-system, BlinkMacSystemFont, Helvetica Neue,Helvetica,Arial,sans-serif; \n          letter-spacing: 0.011em; \n          font-weight: 600;\n          font-size: 16px;\n          -webkit-font-smoothing: antialiased;\n          background: #373B44;  /* fallback for old browsers */\n          background: -webkit-linear-gradient(to right, #4286f4, #373B44);  /* Chrome 10-25, Safari 5.1-6 */\n          background: linear-gradient(to right, #4286f4, #373B44); /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */\n          border: 0px solid #ffffff;\n          border-radius: 10px;\n          padding: 10px;\n          display:block;\n          width:100%;\n          height:240px;\n          \"> <span style=\"\n          color: #eddea4; \n          font-size: 35px;\n          \"> ${service_name} </span><br/>\n          Version: $version\n          <br/>Uptime: ${uptimedecimal} days\n          <br/>Server: <a href=\"/graph/d/node-instance-summary/node-summary?var-node_name=$node_name\" target=\"_blank\">$node_name</a>\n          </div>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 0 },
   "options": {
    "content": " <div style=\"\n          color: #FFFFFF; \n          font-family: -apple-system, BlinkMacSystemFont, Helvetica Neue,Helvetica,Arial,sans-serif; \n          letter-spacing: 0.011em; \n          font-weight: 600;\n          font-size: 15px;\n          -webkit-font-smoothing: antialiased;\n          border: 0px solid #ffffff;\n          border-radius: 10px;\n          background: #141E30;  /* fallback for old browsers */\n          background: -webkit-linear-gradient(to right, #243B55, #141E30);  /* Chrome 10-25, Safari 5.1-6 */\n          background: linear-gradient(to right, #243B55, #141E30); /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */\n          padding: 5px;\n          display:block;\n          width:100%;\n          height:85px;\n          \"> <span style=\"\n          color: #FBEEC1; \n          font-size: 23px;\n          \"> ${currentConn} </span>Open Connections\n          <br/><span style=\"\n          color: #FBEEC1; \n          font-size: 23px;\n          \">${activeConn} </span>Active Connections\n          </div>"
   }
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (service_name,state) (sum(max_over_time(pg_stat_activity_count{service_name=~\"$service_name\",datname=~\"$database\"}[$interval]) or\nmax_over_time(pg_stat_activity_count{service_name=~\"$service_name\",datname=~\"$database\"}[1m])) by (state))",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "sum(max_over_time(pg_stat_activity_count{service_name=~\"$service_name\",datname=~\"$database\"}[$interval]) or\nmax_over_time(pg_stat_activity_count{service_name=~\"$service_name\",datname=~\"$database\"}[1m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Connections per Database",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (datname )(pg_stat_activity_count{service_name=\"$service_name\", datname!~\"template0|template1\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 3 },
   "options": {
    "content": " <div style=\"\n          color: #FFFFFF; \n          font-family: -apple-system, BlinkMacSystemFont, Helvetica Neue,Helvetica,Arial,sans-serif; \n          letter-spacing: 0.011em; \n          font-weight: 600;\n          font-size: 16px;\n          -webkit-font-smoothing: antialiased;\n          border: 0px solid #ffffff;\n          border-radius: 10px;\n          background: #EECDA3;  /* fallback for old browsers */\n          background: -webkit-linear-gradient(to right, #EF629F, #EECDA3);  /* Chrome 10-25, Safari 5.1-6 */\n          background: linear-gradient(to right, #EF629F, #EECDA3); /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */\n          padding: 10px;\n          display:block;\n          width:100%;\n          height:124px;\n          \"> <span style=\"\n          color: #FBEEC1; \n          font-size: 27px;\n          \"> ${slowq} </span>Queries slower than ${qthres} sec(s) <br/>In the last ${rangeCustom} minutes*\n          </br><span style=\"font-size: 9px;\">*Not real time. QAN is expected to have some minutes of lag</span></div>"
   }
  },
  {
   "title": "QPS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(5, avg by (datname) (rate(pg_stat_database_xact_commit{service_name=~\"$service_name\", datname!~\"template1|template0\"}[$interval])))",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Number of Locks",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "conflicts",
     "expr": "avg by (service_name,datname,mode) (max_over_time(pg_locks_count{datname=~\"$database\",service_name=~\"$service_name\",datname!~\"template.*\",datid!=\"0\"}[$interval]) or\nmax_over_time(pg_locks_count{datname=~\"$database\",service_name=~\"$service_name\",datname!~\"template.*\",datid!=\"0\"}[5m]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{mode}} - {{datname}}",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "conflicts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "node_name", "operator": "=~", "value": "/^$node_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Tuples",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_tup_fetched{service_name=~\"$service_name\"}[$interval])) or\nsum(irate(pg_stat_database_tup_fetched{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Fetched"
    },
    {
     "expr": "sum(rate(pg_stat_database_tup_returned{service_name=~\"$service_name\"}[$interval])) or\nsum(irate(pg_stat_database_tup_returned{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Returned"
    },
    {
     "expr": "sum(rate(pg_stat_database_tup_inserted{service_name=~\"$service_name\"}[$interval])) or\nsum(irate(pg_stat_database_tup_inserted{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Inserted"
    },
    {
     "expr": "sum(rate(pg_stat_database_tup_updated{service_name=~\"$service_name\"}[$interval])) or\nsum(irate(pg_stat_database_tup_updated{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Updated"
    },
    {
     "expr": "sum(rate(pg_stat_database_tup_deleted{service_name=~\"$service_name\"}[$interval])) or\nsum(irate(pg_stat_database_tup_deleted{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Deleted"
    }
   ]
  },
  {
   "title": "Queries",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(period_start) as time, service_name \"Service\", username, database, fingerprint \"Query\", avg(m_query_time_sum/m_query_time_cnt) \"Execution_time\" FROM pmm.\"metrics\" WHERE ( period_start  >= $__fromTime AND period_start <= $__toTime ) AND ( service_name LIKE '%$service_name%' ) GROUP BY service_name, username, database, fingerprint , m_query_time_sum, time ORDER BY time DESC LIMIT 10000",
     "selectedFormat": 1
    }
   ]
  },
  {
   "title": "Oldest Autovacuum",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "bottomk(3,pg_stat_user_tables_last_autovacuum{service_name=\"$service_name\"}[$interval]*1000)",
     "legendFormat": "{{datname}}.{{schemaname}}.{{relname}}"
    }
   ]
  },
  {
   "title": "Dead Tuples %",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(5,(pg_stat_user_tables_n_dead_tup{service_name=\"$service_name\"} * 100) / pg_stat_user_tables_n_live_tup{service_name=\"$service_name\"} AND (pg_stat_user_tables_n_live_tup{service_name=\"$service_name\"} > 10000))",
     "legendFormat": "{{datname}}.{{schemaname}}.{{relname}}"
    }
   ]
  },
  {
   "title": "Transaction Wraparound",
   "type": "timeseries",
   "description": "How close are databases to the autovacuum_freeze_max_age value",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(5, max by (datname) (pg_database_wraparound_age_datfrozenxid_seconds{service_name=~\"$service_name\", datname!~\"template1|template0\"}[$interval]))",
     "legendFormat": "{{datname}}"
    },
    {
     "expr": "pg_settings_autovacuum_freeze_max_age{service_name=~\"$service_name\"}",
     "legendFormat": "Autovacuum Freeze MAX age"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "description": "The CPU time is measured in clock ticks or seconds. It is useful to measure CPU time as a percentage of the CPU's capacity, which is called the CPU usage.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by (node_name,mode) (clamp_max(((avg by (mode,node_name) ( (clamp_max(rate(node_cpu_seconds_total{node_name=~\"$node_name\",mode!=\"idle\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{node_name=~\"$node_name\",mode!=\"idle\"}[5m]),1)) ))*100 or (avg_over_time(node_cpu_average{node_name=~\"$node_name\", mode=~\"user|system|wait|steal|irq|nice\"}[$interval]) or avg_over_time(node_cpu_average{node_name=~\"$node_name\", mode=~\"user|system|wait|steal|irq|nice\"}[5m]))),100))",
     "legendFormat": "{{ mode }}"
    }
   ]
  },
  {
   "title": "Disk IO Latency",
   "type": "timeseries",
   "description": "Shows average latency for Reads and Writes IO Devices.  Higher than typical latency for highly loaded storage indicates saturation (overload) and is frequent cause of performance problems.  Higher than normal latency also can indicate internal storage problems.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (node_name) ((sum by (node_name) (rate(node_disk_read_time_seconds_total{node_name=~\"$node_name\"}[$interval])) / sum by (node_name) (rate(node_disk_reads_completed_total{node_name=~\"$node_name\"}[$interval]) > 0 )) or (sum by (node_name) (irate(node_disk_read_time_seconds_total{node_name=~\"$node_name\"}[1m])) / \nsum by (node_name) (irate(node_disk_reads_completed_total{node_name=~\"$node_name\"}[1m]) > 0 ))\nor avg_over_time(aws_rds_read_latency_average{node_name=~\"$node_name\"}[$interval])/1000 or avg_over_time(aws_rds_read_latency_average{node_name=~\"$node_name\"}[1m])/1000 or\navg_over_time(rdsosmetrics_diskIO_readLatency{node_name=~\"$node_name\"}[$interval])/1000 or avg_over_time(rdsosmetrics_diskIO_readLatency{node_name=~\"$node_name\"}[1m])/1000)",
     "legendFormat": "Read Latency"
    },
    {
     "expr": "avg by (node_name) ((sum by (node_name) (rate(node_disk_write_time_seconds_total{node_name=~\"$node_name\"}[$interval])) / sum by (node_name) (rate(node_disk_writes_completed_total{node_name=~\"$node_name\"}[$interval]) > 0 )) or (sum by (node_name) (irate(node_disk_write_time_seconds_total{node_name=~\"$node_name\"}[1m])) / \nsum by (node_name) (irate(node_disk_writes_completed_total{node_name=~\"$node_name\"}[1m]) > 0 ))\nor (avg_over_time(aws_rds_write_latency_average{node_name=~\"$node_name\"}[$interval])/1000 or avg_over_time(aws_rds_write_latency_average{node_name=~\"$node_name\"}[1m])/1000) or\n(avg_over_time(rdsosmetrics_diskIO_writeLatency{node_name=~\"$node_name\"}[$interval]) or avg_over_time(rdsosmetrics_diskIO_writeLatency{node_name=~\"$node_name\"}[1m]))/1000)",
     "legendFormat": "Write Latency"
    }
   ]
  }
 ]
}