{
 "title": "MongoDB Router Summary",
 "tags": [
  "MongoDB_HA",
  "Percona"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, environment)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(mongodb_mongod_replset_my_state{environment=~\"$environment\"},cluster)"
    }
   },
   {
    "name": "node_name",
    "query": {
     "query": "label_values(mongodb_mongos_sharding_shards_total{environment=~\"$environment\",cluster=~\"$cluster\",service_name=~\"$service_name\"}, node_name)"
    }
   },
   {
    "name": "service_name",
    "label": "Router",
    "query": {
     "query": "label_values(mongodb_mongos_sharding_shards_total{environment=~\"$environment\",cluster=~\"$cluster\"}, service_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Current Topology",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Routers",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "max by (service_name) (mongodb_up{environment=~\"$environment\", cluster=~\"$cluster\", service_name=~\"$service_name\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Overview - $node_name", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 }, "repeat": "node_name" },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by (node_name) (rate(node_cpu_seconds_total{node_name=~\"$node_name\",mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "{{ mode }}"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - avg(node_memory_MemAvailable_bytes{node_name=~\"$node_name\"})/ avg(node_memory_MemTotal_bytes{node_name=~\"$node_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk IO Utilization",
   "type": "gauge",
   "description": "The percentage of elapsed time the disk device was busy servicing I/O requests (reads or writes).\n\nA value approaching or at 100% over sustained periods means the disk is likely saturated. If the storage device supports parallelism (e.g. SSDs, NVMe, RAID), even high values may not always imply performance issues. \n\nAlways consider complementing this metric with I/O latency, queue length, and throughput to get the full picture.",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (node_name) (rate(node_disk_io_time_seconds_total{node_name=~\"$node_name\"}[$interval]) or irate(node_disk_io_time_seconds_total{node_name=~\"$node_name\"}[5m]))",
     "legendFormat": "{{ node_name }}"
    }
   ]
  },
  {
   "title": "Disk Space Utilization",
   "type": "gauge",
   "description": "Shows information about the disk space usage of the filesystem where MongoDB stores data",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(mongodb_dbstats_fsUsedSize{service_name=~\"$service_name\"})/ avg (mongodb_dbstats_fsTotalSize{service_name=~\"$service_name\"})",
     "legendFormat": "Total Size"
    }
   ]
  },
  {
   "title": "Disk IOPS",
   "type": "stat",
   "description": "Shows amount of physical IOs (reads and writes) different devices are serving. Spikes in number of IOs served often corresponds to performance problems due to IO subsystem overload.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (node_name) (sum(\n(rate(node_disk_reads_completed_total{node_name=~\"$node_name\"}[$interval]) or \nirate(node_disk_reads_completed_total{node_name=~\"$node_name\"}[5m]))\n))",
     "legendFormat": "Read"
    },
    {
     "calculatedInterval": "2m",
     "expr": "avg by (node_name) (sum(\n(rate(node_disk_writes_completed_total{node_name=~\"$node_name\"}[$interval]) or \nirate(node_disk_writes_completed_total{node_name=~\"$node_name\"}[5m])) \n))",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "sum by (node_name) (rate(node_network_receive_bytes_total{node_name=~\"$node_name\", device!=\"lo\"}[$interval])) or sum by (node_name) (irate(node_network_receive_bytes_total{node_name=~\"$node_name\", device!=\"lo\"}[5m])) or sum by (node_name) (max_over_time(rdsosmetrics_network_rx{node_name=~\"$node_name\"}[$interval])) or sum by (node_name) (max_over_time(rdsosmetrics_network_rx{node_name=~\"$node_name\"}[5m])) ",
     "legendFormat": "Inbound"
    },
    {
     "calculatedInterval": "2s",
     "expr": "sum by (node_name) (rate(node_network_transmit_bytes_total{node_name=~\"$node_name\", device!=\"lo\"}[$interval])) or sum by (node_name) (irate(node_network_transmit_bytes_total{node_name=~\"$node_name\", device!=\"lo\"}[5m])) or\nsum by (node_name) (max_over_time(rdsosmetrics_network_tx{node_name=~\"$node_name\"}[$interval])) or sum by (node_name) (max_over_time(rdsosmetrics_network_tx{node_name=~\"$node_name\"}[5m]))",
     "legendFormat": "Outbound"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "The parameter shows how long a system has been “up” and running without a shut down or restart.",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "mongodb_ss_uptime{node_name=~\"$node_name\"}"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "description": "Mongos version",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "avg by (service_name,mongodb) (mongodb_version_info{service_name=~\"$service_name\"})",
     "legendFormat": "{{mongodb}}"
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Command Operations",
   "type": "timeseries",
   "description": "Ops or Replicated Ops/sec classified by legacy wire protocol type (query, insert, update, delete, getmore). And (from the internal TTL threads) the docs deletes/sec by TTL indexes.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg by (legacy_op_type,service_name) (rate(mongodb_ss_opcountersRepl{service_name=~\"$service_name\", legacy_op_type!~\"(command|query|getmore)\"}[$interval]))",
     "legendFormat": "repl_{{legacy_op_type}} - {{service_name}}"
    },
    {
     "expr": "avg by (service_name) (rate(mongodb_ss_metrics_ttl_deletedDocuments{service_name=~\"$service_name\"}[$interval]))",
     "legendFormat": "ttl_delete - {{service_name}}"
    },
    {
     "expr": "avg by (legacy_op_type,service_name) (rate(mongodb_ss_opcounters{service_name=~\"$service_name\", legacy_op_type!=\"command\"}[$interval]))",
     "legendFormat": "{{legacy_op_type}} - {{service_name}}"
    }
   ]
  },
  {
   "title": "Queued Operations",
   "type": "timeseries",
   "description": "Operations queued due to a lock.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "max by (type,service_name) (mongodb_mongod_global_lock_current_queue{service_name=~\"$service_name\"})",
     "legendFormat": "{{type}} - {{service_name}}"
    }
   ]
  },
  {
   "title": "Operation Latencies",
   "type": "timeseries",
   "description": "Average latency of operations (classified by read, write, or (other) command)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "avg by (op_type,service_name) (rate(mongodb_ss_opLatencies_latency{service_name=~\"$service_name\"}[$interval]) / (rate(mongodb_ss_opLatencies_ops{service_name=~\"$service_name\"}[$interval]) > 0) or irate(mongodb_ss_opLatencies_latency{service_name=~\"$service_name\"}[5m]) / (irate(mongodb_ss_opLatencies_ops{service_name=~\"$service_name\"}[5m]) > 0))",
     "legendFormat": "{{op_type}} - {{service_name}}"
    }
   ]
  },
  {
   "title": "Average Connections",
   "type": "timeseries",
   "description": "MongoDB Connections",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "mongodb_ss_connections{service_name=~\"$service_name\",conn_type=~\"current\"}",
     "legendFormat": " Current - {{ service_name}}"
    },
    {
     "expr": "mongodb_ss_connections{service_name=~\"$service_name\",conn_type=~\"available\"}",
     "legendFormat": " Available - {{ service_name}}"
    },
    {
     "expr": "avg by(service_name)(mongodb_ss_connections{conn_type=\"current\", service_name=~\"$service_name\"}) - avg by(service_name)(mongodb_ss_connections{conn_type=\"active\", service_name=~\"$service_name\"})",
     "legendFormat": " Idle - {{ service_name }}"
    }
   ]
  },
  {
   "title": "Reads & Writes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by(service_name) (mongodb_ss_globalLock_activeClients_readers{service_name=~\"$service_name\"})",
     "legendFormat": "Active Readers - {{service_name}}"
    },
    {
     "expr": "avg by(service_name) (mongodb_ss_globalLock_activeClients_writers{service_name=~\"$service_name\"})",
     "legendFormat": "Active Writers - {{service_name}}"
    },
    {
     "expr": "avg by(service_name) (mongodb_ss_globalLock_currentQueue{service_name=~\"$service_name\",count_type=\"readers\"})",
     "legendFormat": "Queued Readers - {{service_name}}"
    },
    {
     "expr": "avg by(service_name) (mongodb_ss_globalLock_currentQueue{service_name=~\"$service_name\",count_type=\"writers\"})",
     "legendFormat": "Queued Writers - {{service_name}}"
    }
   ]
  },
  {
   "title": "Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Router Status",
     "type": "state-timeline",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max by (service_name) (mongodb_up{environment=~\"$environment\", cluster=~\"$cluster\", service_name=~\"$service_name\"})",
       "legendFormat": "{{service_name}}"
      }
     ]
    }
   ]
  }
 ]
}