// Code generated by go-swagger; DO NOT EDIT.

package object_details_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// GetQueryExampleReader is a Reader for the GetQueryExample structure.
type GetQueryExampleReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetQueryExampleReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetQueryExampleOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetQueryExampleDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetQueryExampleOK creates a GetQueryExampleOK with default headers values
func NewGetQueryExampleOK() *GetQueryExampleOK {
	return &GetQueryExampleOK{}
}

/*
GetQueryExampleOK describes a response with status code 200, with default header values.

A successful response.
*/
type GetQueryExampleOK struct {
	Payload *GetQueryExampleOKBody
}

func (o *GetQueryExampleOK) Error() string {
	return fmt.Sprintf("[POST /v0/qan/ObjectDetails/GetQueryExample][%d] getQueryExampleOk  %+v", 200, o.Payload)
}

func (o *GetQueryExampleOK) GetPayload() *GetQueryExampleOKBody {
	return o.Payload
}

func (o *GetQueryExampleOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
	o.Payload = new(GetQueryExampleOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetQueryExampleDefault creates a GetQueryExampleDefault with default headers values
func NewGetQueryExampleDefault(code int) *GetQueryExampleDefault {
	return &GetQueryExampleDefault{
		_statusCode: code,
	}
}

/*
GetQueryExampleDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type GetQueryExampleDefault struct {
	_statusCode int

	Payload *GetQueryExampleDefaultBody
}

// Code gets the status code for the get query example default response
func (o *GetQueryExampleDefault) Code() int {
	return o._statusCode
}

func (o *GetQueryExampleDefault) Error() string {
	return fmt.Sprintf("[POST /v0/qan/ObjectDetails/GetQueryExample][%d] GetQueryExample default  %+v", o._statusCode, o.Payload)
}

func (o *GetQueryExampleDefault) GetPayload() *GetQueryExampleDefaultBody {
	return o.Payload
}

func (o *GetQueryExampleDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
	o.Payload = new(GetQueryExampleDefaultBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*
GetQueryExampleBody GetQueryExampleRequest defines filtering of query examples for specific value of
// dimension (ex.: host=hostname1 or queryid=1D410B4BE5060972.
swagger:model GetQueryExampleBody
*/
type GetQueryExampleBody struct {
	// period start from
	// Format: date-time
	PeriodStartFrom strfmt.DateTime `json:"period_start_from,omitempty"`

	// period start to
	// Format: date-time
	PeriodStartTo strfmt.DateTime `json:"period_start_to,omitempty"`

	// dimension value: ex: queryid - 1D410B4BE5060972.
	FilterBy string `json:"filter_by,omitempty"`

	// one of dimension: queryid | host ...
	GroupBy string `json:"group_by,omitempty"`

	// labels
	Labels []*GetQueryExampleParamsBodyLabelsItems0 `json:"labels"`

	// limit
	Limit int64 `json:"limit,omitempty"`
}

// Validate validates this get query example body
func (o *GetQueryExampleBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validatePeriodStartFrom(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validatePeriodStartTo(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateLabels(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetQueryExampleBody) validatePeriodStartFrom(formats strfmt.Registry) error {
	if swag.IsZero(o.PeriodStartFrom) { // not required
		return nil
	}

	if err := validate.FormatOf("body"+"."+"period_start_from", "body", "date-time", o.PeriodStartFrom.String(), formats); err != nil {
		return err
	}

	return nil
}

func (o *GetQueryExampleBody) validatePeriodStartTo(formats strfmt.Registry) error {
	if swag.IsZero(o.PeriodStartTo) { // not required
		return nil
	}

	if err := validate.FormatOf("body"+"."+"period_start_to", "body", "date-time", o.PeriodStartTo.String(), formats); err != nil {
		return err
	}

	return nil
}

func (o *GetQueryExampleBody) validateLabels(formats strfmt.Registry) error {
	if swag.IsZero(o.Labels) { // not required
		return nil
	}

	for i := 0; i < len(o.Labels); i++ {
		if swag.IsZero(o.Labels[i]) { // not required
			continue
		}

		if o.Labels[i] != nil {
			if err := o.Labels[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("body" + "." + "labels" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("body" + "." + "labels" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this get query example body based on the context it is used
func (o *GetQueryExampleBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateLabels(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetQueryExampleBody) contextValidateLabels(ctx context.Context, formats strfmt.Registry) error {
	for i := 0; i < len(o.Labels); i++ {
		if o.Labels[i] != nil {
			if err := o.Labels[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("body" + "." + "labels" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("body" + "." + "labels" + "." + strconv.Itoa(i))
				}
				return err
			}
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetQueryExampleBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetQueryExampleBody) UnmarshalBinary(b []byte) error {
	var res GetQueryExampleBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
GetQueryExampleDefaultBody get query example default body
swagger:model GetQueryExampleDefaultBody
*/
type GetQueryExampleDefaultBody struct {
	// code
	Code int32 `json:"code,omitempty"`

	// message
	Message string `json:"message,omitempty"`

	// details
	Details []*GetQueryExampleDefaultBodyDetailsItems0 `json:"details"`
}

// Validate validates this get query example default body
func (o *GetQueryExampleDefaultBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateDetails(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetQueryExampleDefaultBody) validateDetails(formats strfmt.Registry) error {
	if swag.IsZero(o.Details) { // not required
		return nil
	}

	for i := 0; i < len(o.Details); i++ {
		if swag.IsZero(o.Details[i]) { // not required
			continue
		}

		if o.Details[i] != nil {
			if err := o.Details[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("GetQueryExample default" + "." + "details" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("GetQueryExample default" + "." + "details" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this get query example default body based on the context it is used
func (o *GetQueryExampleDefaultBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateDetails(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetQueryExampleDefaultBody) contextValidateDetails(ctx context.Context, formats strfmt.Registry) error {
	for i := 0; i < len(o.Details); i++ {
		if o.Details[i] != nil {
			if err := o.Details[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("GetQueryExample default" + "." + "details" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("GetQueryExample default" + "." + "details" + "." + strconv.Itoa(i))
				}
				return err
			}
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetQueryExampleDefaultBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetQueryExampleDefaultBody) UnmarshalBinary(b []byte) error {
	var res GetQueryExampleDefaultBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
GetQueryExampleDefaultBodyDetailsItems0 get query example default body details items0
swagger:model GetQueryExampleDefaultBodyDetailsItems0
*/
type GetQueryExampleDefaultBodyDetailsItems0 struct {
	// at type
	AtType string `json:"@type,omitempty"`
}

// Validate validates this get query example default body details items0
func (o *GetQueryExampleDefaultBodyDetailsItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this get query example default body details items0 based on context it is used
func (o *GetQueryExampleDefaultBodyDetailsItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetQueryExampleDefaultBodyDetailsItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetQueryExampleDefaultBodyDetailsItems0) UnmarshalBinary(b []byte) error {
	var res GetQueryExampleDefaultBodyDetailsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
GetQueryExampleOKBody GetQueryExampleResponse list of query examples.
swagger:model GetQueryExampleOKBody
*/
type GetQueryExampleOKBody struct {
	// query examples
	QueryExamples []*GetQueryExampleOKBodyQueryExamplesItems0 `json:"query_examples"`
}

// Validate validates this get query example OK body
func (o *GetQueryExampleOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateQueryExamples(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetQueryExampleOKBody) validateQueryExamples(formats strfmt.Registry) error {
	if swag.IsZero(o.QueryExamples) { // not required
		return nil
	}

	for i := 0; i < len(o.QueryExamples); i++ {
		if swag.IsZero(o.QueryExamples[i]) { // not required
			continue
		}

		if o.QueryExamples[i] != nil {
			if err := o.QueryExamples[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("getQueryExampleOk" + "." + "query_examples" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("getQueryExampleOk" + "." + "query_examples" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this get query example OK body based on the context it is used
func (o *GetQueryExampleOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateQueryExamples(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetQueryExampleOKBody) contextValidateQueryExamples(ctx context.Context, formats strfmt.Registry) error {
	for i := 0; i < len(o.QueryExamples); i++ {
		if o.QueryExamples[i] != nil {
			if err := o.QueryExamples[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("getQueryExampleOk" + "." + "query_examples" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("getQueryExampleOk" + "." + "query_examples" + "." + strconv.Itoa(i))
				}
				return err
			}
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetQueryExampleOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetQueryExampleOKBody) UnmarshalBinary(b []byte) error {
	var res GetQueryExampleOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
GetQueryExampleOKBodyQueryExamplesItems0 QueryExample shows query examples and their metrics.
swagger:model GetQueryExampleOKBodyQueryExamplesItems0
*/
type GetQueryExampleOKBodyQueryExamplesItems0 struct {
	// example
	Example string `json:"example,omitempty"`

	// ExampleType is a type of query example selected for this query class in given period of time.
	// Enum: [EXAMPLE_TYPE_UNSPECIFIED EXAMPLE_TYPE_RANDOM EXAMPLE_TYPE_SLOWEST EXAMPLE_TYPE_FASTEST EXAMPLE_TYPE_WITH_ERROR]
	ExampleType *string `json:"example_type,omitempty"`

	// is truncated
	IsTruncated int64 `json:"is_truncated,omitempty"`

	// placeholders count
	PlaceholdersCount int64 `json:"placeholders_count,omitempty"`

	// explain fingerprint
	ExplainFingerprint string `json:"explain_fingerprint,omitempty"`

	// query id
	QueryID string `json:"query_id,omitempty"`

	// example metrics
	ExampleMetrics string `json:"example_metrics,omitempty"`

	// service id
	ServiceID string `json:"service_id,omitempty"`

	// service type
	ServiceType string `json:"service_type,omitempty"`

	// schema
	Schema string `json:"schema,omitempty"`

	// tables
	Tables []string `json:"tables"`
}

// Validate validates this get query example OK body query examples items0
func (o *GetQueryExampleOKBodyQueryExamplesItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateExampleType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var getQueryExampleOkBodyQueryExamplesItems0TypeExampleTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["EXAMPLE_TYPE_UNSPECIFIED","EXAMPLE_TYPE_RANDOM","EXAMPLE_TYPE_SLOWEST","EXAMPLE_TYPE_FASTEST","EXAMPLE_TYPE_WITH_ERROR"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		getQueryExampleOkBodyQueryExamplesItems0TypeExampleTypePropEnum = append(getQueryExampleOkBodyQueryExamplesItems0TypeExampleTypePropEnum, v)
	}
}

const (

	// GetQueryExampleOKBodyQueryExamplesItems0ExampleTypeEXAMPLETYPEUNSPECIFIED captures enum value "EXAMPLE_TYPE_UNSPECIFIED"
	GetQueryExampleOKBodyQueryExamplesItems0ExampleTypeEXAMPLETYPEUNSPECIFIED string = "EXAMPLE_TYPE_UNSPECIFIED"

	// GetQueryExampleOKBodyQueryExamplesItems0ExampleTypeEXAMPLETYPERANDOM captures enum value "EXAMPLE_TYPE_RANDOM"
	GetQueryExampleOKBodyQueryExamplesItems0ExampleTypeEXAMPLETYPERANDOM string = "EXAMPLE_TYPE_RANDOM"

	// GetQueryExampleOKBodyQueryExamplesItems0ExampleTypeEXAMPLETYPESLOWEST captures enum value "EXAMPLE_TYPE_SLOWEST"
	GetQueryExampleOKBodyQueryExamplesItems0ExampleTypeEXAMPLETYPESLOWEST string = "EXAMPLE_TYPE_SLOWEST"

	// GetQueryExampleOKBodyQueryExamplesItems0ExampleTypeEXAMPLETYPEFASTEST captures enum value "EXAMPLE_TYPE_FASTEST"
	GetQueryExampleOKBodyQueryExamplesItems0ExampleTypeEXAMPLETYPEFASTEST string = "EXAMPLE_TYPE_FASTEST"

	// GetQueryExampleOKBodyQueryExamplesItems0ExampleTypeEXAMPLETYPEWITHERROR captures enum value "EXAMPLE_TYPE_WITH_ERROR"
	GetQueryExampleOKBodyQueryExamplesItems0ExampleTypeEXAMPLETYPEWITHERROR string = "EXAMPLE_TYPE_WITH_ERROR"
)

// prop value enum
func (o *GetQueryExampleOKBodyQueryExamplesItems0) validateExampleTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, getQueryExampleOkBodyQueryExamplesItems0TypeExampleTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (o *GetQueryExampleOKBodyQueryExamplesItems0) validateExampleType(formats strfmt.Registry) error {
	if swag.IsZero(o.ExampleType) { // not required
		return nil
	}

	// value enum
	if err := o.validateExampleTypeEnum("example_type", "body", *o.ExampleType); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this get query example OK body query examples items0 based on context it is used
func (o *GetQueryExampleOKBodyQueryExamplesItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetQueryExampleOKBodyQueryExamplesItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetQueryExampleOKBodyQueryExamplesItems0) UnmarshalBinary(b []byte) error {
	var res GetQueryExampleOKBodyQueryExamplesItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
GetQueryExampleParamsBodyLabelsItems0 MapFieldEntry allows to pass labels/dimensions in form like {"server": ["db1", "db2"...]}.
swagger:model GetQueryExampleParamsBodyLabelsItems0
*/
type GetQueryExampleParamsBodyLabelsItems0 struct {
	// key
	Key string `json:"key,omitempty"`

	// value
	Value []string `json:"value"`
}

// Validate validates this get query example params body labels items0
func (o *GetQueryExampleParamsBodyLabelsItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this get query example params body labels items0 based on context it is used
func (o *GetQueryExampleParamsBodyLabelsItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetQueryExampleParamsBodyLabelsItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetQueryExampleParamsBodyLabelsItems0) UnmarshalBinary(b []byte) error {
	var res GetQueryExampleParamsBodyLabelsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
