// Code generated by go-swagger; DO NOT EDIT.

package om_service

import (
	"context"
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// TriggerTopologyCollectionReader is a Reader for the TriggerTopologyCollection structure.
type TriggerTopologyCollectionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *TriggerTopologyCollectionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewTriggerTopologyCollectionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewTriggerTopologyCollectionDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewTriggerTopologyCollectionOK creates a TriggerTopologyCollectionOK with default headers values
func NewTriggerTopologyCollectionOK() *TriggerTopologyCollectionOK {
	return &TriggerTopologyCollectionOK{}
}

/*
TriggerTopologyCollectionOK describes a response with status code 200, with default header values.

A successful response.
*/
type TriggerTopologyCollectionOK struct {
	Payload *TriggerTopologyCollectionOKBody
}

// IsSuccess returns true when this trigger topology collection Ok response has a 2xx status code
func (o *TriggerTopologyCollectionOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this trigger topology collection Ok response has a 3xx status code
func (o *TriggerTopologyCollectionOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this trigger topology collection Ok response has a 4xx status code
func (o *TriggerTopologyCollectionOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this trigger topology collection Ok response has a 5xx status code
func (o *TriggerTopologyCollectionOK) IsServerError() bool {
	return false
}

// IsCode returns true when this trigger topology collection Ok response a status code equal to that given
func (o *TriggerTopologyCollectionOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the trigger topology collection Ok response
func (o *TriggerTopologyCollectionOK) Code() int {
	return 200
}

func (o *TriggerTopologyCollectionOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/om/topology/runs:collect][%d] triggerTopologyCollectionOk %s", 200, payload)
}

func (o *TriggerTopologyCollectionOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/om/topology/runs:collect][%d] triggerTopologyCollectionOk %s", 200, payload)
}

func (o *TriggerTopologyCollectionOK) GetPayload() *TriggerTopologyCollectionOKBody {
	return o.Payload
}

func (o *TriggerTopologyCollectionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
	o.Payload = new(TriggerTopologyCollectionOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewTriggerTopologyCollectionDefault creates a TriggerTopologyCollectionDefault with default headers values
func NewTriggerTopologyCollectionDefault(code int) *TriggerTopologyCollectionDefault {
	return &TriggerTopologyCollectionDefault{
		_statusCode: code,
	}
}

/*
TriggerTopologyCollectionDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type TriggerTopologyCollectionDefault struct {
	_statusCode int

	Payload *TriggerTopologyCollectionDefaultBody
}

// IsSuccess returns true when this trigger topology collection default response has a 2xx status code
func (o *TriggerTopologyCollectionDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this trigger topology collection default response has a 3xx status code
func (o *TriggerTopologyCollectionDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this trigger topology collection default response has a 4xx status code
func (o *TriggerTopologyCollectionDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this trigger topology collection default response has a 5xx status code
func (o *TriggerTopologyCollectionDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this trigger topology collection default response a status code equal to that given
func (o *TriggerTopologyCollectionDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the trigger topology collection default response
func (o *TriggerTopologyCollectionDefault) Code() int {
	return o._statusCode
}

func (o *TriggerTopologyCollectionDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/om/topology/runs:collect][%d] TriggerTopologyCollection default %s", o._statusCode, payload)
}

func (o *TriggerTopologyCollectionDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/om/topology/runs:collect][%d] TriggerTopologyCollection default %s", o._statusCode, payload)
}

func (o *TriggerTopologyCollectionDefault) GetPayload() *TriggerTopologyCollectionDefaultBody {
	return o.Payload
}

func (o *TriggerTopologyCollectionDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
	o.Payload = new(TriggerTopologyCollectionDefaultBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

/*
TriggerTopologyCollectionDefaultBody trigger topology collection default body
swagger:model TriggerTopologyCollectionDefaultBody
*/
type TriggerTopologyCollectionDefaultBody struct {
	// code
	Code int32 `json:"code,omitempty"`

	// message
	Message string `json:"message,omitempty"`

	// details
	Details []*TriggerTopologyCollectionDefaultBodyDetailsItems0 `json:"details"`
}

// Validate validates this trigger topology collection default body
func (o *TriggerTopologyCollectionDefaultBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateDetails(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *TriggerTopologyCollectionDefaultBody) validateDetails(formats strfmt.Registry) error {
	if swag.IsZero(o.Details) { // not required
		return nil
	}

	for i := 0; i < len(o.Details); i++ {
		if swag.IsZero(o.Details[i]) { // not required
			continue
		}

		if o.Details[i] != nil {
			if err := o.Details[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("TriggerTopologyCollection default" + "." + "details" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("TriggerTopologyCollection default" + "." + "details" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this trigger topology collection default body based on the context it is used
func (o *TriggerTopologyCollectionDefaultBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateDetails(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *TriggerTopologyCollectionDefaultBody) contextValidateDetails(ctx context.Context, formats strfmt.Registry) error {
	for i := 0; i < len(o.Details); i++ {
		if o.Details[i] != nil {

			if swag.IsZero(o.Details[i]) { // not required
				return nil
			}

			if err := o.Details[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("TriggerTopologyCollection default" + "." + "details" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("TriggerTopologyCollection default" + "." + "details" + "." + strconv.Itoa(i))
				}

				return err
			}
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *TriggerTopologyCollectionDefaultBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *TriggerTopologyCollectionDefaultBody) UnmarshalBinary(b []byte) error {
	var res TriggerTopologyCollectionDefaultBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
TriggerTopologyCollectionDefaultBodyDetailsItems0 trigger topology collection default body details items0
swagger:model TriggerTopologyCollectionDefaultBodyDetailsItems0
*/
type TriggerTopologyCollectionDefaultBodyDetailsItems0 struct {
	// at type
	AtType string `json:"@type,omitempty"`

	// trigger topology collection default body details items0
	TriggerTopologyCollectionDefaultBodyDetailsItems0 map[string]any `json:"-"`
}

// UnmarshalJSON unmarshals this object with additional properties from JSON
func (o *TriggerTopologyCollectionDefaultBodyDetailsItems0) UnmarshalJSON(data []byte) error {
	// stage 1, bind the properties
	var stage1 struct {
		// at type
		AtType string `json:"@type,omitempty"`
	}
	if err := json.Unmarshal(data, &stage1); err != nil {
		return err
	}
	var rcv TriggerTopologyCollectionDefaultBodyDetailsItems0

	rcv.AtType = stage1.AtType
	*o = rcv

	// stage 2, remove properties and add to map
	stage2 := make(map[string]json.RawMessage)
	if err := json.Unmarshal(data, &stage2); err != nil {
		return err
	}

	delete(stage2, "@type")
	// stage 3, add additional properties values
	if len(stage2) > 0 {
		result := make(map[string]any)
		for k, v := range stage2 {
			var toadd any
			if err := json.Unmarshal(v, &toadd); err != nil {
				return err
			}
			result[k] = toadd
		}
		o.TriggerTopologyCollectionDefaultBodyDetailsItems0 = result
	}

	return nil
}

// MarshalJSON marshals this object with additional properties into a JSON object
func (o TriggerTopologyCollectionDefaultBodyDetailsItems0) MarshalJSON() ([]byte, error) {
	var stage1 struct {
		// at type
		AtType string `json:"@type,omitempty"`
	}

	stage1.AtType = o.AtType

	// make JSON object for known properties
	props, err := json.Marshal(stage1)
	if err != nil {
		return nil, err
	}

	if len(o.TriggerTopologyCollectionDefaultBodyDetailsItems0) == 0 { // no additional properties
		return props, nil
	}

	// make JSON object for the additional properties
	additional, err := json.Marshal(o.TriggerTopologyCollectionDefaultBodyDetailsItems0)
	if err != nil {
		return nil, err
	}

	if len(props) < 3 { // "{}": only additional properties
		return additional, nil
	}

	// concatenate the 2 objects
	return swag.ConcatJSON(props, additional), nil
}

// Validate validates this trigger topology collection default body details items0
func (o *TriggerTopologyCollectionDefaultBodyDetailsItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this trigger topology collection default body details items0 based on context it is used
func (o *TriggerTopologyCollectionDefaultBodyDetailsItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *TriggerTopologyCollectionDefaultBodyDetailsItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *TriggerTopologyCollectionDefaultBodyDetailsItems0) UnmarshalBinary(b []byte) error {
	var res TriggerTopologyCollectionDefaultBodyDetailsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
TriggerTopologyCollectionOKBody TriggerTopologyCollectionResponse acknowledges a completed collection run.
swagger:model TriggerTopologyCollectionOKBody
*/
type TriggerTopologyCollectionOKBody struct {
	// The run's ID.
	RunID string `json:"run_id,omitempty"`

	// RunStatus is how a run ended, for both kinds of run.
	//
	// Shared by the topology collection pass and the inventory refresh deliberately: the two
	// runs differ in what they do, not in how they finish, and two identical enums would
	// invite them to drift apart for no reason.
	//
	//  - RUN_STATUS_RUNNING: Still going. Not a terminal status.
	//  - RUN_STATUS_SUCCESS: Everything it attempted answered.
	//  - RUN_STATUS_PARTIAL: Some of it did. The counts say which. For an inventory refresh this is the common
	// steady state rather than an alarm: a row routinely outlives the executor that served
	// it.
	//  - RUN_STATUS_FAILED: The run itself failed, as opposed to the things it was probing.
	//  - RUN_STATUS_SKIPPED: Refused before doing any work, because another refresh already held the hosts it
	// would have covered. Neither a failure nor a success: it did nothing, deliberately,
	// and it is recorded so a schedule cannot look like it fired and found nothing.
	//
	// Only an inventory refresh reaches this. The collection pass has a single-flight
	// guard too, but a refusal there never reaches a run row at all -- the RPC answers
	// Aborted (already running) or FailedPrecondition (not the HA leader) and nothing is
	// recorded, so this status never applies to it.
	// Enum: ["RUN_STATUS_UNSPECIFIED","RUN_STATUS_RUNNING","RUN_STATUS_SUCCESS","RUN_STATUS_PARTIAL","RUN_STATUS_FAILED","RUN_STATUS_SKIPPED"]
	Status *string `json:"status,omitempty"`

	// When the run began.
	// Format: date-time
	StartTime strfmt.DateTime `json:"start_time,omitempty"`
}

// Validate validates this trigger topology collection OK body
func (o *TriggerTopologyCollectionOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateStartTime(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var triggerTopologyCollectionOkBodyTypeStatusPropEnum []any

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["RUN_STATUS_UNSPECIFIED","RUN_STATUS_RUNNING","RUN_STATUS_SUCCESS","RUN_STATUS_PARTIAL","RUN_STATUS_FAILED","RUN_STATUS_SKIPPED"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		triggerTopologyCollectionOkBodyTypeStatusPropEnum = append(triggerTopologyCollectionOkBodyTypeStatusPropEnum, v)
	}
}

const (

	// TriggerTopologyCollectionOKBodyStatusRUNSTATUSUNSPECIFIED captures enum value "RUN_STATUS_UNSPECIFIED"
	TriggerTopologyCollectionOKBodyStatusRUNSTATUSUNSPECIFIED string = "RUN_STATUS_UNSPECIFIED"

	// TriggerTopologyCollectionOKBodyStatusRUNSTATUSRUNNING captures enum value "RUN_STATUS_RUNNING"
	TriggerTopologyCollectionOKBodyStatusRUNSTATUSRUNNING string = "RUN_STATUS_RUNNING"

	// TriggerTopologyCollectionOKBodyStatusRUNSTATUSSUCCESS captures enum value "RUN_STATUS_SUCCESS"
	TriggerTopologyCollectionOKBodyStatusRUNSTATUSSUCCESS string = "RUN_STATUS_SUCCESS"

	// TriggerTopologyCollectionOKBodyStatusRUNSTATUSPARTIAL captures enum value "RUN_STATUS_PARTIAL"
	TriggerTopologyCollectionOKBodyStatusRUNSTATUSPARTIAL string = "RUN_STATUS_PARTIAL"

	// TriggerTopologyCollectionOKBodyStatusRUNSTATUSFAILED captures enum value "RUN_STATUS_FAILED"
	TriggerTopologyCollectionOKBodyStatusRUNSTATUSFAILED string = "RUN_STATUS_FAILED"

	// TriggerTopologyCollectionOKBodyStatusRUNSTATUSSKIPPED captures enum value "RUN_STATUS_SKIPPED"
	TriggerTopologyCollectionOKBodyStatusRUNSTATUSSKIPPED string = "RUN_STATUS_SKIPPED"
)

// prop value enum
func (o *TriggerTopologyCollectionOKBody) validateStatusEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, triggerTopologyCollectionOkBodyTypeStatusPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (o *TriggerTopologyCollectionOKBody) validateStatus(formats strfmt.Registry) error {
	if swag.IsZero(o.Status) { // not required
		return nil
	}

	// value enum
	if err := o.validateStatusEnum("triggerTopologyCollectionOk"+"."+"status", "body", *o.Status); err != nil {
		return err
	}

	return nil
}

func (o *TriggerTopologyCollectionOKBody) validateStartTime(formats strfmt.Registry) error {
	if swag.IsZero(o.StartTime) { // not required
		return nil
	}

	if err := validate.FormatOf("triggerTopologyCollectionOk"+"."+"start_time", "body", "date-time", o.StartTime.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this trigger topology collection OK body based on context it is used
func (o *TriggerTopologyCollectionOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *TriggerTopologyCollectionOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *TriggerTopologyCollectionOKBody) UnmarshalBinary(b []byte) error {
	var res TriggerTopologyCollectionOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
