// Code generated by go-swagger; DO NOT EDIT.

package server

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PlatformSignOutReader is a Reader for the PlatformSignOut structure.
type PlatformSignOutReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PlatformSignOutReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPlatformSignOutOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPlatformSignOutDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPlatformSignOutOK creates a PlatformSignOutOK with default headers values
func NewPlatformSignOutOK() *PlatformSignOutOK {
	return &PlatformSignOutOK{}
}

/*PlatformSignOutOK handles this case with default header values.

A successful response.
*/
type PlatformSignOutOK struct {
	Payload interface{}
}

func (o *PlatformSignOutOK) Error() string {
	return fmt.Sprintf("[POST /v1/Platform/SignOut][%d] platformSignOutOk  %+v", 200, o.Payload)
}

func (o *PlatformSignOutOK) GetPayload() interface{} {
	return o.Payload
}

func (o *PlatformSignOutOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPlatformSignOutDefault creates a PlatformSignOutDefault with default headers values
func NewPlatformSignOutDefault(code int) *PlatformSignOutDefault {
	return &PlatformSignOutDefault{
		_statusCode: code,
	}
}

/*PlatformSignOutDefault handles this case with default header values.

An unexpected error response.
*/
type PlatformSignOutDefault struct {
	_statusCode int

	Payload *PlatformSignOutDefaultBody
}

// Code gets the status code for the platform sign out default response
func (o *PlatformSignOutDefault) Code() int {
	return o._statusCode
}

func (o *PlatformSignOutDefault) Error() string {
	return fmt.Sprintf("[POST /v1/Platform/SignOut][%d] PlatformSignOut default  %+v", o._statusCode, o.Payload)
}

func (o *PlatformSignOutDefault) GetPayload() *PlatformSignOutDefaultBody {
	return o.Payload
}

func (o *PlatformSignOutDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(PlatformSignOutDefaultBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*PlatformSignOutDefaultBody platform sign out default body
swagger:model PlatformSignOutDefaultBody
*/
type PlatformSignOutDefaultBody struct {

	// error
	Error string `json:"error,omitempty"`

	// code
	Code int32 `json:"code,omitempty"`

	// message
	Message string `json:"message,omitempty"`

	// details
	Details []*DetailsItems0 `json:"details"`
}

// Validate validates this platform sign out default body
func (o *PlatformSignOutDefaultBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateDetails(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PlatformSignOutDefaultBody) validateDetails(formats strfmt.Registry) error {

	if swag.IsZero(o.Details) { // not required
		return nil
	}

	for i := 0; i < len(o.Details); i++ {
		if swag.IsZero(o.Details[i]) { // not required
			continue
		}

		if o.Details[i] != nil {
			if err := o.Details[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("PlatformSignOut default" + "." + "details" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *PlatformSignOutDefaultBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PlatformSignOutDefaultBody) UnmarshalBinary(b []byte) error {
	var res PlatformSignOutDefaultBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
