{
 "title": "MySQL Group Replication Summary",
 "tags": [
  "Percona",
  "MySQL_HA"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "replication_set",
    "label": "Replication Set",
    "query": {
     "query": "label_values({__name__=~\"mysql_perf_schema_replication_group_member_info|mysql_perf_schema_replication_group_5_member_info\"}, replication_set)"
    }
   },
   {
    "name": "channel_name",
    "label": "Channel Name",
    "query": {
     "query": "label_values(mysql_perf_schema_replication_group_member_info, channel_name)"
    }
   },
   {
    "name": "service_name",
    "label": "Service Name",
    "query": {
     "query": "label_values(mysql_perf_schema_replication_group_member_info{channel_name=~\"$channel_name\"}, service_name)"
    }
   },
   {
    "name": "node_name",
    "label": "Node Name",
    "query": {
     "query": "label_values(mysql_up{service_name=~\"$service_name\"}, node_name)"
    }
   },
   {
    "name": "version",
    "query": {
     "query": "query_result(mysql_version_info{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, environment)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, cluster)"
    }
   },
   {
    "name": "database",
    "label": "Database",
    "query": {
     "query": "label_values(pg_stat_database_tup_fetched{service_name=~\"$service_name\",datname!~\"template.*|postgres\"},datname)"
    }
   },
   {
    "name": "node_type",
    "label": "Type",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, node_type)"
    }
   },
   {
    "name": "service_type",
    "label": "Type",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, service_type)"
    }
   },
   {
    "name": "schema",
    "label": "Schema",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, schema)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Group Replication Service States",
   "type": "state-timeline",
   "description": "There are various states that a server instance can be in. If servers are communicating properly, all report the same states for all servers. However, if there is a network partition, or a server leaves the group, then different information could be reported, depending on which server is queried. If the server has left the group then it cannot report updated information about the other servers' states. If there is a partition, such that quorum is lost, servers are not able to coordinate between themselves. As a consequence, they cannot guess what the status of different servers is. Therefore, instead of guessing their state they report that some servers are unreachable.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by (service_name) (mysql_perf_schema_replication_group_member_info{replication_set=~\"$replication_set\"} or mysql_perf_schema_replication_group_5_member_info{replication_set=~\"$replication_set\"})",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "PRIMARY Service",
   "type": "state-timeline",
   "description": "Notice: Collected for MySQL 8.x",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by (service_name) (mysql_perf_schema_replication_group_member_info{member_role=\"PRIMARY\",replication_set=~\"$replication_set\"})",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Replication Group Members",
   "type": "table",
   "description": "This table shows network and status information for replication group members. The network addresses shown are the addresses used to connect clients to the group, and should not be confused with the member's internal group communication address specified by group_replication_local_address.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "mysql_perf_schema_replication_group_member_info{replication_set=~\"$replication_set\"} or mysql_perf_schema_replication_group_5_member_info{replication_set=~\"$replication_set\"}",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Replication Delay Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Replication Lag",
     "type": "graph",
     "description": "Lag in seconds from when the LAST transaction is COMMITTED in the Primary and the time on local Replica.\n\nNotice: Collected for MySQL 8.x",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "(max by (service_name) (max_over_time(mysql_perf_schema_replication_group_worker_lag_in_seconds{replication_set=~\"$replication_set\"}[$interval]) or max_over_time(mysql_perf_schema_replication_group_worker_lag_in_seconds{replication_set=~\"$replication_set\"}[5m]))) and on(service_name) (mysql_perf_schema_replication_group_member_info{replication_set=~\"$replication_set\"} or mysql_perf_schema_replication_group_5_member_info{replication_set=~\"$replication_set\"})",
       "legendFormat": "{{service_name}}"
      }
     ]
    },
    {
     "title": "Transport Time",
     "type": "graph",
     "description": "Time difference from the moment the transaction is COMMITTED on the Primary and the time \ntransaction ENTER the local queue on the Replica.\n\nNotice: Collected for MySQL 8.x",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "(max by (service_name) (max_over_time(mysql_perf_schema_replication_group_worker_transport_time_seconds{replication_set=~\"$replication_set\"}[$interval]) or max_over_time(mysql_perf_schema_replication_group_worker_transport_time_seconds{replication_set=~\"$replication_set\"}[5m])) < 20202020) and on(service_name) (mysql_perf_schema_replication_group_member_info{replication_set=~\"$replication_set\"} or mysql_perf_schema_replication_group_5_member_info{replication_set=~\"$replication_set\"})",
       "legendFormat": "{{service_name}}"
      }
     ]
    },
    {
     "title": "Replication Delay",
     "type": "graph",
     "description": "Time difference from the moment the transaction has being COMMITTED on the Primary and the time transaction exit the queue to be apply in the local Replica.\n\nNotice: Collected for MySQL 8.x",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "(max by (service_name) (max_over_time(mysql_perf_schema_replication_group_worker_rep_delay_seconds{replication_set=~\"$replication_set\"}[$interval]) or max_over_time(mysql_perf_schema_replication_group_worker_rep_delay_seconds{replication_set=~\"$replication_set\"}[5m])) < 20202020) and on(service_name) (mysql_perf_schema_replication_group_member_info{replication_set=~\"$replication_set\"} or mysql_perf_schema_replication_group_5_member_info{replication_set=~\"$replication_set\"})",
       "legendFormat": "{{service_name}}"
      }
     ]
    },
    {
     "title": "Transaction Apply Time",
     "type": "graph",
     "description": "Time pass to apply the transaction on the local node.\n\nNotice: Collected for MySQL 8.x",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "(max by (service_name) (max_over_time(mysql_perf_schema_replication_group_worker_apply_time_seconds{replication_set=~\"$replication_set\"}[$interval]) or max_over_time(mysql_perf_schema_replication_group_worker_apply_time_seconds{replication_set=~\"$replication_set\"}[5m]))) and on(service_name) (mysql_perf_schema_replication_group_member_info{replication_set=~\"$replication_set\"} or mysql_perf_schema_replication_group_5_member_info{replication_set=~\"$replication_set\"})",
       "legendFormat": "{{service_name}}"
      }
     ]
    },
    {
     "title": "Transaction Time Inside the Local Queue",
     "type": "graph",
     "description": "Time spent by transaction inside the local queue in the Replica. \n\nNotice: Collected for MySQL 8.x",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "(max by (service_name) (max_over_time(mysql_perf_schema_replication_group_worker_time_RL_seconds{replication_set=~\"$replication_set\"}[$interval]) or max_over_time(mysql_perf_schema_replication_group_worker_time_RL_seconds{replication_set=~\"$replication_set\"}[5m]))) and on(service_name) (mysql_perf_schema_replication_group_member_info{replication_set=~\"$replication_set\"} or mysql_perf_schema_replication_group_5_member_info{replication_set=~\"$replication_set\"})",
       "legendFormat": "{{service_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Checked Transactions",
     "type": "graph",
     "description": "The number of transactions that have been checked for conflicts.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name) (rate(mysql_perf_schema_transactions_checked_total{replication_set=~\"$replication_set\"}[$interval]) or irate(mysql_perf_schema_transactions_checked_total{replication_set=~\"$replication_set\"}[5m]) or\nrate(mysql_perf_schema_5_transactions_checked_total{replication_set=~\"$replication_set\"}[$interval]) or irate(mysql_perf_schema_5_transactions_checked_total{replication_set=~\"$replication_set\"}[5m]))",
       "legendFormat": "{{service_name}}"
      }
     ]
    },
    {
     "title": "Transactions Row Validating",
     "type": "graph",
     "description": "Number of transaction rows which can be used for certification, but have not been garbage collected. Can be thought of as the current size of the conflict detection database against which each transaction is certified.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name) (rate(mysql_perf_schema_transactions_rows_validating_total{replication_set=~\"$replication_set\"}[$interval]) or irate(mysql_perf_schema_transactions_rows_validating_total{replication_set=~\"$replication_set\"}[5m]) or\nrate(mysql_perf_schema_5_transactions_rows_validating_total{replication_set=~\"$replication_set\"}[$interval]) or irate(mysql_perf_schema_5_transactions_rows_validating_total{replication_set=~\"$replication_set\"}[5m]))",
       "legendFormat": "{{service_name}}"
      }
     ]
    },
    {
     "title": "Applied Transactions ",
     "type": "graph",
     "description": "Number of transactions that members have received from the group and applied.\n\nNotice: Collected for MySQL 8.x",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name) (rate(mysql_perf_schema_transactions_remote_applied_total{replication_set=~\"$replication_set\"}[$interval]) or irate(mysql_perf_schema_transactions_remote_applied_total{replication_set=~\"$replication_set\"}[5m]))",
       "legendFormat": "{{service_name}}"
      }
     ]
    },
    {
     "title": "Sent Transactions ",
     "type": "graph",
     "description": "Number of transactions which originated on members and were sent to the group.\n\nNotice: Collected for MySQL 8.x",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name) (rate(mysql_perf_schema_transactions_local_proposed_total{replication_set=~\"$replication_set\"}[$interval]) or irate(mysql_perf_schema_transactions_local_proposed_total{replication_set=~\"$replication_set\"}[5m]))",
       "legendFormat": "{{service_name}}"
      }
     ]
    },
    {
     "title": "Received Transactions Queue",
     "type": "graph",
     "description": "The number of transactions that members have received from the replication group which are waiting to be applied.\n\nNotice: Collected for MySQL 8.x",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name) (mysql_perf_schema_transactions_remote_in_applier_queue{replication_set=~\"$replication_set\"})",
       "legendFormat": "{{service_name}}"
      }
     ]
    },
    {
     "title": "Rolled Back Transactions ",
     "type": "graph",
     "description": "Number of transactions which originated on members and were rolled back by the group.\n\nNotice: Collected for MySQL 8.x",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name) (rate(mysql_perf_schema_transactions_local_rollback_total{replication_set=~\"$replication_set\"}[$interval]) or irate(mysql_perf_schema_transactions_local_rollback_total{replication_set=~\"$replication_set\"}[5m]))",
       "legendFormat": "{{service_name}}"
      }
     ]
    },
    {
     "title": "Transactions in the Queue for Checking",
     "type": "graph",
     "description": "The number of transactions in the queue pending conflict detection checks. Once the transactions have been checked for conflicts, if they pass the check, they are queued to be applied as well.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 56 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name) (mysql_perf_schema_transactions_in_queue{replication_set=~\"$replication_set\"} or mysql_perf_schema_5_transactions_in_queue{replication_set=~\"$replication_set\"})",
       "legendFormat": "{{service_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Conflicts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Detected Conflicts",
     "type": "graph",
     "description": "The number of transactions that have not passed the conflict detection check.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name) (rate(mysql_perf_schema_conflicts_detected_total{replication_set=~\"$replication_set\"}[$interval]) or irate(mysql_perf_schema_conflicts_detected_total{replication_set=~\"$replication_set\"}[5m]) or \nrate(mysql_perf_schema_5_conflicts_detected_total{replication_set=~\"$replication_set\"}[$interval]) or irate(mysql_perf_schema_5_conflicts_detected_total{replication_set=~\"$replication_set\"}[5m]))",
       "legendFormat": "{{service_name}}"
      }
     ]
    }
   ]
  }
 ]
}