# This task installs and starts Percona Server 5.7 on CentOS and Debian/Ubuntu
#
# Task adjustments are handled by parent playbook vars:
#             var "port_flag"      :  to access agent with custom port
#                                     ex: port_flag: "--pmm-agent-listen-port={{ custom_port }}"
#

- name: set password for mysql
  set_fact:
    mysql_password: "UfY9s73Gx~!?@#$%^&*(){}[]<>|/:;,.-_+="

- name: enable ps-80 release repo
  include_tasks: ./enable_repo.yml
  vars:
    only: yes
    package: "ps-80"
    repository: "release"

- name: install Percona Server deb packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
    state: latest
  vars:
    packages:
      - percona-server-server{{ pro_suf | default('') }}
      - percona-server-test{{ pro_suf | default('') }}
      - percona-server{{ pro_suf | default('') }}-dbg
      - percona-server{{ pro_suf | default('') }}-source
      - percona-server-client{{ pro_suf | default('') }}
      - percona-server-rocksdb{{ pro_suf | default('') }}
      - percona-mysql-router{{ pro_suf | default('') }}
  when: ansible_os_family == "Debian"
  environment:
    PERCONA_TELEMETRY_URL: "https://check-dev.percona.com/v1/telemetry/GenericReport"

- name: get list of enabled dnf modules on centos 8
  command: dnf module list --enabled
  register: enabled_dnf_modules
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version >= "8"

- name: list enabled dnf modules on centos 8
  debug:
    var: enabled_dnf_modules
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version >= "8"

- name: disable the mysql module on RHEL/CentOS 8 using DNF
  dnf:
    name: '@mysql'
    state: absent
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"

- name: disable the mariadb RHEL/CentOS 8
  dnf:
    name: '@mariadb'
    state: absent
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"

- name: Install libgflags-dev for rhel9 aarm64 using DNF
  dnf:
    name: https://dl.fedoraproject.org/pub/epel/9/Everything/aarch64/Packages/g/gflags-2.2.2-9.el9.aarch64.rpm
    state: present
    disable_gpg_check: yes
  when:
    - ansible_os_family == "RedHat"
    - (ansible_distribution_major_version == "9") or (ansible_distribution == "Amazon" and ansible_distribution_major_version == "2023")
    - ansible_architecture == "aarch64"

- name: Install libgflags-dev for rhel9 using DNF
  dnf:
    name: https://dl.fedoraproject.org/pub/epel/9/Everything/x86_64/Packages/g/gflags-2.2.2-9.el9.x86_64.rpm
    state: present
    disable_gpg_check: yes
  when:
    - ansible_os_family == "RedHat"
    - (ansible_distribution_major_version == "9") or (ansible_distribution == "Amazon")
    - ansible_architecture != "aarch64"

- name: install Percona Server rpm packages Amazon using DNF
  dnf:
    name: "{{ packages }}"
    state: latest
    disablerepo: "epel"
    update_cache: yes
  vars:
    packages:
      - percona-server-server{{ pro_suf | default('') }}
      - percona-mysql-router{{ pro_suf | default('') }}
      - percona-server-client{{ pro_suf | default('') }}
      - percona-server-test{{ pro_suf | default('') }}
      - percona-server{{ pro_suf | default('') }}-debuginfo
      - percona-server-devel{{ pro_suf | default('') }}
      - percona-server-rocksdb{{ pro_suf | default('') }}
  when:
    - ansible_distribution == "Amazon" and ansible_distribution_major_version == "2023"
  environment:
    PERCONA_TELEMETRY_URL: "https://check-dev.percona.com/v1/telemetry/GenericReport"

- name: install Percona Server rpm packages RHEL7 using YUM
  yum:
    name: "{{ packages }}"
    state: latest
    disablerepo: "epel"
    update_cache: yes
  vars:
    packages:
      - percona-server-server{{ pro_suf | default('') }}
      - percona-mysql-router{{ pro_suf | default('') }}
      - percona-server-client{{ pro_suf | default('') }}
      - percona-server-test{{ pro_suf | default('') }}
      - percona-server{{ pro_suf | default('') }}-debuginfo
      - percona-server-devel{{ pro_suf | default('') }}
      - percona-server-rocksdb{{ pro_suf | default('') }}
  when:
    - ansible_facts['distribution'] in ["RedHat", "CentOS", "OracleLinux", "Amazon"]
    - ansible_facts['distribution_major_version'] | int <= 7
  environment:
    PERCONA_TELEMETRY_URL: "https://check-dev.percona.com/v1/telemetry/GenericReport"

- name: install Percona Server rpm packages RHEL8+ using DNF
  dnf:
    name: "{{ packages }}"
    state: latest
    disablerepo: "epel"
    update_cache: yes
  vars:
    packages:
      - percona-server-server{{ pro_suf | default('') }}
      - percona-mysql-router{{ pro_suf | default('') }}
      - percona-server-client{{ pro_suf | default('') }}
      - percona-server-test{{ pro_suf | default('') }}
      - percona-server{{ pro_suf | default('') }}-debuginfo
      - percona-server-devel{{ pro_suf | default('') }}
      - percona-server-rocksdb{{ pro_suf | default('') }}
    when:
    - ansible_facts['distribution'] in ["RedHat", "CentOS", "OracleLinux", "Amazon"]
    - ansible_facts['distribution_major_version'] | int >= 8
  environment:
    PERCONA_TELEMETRY_URL: "https://check-dev.percona.com/v1/telemetry/GenericReport"

- name: start mysql service
  service: name=mysql state=started

- name: start mysql service with service command
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "6"
  command: service mysql start

- name: start mysql service with systemctl command
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version >= "7"
  command: systemctl start mysql

- name: set root password on centos
  when: ansible_os_family == "RedHat"
  shell: |
    init_pass=$(grep "temporary password" /var/log/mysqld.log | awk '{print $NF}' | tail -1)
    mysql --connect-expired-password -uroot --password="$init_pass" -e "ALTER USER 'root'@'localhost' IDENTIFIED BY '{{ mysql_password }}';"
    cp ./templates/my_57.j2 /root/.my.cnf

- name: copy .my.cnf with credentials on centos
  when: ansible_os_family == "RedHat"
  template: src=./templates/my_57.j2
    dest=/root/.my.cnf
    mode=0640 owner=root group=root

- name: add mysql instance for monitoring
  when: ansible_os_family == "RedHat"
  command: >-
    pmm-admin add mysql {{ port_flag if port_flag is defined else '' }}
    --password={{ mysql_password }} --service-name={{ mysql_service_name }} --query-source=perfschema 
    {{ '' if agent_password is not defined or '/agent_id/' in agent_password else '--agent-password=%s' | format(agent_password) }}

- name: add mysql instance for monitoring via socket
  when: ansible_os_family != "RedHat"
  command: >-
    pmm-admin add mysql {{ port_flag if port_flag is defined else '' }}
    --socket=/var/run/mysqld/mysqld.sock --service-name={{ mysql_socket_service_name }} --query-source=perfschema
    {{ '' if agent_password is not defined or '/agent_id/' in agent_password else '--agent-password=%s' | format(agent_password) }}

- name: "Validate pmm-admin list output contains 'MySQL'"
  include_tasks: ./verify_pmm-admin_list_contains.yml
  vars:
    expected: "MySQL"

- name: "Wait for 'mysqld_exporter' is Running"
  include_tasks: ./wait_exporter_is_running.yml
  vars:
    process_name: "mysqld_exporter"

- name: "Wait for 'mysql_perfschema_agent' is Running"
  include_tasks: ./wait_exporter_is_running.yml
  vars:
    process_name: "mysql_perfschema_agent"
