{
 "title": "HAProxy Instance Summary",
 "tags": [
  "Percona",
  "MySQL_HA"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "service_name",
    "label": "HAProxy Instance",
    "query": {
     "query": "label_values(haproxy_server_status, service_name)"
    }
   },
   {
    "name": "backend",
    "label": "Backend",
    "query": {
     "query": "label_values(haproxy_backend_status{service_name=\"$service_name\"}, proxy)"
    }
   },
   {
    "name": "frontend",
    "label": "Frontend",
    "query": {
     "query": "label_values(haproxy_frontend_status{service_name=~\"$service_name\"}, proxy)"
    }
   },
   {
    "name": "server",
    "label": "Server",
    "query": {
     "query": "label_values({__name__=~\"haproxy_server_bytes_in_total|haproxy_frontend_bytes_in_total\"}, server)"
    }
   },
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, environment)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values({__name__=~\"haproxy_server_status\"}, cluster)"
    }
   },
   {
    "name": "replication_set",
    "label": "Replication Set",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, replication_set)"
    }
   },
   {
    "name": "database",
    "label": "Database",
    "query": {
     "query": "label_values(pg_stat_database_tup_fetched{service_name=~\"$service_name\",datname!~\"template.*|postgres\"},datname)"
    }
   },
   {
    "name": "node_type",
    "label": "Type",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, node_type)"
    }
   },
   {
    "name": "service_type",
    "label": "Type",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, service_type)"
    }
   },
   {
    "name": "schema",
    "label": "Schema",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, schema)"
    }
   },
   {
    "name": "node_name",
    "label": "Nodename",
    "query": {
     "query": "label_values(haproxy_server_bytes_in_total{service_name=~\"$service_name\"}, node_name)"
    }
   },
   {
    "name": "active_backend",
    "label": "Backend",
    "query": {
     "query": "query_result(haproxy_server_last_session_seconds{service_name=\"$service_name\"} > 0)"
    }
   },
   {
    "name": "servers_backend",
    "label": "Backend",
    "query": {
     "query": "query_result(haproxy_server_status{service_name=\"$service_name\",proxy=~\"$backend\"})"
    }
   }
  ]
 },
 "panels": [
  { "title": "HAProxy Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Connected",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(haproxy_process_start_time_seconds{service_name=\"$service_name\"}) > 0"
    }
   ]
  },
  {
   "title": "Frontend Sections Status ($frontend)",
   "type": "stat",
   "gridPos": { "h": 9, "w": 10, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count by (service_name,proxy) (haproxy_frontend_status{service_name=~\"$service_name\",proxy=~\"$frontend\"})",
     "legendFormat": "{{proxy}}"
    }
   ]
  },
  {
   "title": "Backend Sections Status ($backend)",
   "type": "stat",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg by (service_name,proxy) (haproxy_backend_status{service_name=~\"$service_name\",proxy=~\"$backend\"})",
     "legendFormat": "{{proxy}}"
    }
   ]
  },
  {
   "title": "Active Servers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(count by (server) (haproxy_server_status{service_name=~\"$service_name\",proxy=~\"$active_backend\"} == 1))"
    }
   ]
  },
  {
   "title": "Active Sessions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by () (haproxy_server_current_sessions{service_name=~\"$service_name\",proxy=~\"$backend|$frontend\"})"
    }
   ]
  },
  {
   "title": "Active Sessions",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "Backend (-) / Frontend (+)" }
   ],
   "targets": [
    {
     "expr": "sum by () (haproxy_backend_current_sessions{proxy=~\"$backend\"})",
     "legendFormat": "Backend"
    },
    {
     "expr": "sum by () (haproxy_frontend_current_sessions{proxy=~\"$frontend\"})",
     "legendFormat": "Fronend"
    }
   ]
  },
  {
   "title": "Servers in $servers_backend Section",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 16 },
   "repeat": "servers_backend",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (service_name,proxy,server) (haproxy_server_status{service_name=~\"$service_name\",proxy=~\"$servers_backend\"})",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Frontend Section",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sessions",
     "type": "graph",
     "description": "Total number of sessions.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "max by (proxy) (increase(haproxy_frontend_sessions_total{proxy=~\"$frontend\",service_name=~\"$service_name\"}[$interval]))",
       "legendFormat": "{{proxy}}"
      }
     ]
    },
    {
     "title": "Session Limit",
     "type": "table",
     "description": "The maximum per-process number of concurrent sessions. Proxies will stop accepting connections when this limit is reached.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "targets": [
      {
       "expr": "avg by (proxy) (haproxy_frontend_limit_sessions{proxy=~\"$frontend\",service_name=~\"$service_name\"})",
       "legendFormat": "{{proxy}}"
      },
      {
       "expr": "avg by (proxy) (haproxy_frontend_max_sessions{proxy=~\"$frontend\",service_name=~\"$service_name\"})",
       "legendFormat": "{{proxy}}"
      }
     ]
    },
    {
     "title": "Sessions Rate Limit",
     "type": "table",
     "description": "The maximum per-process number of sessions per second.\nProxies will stop accepting connections when this limit is reached. It can be\nused to limit the global capacity regardless of each frontend capacity. It is\nimportant to note that this can only be used as a service protection measure,\nas there will not necessarily be a fair share between frontends when the\nlimit is reached, so it's a good idea to also limit each frontend to some\nvalue close to its expected share. Also, lowering tune.maxaccept can improve\nfairness.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "targets": [
      {
       "expr": "max by (proxy) (haproxy_frontend_limit_session_rate{proxy=~\"$frontend\",service_name=~\"$service_name\"})",
       "legendFormat": "{{proxy}}"
      },
      {
       "expr": "max by (proxy) (haproxy_frontend_max_session_rate{proxy=~\"$frontend\",service_name=~\"$service_name\"})"
      }
     ]
    },
    {
     "title": "Connections",
     "type": "graph",
     "description": "Observed number of connections per second",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "short", "label": "Successful (+) / Denied (-)" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "max by (proxy) (increase(haproxy_frontend_connections_total{proxy=~\"$frontend\",service_name=~\"$service_name\"}[$interval]))",
       "legendFormat": "{{proxy}}"
      },
      {
       "expr": "max by (proxy) (increase(haproxy_frontend_denied_connections_total{proxy=~\"$frontend\",service_name=~\"$service_name\"}[$interval]))",
       "legendFormat": "{{proxy}} - Denied"
      }
     ]
    },
    {
     "title": "Frontend Data",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "bytes", "label": "Out (+) / In (-)" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (proxy) (rate(haproxy_frontend_bytes_in_total{proxy=~\"$frontend\",service_name=~\"$service_name\"}[$interval]) or irate(haproxy_frontend_bytes_in_total{proxy=~\"$frontend\",service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Incoming - {{proxy}}"
      },
      {
       "expr": "avg by (proxy) (rate(haproxy_frontend_bytes_out_total{proxy=~\"$frontend\",service_name=~\"$service_name\"}[$interval]) or irate(haproxy_frontend_bytes_out_total{proxy=~\"$frontend\",service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Outgoing - {{proxy}}"
      }
     ]
    },
    {
     "title": "Error Requests",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "max by (proxy) (increase(haproxy_frontend_request_errors_total{proxy=~\"$frontend\",service_name=~\"$service_name\"}[$interval]))",
       "legendFormat": "{{frontend}}"
      }
     ]
    },
    {
     "title": "Denied Requests",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (proxy) (increase(haproxy_frontend_requests_denied_total{proxy=~\"$frontend\",service_name=~\"$service_name\"}[$interval]))",
       "legendFormat": "{{proxy}}"
      }
     ]
    },
    {
     "title": "Denied Sessions",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (proxy) (increase(haproxy_frontend_denied_sessions_total{proxy=~\"$frontend\",service_name=~\"$service_name\"}[$interval]))",
       "legendFormat": "{{proxy}}"
      }
     ]
    },
    {
     "title": "Denied Responses",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (proxy) (increase(haproxy_frontend_responses_denied_total{proxy=~\"$frontend\",service_name=~\"$service_name\"}[$interval]))",
       "legendFormat": "{{proxy}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Backend Section",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sessions",
     "type": "graph",
     "description": "Total number of sessions.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name,proxy) (increase(haproxy_backend_sessions_total{proxy=~\"$backend\",service_name=~\"$service_name\"}[$interval]))",
       "legendFormat": "{{proxy}}"
      }
     ]
    },
    {
     "title": "Session Limit",
     "type": "table",
     "description": "The maximum per-process number of concurrent sessions. Proxies will stop accepting connections when this limit is reached.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "targets": [
      {
       "expr": "avg by (proxy) (haproxy_backend_limit_sessions{proxy=~\"$backend\",service_name=~\"$service_name\"})",
       "legendFormat": "{{proxy}}"
      },
      {
       "expr": "avg by (proxy) (haproxy_backend_max_sessions{proxy=~\"$backend\",service_name=~\"$service_name\"})",
       "legendFormat": "{{proxy}}"
      }
     ]
    },
    {
     "title": "Maximum Observed Sessions Rate",
     "type": "table",
     "description": "Maximum observed number of sessions per second.\nProxies will stop accepting connections when this limit is reached. It can be\nused to limit the global capacity regardless of each frontend capacity. It is\nimportant to note that this can only be used as a service protection measure,\nas there will not necessarily be a fair share between frontends when the\nlimit is reached, so it's a good idea to also limit each frontend to some\nvalue close to its expected share. Also, lowering tune.maxaccept can improve\nfairness.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
     "targets": [
      {
       "expr": "max by (proxy) (haproxy_backend_max_session_rate{proxy=~\"$backend\",service_name=~\"$service_name\"})",
       "legendFormat": "{{proxy}}"
      }
     ]
    },
    {
     "title": "Backend Data",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "bytes", "label": "Out (+) / In (-)" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (proxy) (rate(haproxy_backend_bytes_in_total{proxy=~\"$backend\",service_name=~\"$service_name\"}[$interval]) or irate(haproxy_backend_bytes_in_total{proxy=~\"$backend\",service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Incoming - {{proxy}}"
      },
      {
       "expr": "avg by (proxy) (rate(haproxy_backend_bytes_out_total{proxy=~\"$backend\",service_name=~\"$service_name\"}[$interval]) or irate(haproxy_backend_bytes_out_total{proxy=~\"$backend\",service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Outgoing - {{proxy}}"
      }
     ]
    },
    {
     "title": "Aborted Data Transfers",
     "type": "graph",
     "description": "Total number of data transfers aborted by the server or a client",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 54 },
     "yaxes": [
      { "format": "short", "label": "Client (-) / Server (+)" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (proxy) (increase(haproxy_backend_server_aborts_total{proxy=~\"$backend\",service_name=~\"$service_name\"}))",
       "legendFormat": "{{proxy}} - Server"
      },
      {
       "expr": "avg by (proxy) (increase(haproxy_backend_client_aborts_total{proxy=~\"$backend\",service_name=~\"$service_name\"}))",
       "legendFormat": "{{proxy}} - Client"
      }
     ]
    },
    {
     "title": "Connection Errors",
     "type": "graph",
     "description": "Number of connection errors",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "max by (proxy) (increase(haproxy_backend_connection_errors_total{proxy=~\"$backend\",service_name=~\"$service_name\"}[$interval]))",
       "legendFormat": "{{proxy}}"
      }
     ]
    },
    {
     "title": "Connection Establishment Attempts",
     "type": "graph",
     "description": "Number of connection establishment attempts",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "max by (proxy) (increase(haproxy_backend_connection_attempts_total{proxy=~\"$backend\",service_name=~\"$service_name\"}[$interval]))",
       "legendFormat": "{{proxy}}"
      }
     ]
    },
    {
     "title": "Connection Reuses",
     "type": "graph",
     "description": "Number of connection reuses",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "max by (proxy) (increase(haproxy_backend_connection_reuses_total{proxy=~\"$backend\",service_name=~\"$service_name\"}[$interval]))",
       "legendFormat": "{{proxy}}"
      }
     ]
    },
    {
     "title": "Queue Time",
     "type": "graph",
     "description": "Avg. queue time for last 1024 successful connections.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "max by (proxy) (max_over_time(haproxy_backend_queue_time_average_seconds{proxy=~\"$backend\",service_name=~\"$service_name\"}[$interval]) or max_over_time(haproxy_backend_queue_time_average_seconds{proxy=~\"$backend\",service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "{{proxy}}"
      }
     ]
    },
    {
     "title": "Queued Requests",
     "type": "graph",
     "description": "Current number of queued requests not assigned to any server.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "max by (proxy) (max_over_time(haproxy_backend_current_queue{proxy=~\"$backend\",service_name=~\"$service_name\"}[$interval]) or max_over_time(haproxy_backend_current_queue{proxy=~\"$backend\",service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "{{proxy}}"
      }
     ]
    },
    {
     "title": "Denied Responses",
     "type": "graph",
     "description": "Number of denied responses",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 78 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "max by (proxy) (increase(haproxy_backend_responses_denied_total{proxy=~\"$backend\",service_name=~\"$service_name\"}[$interval]))",
       "legendFormat": "{{proxy}}"
      }
     ]
    },
    {
     "title": "Denied Requests",
     "type": "graph",
     "description": "Number of denied requests",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 86 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "max by (proxy) (increase(haproxy_backend_requests_denied_total{proxy=~\"$backend\",service_name=~\"$service_name\"}[$interval]))",
       "legendFormat": "{{proxy}}"
      }
     ]
    },
    {
     "title": "Response Errors",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 86 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (proxy) (increase(haproxy_backend_response_errors_total{proxy=~\"$backend\",service_name=~\"$service_name\"}[$interval]))",
       "legendFormat": "{{proxy}}"
      }
     ]
    },
    {
     "title": "Redispatch Warnings",
     "type": "graph",
     "description": "Number of redispatch warnings",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 94 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (proxy) (increase(haproxy_backend_redispatch_warnings_total{proxy=~\"$backend\",service_name=~\"$service_name\"}[$interval]))",
       "legendFormat": "{{proxy}}"
      }
     ]
    },
    {
     "title": "Failed Header Rewriting Warnings",
     "type": "graph",
     "description": "Number of failed header rewriting warnings",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 94 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (proxy) (increase(haproxy_backend_failed_header_rewriting_total{proxy=~\"$backend\",service_name=~\"$service_name\"}[$interval]))",
       "legendFormat": "{{proxy}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Servers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Servers Weight in $active_backend Section",
     "type": "table",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
     "repeat": "active_backend",
     "targets": [
      {
       "expr": "max by (server,proxy) (haproxy_server_weight{service_name=~\"$service_name\",proxy=~\"$active_backend\"})",
       "legendFormat": "{{server}}"
      },
      {
       "expr": "max by (server,proxy) (haproxy_server_max_session_rate{service_name=~\"$service_name\",proxy=~\"$active_backend\"})",
       "legendFormat": "{{server}}"
      },
      {
       "expr": "max by (server,proxy) (haproxy_server_last_session_seconds{service_name=~\"$service_name\",proxy=~\"$active_backend\"})"
      }
     ]
    },
    {
     "title": "Sessions in $active_backend Section",
     "type": "state-timeline",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
     "repeat": "active_backend",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "count by (server) (avg by (server) (increase(haproxy_server_sessions_total{service_name=~\"$service_name\",proxy=~\"$active_backend\"}[$interval])) > 0)",
       "legendFormat": "{{server}}"
      }
     ]
    },
    {
     "title": "Selections of Servers",
     "type": "bargauge",
     "description": "Number of times a service was selected, either for new sessions, or when redispatching",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 39 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "haproxy_server_loadbalanced_total",
       "legendFormat": "{{server}} - {{proxy}}"
      }
     ]
    },
    {
     "title": "Sessions",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max by (proxy,server) (increase(haproxy_server_sessions_total{service_name=~\"$service_name\",proxy=~\"$active_backend\"}[$interval]))",
       "legendFormat": "{{proxy}} - {{server}}"
      }
     ]
    },
    {
     "title": "Incoming Data",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "avg by (server, proxy) (rate(haproxy_server_bytes_in_total{proxy=~\"$active_backend\",service_name=~\"$service_name\"}[$interval]) or irate(haproxy_server_bytes_in_total{proxy=~\"$active_backend\",service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "{{server}} - {{proxy}}"
      }
     ]
    },
    {
     "title": "Outgoing Data",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 52 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "avg by (server, proxy) (rate(haproxy_server_bytes_out_total{proxy=~\"$active_backend\",service_name=~\"$service_name\"}[$interval]) or irate(haproxy_server_bytes_out_total{proxy=~\"$active_backend\",service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "{{server}} - {{proxy}}"
      }
     ]
    },
    {
     "title": "Queued Requests Limits",
     "type": "table",
     "description": "The \"maxqueue\" parameter specifies the maximal number of connections which\nwill wait in the queue for this server. If this limit is reached, next\nrequests will be redispatched to other servers instead of indefinitely\nwaiting to be served. This will break persistence but may allow people to\nquickly re-log in when the server they try to connect to is dying. The\ndefault value is \"0\" which means the queue is unlimited.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 61 },
     "targets": [
      {
       "expr": "max by (server,proxy) (haproxy_server_queue_limit{service_name=~\"$service_name\",proxy=~\"$backend\"})",
       "legendFormat": "{{server}}"
      },
      {
       "expr": "max by (server,proxy) (haproxy_server_max_queue{service_name=~\"$service_name\",proxy=~\"$backend\"})",
       "legendFormat": "{{server}}"
      }
     ]
    },
    {
     "title": "Queued Requests",
     "type": "graph",
     "description": "Number of queued requests",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 61 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max by (proxy,server) (max_over_time(haproxy_server_current_queue{service_name=~\"$service_name\",proxy=~\"$active_backend\"}[$interval]))",
       "legendFormat": "{{proxy}} - {{server}}"
      }
     ]
    },
    {
     "title": "Idle Connections",
     "type": "table",
     "description": "Limit on the number of available idle connections.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 70 },
     "targets": [
      {
       "expr": "max by (server,proxy) (haproxy_server_server_idle_connections_limit{service_name=~\"$service_name\",proxy=~\"$backend\"})",
       "legendFormat": "{{server}}"
      },
      {
       "expr": "max by (server,proxy) (haproxy_server_server_idle_connections_current{service_name=~\"$service_name\",proxy=~\"$backend\"})",
       "legendFormat": "{{server}}"
      }
     ]
    },
    {
     "title": "Connection Attempts",
     "type": "graph",
     "description": "Number of connection establishment attempts",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 70 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max by (proxy,server) (increase(haproxy_server_connection_attempts_total{service_name=~\"$service_name\",proxy=~\"$active_backend\"}[$interval]))",
       "legendFormat": "{{proxy}} - {{server}}"
      }
     ]
    },
    {
     "title": "Connection Reuses",
     "type": "graph",
     "description": "Number of connection reuses",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 79 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max by (proxy,server) (increase(haproxy_server_connection_reuses_total{service_name=~\"$service_name\",proxy=~\"$active_backend\"}[$interval]))",
       "legendFormat": "{{proxy}} - {{server}}"
      }
     ]
    },
    {
     "title": "Connection Errors",
     "type": "graph",
     "description": "Number of connection errors",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 79 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max by (proxy,server) (increase(haproxy_server_connection_errors_total{service_name=~\"$service_name\",proxy=~\"$active_backend\"}[$interval]))",
       "legendFormat": "{{proxy}} - {{server}}"
      }
     ]
    },
    {
     "title": "Request and Response Time",
     "type": "graph",
     "description": "Observed request+response time (request+queue+connect+response+processing)",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 88 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "max by (proxy,server) (increase(haproxy_server_max_total_time_seconds{service_name=~\"$service_name\",proxy=~\"$active_backend\"}[$interval]))",
       "legendFormat": "{{proxy}} - {{server}}"
      }
     ]
    },
    {
     "title": "Response Errors",
     "type": "graph",
     "description": "Number of response errors",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 88 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max by (proxy,server) (increase(haproxy_server_response_errors_total{service_name=~\"$service_name\",proxy=~\"$active_backend\"}[$interval]))",
       "legendFormat": "{{proxy}} - {{server}}"
      }
     ]
    },
    {
     "title": "Data Transfers Aborted by the Client",
     "type": "graph",
     "description": "Number of data transfers aborted by the client",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 97 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max by (proxy,server) (increase(haproxy_server_client_aborts_total{service_name=~\"$service_name\",proxy=~\"$active_backend\"}[$interval]))",
       "legendFormat": "{{proxy}} - {{server}}"
      }
     ]
    },
    {
     "title": "Retry Warnings",
     "type": "graph",
     "description": "Number of retry warnings",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 97 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max by (proxy,server) (increase(haproxy_server_retry_warnings_total{service_name=~\"$service_name\",proxy=~\"$active_backend\"}[$interval]))",
       "legendFormat": "{{proxy}} - {{server}}"
      }
     ]
    },
    {
     "title": "Redispatch Warnings",
     "type": "graph",
     "description": "Number of redispatch warnings",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 106 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max by (proxy,server) (increase(haproxy_server_redispatch_warnings_total{service_name=~\"$service_name\",proxy=~\"$active_backend\"}[$interval]))",
       "legendFormat": "{{proxy}} - {{server}}"
      }
     ]
    },
    {
     "title": "Failed Header Rewriting Warnings",
     "type": "graph",
     "description": "Number of failed header rewriting warnings",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 106 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max by (proxy,server) (increase(haproxy_server_failed_header_rewriting_total{service_name=~\"$service_name\",proxy=~\"$active_backend\"}[$interval]))",
       "legendFormat": "{{proxy}} - {{server}}"
      }
     ]
    },
    {
     "title": "Checks Statistic",
     "type": "table",
     "description": "The \"maxqueue\" parameter specifies the maximal number of connections which\nwill wait in the queue for this server. If this limit is reached, next\nrequests will be redispatched to other servers instead of indefinitely\nwaiting to be served. This will break persistence but may allow people to\nquickly re-log in when the server they try to connect to is dying. The\ndefault value is \"0\" which means the queue is unlimited.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 115 },
     "targets": [
      {
       "expr": "max by (server,proxy) (haproxy_server_check_failures_total{service_name=~\"$service_name\",proxy=~\"$backend\"})",
       "legendFormat": "{{server}}"
      },
      {
       "expr": "max by (server,proxy) (haproxy_server_check_up_down_total{service_name=~\"$service_name\",proxy=~\"$backend\"})",
       "legendFormat": "{{server}}"
      }
     ]
    },
    {
     "title": "Data Transfers Aborted by the Server",
     "type": "graph",
     "description": "Number of data transfers aborted by the server",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 115 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max by (proxy,server) (increase(haproxy_server_server_aborts_total{service_name=~\"$service_name\",proxy=~\"$active_backend\"}[$interval]))",
       "legendFormat": "{{proxy}} - {{server}}"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP Statistic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP Responses by Code",
     "type": "graph",
     "description": "Total of HTTP responses.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "sum by (code) (increase(haproxy_frontend_http_responses_total{proxy=~\"$frontend\",service_name=~\"$service_name\"}[$interval]) or irate(haproxy_frontend_http_responses_total{proxy=~\"$frontend\",service_name=~\"$service_name\"}[5m]) or increase(haproxy_backend_http_responses_total{proxy=~\"$backend\",service_name=~\"$service_name\"}[$interval]) or irate(haproxy_backend_http_responses_total{proxy=~\"$backend\",service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "{{code}}"
      }
     ]
    },
    {
     "title": "HTTP Requests/Responses",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "short", "label": "Requests (+) /Responses (-)" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name,proxy) (increase(haproxy_frontend_http_requests_total{proxy=~\"$frontend\",service_name=~\"$service_name\"}[$interval]) or irate(haproxy_frontend_http_requests_total{proxy=~\"$frontend\",service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Requests - {{proxy}}"
      },
      {
       "expr": "sum by (service_name,proxy) (increase(haproxy_frontend_http_responses_total{proxy=~\"$frontend\",service_name=~\"$service_name\"}[$interval]) or irate(haproxy_frontend_http_responses_total{proxy=~\"$frontend\",service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Responses - {{proxy}}"
      }
     ]
    },
    {
     "title": "Frontend HTTP Requests",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name,proxy) (increase(haproxy_frontend_http_requests_total{proxy=~\"$frontend\",service_name=~\"$service_name\"}[$interval]))",
       "legendFormat": "{{proxy}}"
      }
     ]
    },
    {
     "title": "Intercepted HTTP Requests",
     "type": "graph",
     "description": "The request was intercepted and locally handled by haproxy. Generally\n it means that this was a redirect or a stats request.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name,proxy) (increase(haproxy_frontend_intercepted_requests_total{proxy=~\"$frontend\",service_name=~\"$service_name\"}[$interval]) or irate(haproxy_frontend_intercepted_requests_total{proxy=~\"$frontend\",service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "{{proxy}}"
      }
     ]
    }
   ]
  },
  {
   "title": "HAProxy Settings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "clocks" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "time() - haproxy_process_start_time_seconds{service_name=\"$service_name\"}"
      }
     ]
    },
    {
     "title": "Startup Process",
     "type": "stat",
     "description": "The nbproc setting specify the number of processes that HAProxy should spawn on startup. This can increase the efficiency of your load balancer. Each process created by nbproc has its own stats, stick tables, health checks, and so on. ",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 32 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "haproxy_process_nbproc{service_name=\"$service_name\"}"
      }
     ]
    },
    {
     "title": "Startup Threads",
     "type": "stat",
     "description": "The nbthread setting specify the number of threads that HAProxy should spawn on startup. This can increase the efficiency of your load balancer.  Threads created with nbthread share stats, stick tables, health checks, and so on.",
     "gridPos": { "h": 3, "w": 3, "x": 6, "y": 32 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "haproxy_process_nbthread{service_name=\"$service_name\"}"
      }
     ]
    },
    {
     "title": "Per-process Mem Limit",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 9, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "haproxy_process_max_memory_bytes{service_name=\"$service_name\"}"
      }
     ]
    },
    {
     "title": "Ulimit-n",
     "type": "stat",
     "description": "The maximum number of per-process file-descriptors. By\ndefault, it is automatically computed, so it is recommended not to use this\noption.",
     "gridPos": { "h": 3, "w": 3, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "haproxy_process_max_fds{service_name=\"$service_name\"}"
      }
     ]
    },
    {
     "title": "Max Open Sockets",
     "type": "stat",
     "description": "Maximum number of open sockets",
     "gridPos": { "h": 3, "w": 3, "x": 15, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "haproxy_process_max_sockets{service_name=\"$service_name\"}"
      }
     ]
    },
    {
     "title": "Max Concurrent Conn",
     "type": "stat",
     "description": "Maximum number of concurrent connections",
     "gridPos": { "h": 3, "w": 3, "x": 18, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "haproxy_process_max_connections{service_name=\"$service_name\"}"
      }
     ]
    },
    {
     "title": "Max Pipes Number",
     "type": "stat",
     "description": "The maximum per-process number of pipes. Currently, pipes\nare only used by kernel-based tcp splicing. Since a pipe contains two file\ndescriptors, the \"ulimit-n\" value will be increased accordingly. The default\nvalue is maxconn/4, which seems to be more than enough for most heavy usages.\nThe splice code dynamically allocates and releases pipes, and can fall back\nto standard copy, so setting this value too low may only impact performance.",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "haproxy_process_max_pipes{service_name=\"$service_name\"}"
      }
     ]
    },
    {
     "title": "Pools Memory Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "haproxy_process_pool_allocated_bytes{service_name=\"$service_name\"}",
       "legendFormat": "Allocated"
      },
      {
       "expr": "haproxy_process_pool_used_bytes{service_name=\"$service_name\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "rate(haproxy_process_pool_failures_total[$interval]) or irate(haproxy_process_pool_failures_total[5m])",
       "legendFormat": "Failed Allocation"
      }
     ]
    },
    {
     "title": "Connections",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(haproxy_process_connections_total{service_name=\"$service_name\"}[$interval])",
       "legendFormat": "TCP/HTTP"
      },
      {
       "expr": "rate(haproxy_process_ssl_connections_total{service_name=\"$service_name\"}[$interval])",
       "legendFormat": "SSL"
      }
     ]
    },
    {
     "title": "Tasks",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max_over_time(haproxy_process_current_tasks{service_name=\"$service_name\"}[$interval])",
       "legendFormat": "Current"
      },
      {
       "expr": "max_over_time(haproxy_process_current_run_queue{service_name=\"$service_name\"}[$interval])",
       "legendFormat": "Run"
      }
     ]
    },
    {
     "title": "Jobs",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max_over_time(haproxy_process_jobs{service_name=\"$service_name\"}[$interval])",
       "legendFormat": "Active"
      },
      {
       "expr": "max_over_time(haproxy_process_unstoppable_jobs{service_name=\"$service_name\"}[$interval])",
       "legendFormat": "Unstoppable"
      }
     ]
    }
   ]
  },
  {
   "title": "Node Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "System Uptime",
     "type": "stat",
     "description": "The parameter shows how long a system has been “up” and running without a shut down or restart.",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "avg by (node_name)  (time() - container_start_time_seconds{node_name=~\"$node_name\",id=~\"/kubepods.*\",container!~\"POD|pmm-client|\"}) or avg by (node_name) ((node_time_seconds{node_name=~\"$node_name\"} - node_boot_time_seconds{node_name=~\"$node_name\"}) or (time() - node_boot_time_seconds{node_name=~\"$node_name\"}))"
      }
     ]
    },
    {
     "title": "Load Average",
     "type": "stat",
     "description": "The system load is a measurement of the computational work the system is performing. Each running process either using or waiting for CPU resources adds 1 to the load.",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by () (avg_over_time(node_load1{node_name=~\"$node_name\"}[$interval]) or avg_over_time(node_load1{node_name=~\"$node_name\"}[5m]))"
      }
     ]
    },
    {
     "title": "RAM",
     "type": "stat",
     "description": "RAM (Random Access Memory) is the hardware in a computing device where the operating system, application programs and data in current use are kept so they can be quickly reached by the device's processor.",
     "gridPos": { "h": 3, "w": 3, "x": 6, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by () (container_spec_memory_limit_bytes{node_name=~\"$node_name\",id=~\"/kubepods.*\",container!~\"POD|pmm-client|\"}) or \nmax by () (node_memory_MemTotal_bytes{node_name=~\"$node_name\"})"
      }
     ]
    },
    {
     "title": "Memory Available",
     "type": "stat",
     "description": "Percent of Memory Available\nNote: on Modern Linux Kernels amount of Memory Available for application is not the same as Free+Cached+Buffers",
     "gridPos": { "h": 3, "w": 3, "x": 9, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "clamp_max(avg by () (container_memory_usage_bytes{node_name=~\"$node_name\",id=~\"/kubepods.*\",container!~\"POD|pmm-client|backup-agent|\"} * 100 / container_spec_memory_limit_bytes{node_name=\"$node_name\",id=~\"/kubepods.*\",container!~\"POD|pmm-client|backup-agent|\"}),100) or  \navg by () (((node_memory_MemAvailable_bytes{node_name=~\"$node_name\"} or (node_memory_MemFree_bytes{node_name=~\"$node_name\"} + node_memory_Buffers_bytes{node_name=~\"$node_name\"} + node_memory_Cached_bytes{node_name=~\"$node_name\"})) / node_memory_MemTotal_bytes{node_name=~\"$node_name\"}) * 100 or (100 - azure_memory_percent_average{node_name=~\"$node_name\"}))"
      }
     ]
    },
    {
     "title": "Virtual Memory",
     "type": "stat",
     "description": "RAM + SWAP",
     "gridPos": { "h": 3, "w": 3, "x": 12, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by () (container_spec_memory_limit_bytes{node_name=~\"$node_name\",id=~\"/kubepods.*\",container!~\"POD|pmm-client|\"}+container_spec_memory_swap_limit_bytes{node_name=~\"$node_name\",id=~\"/kubepods.*\",container!~\"POD|pmm-client|\"}) or\nmax by () (node_memory_MemTotal_bytes{node_name=~\"$node_name\"}+node_memory_SwapTotal_bytes{node_name=~\"$node_name\"})"
      }
     ]
    },
    {
     "title": "Disk Space",
     "type": "stat",
     "description": "Sum of disk space on all partitions. Note  it can be significantly over-reported in some installations",
     "gridPos": { "h": 3, "w": 3, "x": 15, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by () (container_fs_limit_bytes{node_name=~\"$node_name\",id=~\"/kubepods.*\",container!~\"POD|pmm-client|\"}) or \navg by () (sum(avg(node_filesystem_size_bytes{node_name=~\"$node_name\",fstype=~\"(ext.|xfs|vfat|)\"}) without (mountpoint)) without (device,fstype))"
      }
     ]
    },
    {
     "title": "Min Space Available",
     "type": "stat",
     "description": "Lowest percent of the disk space available",
     "gridPos": { "h": 3, "w": 3, "x": 18, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "min(node_filesystem_free_bytes{node_name=~\"$node_name\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs|shm|overlay|squashfs\"}/node_filesystem_size_bytes{node_name=~\"$node_name\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs|shm|overlay|squashfs\"})*100"
      }
     ]
    },
    {
     "title": "Node",
     "type": "text",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 52 },
     "options": {
      "content": "<h5><b><font color=#e68a00><center><a href=\"/graph/d/node-instance-summary/node-summary?var-node_name=$node_name\" target=\"_blank\">$node_name</a></center></font></b></h5>\n\n\n"
     }
    },
    {
     "title": "CPU Usage",
     "type": "graph",
     "description": "The CPU time is measured in clock ticks or seconds. It is useful to measure CPU time as a percentage of the CPU's capacity, which is called the CPU usage.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "avg by (node_name,mode) (clamp_max(((avg by (mode) ( (clamp_max(rate(node_cpu_seconds_total{node_name=~\"$node_name\",mode!=\"idle\", mode!=\"user\", mode!=\"system\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{node_name=~\"$node_name\",mode!=\"idle\", mode!=\"user\", mode!=\"system\"}[5m]),1)) ))*100 or (avg_over_time(node_cpu_average{node_name=~\"$node_name\", mode!=\"total\", mode!=\"idle\", mode!=\"user\", mode!=\"system\"}[$interval]) or avg_over_time(node_cpu_average{node_name=~\"$node_name\", mode!=\"total\", mode!=\"idle\", mode!=\"user\", mode!=\"system\"}[5m]))),100))",
       "legendFormat": "{{ mode }}"
      },
      {
       "expr": "clamp_max(avg(rate(container_cpu_system_seconds_total{node_name=~\"$node_name\",id=~\"/kubepods.*\",container!~\"POD|pmm-client|\"}[$interval])) or \n((avg by () ((clamp_max(rate(node_cpu_seconds_total{node_name=~\"$node_name\",mode=\"system\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{node_name=~\"$node_name\",mode=\"system\"}[5m]),1)) ))*100 or \n(avg_over_time(node_cpu_average{node_name=~\"$node_name\", mode=\"system\"}[$interval]) or \navg_over_time(node_cpu_average{node_name=~\"$node_name\", mode=\"system\"}[5m]))),100)",
       "legendFormat": "system"
      },
      {
       "expr": "clamp_max(avg(rate(container_cpu_user_seconds_total{node_name=~\"$node_name\",id=~\"/kubepods.*\",container!~\"POD|pmm-client|\"}[$interval])) or \n((avg by () ((clamp_max(rate(node_cpu_seconds_total{node_name=~\"$node_name\",mode=\"user\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{node_name=~\"$node_name\",mode=\"user\"}[5m]),1)) ))*100 or \n(avg_over_time(node_cpu_average{node_name=~\"$node_name\", mode=\"user\"}[$interval]) or \navg_over_time(node_cpu_average{node_name=~\"$node_name\", mode=\"user\"}[5m]))),100)",
       "legendFormat": "user"
      }
     ]
    },
    {
     "title": "CPU Saturation and Max Core Usage",
     "type": "graph",
     "description": "When a system is running with maximum CPU utilization, the transmitting and receiving threads must all share the available CPU. This will cause data to be queued more frequently to cope with the lack of CPU. CPU Saturation may be measured as the length of a wait queue, or the time spent waiting on the queue.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "((sum(avg_over_time(container_processes{node_name=~\"$node_name\",id=~\"/kubepods.*\",container!~\"POD|pmm-client|\"}[$interval]))-1) / avg by () (machine_cpu_cores)) or\navg by () ((avg_over_time(node_procs_running{node_name=~\"$node_name\"}[$interval])-1) / scalar(count(node_cpu_seconds_total{mode=\"user\", node_name=~\"$node_name\"})) or (avg_over_time(node_procs_running{node_name=~\"$node_name\"}[5m])-1) / scalar(count(node_cpu_seconds_total{mode=\"user\", node_name=~\"$node_name\"})))",
       "legendFormat": "Normalized CPU Load"
      },
      {
       "calculatedInterval": "2s",
       "expr": "clamp_max(sum(rate(container_cpu_usage_seconds_total{node_name=~\"$node_name\",id=~\"/kubepods.*\",container!~\"POD|pmm-client|\"}[$interval]) or rate(container_cpu_usage_seconds_total{node_name=\"$node_name\",id=~\"/kubepods.*\",container!~\"POD|pmm-client|\"}[5m])) or\nmax by () (sum  by (cpu) ( (clamp_max(rate(node_cpu_seconds_total{node_name=~\"$node_name\",mode!=\"idle\",mode!=\"iowait\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{node_name=~\"$node_name\",mode!=\"idle\",mode!=\"iowait\"}[5m]),1)) )),1)",
       "legendFormat": "Max CPU Core Utilization"
      }
     ]
    },
    {
     "title": "Disk I/O and Swap Activity",
     "type": "graph",
     "description": "Disk I/O includes read or write or input/output operations involving a physical disk. It is the speed with which the data transfer takes place between the hard disk drive and RAM.\n\nSwap Activity is memory management that involves swapping sections of memory to and from physical storage.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
     "yaxes": [
      { "format": "Bps", "label": "Page Out (-) / Page In (+)" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "avg by () (sum(rate(container_fs_reads_bytes_total{node_name=\"$proxysql\",id=~\"/kubepods.*\"}[5s]) or irate(container_fs_reads_bytes_total{node_name=\"$proxysql\",id=~\"/kubepods.*\"}[5s]))) or\navg by () (rate(node_vmstat_pgpgin{node_name=\"$proxysql\"}[$interval]) * 1024 or irate(node_vmstat_pgpgin{node_name=\"$proxysql\"}[5m]) * 1024)",
       "legendFormat": "Disk Reads (Page In)"
      },
      {
       "calculatedInterval": "2s",
       "expr": "avg by () (sum(rate(container_fs_writes_bytes_total{node_name=\"$proxysql\",id=~\"/kubepods.*\"}[5s]) or irate(container_fs_writes_bytes_total{node_name=\"$proxysql\",id=~\"/kubepods.*\"}[5s]))) or\navg by () ((rate(node_vmstat_pgpgout{node_name=\"$proxysql\"}[$interval]) * 1024 or irate(node_vmstat_pgpgout{node_name=\"$proxysql\"}[5m]) * 1024))",
       "legendFormat": "Disk Writes (Page Out)"
      },
      {
       "expr": "avg by () (sum(rate(container_fs_reads_bytes_total{node_name=\"$proxysql\",id=~\"/kubepods.*\"}[5s]) or irate(container_fs_reads_bytes_total{node_name=\"$proxysql\",id=~\"/kubepods.*\"}[5s]))) + \navg by () (sum(rate(container_fs_writes_bytes_total{node_name=\"$proxysql\",id=~\"/kubepods.*\"}[5s]) or irate(container_fs_writes_bytes_total{node_name=\"$proxysql\",id=~\"/kubepods.*\"}[5s]))) or \navg  by () ((rate(node_vmstat_pgpgin{node_name=\"$proxysql\"}[$interval]) * 1024 or irate(node_vmstat_pgpgin{node_name=\"$proxysql\"}[5m]) * 1024 ) + (rate(container_fs_writes_bytes_total{node_name=\"$proxysql\",id=~\"/kubepods.*\"}[5s]) or irate(container_fs_writes_bytes_total{node_name=\"$proxysql\",id=~\"/kubepods.*\"}[5s]))) + \navg by () (sum(rate(container_fs_writes_bytes_total{node_name=\"$proxysql\",id=~\"/kubepods.*\"}[5s]) or irate(container_fs_writes_bytes_total{node_name=\"$proxysql\",id=~\"/kubepods.*\"}[5s]))) or \navg  by () ((rate(node_vmstat_pgpgout{node_name=\"$proxysql\"}[$interval]) * 1024 or irate(node_vmstat_pgpgout{node_name=\"$proxysql\"}[5m]) * 1024))",
       "legendFormat": "Total"
      },
      {
       "expr": "avg by (node_name) (rate(node_vmstat_pswpin{node_name=\"$proxysql\"}[$interval]) * 4096 or irate(node_vmstat_pswpin{node_name=\"$proxysql\"}[5m]) * 4096)",
       "legendFormat": "Swap In (Reads)"
      },
      {
       "expr": "avg by () (rate(container_memory_swap{node_name=\"$proxysql\",id=~\"/kubepods.*\",container!~\"POD|pmm-client|\"}[$interval]) or \nirate(container_memory_swap{node_name=\"$proxysql\",id=~\"/kubepods.*\",container!~\"POD|pmm-client|\"}[5s])) or \navg by () (rate(node_vmstat_pswpout{node_name=\"$proxysql\"}[$interval]) * 4096 or \nirate(node_vmstat_pswpout{node_name=\"$proxysql\"}[5m]) * 4096)",
       "legendFormat": "Swap Out (Writes)"
      }
     ]
    },
    {
     "title": "Network Traffic",
     "type": "graph",
     "description": "Network traffic refers to the amount of data moving across a network at a given point in time.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
     "yaxes": [
      { "format": "Bps", "label": "Outbound (-) / Inbound (+)" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "sum(rate(container_network_receive_bytes_total{node_name=\"$node_name\",id=~\"/kubepods/.*\"}[$interval]) or \nirate(container_network_receive_bytes_total{node_name=\"$node_name\",id=~\"/kubepods/.*\"}[5m])) or\nsum(rate(node_network_receive_bytes_total{node_name=\"$node_name\", device!=\"lo\"}[$interval])) or \nsum(irate(node_network_receive_bytes_total{node_name=\"$node_name\", device!=\"lo\"}[5m])) or \nsum(max_over_time(rdsosmetrics_network_rx{node_name=\"$node_name\"}[$interval])) or \nsum(max_over_time(rdsosmetrics_network_rx{node_name=\"$node_name\"}[5m]))",
       "legendFormat": "Inbound"
      },
      {
       "calculatedInterval": "2s",
       "expr": "sum(rate(container_network_transmit_bytes_total{node_name=\"$node_name\",id=~\"/kubepods/.*\"}[$interval]) or \nirate(container_network_transmit_bytes_total{node_name=\"$node_name\",id=~\"/kubepods/.*\"}[5m])) or \nsum(rate(node_network_transmit_bytes_total{node_name=\"$node_name\", device!=\"lo\"}[$interval])) or \nsum(irate(node_network_transmit_bytes_total{node_name=\"$node_name\", device!=\"lo\"}[5m])) or\nsum(max_over_time(rdsosmetrics_network_tx{node_name=\"$node_name\"}[$interval])) or \nsum(max_over_time(rdsosmetrics_network_tx{node_name=\"$node_name\"}[5m]))",
       "legendFormat": "Outbound"
      }
     ]
    }
   ]
  }
 ]
}