{
 "title": "MySQL User Details",
 "tags": [
  "MySQL",
  "Percona"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "node_name",
    "label": "Node Name",
    "query": {
     "query": "label_values(mysql_info_schema_user_statistics_bytes_sent_total{service_name=~\"$service_name\"}, node_name)"
    }
   },
   {
    "name": "service_name",
    "label": "Service Name",
    "query": {
     "query": "label_values(mysql_info_schema_user_statistics_bytes_sent_total, service_name)"
    }
   },
   {
    "name": "version",
    "query": {
     "query": "query_result(mysql_version_info{service_name=~\"$service_name\"})"
    }
   },
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, environment)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, cluster)"
    }
   },
   {
    "name": "replication_set",
    "label": "Replication Set",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, replication_set)"
    }
   },
   {
    "name": "database",
    "label": "Database",
    "query": {
     "query": "label_values(pg_stat_database_tup_fetched{service_name=~\"$service_name\",datname!~\"template.*|postgres\"},datname)"
    }
   },
   {
    "name": "node_type",
    "label": "Type",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, node_type)"
    }
   },
   {
    "name": "service_type",
    "label": "Type",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, service_type)"
    }
   },
   {
    "name": "username",
    "label": "Username",
    "query": {
     "query": "label_values(mysql_info_schema_user_statistics_connected_time_seconds_total{service_name=\"$service_name\"},user)"
    }
   },
   {
    "name": "schema",
    "label": "Schema",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, schema)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "\nThese graphs are available only for [Percona Server](https://per.co.na/8_0_diagnostics_user_stat) and [MariaDB](https://mariadb.com/kb/en/mariadb/user-statistics/) and require `userstat` variable turned on."
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Active Users",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum by (user) (increase(mysql_info_schema_user_statistics_connected_time_seconds_total{service_name=~\"$service_name\",user=~\"$username\"}[$__range]) > 0 ))"
    }
   ]
  },
  {
   "title": "Lost Connections",
   "type": "stat",
   "description": "The number of connections that were terminated uncleanly.",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(mysql_info_schema_user_statistics_lost_connections_total{service_name=~\"$service_name\",user=~\"$username\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Users Activity",
   "type": "state-timeline",
   "description": "Time while there were connections from clients.",
   "gridPos": { "h": 18, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (service_name,user) (clamp_min(clamp_max(irate(mysql_info_schema_user_statistics_connected_time_seconds_total{service_name=~\"$service_name\",user=~\"$username\"}[$interval]) or irate(mysql_info_schema_user_statistics_connected_time_seconds_total{service_name=~\"$service_name\",user=~\"$username\"}[5m]),1),0))",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "Denied Connections",
   "type": "stat",
   "description": "The number of connections denied to clients.",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(mysql_info_schema_user_statistics_denied_connections_total{service_name=~\"$service_name\",user=~\"$username\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Access Denied",
   "type": "stat",
   "description": "The number of times clients' connections issued commands that were denied.",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(mysql_info_schema_user_statistics_access_denied_total{service_name=~\"$service_name\",user=~\"$username\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Top 10 Sessions",
   "type": "bargauge",
   "description": "Utilization percentage among clients while there were connections.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(10,(increase(mysql_info_schema_user_statistics_connected_time_seconds_total{service_name=~\"$service_name\",user=~\"$username\"}[$__range])/$__range_ms) / \nignoring(user) group_left sum without(user) (\nincrease(mysql_info_schema_user_statistics_connected_time_seconds_total{service_name=~\"$service_name\",user=~\"$username\"}[$__range])/$__range_ms\n))",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "Connections Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Users by Connections Created",
     "type": "graph",
     "description": "The number of connections created for clients.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short", "label": "Connections/sec" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name,user) ((rate(mysql_info_schema_user_statistics_total_ssl_connections_total{service_name=~\"$service_name\",user=~\"$username\"}[$interval]) + rate(mysql_info_schema_user_statistics_total_connections{service_name=~\"$service_name\",user=~\"$username\"}[$interval])) or  (irate(mysql_info_schema_user_statistics_total_ssl_connections_total{service_name=~\"$service_name\",user=~\"$username\"}[5m]) + irate(mysql_info_schema_user_statistics_total_connections{service_name=~\"$service_name\",user=~\"$username\"}[5m])))",
       "legendFormat": "{{ user }}"
      }
     ]
    },
    {
     "title": "Users by Concurrent Connections",
     "type": "graph",
     "description": "The number of concurrent connections for clients.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "short", "label": "Connections/sec" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name,user) (rate(mysql_info_schema_user_statistics_concurrent_connections{service_name=~\"$service_name\",user=~\"$username\"}[$interval]) or irate(mysql_info_schema_user_statistics_concurrent_connections{service_name=~\"$service_name\",user=~\"$username\"}[5m]))",
       "legendFormat": "{{ user }}"
      }
     ]
    },
    {
     "title": "Users by Lost Connections",
     "type": "graph",
     "description": "The number of this client’s connections that were terminated uncleanly.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short", "label": "Connections/sec" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name,user) (rate(mysql_info_schema_user_statistics_lost_connections_total{service_name=~\"$service_name\",user=~\"$username\"}[$interval]) or irate(mysql_info_schema_user_statistics_lost_connections_total{service_name=~\"$service_name\",user=~\"$username\"}[5m]))",
       "legendFormat": "{{ user }}"
      }
     ]
    },
    {
     "title": "Top Users by Denied Connections",
     "type": "graph",
     "description": "The number of connections denied to this client.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
     "yaxes": [
      { "format": "short", "label": "Connections/sec" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name,user) (rate(mysql_info_schema_user_statistics_denied_connections_total{service_name=~\"$service_name\",user=~\"$username\"}[$interval]) or irate(mysql_info_schema_user_statistics_denied_connections_total{service_name=~\"$service_name\",user=~\"$username\"}[5m]))",
       "legendFormat": "{{ user }}"
      }
     ]
    },
    {
     "title": "Users by Busy Load",
     "type": "graph",
     "description": "Time of activity on connections from clients.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name,user) (rate(mysql_info_schema_user_statistics_busy_seconds_total{service_name=~\"$service_name\",user=~\"$username\"}[$interval]) or  irate(mysql_info_schema_user_statistics_busy_seconds_total{service_name=~\"$service_name\",user=~\"$username\"}[5m]))",
       "legendFormat": "{{ user }}"
      }
     ]
    },
    {
     "title": "Users by CPU Time",
     "type": "graph",
     "description": "CPU time, while servicing  clients' connections.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name,user) (rate(mysql_info_schema_user_statistics_cpu_time_seconds_total{service_name=~\"$service_name\",user=~\"$username\"}[$interval]) or \nirate(mysql_info_schema_user_statistics_cpu_time_seconds_total{service_name=~\"$service_name\",user=~\"$username\"}[5m]))",
       "legendFormat": "{{ user }}"
      }
     ]
    },
    {
     "title": "Users by Traffic",
     "type": "graph",
     "description": "Data sent and received to clients' connections.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name,user) ((rate(mysql_info_schema_user_statistics_bytes_sent_total{service_name=~\"$service_name\",user=~\"$username\"}[$interval]) + rate(mysql_info_schema_user_statistics_bytes_received_total{service_name=~\"$service_name\",user=~\"$username\"}[$interval])) or \n(irate(mysql_info_schema_user_statistics_bytes_sent_total{service_name=~\"$service_name\",user=~\"$username\"}[5m]) + irate(mysql_info_schema_user_statistics_bytes_received_total{service_name=~\"$service_name\",user=~\"$username\"}[5m])))",
       "legendFormat": "{{ user }}"
      }
     ]
    },
    {
     "title": "Users by Bytes Written to The Binary Log",
     "type": "graph",
     "description": "Data written to the binary log from clients' connections.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name,user) (rate(mysql_info_schema_user_statistics_binlog_bytes_written_total{service_name=~\"$service_name\",user=~\"$username\"}[$interval]) or \nirate(mysql_info_schema_user_statistics_binlog_bytes_written_total{service_name=~\"$service_name\",user=~\"$username\"}[5m]))",
       "legendFormat": "{{ user }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Rows Operations / Transactions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Rows Fetched",
   "type": "table",
   "description": "Numbers of rows fetched by clients' connections.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum by (user) ((increase(mysql_info_schema_user_statistics_rows_fetched_total{service_name=~\"$service_name\",user=~\"$username\"}[$__range])) or (increase(mysql_info_schema_user_statistics_rows_sent_total{service_name=~\"$service_name\",user=~\"$username\"}[$__range])))",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "Rows Read",
   "type": "table",
   "description": "Numbers of rows read by clients' connections.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "sum by (user) ((increase(mysql_info_schema_user_statistics_table_rows_read_total{service_name=~\"$service_name\",user=~\"$username\"}[$__range])) or (increase(mysql_info_schema_user_statistics_rows_read_total{service_name=~\"$service_name\",user=~\"$username\"}[$__range])))",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "Rows Updated",
   "type": "table",
   "description": "Numbers of rows updated by clients' connections.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "avg by (service_name,user) (increase(mysql_info_schema_user_statistics_rows_updated_total{service_name=~\"$service_name\",user=~\"$username\"}[$__range]))",
     "legendFormat": " {{user}}"
    }
   ]
  },
  {
   "title": "Rows Operations / Transactions Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Users by Rows Fetched/Read",
     "type": "graph",
     "description": "Numbers of rows fetched/read from tables by clients' connections.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "short", "label": "Rows/sec" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name,user) (rate(mysql_info_schema_user_statistics_rows_fetched_total{service_name=~\"$service_name\",user=~\"$username\"}[$interval]) or rate(mysql_info_schema_user_statistics_rows_sent_total{service_name=~\"$service_name\",user=~\"$username\"}[$interval]) or  irate(mysql_info_schema_user_statistics_rows_fetched_total{service_name=~\"$service_name\",user=~\"$username\"}[5m]) or irate(mysql_info_schema_user_statistics_rows_sent_total{service_name=~\"$service_name\",user=~\"$username\"}[5m]))",
       "legendFormat": "Fetched {{ user }}"
      },
      {
       "expr": "avg by (service_name,user) (rate(mysql_info_schema_user_statistics_table_rows_read_total{service_name=~\"$service_name\",user=~\"$username\"}[$interval]) or rate(mysql_info_schema_user_statistics_rows_read_total{service_name=~\"$service_name\",user=~\"$username\"}[$interval]) or irate(mysql_info_schema_user_statistics_table_rows_read_total{service_name=~\"$service_name\",user=~\"$username\"}[5m]) or irate(mysql_info_schema_user_statistics_rows_read_total{service_name=~\"$service_name\",user=~\"$username\"}[5m]))",
       "legendFormat": "Read {{ user }}"
      }
     ]
    },
    {
     "title": "Users by Rows Updated",
     "type": "graph",
     "description": "Numbers of rows updated by clients' connections.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
     "yaxes": [
      { "format": "short", "label": "Rows/sec" }
     ],
     "targets": [
      {
       "expr": "avg by (service_name,user) (rate(mysql_info_schema_user_statistics_rows_updated_total{service_name=~\"$service_name\",user=~\"$username\"}[$interval]) or irate(mysql_info_schema_user_statistics_rows_updated_total{service_name=~\"$service_name\",user=~\"$username\"}[5m]))",
       "legendFormat": "{{user}}"
      }
     ]
    },
    {
     "title": "Users by Rollback Transactions",
     "type": "graph",
     "description": "Numbers of ROLLBACK commands issued by clients' connections.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "short", "label": "Transactions/sec" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name,user) (rate(mysql_info_schema_user_statistics_rollback_transactions_total{service_name=~\"$service_name\",user=~\"$username\"}[$interval]) or \nirate(mysql_info_schema_user_statistics_rollback_transactions_total{service_name=~\"$service_name\",user=~\"$username\"}[5m]))",
       "legendFormat": "{{ user }}"
      }
     ]
    },
    {
     "title": "Users by Commit Transactions",
     "type": "graph",
     "description": "Numbers of COMMIT commands issued by clients' connections.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
     "yaxes": [
      { "format": "short", "label": "Transactions/sec" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name,user) (rate(mysql_info_schema_user_statistics_commit_transactions_total{service_name=~\"$service_name\",user=~\"$username\"}[$interval]) or irate(mysql_info_schema_user_statistics_commit_transactions_total{service_name=~\"$service_name\",user=~\"$username\"}[5m]))",
       "legendFormat": "{{ user }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Commands / Empty Queries Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Users by Update Commands",
     "type": "graph",
     "description": "Numbers of UPDATE commands executed from  clients' connections.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "short", "label": "Commands/sec" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name,user) (rate(mysql_info_schema_user_statistics_update_commands_total{service_name=~\"$service_name\",user=~\"$username\"}[$interval]) or irate(mysql_info_schema_user_statistics_update_commands_total{service_name=~\"$service_name\",user=~\"$username\"}[5m]))",
       "legendFormat": "{{ user }}"
      }
     ]
    },
    {
     "title": "Users by Select Commands",
     "type": "graph",
     "description": "Numbers of SELECT commands executed from  clients' connections.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
     "yaxes": [
      { "format": "short", "label": "Commands/sec" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name,user) (rate(mysql_info_schema_user_statistics_select_commands_total{service_name=~\"$service_name\",user=~\"$username\"}[$interval]) or irate(mysql_info_schema_user_statistics_select_commands_total{service_name=~\"$service_name\",user=~\"$username\"}[5m]))",
       "legendFormat": "{{ user }}"
      }
     ]
    },
    {
     "title": "Users by Other Commands",
     "type": "graph",
     "description": "Numbers of other commands executed from  clients' connections.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "short", "label": "Commands/sec" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name,user) (rate(mysql_info_schema_user_statistics_other_commands_total{service_name=~\"$service_name\",user=~\"$username\"}[$interval]) or irate(mysql_info_schema_user_statistics_other_commands_total{service_name=~\"$service_name\",user=~\"$username\"}[5m]))",
       "legendFormat": "{{ user }}"
      }
     ]
    },
    {
     "title": "Users by Access Denied",
     "type": "graph",
     "description": "Numbers of times clients' connections issued commands that were denied.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
     "yaxes": [
      { "format": "short", "label": "Requests/sec" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name,user) (rate(mysql_info_schema_user_statistics_access_denied_total{service_name=~\"$service_name\",user=~\"$username\"}[$interval]) or irate(mysql_info_schema_user_statistics_access_denied_total{service_name=~\"$service_name\",user=~\"$username\"}[5m]))",
       "legendFormat": "{{ user }}"
      }
     ]
    },
    {
     "title": "Users by Empty Queries",
     "type": "graph",
     "description": "Numbers of times clients sent empty queries to the server.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
     "yaxes": [
      { "format": "short", "label": "Queries/sec" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name,user) (rate(mysql_info_schema_user_statistics_empty_queries_total{service_name=~\"$service_name\",user=~\"$username\"}[$interval]) or irate(mysql_info_schema_user_statistics_empty_queries_total{service_name=~\"$service_name\",user=~\"$username\"}[5m]))",
       "legendFormat": "{{ user }}"
      }
     ]
    }
   ]
  },
  {
   "title": "MySQL Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "MySQL Uptime",
     "type": "stat",
     "description": "**MySQL Uptime**\n\nThe amount of time since the last restart of the MySQL server process.",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "avg by (service_name) (mysql_global_status_uptime{service_name=~\"$service_name\"})"
      }
     ]
    },
    {
     "title": "Version",
     "type": "text",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 42 },
     "options": {
      "content": "<h3 style='color:#e68a00;font-weight:bold;text-align:center'>$version</h3>"
     }
    },
    {
     "title": "Current QPS",
     "type": "stat",
     "description": "**Current QPS**\n\nBased on the queries reported by MySQL's ``SHOW STATUS`` command, it is the number of statements executed by the server within the last second. This variable includes statements executed within stored programs, unlike the Questions variable. It does not count \n``COM_PING`` or ``COM_STATISTICS`` commands.",
     "gridPos": { "h": 3, "w": 3, "x": 6, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "avg by (service_name) (rate(mysql_global_status_queries{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_queries{service_name=~\"$service_name\"}[5m]))"
      }
     ]
    },
    {
     "title": "File Handlers Used",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 9, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "avg by (service_name) ((sum(max_over_time(mysql_global_status_open_files{service_name=~\"$service_name\"}[$interval])) or sum(max_over_time(mysql_global_status_open_files{service_name=~\"$service_name\"}[5m]))) / (sum\r(max_over_time(mysql_global_variables_open_files_limit{service_name=~\"$service_name\"}[$interval])) or sum(max_over_time(mysql_global_variables_open_files_limit{service_name=~\"$service_name\"}[5m]))\r))"
      }
     ]
    },
    {
     "title": "Table Open Cache Miss Ratio",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 12, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "avg by (service_name) (1-((rate(mysql_global_status_table_open_cache_hits{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_table_open_cache_hits{service_name=~\"$service_name\"}[5m]))/((rate(mysql_global_status_table_open_cache_hits{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_table_open_cache_hits{service_name=~\"$service_name\"}[5m]))+(rate(mysql_global_status_table_open_cache_misses{service_name=~\"$service_name\"}[$interval]) or irate(mysql_global_status_table_open_cache_misses{service_name=~\"$service_name\"}[5m])))))"
      }
     ]
    },
    {
     "title": "Table Open Cache Size",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 15, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "avg by (service_name) (mysql_global_variables_table_open_cache{service_name=~\"$service_name\"})"
      }
     ]
    },
    {
     "title": "Table Definition Cache Size",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 18, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "avg by (service_name) (mysql_global_variables_table_definition_cache{service_name=~\"$service_name\"} )"
      }
     ]
    },
    {
     "title": "Service",
     "type": "text",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 42 },
     "options": {
      "content": "<h5 style='color:#e68a00;font-weight:bold;text-align:center'><a href=\"/graph/d/mysql-instance-summary/mysql-instance-summary?var-service_name=$service_name\" target=\"_blank\">$service_name</h5>"
     }
    },
    {
     "title": "MySQL Connections",
     "type": "graph",
     "description": "**Max Connections** \n\nMax Connections is the maximum permitted number of simultaneous client connections. By default, this is 151. Increasing this value increases the number of file descriptors that mysqld requires. If the required number of descriptors are not available, the server reduces the value of Max Connections.\n\nmysqld actually permits Max Connections + 1 clients to connect. The extra connection is reserved for use by accounts that have the SUPER privilege, such as root.\n\nMax Used Connections is the maximum number of connections that have been in use simultaneously since the server started.\n\nConnections is the number of connection attempts (successful or not) to the MySQL server.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name) (max(max_over_time(mysql_global_status_threads_connected{service_name=~\"$service_name\"}[$interval]) or \nmax_over_time(mysql_global_status_threads_connected{service_name=~\"$service_name\"}[5m])))",
       "legendFormat": "Connections"
      },
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name) (max_over_time(mysql_global_status_max_used_connections{service_name=~\"$service_name\"}[$interval]) or \nmax_over_time(mysql_global_status_max_used_connections{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Max Used Connections"
      },
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name) (max_over_time(mysql_global_variables_max_connections{service_name=~\"$service_name\"}[$interval]) or\nmax_over_time(mysql_global_variables_max_connections{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Max Connections"
      }
     ]
    },
    {
     "title": "MySQL Client Thread Activity",
     "type": "graph",
     "description": "**MySQL Active Threads**\n\nThreads Connected is the number of open connections, while Threads Running is the number of threads not sleeping.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
     "yaxes": [
      { "format": "short", "label": "Threads" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name) (max_over_time(mysql_global_status_threads_connected{service_name=~\"$service_name\"}[$interval]) or\nmax_over_time(mysql_global_status_threads_connected{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Peak Threads Connected"
      },
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name) (max_over_time(mysql_global_status_threads_running{service_name=~\"$service_name\"}[$interval]) or\nmax_over_time(mysql_global_status_threads_running{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Peak Threads Running"
      },
      {
       "expr": "avg by (service_name) (avg_over_time(mysql_global_status_threads_running{service_name=~\"$service_name\"}[$interval]) or \navg_over_time(mysql_global_status_threads_running{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Avg Threads Running"
      }
     ]
    },
    {
     "title": "MySQL Handlers",
     "type": "graph",
     "description": "**MySQL Handlers**\n\nHandler statistics are internal statistics on how MySQL is selecting, updating, inserting, and modifying rows, tables, and indexes.\n\nThis is in fact the layer between the Storage Engine and MySQL.\n\n* `read_rnd_next` is incremented when the server performs a full table scan and this is a counter you don't really want to see with a high value.\n* `read_key` is incremented when a read is done with an index.\n* `read_next` is incremented when the storage engine is asked to 'read the next index entry'. A high value means a lot of index scans are being done.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name,handler) (rate(mysql_global_status_handlers_total{service_name=~\"$service_name\"}[$interval]) or \nirate(mysql_global_status_handlers_total{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "{{ handler }}"
      }
     ]
    },
    {
     "title": "Top Command Counters",
     "type": "graph",
     "description": "**Top Command Counters**\n\nThe Com_{{xxx}} statement counter variables indicate the number of times each xxx statement has been executed. There is one status variable for each type of statement. For example, Com_delete and Com_update count [``DELETE``](https://dev.mysql.com/doc/refman/8.4/en/delete.html) and [``UPDATE``](https://dev.mysql.com/doc/refman/8.4/en/update.html) statements, respectively. Com_delete_multi and Com_update_multi are similar but apply to [``DELETE``](https://dev.mysql.com/doc/refman/8.4/en/delete.html) and [``UPDATE``](https://dev.mysql.com/doc/refman/8.4/en/update.html) statements that use multiple-table syntax.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name,command) (topk(10, rate(mysql_global_status_commands_total{service_name=~\"$service_name\"}[$interval])>0) or \nirate(mysql_global_status_commands_total{service_name=~\"$service_name\"}[5m])>0)",
       "legendFormat": "Com_{{ command }}"
      }
     ]
    },
    {
     "title": "Process States",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name,state) (max_over_time(mysql_info_schema_threads{service_name=~\"$service_name\"}[$interval]) or\nmax_over_time(mysql_info_schema_threads{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "{{ state }}"
      }
     ]
    },
    {
     "title": "MySQL Network Traffic",
     "type": "graph",
     "description": "**MySQL Network Traffic**\n\nHere we can see how much network traffic is generated by MySQL. Outbound is network traffic sent from MySQL and Inbound is network traffic MySQL has received.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name) (rate(mysql_global_status_bytes_received{service_name=~\"$service_name\"}[$interval]) or \nirate(mysql_global_status_bytes_received{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Inbound"
      },
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name) (rate(mysql_global_status_bytes_sent{service_name=~\"$service_name\"}[$interval]) or \nirate(mysql_global_status_bytes_sent{service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "Outbound"
      }
     ]
    }
   ]
  },
  {
   "title": "Node Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "System Uptime",
     "type": "stat",
     "description": "The parameter shows how long a system has been “up” and running without a shut down or restart.",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "avg by (node_name)  (time() - container_start_time_seconds{node_name=~\"$node_name\",id=~\"/kubepods.*\",container!~\"POD|pmm-client|\"}) or avg by (node_name) ((node_time_seconds{node_name=~\"$node_name\"} - node_boot_time_seconds{node_name=~\"$node_name\"}) or (time() - node_boot_time_seconds{node_name=~\"$node_name\"}))"
      }
     ]
    },
    {
     "title": "Load Average",
     "type": "stat",
     "description": "The system load is a measurement of the computational work the system is performing. Each running process either using or waiting for CPU resources adds 1 to the load.",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by () (avg_over_time(node_load1{node_name=~\"$node_name\"}[$interval]) or avg_over_time(node_load1{node_name=~\"$node_name\"}[5m]))"
      }
     ]
    },
    {
     "title": "RAM",
     "type": "stat",
     "description": "RAM (Random Access Memory) is the hardware in a computing device where the operating system, application programs and data in current use are kept so they can be quickly reached by the device's processor.",
     "gridPos": { "h": 3, "w": 3, "x": 6, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by () (container_spec_memory_limit_bytes{node_name=~\"$node_name\",id=~\"/kubepods.*\",container!~\"POD|pmm-client|\"}) or \nmax by () (node_memory_MemTotal_bytes{node_name=~\"$node_name\"})"
      }
     ]
    },
    {
     "title": "Memory Available",
     "type": "stat",
     "description": "Percent of Memory Available\nNote: on Modern Linux Kernels amount of Memory Available for application is not the same as Free+Cached+Buffers",
     "gridPos": { "h": 3, "w": 3, "x": 9, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "clamp_max(avg by () (container_memory_usage_bytes{node_name=~\"$node_name\",id=~\"/kubepods.*\",container!~\"POD|pmm-client|backup-agent|\"} * 100 / container_spec_memory_limit_bytes{node_name=\"$node_name\",id=~\"/kubepods.*\",container!~\"POD|pmm-client|backup-agent|\"}),100) or  \navg by () (((node_memory_MemAvailable_bytes{node_name=~\"$node_name\"} or (node_memory_MemFree_bytes{node_name=~\"$node_name\"} + node_memory_Buffers_bytes{node_name=~\"$node_name\"} + node_memory_Cached_bytes{node_name=~\"$node_name\"})) / node_memory_MemTotal_bytes{node_name=~\"$node_name\"}) * 100 or (100 - azure_memory_percent_average{node_name=~\"$node_name\"}))"
      }
     ]
    },
    {
     "title": "Virtual Memory",
     "type": "stat",
     "description": "RAM + SWAP",
     "gridPos": { "h": 3, "w": 3, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by () (container_spec_memory_limit_bytes{node_name=~\"$node_name\",id=~\"/kubepods.*\",container!~\"POD|pmm-client|\"}+container_spec_memory_swap_limit_bytes{node_name=~\"$node_name\",id=~\"/kubepods.*\",container!~\"POD|pmm-client|\"}) or\nmax by () (node_memory_MemTotal_bytes{node_name=~\"$node_name\"}+node_memory_SwapTotal_bytes{node_name=~\"$node_name\"})"
      }
     ]
    },
    {
     "title": "Disk Space",
     "type": "stat",
     "description": "Sum of disk space on all partitions. Note  it can be significantly over-reported in some installations",
     "gridPos": { "h": 3, "w": 3, "x": 15, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by () (container_fs_limit_bytes{node_name=~\"$node_name\",id=~\"/kubepods.*\",container!~\"POD|pmm-client|\"}) or \navg by () (sum(avg(node_filesystem_size_bytes{node_name=~\"$node_name\",fstype=~\"(ext.|xfs|vfat|)\"}) without (mountpoint)) without (device,fstype))"
      }
     ]
    },
    {
     "title": "Min Space Available",
     "type": "stat",
     "description": "Lowest percent of the disk space available",
     "gridPos": { "h": 3, "w": 3, "x": 18, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (node_name) (min(node_filesystem_free_bytes{node_name=~\"$node_name\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs|shm|overlay|squashfs\"}/node_filesystem_size_bytes{node_name=~\"$node_name\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs|shm|overlay|squashfs\"})*100 or \n(100 - azure_storage_percent_average{node_name=~\"$node_name\"}))"
      }
     ]
    },
    {
     "title": "Node",
     "type": "text",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 43 },
     "options": {
      "content": "<h5 style='color:#e68a00;font-weight:bold;text-align:center'><a href=\"/graph/d/node-instance-summary/node-summary?var-node_name=$node_name\" target=\"_blank\">$node_name</a></h5>"
     },
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "mysql_global_variables_innodb_buffer_pool_size{service_name=~\"$service_name\"} "
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "graph",
     "description": "The CPU time is measured in clock ticks or seconds. It is useful to measure CPU time as a percentage of the CPU's capacity, which is called the CPU usage.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "avg by (node_name,mode) (clamp_max(((avg by (mode) ( (clamp_max(rate(node_cpu_seconds_total{node_name=~\"$node_name\",mode!=\"idle\", mode!=\"user\", mode!=\"system\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{node_name=~\"$node_name\",mode!=\"idle\", mode!=\"user\", mode!=\"system\"}[5m]),1)) ))*100 or (avg_over_time(node_cpu_average{node_name=~\"$node_name\", mode!=\"total\", mode!=\"idle\", mode!=\"user\", mode!=\"system\"}[$interval]) or avg_over_time(node_cpu_average{node_name=~\"$node_name\", mode!=\"total\", mode!=\"idle\", mode!=\"user\", mode!=\"system\"}[5m]))),100))",
       "legendFormat": "{{ mode }}"
      },
      {
       "expr": "clamp_max(avg(rate(container_cpu_system_seconds_total{node_name=~\"$node_name\",id=~\"/kubepods.*\",container!~\"POD|pmm-client|\"}[$interval])) or \n((avg by () ((clamp_max(rate(node_cpu_seconds_total{node_name=~\"$node_name\",mode=\"system\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{node_name=~\"$node_name\",mode=\"system\"}[5m]),1)) ))*100 or \n(avg_over_time(node_cpu_average{node_name=~\"$node_name\", mode=\"system\"}[$interval]) or \navg_over_time(node_cpu_average{node_name=~\"$node_name\", mode=\"system\"}[5m]))),100)",
       "legendFormat": "system"
      },
      {
       "expr": "clamp_max(avg(rate(container_cpu_user_seconds_total{node_name=~\"$node_name\",id=~\"/kubepods.*\",container!~\"POD|pmm-client|\"}[$interval])) or \n((avg by () ((clamp_max(rate(node_cpu_seconds_total{node_name=~\"$node_name\",mode=\"user\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{node_name=~\"$node_name\",mode=\"user\"}[5m]),1)) ))*100 or \n(avg_over_time(node_cpu_average{node_name=~\"$node_name\", mode=\"user\"}[$interval]) or \navg_over_time(node_cpu_average{node_name=~\"$node_name\", mode=\"user\"}[5m]))),100)",
       "legendFormat": "user"
      }
     ]
    },
    {
     "title": "CPU Saturation and Max Core Usage",
     "type": "graph",
     "description": "When a system is running with maximum CPU utilization, the transmitting and receiving threads must all share the available CPU. This will cause data to be queued more frequently to cope with the lack of CPU. CPU Saturation may be measured as the length of a wait queue, or the time spent waiting on the queue.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "((sum(avg_over_time(container_processes{node_name=~\"$node_name\",id=~\"/kubepods.*\",container!~\"POD|pmm-client|\"}[$interval]))-1) / avg by () (machine_cpu_cores)) or\navg by () ((avg_over_time(node_procs_running{node_name=~\"$node_name\"}[$interval])-1) / scalar(count(node_cpu_seconds_total{mode=\"user\", node_name=~\"$node_name\"})) or (avg_over_time(node_procs_running{node_name=~\"$node_name\"}[5m])-1) / scalar(count(node_cpu_seconds_total{mode=\"user\", node_name=~\"$node_name\"})))",
       "legendFormat": "Normalized CPU Load"
      },
      {
       "calculatedInterval": "2s",
       "expr": "clamp_max(sum(rate(container_cpu_usage_seconds_total{node_name=~\"$node_name\",id=~\"/kubepods.*\",container!~\"POD|pmm-client|\"}[$interval]) or rate(container_cpu_usage_seconds_total{node_name=\"$node_name\",id=~\"/kubepods.*\",container!~\"POD|pmm-client|\"}[5m])) or\nmax by () (sum  by (cpu) ( (clamp_max(rate(node_cpu_seconds_total{node_name=~\"$node_name\",mode!=\"idle\",mode!=\"iowait\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{node_name=~\"$node_name\",mode!=\"idle\",mode!=\"iowait\"}[5m]),1)) )),1)",
       "legendFormat": "Max CPU Core Utilization"
      }
     ]
    },
    {
     "title": "Disk I/O and Swap Activity",
     "type": "graph",
     "description": "Disk I/O includes read or write or input/output operations involving a physical disk. It is the speed with which the data transfer takes place between the hard disk drive and RAM.\n\nSwap Activity is memory management that involves swapping sections of memory to and from physical storage.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
     "yaxes": [
      { "format": "Bps", "label": "Page Out (-) / Page In (+)" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "avg by () (sum(rate(container_fs_reads_bytes_total{node_name=\"$node_name\",id=~\"/kubepods.*\"}[5s]) or irate(container_fs_reads_bytes_total{node_name=\"$node_name\",id=~\"/kubepods.*\"}[5s]))) or\navg by () (rate(node_vmstat_pgpgin{node_name=\"$node_name\"}[$interval]) * 1024 or irate(node_vmstat_pgpgin{node_name=\"$node_name\"}[5m]) * 1024)",
       "legendFormat": "Disk Reads (Page In)"
      },
      {
       "calculatedInterval": "2s",
       "expr": "avg by () (sum(rate(container_fs_writes_bytes_total{node_name=\"$node_name\",id=~\"/kubepods.*\"}[5s]) or irate(container_fs_writes_bytes_total{node_name=\"$node_name\",id=~\"/kubepods.*\"}[5s]))) or\navg by () ((rate(node_vmstat_pgpgout{node_name=\"$node_name\"}[$interval]) * 1024 or irate(node_vmstat_pgpgout{node_name=\"$node_name\"}[5m]) * 1024))",
       "legendFormat": "Disk Writes (Page Out)"
      },
      {
       "expr": "avg by () (sum(rate(container_fs_reads_bytes_total{node_name=\"$node_name\",id=~\"/kubepods.*\"}[5s]) or irate(container_fs_reads_bytes_total{node_name=\"$node_name\",id=~\"/kubepods.*\"}[5s]))) + \navg by () (sum(rate(container_fs_writes_bytes_total{node_name=\"$node_name\",id=~\"/kubepods.*\"}[5s]) or irate(container_fs_writes_bytes_total{node_name=\"$node_name\",id=~\"/kubepods.*\"}[5s]))) or \navg  by () ((rate(node_vmstat_pgpgin{node_name=\"$node_name\"}[$interval]) * 1024 or irate(node_vmstat_pgpgin{node_name=\"$node_name\"}[5m]) * 1024 ) + (rate(container_fs_writes_bytes_total{node_name=\"$node_name\",id=~\"/kubepods.*\"}[5s]) or irate(container_fs_writes_bytes_total{node_name=\"$node_name\",id=~\"/kubepods.*\"}[5s]))) + \navg by () (sum(rate(container_fs_writes_bytes_total{node_name=\"$node_name\",id=~\"/kubepods.*\"}[5s]) or irate(container_fs_writes_bytes_total{node_name=\"$node_name\",id=~\"/kubepods.*\"}[5s]))) or \navg  by () ((rate(node_vmstat_pgpgout{node_name=\"$node_name\"}[$interval]) * 1024 or irate(node_vmstat_pgpgout{node_name=\"$node_name\"}[5m]) * 1024))",
       "legendFormat": "Total"
      },
      {
       "expr": "avg by (node_name) (rate(node_vmstat_pswpin{node_name=\"$node_name\"}[$interval]) * 4096 or irate(node_vmstat_pswpin{node_name=\"$node_name\"}[5m]) * 4096)",
       "legendFormat": "Swap In (Reads)"
      },
      {
       "expr": "avg by () (rate(container_memory_swap{node_name=\"$node_name\",id=~\"/kubepods.*\",container!~\"POD|pmm-client|\"}[$interval]) or \nirate(container_memory_swap{node_name=\"$node_name\",id=~\"/kubepods.*\",container!~\"POD|pmm-client|\"}[5s])) or \navg by () (rate(node_vmstat_pswpout{node_name=\"$node_name\"}[$interval]) * 4096 or \nirate(node_vmstat_pswpout{node_name=\"$node_name\"}[5m]) * 4096)",
       "legendFormat": "Swap Out (Writes)"
      }
     ]
    },
    {
     "title": "Network Traffic",
     "type": "graph",
     "description": "Network traffic refers to the amount of data moving across a network at a given point in time.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
     "yaxes": [
      { "format": "Bps", "label": "Outbound (-) / Inbound (+)" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "sum(rate(container_network_receive_bytes_total{node_name=\"$node_name\",id=~\"/kubepods/.*\"}[$interval]) or \nirate(container_network_receive_bytes_total{node_name=\"$node_name\",id=~\"/kubepods/.*\"}[5m])) or\nsum(rate(node_network_receive_bytes_total{node_name=\"$node_name\", device!=\"lo\"}[$interval])) or \nsum(irate(node_network_receive_bytes_total{node_name=\"$node_name\", device!=\"lo\"}[5m])) or \nsum(max_over_time(rdsosmetrics_network_rx{node_name=\"$node_name\"}[$interval])) or \nsum(max_over_time(rdsosmetrics_network_rx{node_name=\"$node_name\"}[5m]))",
       "legendFormat": "Inbound"
      },
      {
       "calculatedInterval": "2s",
       "expr": "sum(rate(container_network_transmit_bytes_total{node_name=\"$node_name\",id=~\"/kubepods/.*\"}[$interval]) or \nirate(container_network_transmit_bytes_total{node_name=\"$node_name\",id=~\"/kubepods/.*\"}[5m])) or \nsum(rate(node_network_transmit_bytes_total{node_name=\"$node_name\", device!=\"lo\"}[$interval])) or \nsum(irate(node_network_transmit_bytes_total{node_name=\"$node_name\", device!=\"lo\"}[5m])) or\nsum(max_over_time(rdsosmetrics_network_tx{node_name=\"$node_name\"}[$interval])) or \nsum(max_over_time(rdsosmetrics_network_tx{node_name=\"$node_name\"}[5m]))",
       "legendFormat": "Outbound"
      }
     ]
    }
   ]
  }
 ]
}