- hosts: localhost
  become: yes
  gather_facts: yes
  tasks:
    - name: Stop supervisord
      service:
        name: supervisord
        state: stopped

    - name: "Copy /srv dir to a safe location"
      synchronize:
        src: "/srv/"
        dest: "/srv-copy"
        recursive: yes

    - name: Delete the old /srv directory
      file:
        state: absent
        path: /srv/

    - name: Create a Volume Group
      lvg:
        vg: DataVG
        pvs: "/dev/nvme1n1"

    - name: Create Thin Pool
      register: thin_pool
      failed_when: "thin_pool is failed and 'Sorry, no shrinking of DataLV to 0 permitted' not in thin_pool.msg"
      lvol:
        lv: DataLV
        vg: DataVG
        size: 100%FREE
        opts: --thinpool ThinPool -V 50G

    - name: Format LVM
      filesystem:
        fstype: xfs
        dev: /dev/DataVG/DataLV
        opts: -L DATA

    - name: Mount
      mount:
        name: "/srv"
        src: LABEL=DATA
        fstype: xfs
        opts: defaults,nofail
        state: mounted

    - name: Copy files to new partition
      synchronize:
        src: "/srv-copy/"
        dest: "/srv/"
        delete: yes
        recursive: yes

    - name: Delete the copy of /srv directory
      file:
        state: absent
        path: /srv-copy/

    - name: Start supervisord
      service:
        name: supervisord
        state: started
