---
# This playbook contains tasks executed during initialization PMM Server
- hosts: localhost
  become: true
  gather_facts: true
  tasks:
    - name: Run initializaion role
      include_role:
        name: initialization
