---
# This playbook contains tasks executed during initialization PMM Server
- hosts: localhost
  become: true
  gather_facts: true
  vars:
    IPV6ONLY: "{{ lookup('env','PMM_IPV6ONLY') }}"
  tasks:
    - name: Run initialization role
      include_role:
        name: initialization
