---
# This playbook contains tasks executed during initialization PMM Server
- hosts: localhost
  become: yes
  gather_facts: yes
  tasks:
    - name: Run initializaion role
      include_role:
        name: initialization
