---
# This playbook contains tasks executed during PMM Server update in non-docker environments.
- hosts: localhost
  become: true
  remote_user: root
  gather_facts: true

  tasks:
    - name: Remove supervisord
      file:
        state: absent
        path: /etc/supervisord.d/supervisord.ini
      when: not is_docker

    # Note: forking type must be set to 'simple'
    - name: Configure systemd
      when: not is_docker
      copy:
        src: supervisord.service
        dest: /usr/lib/systemd/system/supervisord.service
        mode: 0644

    - name: Remove old supervisord service configuration
      when: not is_docker
      file:
        path: /etc/systemd/system/supervisord.service
        state: absent

    # Start the services
    - name: Enable supervisord service to persist between reboots
      systemd:
        name: supervisord
        enabled: yes

    - name: Start supervisord service for AMI/OVF
      when: not is_docker
      systemd:
        name: supervisord
        state: started # supervisord may already be running
        daemon_reload: yes

    - name: Run initialization playbook
      include_role:
        name: initialization

    - name: Enable crond service
      when: not is_docker
      service:
        name: crond
        state: started
        enabled: yes

    - name: Increase number of open files for jobs
      when: not is_docker
      ini_file:
        dest: /etc/supervisord.conf
        section: supervisord
        option: minfds
        value: "800000"

    - name: Stop systemd pmm-agent service, if running
      systemd:
        name: pmm-agent
        state: stopped
        enabled: no
      when: not is_docker

    # https://jira.percona.com/browse/PMM-9298
    - name: Copy rezise-xfs file for lvm
      copy:
        src: resize-xfs-lvm
        dest: /var/lib/cloud/scripts/per-boot/resize-xfs
        mode: 0755
      when: not is_docker

    # https://jira.percona.com/browse/PMM-5271
    - name: Check volume size
      when: not is_docker
      replace:
        dest: /var/lib/cloud/scripts/per-boot/resize-xfs
        regexp: "set -o errexit"
        replace: ""
