// Code generated by go-swagger; DO NOT EDIT.

package actions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewActionsCancelActionParams creates a new ActionsCancelActionParams object
// with the default values initialized.
func NewActionsCancelActionParams() *ActionsCancelActionParams {
	var ()
	return &ActionsCancelActionParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewActionsCancelActionParamsWithTimeout creates a new ActionsCancelActionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewActionsCancelActionParamsWithTimeout(timeout time.Duration) *ActionsCancelActionParams {
	var ()
	return &ActionsCancelActionParams{

		timeout: timeout,
	}
}

// NewActionsCancelActionParamsWithContext creates a new ActionsCancelActionParams object
// with the default values initialized, and the ability to set a context for a request
func NewActionsCancelActionParamsWithContext(ctx context.Context) *ActionsCancelActionParams {
	var ()
	return &ActionsCancelActionParams{

		Context: ctx,
	}
}

// NewActionsCancelActionParamsWithHTTPClient creates a new ActionsCancelActionParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewActionsCancelActionParamsWithHTTPClient(client *http.Client) *ActionsCancelActionParams {
	var ()
	return &ActionsCancelActionParams{
		HTTPClient: client,
	}
}

/*ActionsCancelActionParams contains all the parameters to send to the API endpoint
for the actions cancel action operation typically these are written to a http.Request
*/
type ActionsCancelActionParams struct {

	/*Body*/
	Body ActionsCancelActionBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the actions cancel action params
func (o *ActionsCancelActionParams) WithTimeout(timeout time.Duration) *ActionsCancelActionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the actions cancel action params
func (o *ActionsCancelActionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the actions cancel action params
func (o *ActionsCancelActionParams) WithContext(ctx context.Context) *ActionsCancelActionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the actions cancel action params
func (o *ActionsCancelActionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the actions cancel action params
func (o *ActionsCancelActionParams) WithHTTPClient(client *http.Client) *ActionsCancelActionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the actions cancel action params
func (o *ActionsCancelActionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the actions cancel action params
func (o *ActionsCancelActionParams) WithBody(body ActionsCancelActionBody) *ActionsCancelActionParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the actions cancel action params
func (o *ActionsCancelActionParams) SetBody(body ActionsCancelActionBody) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *ActionsCancelActionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
