{
 "title": "Kubernetes Cluster Overview",
 "description": "Kubernetes Cluster Overview - provides insignts into k8s health and its objects, including Percona Custom Resources",
 "tags": [
  "Kubernetes",
  "Operators",
  "Percona"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "Data_Usage_Interval", "query": "1m,1h,1d,1w" },
   { "name": "k8s_cluster", "label": "K8S Cluster", "query": { "query": "label_values(k8s_cluster_id)" } }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total nodes",
   "type": "stat",
   "description": "The total number of nodes",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_node_info{k8s_cluster_id=\"$k8s_cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Not Ready Nodes",
   "type": "stat",
   "description": "The total number of nodes that are not in Ready state",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{k8s_cluster_id=\"$k8s_cluster\",condition!=\"Ready\",status=\"true\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Pods",
   "type": "stat",
   "description": "The total number of Pods in the cluster",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{k8s_cluster_id=\"$k8s_cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Not Running Pods",
   "type": "stat",
   "description": "The total number of Pods not in the Running Status",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{k8s_cluster_id=\"$k8s_cluster\",phase!=\"Running\",phase!=\"Succeeded\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU capacity",
   "type": "stat",
   "description": "Total CPU (cores) capacity of the Kubernetes cluster",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{k8s_cluster_id=\"$k8s_cluster\",resource=\"cpu\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU requests",
   "type": "stat",
   "description": "How many CPU cores were requested by Containers",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{k8s_cluster_id=\"$k8s_cluster\",resource=\"cpu\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU requests %",
   "type": "gauge",
   "description": "Percentage showing the requested CPU cores or used CPU cluster capacity",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{k8s_cluster_id=\"$k8s_cluster\",resource=\"cpu\"}) / sum(kube_node_status_capacity{k8s_cluster_id=\"$k8s_cluster\",resource=\"cpu\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU limits",
   "type": "stat",
   "description": "The sum of CPU (cores) limits for all containers in the cluster",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{k8s_cluster_id=\"$k8s_cluster\",resource=\"cpu\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Percona Clusters",
   "type": "stat",
   "description": "The number of Percona Clusters (Custom Resources) deployed in the cluster",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum(kube_pxc_info{k8s_cluster_id=\"$k8s_cluster\"}),sum(kube_psmdb_info{k8s_cluster_id=\"$k8s_cluster\"}),sum(kube_pg_info{k8s_cluster_id=\"$k8s_cluster\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Percona Clusters not Ready",
   "type": "stat",
   "description": "The number of Percona Clusters (Custom Resources) deployed in the cluster that are not in Ready state",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum(kube_pxc_status_state{k8s_cluster_id=\"$k8s_cluster\",state!=\"ready\"}),sum(kube_psmdb_status_state{k8s_cluster_id=\"$k8s_cluster\",state!=\"ready\"}),sum(kube_pg_status_state{k8s_cluster_id=\"$k8s_cluster\",state!=\"ready\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory capacity",
   "type": "stat",
   "description": "Total Memory (RAM) capacity of the Kubernetes cluster",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{k8s_cluster_id=\"$k8s_cluster\",resource=\"memory\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory requests",
   "type": "stat",
   "description": "How many Memory (RAM) bytes were requested by Containers",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{k8s_cluster_id=\"$k8s_cluster\",resource=\"memory\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory requests %",
   "type": "gauge",
   "description": "Percentage showing the requested Memory or used Memory cluster capacity",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{k8s_cluster_id=\"$k8s_cluster\",resource=\"memory\"}) / sum(kube_node_status_capacity{k8s_cluster_id=\"$k8s_cluster\",resource=\"memory\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory limits",
   "type": "stat",
   "description": "The sum of Memory (RAM) bytes limits set for containers",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{k8s_cluster_id=\"$k8s_cluster\",resource=\"memory\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Cluster - Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Node Status",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{k8s_cluster_id=\"$k8s_cluster\",status=\"true\"}) by (condition)",
     "legendFormat": "{{condition}}"
    }
   ]
  },
  {
   "title": "Pod Status",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{k8s_cluster_id=\"$k8s_cluster\"}) by (phase)",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "Percona Custom Resources - Clusters",
   "type": "timeseries",
   "description": "The health of Percona Custom Resources (CRs) for Clusters - PXC, Percona Server for MongoDB, Percona Distribution for PostgreSQL",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum(kube_pxc_status_state{k8s_cluster_id=\"$k8s_cluster\"},kube_psmdb_status_state{k8s_cluster_id=\"$k8s_cluster\"},kube_pg_status_state{k8s_cluster_id=\"$k8s_cluster\"}) by (state)",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "Percona Custom Resources - Clusters",
   "type": "table",
   "description": "The table that lists Percona Custom Resources - Clusters",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "kube_pxc_status_state{k8s_cluster_id=\"$k8s_cluster\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "kube_psmdb_status_state{k8s_cluster_id=\"$k8s_cluster\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "kube_pg_status_state{k8s_cluster_id=\"$k8s_cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Percona Custom Resources - Backups",
   "type": "timeseries",
   "description": "The health of Percona Custom Resources (CRs) for Backups - pxc-backup, psmdb-backup, pg-backup",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum(kube_pxc_backup_status_state{k8s_cluster_id=\"$k8s_cluster\"},kube_psmdb_backup_status_state{k8s_cluster_id=\"$k8s_cluster\"},kube_pg_backup_status_state{k8s_cluster_id=\"$k8s_cluster\"}) by (state)",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "Percona Custom Resources - Backups",
   "type": "table",
   "description": "The table that lists Percona Custom Resources - Backups",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "kube_pxc_backup_status_state{k8s_cluster_id=\"$k8s_cluster\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "kube_psmdb_backup_status_state{k8s_cluster_id=\"$k8s_cluster\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "kube_pg_backup_status_state{k8s_cluster_id=\"$k8s_cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PV and PVC Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "sum(kube_persistentvolumeclaim_status_phase{k8s_cluster_id=\"$k8s_cluster\"}) by (phase)",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "Storage Class",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "kube_storageclass_info{k8s_cluster_id=\"$k8s_cluster\"}"
    }
   ]
  },
  { "title": "Cluster - Compute and Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "CPU and Memory %",
   "type": "timeseries",
   "description": "CPU and Memory requests and limits utilization for the whole Kubernetes cluster",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{k8s_cluster_id=\"$k8s_cluster\",resource=\"cpu\"}) / \r\nsum(kube_node_status_capacity{k8s_cluster_id=\"$k8s_cluster\",resource=\"cpu\"})\r\n* 100",
     "legendFormat": "CPU Request %"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{k8s_cluster_id=\"$k8s_cluster\",resource=\"cpu\"}) / \r\nsum(kube_node_status_capacity{k8s_cluster_id=\"$k8s_cluster\",resource=\"cpu\"})\r\n* 100",
     "legendFormat": "CPU Limit %"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{k8s_cluster_id=\"$k8s_cluster\",resource=\"memory\"}) / \r\nsum(kube_node_status_capacity{k8s_cluster_id=\"$k8s_cluster\",resource=\"memory\"})\r\n* 100",
     "legendFormat": "Memory Requests %"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{k8s_cluster_id=\"$k8s_cluster\",resource=\"memory\"}) / \r\nsum(kube_node_status_capacity{k8s_cluster_id=\"$k8s_cluster\",resource=\"memory\"})\r\n* 100",
     "legendFormat": "Memory Limit %"
    }
   ]
  },
  {
   "title": "Cluster Network",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{k8s_cluster_id=\"$k8s_cluster\"}[1m]))",
     "legendFormat": "Received"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{k8s_cluster_id=\"$k8s_cluster\"}[1m]))",
     "legendFormat": "Sent"
    }
   ]
  }
 ]
}