-- metrics_raw: 1-minute landing table. Plain MergeTree, short TTL. Receives the
-- full bucket (incl. identity/example columns); materialized views fan it out to
-- the rollups and sidecars. Nothing is merged here, so it can carry exact min/max.
CREATE TABLE IF NOT EXISTS metrics_raw (
  queryid          LowCardinality(String),
  service_id       LowCardinality(String),
  service_name     LowCardinality(String),
  service_type     LowCardinality(String),
  `database`       LowCardinality(String),
  `schema`         LowCardinality(String),
  username         LowCardinality(String),
  client_host      LowCardinality(String),
  cluster          LowCardinality(String),
  environment      LowCardinality(String),
  replication_set  LowCardinality(String),
  node_id          LowCardinality(String),
  node_name        LowCardinality(String),
  az               LowCardinality(String),
  region           LowCardinality(String),
  container_name   LowCardinality(String),
  cmd_type         LowCardinality(String),
  agent_id         LowCardinality(String),
  agent_type       LowCardinality(String),
  labels           Map(String, String),
  fingerprint          String,
  `tables`             Array(String),
  explain_fingerprint  String,
  placeholders_count   UInt32,
  example              String,
  example_metrics      String,
  query_plan           String,
  planid               String,
  plan_summary         String,
  is_truncated         UInt8,
  example_type         LowCardinality(String),
  period_start     DateTime,
  period_length    UInt32,
  sketch_layout    UInt16,
  num_queries                Float64,
  num_queries_with_errors    Float64,
  num_queries_with_warnings  Float64,
  m_query_time_sum     Float64,
  m_query_time_cnt     UInt64,
  m_query_time_min     Float32,
  m_query_time_max     Float32,
  m_query_time_sketch  Map(UInt16, UInt64),
  m_lock_time_sum      Float64,
  m_lock_time_cnt      UInt64,
  m_lock_time_min      Float32,
  m_lock_time_max      Float32,
  m_lock_time_sketch   Map(UInt16, UInt64),
  m_rows_sent_sum      Float64,
  m_rows_sent_cnt      UInt64,
  m_rows_sent_min      Float32,
  m_rows_sent_max      Float32,
  m_rows_examined_sum  Float64,
  m_rows_examined_cnt  UInt64,
  m_rows_examined_min  Float32,
  m_rows_examined_max  Float32,
  m_rows_affected_sum  Float64,
  m_rows_affected_cnt  UInt64,
  m_rows_affected_min  Float32,
  m_rows_affected_max  Float32,
  m_bytes_sent_sum     Float64,
  m_bytes_sent_cnt     UInt64,
  m_bytes_sent_min     Float32,
  m_bytes_sent_max     Float32,
  m_sum  Map(String, Float64),
  m_cnt  Map(String, UInt64),
  INDEX idx_labels_keys mapKeys(labels) TYPE bloom_filter GRANULARITY 1
) ENGINE = {{ .MergeTree }}
PARTITION BY toYYYYMMDD(period_start)
ORDER BY (service_id, period_start, `database`, `schema`, cmd_type, queryid)
TTL period_start + INTERVAL 7 DAY
SETTINGS index_granularity = 8192;
