CREATE MATERIALIZED VIEW IF NOT EXISTS mv_metrics_1d TO metrics_1d AS
SELECT
  queryid, service_id, `database`, `schema`, cmd_type,
  toStartOfDay(period_start) AS period_start,
  anyLast(service_name) AS service_name,
  anyLast(service_type) AS service_type,
  anyLast(cluster) AS cluster,
  anyLast(environment) AS environment,
  anyLast(replication_set) AS replication_set,
  anyLast(node_name) AS node_name,
  anyLast(az) AS az,
  anyLast(region) AS region,
  anyLast(container_name) AS container_name,
  anyLast(labels) AS labels,
  sum(num_queries) AS num_queries,
  sum(num_queries_with_errors) AS num_queries_with_errors,
  sum(num_queries_with_warnings) AS num_queries_with_warnings,
  sum(m_query_time_sum) AS m_query_time_sum,
  sum(m_query_time_cnt) AS m_query_time_cnt,
  min(m_query_time_min) AS m_query_time_min,
  max(m_query_time_max) AS m_query_time_max,
  sumMap(m_query_time_sketch) AS m_query_time_sketch,
  sum(m_lock_time_sum) AS m_lock_time_sum,
  sum(m_lock_time_cnt) AS m_lock_time_cnt,
  min(m_lock_time_min) AS m_lock_time_min,
  max(m_lock_time_max) AS m_lock_time_max,
  sumMap(m_lock_time_sketch) AS m_lock_time_sketch,
  sum(m_rows_sent_sum) AS m_rows_sent_sum,
  sum(m_rows_sent_cnt) AS m_rows_sent_cnt,
  min(m_rows_sent_min) AS m_rows_sent_min,
  max(m_rows_sent_max) AS m_rows_sent_max,
  sum(m_rows_examined_sum) AS m_rows_examined_sum,
  sum(m_rows_examined_cnt) AS m_rows_examined_cnt,
  min(m_rows_examined_min) AS m_rows_examined_min,
  max(m_rows_examined_max) AS m_rows_examined_max,
  sum(m_rows_affected_sum) AS m_rows_affected_sum,
  sum(m_rows_affected_cnt) AS m_rows_affected_cnt,
  min(m_rows_affected_min) AS m_rows_affected_min,
  max(m_rows_affected_max) AS m_rows_affected_max,
  sum(m_bytes_sent_sum) AS m_bytes_sent_sum,
  sum(m_bytes_sent_cnt) AS m_bytes_sent_cnt,
  min(m_bytes_sent_min) AS m_bytes_sent_min,
  max(m_bytes_sent_max) AS m_bytes_sent_max,
  sumMap(m_sum) AS m_sum,
  sumMap(m_cnt) AS m_cnt
FROM metrics_raw
GROUP BY queryid, service_id, `database`, `schema`, cmd_type, period_start;
