import { UniversalService } from 'types/services.types';

// Mock data matching Figma design for Real-Time Query Analytics selection page
export const mockMongoDBServices: UniversalService[] = [
  // Standalone Services (no cluster)
  {
    serviceId: '/service_id/accounting-prod-rs',
    serviceType: 'SERVICE_TYPE_MONGODB_SERVICE',
    serviceName: 'accounting-prod-rs',
    databaseName: '',
    nodeId: '/node_id/node1',
    nodeName: 'node1',
    environment: 'production',
    cluster: '',
    replicationSet: '',
    customLabels: {},
    externalGroup: '',
    address: '127.0.0.1',
    port: 27017,
    socket: '',
    version: '7.0.5',
    status: 'STATUS_UP',
  },
  {
    serviceId: '/service_id/billing-service',
    serviceType: 'SERVICE_TYPE_MONGODB_SERVICE',
    serviceName: 'billing-service',
    databaseName: '',
    nodeId: '/node_id/node2',
    nodeName: 'node2',
    environment: 'production',
    cluster: '',
    replicationSet: '',
    customLabels: {},
    externalGroup: '',
    address: '127.0.0.1',
    port: 27018,
    socket: '',
    version: '7.0.5',
    status: 'STATUS_UP',
  },

  // Cluster: mc-ga (matching Figma design)
  {
    serviceId: '/service_id/mc-ga-config-01',
    serviceType: 'SERVICE_TYPE_MONGODB_SERVICE',
    serviceName: 'mc-ga-config-01',
    databaseName: '',
    nodeId: '/node_id/node3',
    nodeName: 'node3',
    environment: 'production',
    cluster: 'mc-ga',
    replicationSet: 'rs0',
    customLabels: {},
    externalGroup: '',
    address: '127.0.0.1',
    port: 27019,
    socket: '',
    version: '7.0.5',
    status: 'STATUS_UP',
  },
  {
    serviceId: '/service_id/mc-ga-config-02',
    serviceType: 'SERVICE_TYPE_MONGODB_SERVICE',
    serviceName: 'mc-ga-config-02',
    databaseName: '',
    nodeId: '/node_id/node4',
    nodeName: 'node4',
    environment: 'production',
    cluster: 'mc-ga',
    replicationSet: 'rs0',
    customLabels: {},
    externalGroup: '',
    address: '127.0.0.1',
    port: 27020,
    socket: '',
    version: '7.0.5',
    status: 'STATUS_UP',
  },
  {
    serviceId: '/service_id/mc-ga-router-01',
    serviceType: 'SERVICE_TYPE_MONGODB_SERVICE',
    serviceName: 'mc-ga-router-01',
    databaseName: '',
    nodeId: '/node_id/node5',
    nodeName: 'node5',
    environment: 'production',
    cluster: 'mc-ga',
    replicationSet: '',
    customLabels: {},
    externalGroup: '',
    address: '127.0.0.1',
    port: 27021,
    socket: '',
    version: '7.0.5',
    status: 'STATUS_UP',
  },
  {
    serviceId: '/service_id/mc-ga-router-02',
    serviceType: 'SERVICE_TYPE_MONGODB_SERVICE',
    serviceName: 'mc-ga-router-02',
    databaseName: '',
    nodeId: '/node_id/node6',
    nodeName: 'node6',
    environment: 'production',
    cluster: 'mc-ga',
    replicationSet: '',
    customLabels: {},
    externalGroup: '',
    address: '127.0.0.1',
    port: 27022,
    socket: '',
    version: '7.0.5',
    status: 'STATUS_UP',
  },

  // Additional services for testing (mixed statuses)
  {
    serviceId: '/service_id/analytics-cache',
    serviceType: 'SERVICE_TYPE_MONGODB_SERVICE',
    serviceName: 'analytics-cache',
    databaseName: '',
    nodeId: '/node_id/node7',
    nodeName: 'node7',
    environment: 'staging',
    cluster: '',
    replicationSet: '',
    customLabels: {},
    externalGroup: '',
    address: '127.0.0.1',
    port: 27023,
    socket: '',
    version: '6.0.12',
    status: 'STATUS_DOWN',
  },
  {
    serviceId: '/service_id/dev-cluster-primary',
    serviceType: 'SERVICE_TYPE_MONGODB_SERVICE',
    serviceName: 'dev-cluster-primary',
    databaseName: '',
    nodeId: '/node_id/node8',
    nodeName: 'node8',
    environment: 'development',
    cluster: 'dev-cluster',
    replicationSet: 'rs1',
    customLabels: {},
    externalGroup: '',
    address: '127.0.0.1',
    port: 27024,
    socket: '',
    version: '6.0.12',
    status: 'STATUS_UP',
  },
  {
    serviceId: '/service_id/dev-cluster-secondary',
    serviceType: 'SERVICE_TYPE_MONGODB_SERVICE',
    serviceName: 'dev-cluster-secondary',
    databaseName: '',
    nodeId: '/node_id/node9',
    nodeName: 'node9',
    environment: 'development',
    cluster: 'dev-cluster',
    replicationSet: 'rs1',
    customLabels: {},
    externalGroup: '',
    address: '127.0.0.1',
    port: 27025,
    socket: '',
    version: '6.0.12',
    status: 'STATUS_DOWN',
  },
];
