import { VersionedService } from 'types/services.types';

export const mockMongoDBServices: VersionedService[] = [
  {
    serviceId: '/service_id/accounting-prod-rs',
    serviceName: 'accounting-prod-rs',
    nodeId: '/node_id/node1',
    environment: 'production',
    cluster: '',
    replicationSet: '',
    customLabels: {},
    address: '127.0.0.1',
    port: 27017,
    socket: '',
    version: '6.0.5',
  },
  {
    serviceId: '/service_id/accounts-receivable-dev-primary',
    serviceName: 'accounts-receivable-dev-primary',
    nodeId: '/node_id/node2',
    environment: 'dev',
    cluster: 'accounts-receivable-dev',
    replicationSet: 'rs0',
    customLabels: {},
    address: '127.0.0.1',
    port: 27018,
    socket: '',
    version: '6.0.5',
  },
  {
    serviceId: '/service_id/accounts-receivable-dev-secondary-a',
    serviceName: 'accounts-receivable-dev-secondary-a',
    nodeId: '/node_id/node3',
    environment: 'dev',
    cluster: 'accounts-receivable-dev',
    replicationSet: 'rs0',
    customLabels: {},
    address: '127.0.0.1',
    port: 27019,
    socket: '',
    version: '6.0.5',
  },
  {
    serviceId: '/service_id/accounts-receivable-dev-secondary-b',
    serviceName: 'accounts-receivable-dev-secondary-b',
    nodeId: '/node_id/node4',
    environment: 'dev',
    cluster: 'accounts-receivable-dev',
    replicationSet: 'rs0',
    customLabels: {},
    address: '127.0.0.1',
    port: 27020,
    socket: '',
    version: '6.0.5',
  },
  {
    serviceId: '/service_id/active-sessions-cache',
    serviceName: 'active-sessions-cache',
    nodeId: '/node_id/node5',
    environment: 'production',
    cluster: '',
    replicationSet: '',
    customLabels: {},
    address: '127.0.0.1',
    port: 27021,
    socket: '',
    version: '7.0.2',
  },
  {
    serviceId: '/service_id/ad-campaigns-global-config-01',
    serviceName: 'ad-campaigns-global-config-01',
    nodeId: '/node_id/node6',
    environment: 'production',
    cluster: 'ad-campaigns-global',
    replicationSet: 'rs1',
    customLabels: {},
    address: '127.0.0.1',
    port: 27022,
    socket: '',
    version: '6.0.5',
  },
  {
    serviceId: '/service_id/ad-campaigns-global-config-02',
    serviceName: 'ad-campaigns-global-config-02',
    nodeId: '/node_id/node7',
    environment: 'production',
    cluster: 'ad-campaigns-global',
    replicationSet: 'rs1',
    customLabels: {},
    address: '127.0.0.1',
    port: 27023,
    socket: '',
    version: '6.0.5',
  },
  {
    serviceId: '/service_id/ad-campaigns-global-router-01',
    serviceName: 'ad-campaigns-global-router-01',
    nodeId: '/node_id/node8',
    environment: 'production',
    cluster: 'ad-campaigns-global',
    replicationSet: '',
    customLabels: {},
    address: '127.0.0.1',
    port: 27024,
    socket: '',
    version: '6.0.5',
  },
  {
    serviceId: '/service_id/ad-campaigns-global-router-02',
    serviceName: 'ad-campaigns-global-router-02',
    nodeId: '/node_id/node9',
    environment: 'production',
    cluster: 'ad-campaigns-global',
    replicationSet: '',
    customLabels: {},
    address: '127.0.0.1',
    port: 27025,
    socket: '',
    version: '6.0.5',
  },
];
