{
 "title": "PostgreSQL Replication Overview",
 "tags": [
  "PostgreSQL",
  "Replication"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values({__name__=~\"pg_up\"}, environment)"
    }
   },
   { "name": "cluster", "label": "Cluster", "query": { "query": "label_values(pg_up,cluster)" } },
   {
    "name": "node_name",
    "label": "Node Name",
    "query": {
     "query": "label_values(pg_up{environment=~\"$environment\", cluster=~\"$cluster\"},node_name)"
    }
   },
   {
    "name": "service_name",
    "label": "Service Name",
    "query": {
     "query": "label_values(pg_up{node_name=~\"$node_name\",environment=~\"$environment\"}, service_name)"
    }
   },
   {
    "name": "database",
    "label": "DB",
    "query": {
     "query": "label_values(pg_stat_database_tup_fetched{service_name=~\"$service_name\",datname!~\"template.*|postgres\",node_name=~\"$node_name\",environment=~\"$environment\"},datname)"
    }
   },
   {
    "name": "work_mem",
    "query": {
     "query": "query_result(pg_settings_work_mem_bytes{service_name=~\"$service_name\",node_name=~\"$node_name\",environment=~\"$environment\"})"
    }
   },
   {
    "name": "version",
    "query": {
     "query": "label_values(pg_static{service_name=~\"$service_name\",node_name=~\"$node_name\",environment=~\"$environment\"},version)"
    }
   },
   {
    "name": "max_connections",
    "query": {
     "query": "query_result(pg_settings_max_connections{service_name=~\"$service_name\",node_name=~\"$node_name\",environment=~\"$environment\"})"
    }
   },
   {
    "name": "shared_buffers",
    "query": {
     "query": "query_result(pg_settings_shared_buffers_bytes{service_name=~\"$service_name\",node_name=~\"$node_name\",environment=~\"$environment\"})"
    }
   },
   {
    "name": "wal_buffers",
    "query": {
     "query": "query_result(pg_settings_wal_buffers_bytes{service_name=~\"$service_name\",node_name=~\"$node_name\",environment=~\"$environment\"})"
    }
   },
   {
    "name": "wal_segment_size",
    "query": {
     "query": "query_result(pg_settings_wal_segment_size_bytes{service_name=~\"$service_name\",node_name=~\"$node_name\",environment=~\"$environment\"})"
    }
   },
   {
    "name": "maintenance_work_mem",
    "query": {
     "query": "query_result(pg_settings_maintenance_work_mem_bytes{service_name=~\"$service_name\",node_name=~\"$node_name\",environment=~\"$environment\"})"
    }
   },
   {
    "name": "block_size",
    "query": {
     "query": "query_result(pg_settings_block_size{service_name=~\"$service_name\",node_name=~\"$node_name\",environment=~\"$environment\"})"
    }
   },
   {
    "name": "checkpoint_segments",
    "query": {
     "query": "query_result(pg_settings_checkpoint_segments{service_name=~\"$service_name\",node_name=~\"$node_name\",environment=~\"$environment\"})"
    }
   },
   {
    "name": "checkpoint_timeout",
    "query": {
     "query": "query_result(pg_settings_checkpoint_timeout_seconds{service_name=~\"$service_name\",node_name=~\"$node_name\",environment=~\"$environment\"})"
    }
   },
   {
    "name": "default_statistics_target",
    "query": {
     "query": "query_result(pg_settings_default_statistics_target{service_name=~\"$service_name\",node_name=~\"$node_name\",environment=~\"$environment\"})"
    }
   },
   {
    "name": "seq_page_cost",
    "query": {
     "query": "query_result(pg_settings_seq_page_cost{service_name=~\"$service_name\",node_name=~\"$node_name\",environment=~\"$environment\"})"
    }
   },
   {
    "name": "random_page_cost",
    "query": {
     "query": "query_result(pg_settings_random_page_cost{service_name=~\"$service_name\",node_name=~\"$node_name\",environment=~\"$environment\"})"
    }
   },
   {
    "name": "effective_cache_size",
    "query": {
     "query": "query_result(pg_settings_effective_cache_size_bytes{service_name=~\"$service_name\",node_name=~\"$node_name\",environment=~\"$environment\"})"
    }
   },
   {
    "name": "effective_io_concurrency",
    "query": {
     "query": "query_result(pg_settings_effective_io_concurrency{service_name=~\"$service_name\",node_name=~\"$node_name\",environment=~\"$environment\"})"
    }
   },
   {
    "name": "fsync",
    "query": {
     "query": "query_result(pg_settings_fsync{service_name=~\"$service_name\",node_name=~\"$node_name\",environment=~\"$environment\"})"
    }
   },
   {
    "name": "autovacuum",
    "query": {
     "query": "query_result(pg_settings_autovacuum{service_name=~\"$service_name\",node_name=~\"$node_name\",environment=~\"$environment\"})"
    }
   },
   {
    "name": "autovacuum_analyze_scale_factor",
    "query": {
     "query": "query_result(pg_settings_autovacuum_analyze_scale_factor{service_name=~\"$service_name\",node_name=~\"$node_name\",environment=~\"$environment\"})"
    }
   },
   {
    "name": "autovacuum_analyze_threshold",
    "query": {
     "query": "query_result(pg_settings_autovacuum_analyze_threshold{service_name=~\"$service_name\",node_name=~\"$node_name\",environment=~\"$environment\"})"
    }
   },
   {
    "name": "autovacuum_vacuum_scale_factor",
    "query": {
     "query": "query_result(pg_settings_autovacuum_vacuum_scale_factor{service_name=~\"$service_name\",node_name=~\"$node_name\",environment=~\"$environment\"})"
    }
   },
   {
    "name": "autovacuum_vacuum_threshold",
    "query": {
     "query": "query_result(pg_settings_autovacuum_vacuum_threshold{service_name=~\"$service_name\",node_name=~\"$node_name\",environment=~\"$environment\"})"
    }
   },
   {
    "name": "autovacuum_vacuum_cost_limit",
    "query": {
     "query": "query_result(pg_settings_autovacuum_vacuum_cost_limit{service_name=~\"$service_name\",node_name=~\"$node_name\",environment=~\"$environment\"})"
    }
   },
   {
    "name": "autovacuum_vacuum_cost_delay",
    "query": {
     "query": "query_result(pg_settings_autovacuum_vacuum_cost_delay_seconds{service_name=~\"$service_name\",node_name=~\"$node_name\",environment=~\"$environment\"})"
    }
   },
   {
    "name": "autovacuum_max_workers",
    "query": {
     "query": "query_result(pg_settings_autovacuum_max_workers{service_name=~\"$service_name\",node_name=~\"$node_name\",environment=~\"$environment\"})"
    }
   },
   {
    "name": "autovacuum_naptime",
    "query": {
     "query": "query_result(pg_settings_autovacuum_naptime_seconds{service_name=~\"$service_name\",node_name=~\"$node_name\",environment=~\"$environment\"})"
    }
   },
   {
    "name": "autovacuum_freeze_max_age",
    "query": {
     "query": "query_result(pg_settings_autovacuum_freeze_max_age{service_name=~\"$service_name\",node_name=~\"$node_name\",environment=~\"$environment\"})"
    }
   },
   {
    "name": "logging_collector",
    "query": {
     "query": "query_result(pg_settings_logging_collector{service_name=~\"$service_name\",node_name=~\"$node_name\",environment=~\"$environment\"})"
    }
   },
   {
    "name": "log_min_duration_statement",
    "query": {
     "query": "query_result(pg_settings_log_min_duration_statement_seconds{service_name=~\"$service_name\",node_name=~\"$node_name\",environment=~\"$environment\"})"
    }
   },
   {
    "name": "log_duration",
    "query": {
     "query": "query_result(pg_settings_log_duration{service_name=~\"$service_name\",node_name=~\"$node_name\",environment=~\"$environment\"})"
    }
   },
   {
    "name": "log_lock_waits",
    "query": {
     "query": "query_result(pg_settings_log_lock_waits{service_name=~\"$service_name\",node_name=~\"$node_name\",environment=~\"$environment\"})"
    }
   },
   {
    "name": "max_wal_senders",
    "query": {
     "query": "query_result(pg_settings_max_wal_senders{service_name=~\"$service_name\",node_name=~\"$node_name\",environment=~\"$environment\"})"
    }
   },
   {
    "name": "max_wal_size",
    "query": {
     "query": "query_result(pg_settings_max_wal_size_bytes{service_name=~\"$service_name\",node_name=~\"$node_name\",environment=~\"$environment\"})"
    }
   },
   {
    "name": "min_wal_size",
    "query": {
     "query": "query_result(pg_settings_min_wal_size_bytes{service_name=~\"$service_name\",node_name=~\"$node_name\",environment=~\"$environment\"})"
    }
   },
   {
    "name": "wal_compression",
    "query": {
     "query": "query_result(pg_settings_wal_compression{service_name=~\"$service_name\",node_name=~\"$node_name\",environment=~\"$environment\"})"
    }
   },
   {
    "name": "max_worker_processes",
    "query": {
     "query": "query_result(pg_settings_max_worker_processes{service_name=~\"$service_name\",node_name=~\"$node_name\",environment=~\"$environment\"})"
    }
   },
   {
    "name": "max_parallel_workers_per_gather",
    "query": {
     "query": "query_result(pg_settings_max_parallel_workers_per_gather{service_name=~\"$service_name\",node_name=~\"$node_name\",environment=~\"$environment\"})"
    }
   },
   {
    "name": "max_parallel_workers",
    "query": {
     "query": "query_result(pg_settings_max_parallel_workers_per_gather{service_name=~\"$service_name\",node_name=~\"$node_name\",environment=~\"$environment\"})"
    }
   },
   {
    "name": "autovacuum_work_mem",
    "query": {
     "query": "query_result(pg_settings_autovacuum_work_mem_bytes{service_name=~\"$service_name\",node_name=~\"$node_name\",environment=~\"$environment\"})"
    }
   },
   {
    "name": "autovacuum_multixact_freeze_max_age",
    "query": {
     "query": "query_result(pg_settings_autovacuum_multixact_freeze_max_age{service_name=~\"$service_name\",node_name=~\"$node_name\",environment=~\"$environment\"})"
    }
   },
   {
    "name": "replication_set",
    "label": "Replication Set",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, replication_set)"
    }
   },
   {
    "name": "node_type",
    "label": "Type",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, node_type)"
    }
   },
   {
    "name": "service_type",
    "label": "Type",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, service_type)"
    }
   },
   {
    "name": "username",
    "label": "Username",
    "query": {
     "query": "label_values(mysql_info_schema_user_statistics_connected_time_seconds_total{service_name=\"$service_name\",node_name=~\"$node_name\",environment=~\"$environment\"},user)"
    }
   },
   {
    "name": "schema",
    "label": "Schema",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, schema)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Primary Host",
   "type": "stat",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum(\n    pg_custom_stat_wal_receiver_written_lsn_bytes{environment=~\"$environment\",cluster=~\"$cluster\",node_name=~\"$node_name\",service_name=~\"$service_name\"}\n  ) by (primary_host)\n\n  and on()\n  (\n    sum(\n      pg_replication_is_replica{environment=~\"$environment\",cluster=~\"$cluster\",node_name=~\"$node_name\",service_name=~\"$service_name\"} == 1\n    )\n  )\n)\nor on()\nlabel_replace(\n  sum(\n    pg_replication_is_replica{environment=~\"$environment\",cluster=~\"$cluster\",node_name=~\"$node_name\",service_name=~\"$service_name\"} == 0\n  ) by (node_name),\n  \"primary_host\",\n  \"$1\",\n  \"node_name\",\n  \"(.*)\"\n)\n",
     "legendFormat": "{{primary_host}}"
    }
   ]
  },
  {
   "title": "Number of Replicas",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(last_over_time(pg_custom_stat_replication_replay_lsn_bytes{environment=~\"$environment\",cluster=~\"$cluster\",node_name=~\"$node_name\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "table",
   "gridPos": { "h": 4, "w": 10, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "max by (client_addr,state,sync_state)(max_over_time(pg_custom_stat_replication_flush_lag_seconds{environment=~\"$environment\",cluster=~\"$cluster\",node_name=~\"$node_name\"}[$__range]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Replication Lag",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(pg_replication_lag_seconds{environment=~\"$environment\",cluster=~\"$cluster\",node_name=~\"$node_name\",service_name=~\"$service_name\"}[$__interval] or pg_replication_lag_seconds{environment=~\"$environment\",cluster=~\"$cluster\",node_name=~\"$node_name\",service_name=~\"$service_name\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Written Lag",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(rate(pg_custom_stat_replication_write_lsn_bytes{environment=~\"$environment\",cluster=~\"$cluster\",node_name=~\"$node_name\",service_name=~\"$service_name\"}[$interval]) or irate(pg_custom_stat_replication_write_lsn_bytes{environment=~\"$environment\",cluster=~\"$cluster\",node_name=~\"$node_name\",service_name=~\"$service_name\"}[5m])) by (node_name)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Flush Lag",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(rate(pg_custom_stat_replication_flush_lsn_bytes{environment=~\"$environment\",cluster=~\"$cluster\",node_name=~\"$node_name\",service_name=~\"$service_name\"}[$interval]) or irate(pg_custom_stat_replication_flush_lsn_bytes{environment=~\"$environment\",cluster=~\"$cluster\",node_name=~\"$node_name\",service_name=~\"$service_name\"}[5m])) by (node_name)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Replay Lag",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(rate(pg_custom_stat_replication_replay_lsn_bytes{environment=~\"$environment\",cluster=~\"$cluster\",node_name=~\"$node_name\",service_name=~\"$service_name\"}[$interval]) or irate(pg_custom_stat_replication_replay_lsn_bytes{environment=~\"$environment\",cluster=~\"$cluster\",node_name=~\"$node_name\",service_name=~\"$service_name\"}[5m])) by (node_name)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replication Members State",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "max by (node_name) (pg_replication_is_replica{environment=~\"$environment\",cluster=~\"$cluster\",node_name=~\"$node_name\",service_name=~\"$service_name\"})",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Replication Lag (Seconds)",
   "type": "timeseries",
   "description": "Displays the replication lag in seconds. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pg_replication_lag_seconds{environment=~\"$environment\",cluster=~\"$cluster\",node_name=~\"$node_name\",service_name=~\"$service_name\"}",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Replication Lag (Bytes)",
   "type": "timeseries",
   "description": "Displays the replication lag in bytes. Thresholds indicate acceptable and critical levels.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "pg_custom_stat_wal_receiver_lag_bytes{environment=~\"$environment\",cluster=~\"$cluster\",node_name=~\"$node_name\",service_name=~\"$service_name\"}\n",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Top 10 Replication Conflicts by Node",
   "type": "timeseries",
   "description": "Tracks conflicts occurring during replication, categorized by type.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "topk(10, sum(rate(pg_stat_database_conflicts{environment=~\"$environment\",cluster=~\"$cluster\",node_name=~\"$node_name\",service_name=~\"$service_name\"}[$__interval])) by (node_name))\n",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "WAL Activity",
   "type": "timeseries",
   "description": "Monitors Write-Ahead Logging (WAL) activity, including WAL writes and archives.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(pg_custom_stat_wal_receiver_written_lsn_bytes{environment=~\"$environment\",cluster=~\"$cluster\",node_name=~\"$node_name\",service_name=~\"$service_name\"}[$interval])) by (node_name)\n",
     "legendFormat": "{{wal_activity_type}}"
    }
   ]
  },
  {
   "title": "Replication Slots Status",
   "type": "timeseries",
   "description": "Provides the status of replication slots, indicating active and inactive slots.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "max by (node_name,slot_name,slot_type) (pg_replication_slot_slot_is_active{environment=~\"$environment\",cluster=~\"$cluster\",node_name=~\"$node_name\",service_name=~\"$service_name\"})",
     "legendFormat": "{{node_name}}/{{slot_name}}/{{slot_type}}"
    }
   ]
  },
  {
   "title": "Top 10 Replication Conflicts",
   "type": "timeseries",
   "description": "Tracks conflicts occurring during replication, categorized by type.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "topk(10, rate(pg_stat_database_conflicts{environment=~\"$environment\",cluster=~\"$cluster\",node_name=~\"$node_name\",service_name=~\"$service_name\"}[$__interval])) by (datname)\n",
     "legendFormat": "{{node_name}}/{{datname}}"
    }
   ]
  }
 ]
}