{
 "title": "PostgreSQL Top Queries",
 "tags": [
  "Percona",
  "PostgreSQL",
  "Services"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values({__name__=~\"pg_up\"}, environment)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(pg_up{environment=~\"$environment\"},cluster)"
    }
   },
   {
    "name": "node_name",
    "label": "Node Name",
    "query": {
     "query": "label_values(pg_up{environment=~\"$environment\", cluster=~\"$cluster\"},node_name)"
    }
   },
   {
    "name": "service_name",
    "label": "Service Name",
    "query": {
     "query": "label_values(pg_up{node_name=~\"$node_name\", environment=~\"$environment\", cluster=~\"$cluster\"},service_name)"
    }
   },
   {
    "name": "database",
    "label": "DB",
    "query": {
     "query": "label_values(pg_stat_database_tup_fetched{service_name=~\"$service_name\",datname!~\"template.*|postgres\",node_name=~\"$node_name\",environment=~\"$environment\",cluster=~\"$cluster\"},datname)"
    }
   },
   {
    "name": "work_mem",
    "query": {
     "query": "query_result(pg_settings_work_mem_bytes{service_name=~\"$service_name\",node_name=~\"$node_name\",environment=~\"$environment\",cluster=~\"$cluster\"})"
    }
   },
   {
    "name": "version",
    "query": {
     "query": "label_values(pg_static{service_name=~\"$service_name\",node_name=~\"$node_name\",environment=~\"$environment\",cluster=~\"$cluster\"},version)"
    }
   },
   {
    "name": "max_connections",
    "query": {
     "query": "query_result(pg_settings_max_connections{service_name=~\"$service_name\",node_name=~\"$node_name\",environment=~\"$environment\",cluster=~\"$cluster\"})"
    }
   },
   {
    "name": "shared_buffers",
    "query": {
     "query": "query_result(pg_settings_shared_buffers_bytes{service_name=~\"$service_name\",node_name=~\"$node_name\",environment=~\"$environment\",cluster=~\"$cluster\"})"
    }
   },
   {
    "name": "wal_buffers",
    "query": {
     "query": "query_result(pg_settings_wal_buffers_bytes{service_name=~\"$service_name\",node_name=~\"$node_name\",environment=~\"$environment\",cluster=~\"$cluster\"})"
    }
   },
   {
    "name": "wal_segment_size",
    "query": {
     "query": "query_result(pg_settings_wal_segment_size_bytes{service_name=~\"$service_name\",node_name=~\"$node_name\",environment=~\"$environment\",cluster=~\"$cluster\"})"
    }
   },
   {
    "name": "maintenance_work_mem",
    "query": {
     "query": "query_result(pg_settings_maintenance_work_mem_bytes{service_name=~\"$service_name\",node_name=~\"$node_name\",environment=~\"$environment\",cluster=~\"$cluster\"})"
    }
   },
   {
    "name": "block_size",
    "query": {
     "query": "query_result(pg_settings_block_size{service_name=~\"$service_name\",node_name=~\"$node_name\",environment=~\"$environment\",cluster=~\"$cluster\"})"
    }
   },
   {
    "name": "checkpoint_segments",
    "query": {
     "query": "query_result(pg_settings_checkpoint_segments{service_name=~\"$service_name\",node_name=~\"$node_name\",environment=~\"$environment\",cluster=~\"$cluster\"})"
    }
   },
   {
    "name": "checkpoint_timeout",
    "query": {
     "query": "query_result(pg_settings_checkpoint_timeout_seconds{service_name=~\"$service_name\",node_name=~\"$node_name\",environment=~\"$environment\",cluster=~\"$cluster\"})"
    }
   },
   {
    "name": "default_statistics_target",
    "query": {
     "query": "query_result(pg_settings_default_statistics_target{service_name=~\"$service_name\",node_name=~\"$node_name\",environment=~\"$environment\",cluster=~\"$cluster\"})"
    }
   },
   {
    "name": "seq_page_cost",
    "query": {
     "query": "query_result(pg_settings_seq_page_cost{service_name=~\"$service_name\",node_name=~\"$node_name\",environment=~\"$environment\",cluster=~\"$cluster\"})"
    }
   },
   {
    "name": "random_page_cost",
    "query": {
     "query": "query_result(pg_settings_random_page_cost{service_name=~\"$service_name\",node_name=~\"$node_name\",environment=~\"$environment\",cluster=~\"$cluster\"})"
    }
   },
   {
    "name": "effective_cache_size",
    "query": {
     "query": "query_result(pg_settings_effective_cache_size_bytes{service_name=~\"$service_name\",node_name=~\"$node_name\",environment=~\"$environment\",cluster=~\"$cluster\"})"
    }
   },
   {
    "name": "effective_io_concurrency",
    "query": {
     "query": "query_result(pg_settings_effective_io_concurrency{service_name=~\"$service_name\",node_name=~\"$node_name\",environment=~\"$environment\",cluster=~\"$cluster\"})"
    }
   },
   {
    "name": "fsync",
    "query": {
     "query": "query_result(pg_settings_fsync{service_name=~\"$service_name\",node_name=~\"$node_name\",environment=~\"$environment\",cluster=~\"$cluster\"})"
    }
   },
   {
    "name": "autovacuum",
    "query": {
     "query": "query_result(pg_settings_autovacuum{service_name=~\"$service_name\",node_name=~\"$node_name\",environment=~\"$environment\",cluster=~\"$cluster\"})"
    }
   },
   {
    "name": "autovacuum_analyze_scale_factor",
    "query": {
     "query": "query_result(pg_settings_autovacuum_analyze_scale_factor{service_name=~\"$service_name\",node_name=~\"$node_name\",environment=~\"$environment\",cluster=~\"$cluster\"})"
    }
   },
   {
    "name": "autovacuum_analyze_threshold",
    "query": {
     "query": "query_result(pg_settings_autovacuum_analyze_threshold{service_name=~\"$service_name\",node_name=~\"$node_name\",environment=~\"$environment\",cluster=~\"$cluster\"})"
    }
   },
   {
    "name": "autovacuum_vacuum_scale_factor",
    "query": {
     "query": "query_result(pg_settings_autovacuum_vacuum_scale_factor{service_name=~\"$service_name\",node_name=~\"$node_name\",environment=~\"$environment\",cluster=~\"$cluster\"})"
    }
   },
   {
    "name": "autovacuum_vacuum_threshold",
    "query": {
     "query": "query_result(pg_settings_autovacuum_vacuum_threshold{service_name=~\"$service_name\",node_name=~\"$node_name\",environment=~\"$environment\",cluster=~\"$cluster\"})"
    }
   },
   {
    "name": "autovacuum_vacuum_cost_limit",
    "query": {
     "query": "query_result(pg_settings_autovacuum_vacuum_cost_limit{service_name=~\"$service_name\",node_name=~\"$node_name\",environment=~\"$environment\",cluster=~\"$cluster\"})"
    }
   },
   {
    "name": "autovacuum_vacuum_cost_delay",
    "query": {
     "query": "query_result(pg_settings_autovacuum_vacuum_cost_delay_seconds{service_name=~\"$service_name\",node_name=~\"$node_name\",environment=~\"$environment\",cluster=~\"$cluster\"})"
    }
   },
   {
    "name": "autovacuum_max_workers",
    "query": {
     "query": "query_result(pg_settings_autovacuum_max_workers{service_name=~\"$service_name\",node_name=~\"$node_name\",environment=~\"$environment\",cluster=~\"$cluster\"})"
    }
   },
   {
    "name": "autovacuum_naptime",
    "query": {
     "query": "query_result(pg_settings_autovacuum_naptime_seconds{service_name=~\"$service_name\",node_name=~\"$node_name\",environment=~\"$environment\",cluster=~\"$cluster\"})"
    }
   },
   {
    "name": "autovacuum_freeze_max_age",
    "query": {
     "query": "query_result(pg_settings_autovacuum_freeze_max_age{service_name=~\"$service_name\",node_name=~\"$node_name\",environment=~\"$environment\",cluster=~\"$cluster\"})"
    }
   },
   {
    "name": "logging_collector",
    "query": {
     "query": "query_result(pg_settings_logging_collector{service_name=~\"$service_name\",node_name=~\"$node_name\",environment=~\"$environment\",cluster=~\"$cluster\"})"
    }
   },
   {
    "name": "log_min_duration_statement",
    "query": {
     "query": "query_result(pg_settings_log_min_duration_statement_seconds{service_name=~\"$service_name\",node_name=~\"$node_name\",environment=~\"$environment\",cluster=~\"$cluster\"})"
    }
   },
   {
    "name": "log_duration",
    "query": {
     "query": "query_result(pg_settings_log_duration{service_name=~\"$service_name\",node_name=~\"$node_name\",environment=~\"$environment\",cluster=~\"$cluster\"})"
    }
   },
   {
    "name": "log_lock_waits",
    "query": {
     "query": "query_result(pg_settings_log_lock_waits{service_name=~\"$service_name\",node_name=~\"$node_name\",environment=~\"$environment\",cluster=~\"$cluster\"})"
    }
   },
   {
    "name": "max_wal_senders",
    "query": {
     "query": "query_result(pg_settings_max_wal_senders{service_name=~\"$service_name\",node_name=~\"$node_name\",environment=~\"$environment\",cluster=~\"$cluster\"})"
    }
   },
   {
    "name": "max_wal_size",
    "query": {
     "query": "query_result(pg_settings_max_wal_size_bytes{service_name=~\"$service_name\",node_name=~\"$node_name\",environment=~\"$environment\",cluster=~\"$cluster\"})"
    }
   },
   {
    "name": "min_wal_size",
    "query": {
     "query": "query_result(pg_settings_min_wal_size_bytes{service_name=~\"$service_name\",node_name=~\"$node_name\",environment=~\"$environment\",cluster=~\"$cluster\"})"
    }
   },
   {
    "name": "wal_compression",
    "query": {
     "query": "query_result(pg_settings_wal_compression{service_name=~\"$service_name\",node_name=~\"$node_name\",environment=~\"$environment\",cluster=~\"$cluster\"})"
    }
   },
   {
    "name": "max_worker_processes",
    "query": {
     "query": "query_result(pg_settings_max_worker_processes{service_name=~\"$service_name\",node_name=~\"$node_name\",environment=~\"$environment\",cluster=~\"$cluster\"})"
    }
   },
   {
    "name": "max_parallel_workers_per_gather",
    "query": {
     "query": "query_result(pg_settings_max_parallel_workers_per_gather{service_name=~\"$service_name\",node_name=~\"$node_name\",environment=~\"$environment\",cluster=~\"$cluster\"})"
    }
   },
   {
    "name": "max_parallel_workers",
    "query": {
     "query": "query_result(pg_settings_max_parallel_workers_per_gather{service_name=~\"$service_name\",node_name=~\"$node_name\",environment=~\"$environment\",cluster=~\"$cluster\"})"
    }
   },
   {
    "name": "autovacuum_work_mem",
    "query": {
     "query": "query_result(pg_settings_autovacuum_work_mem_bytes{service_name=~\"$service_name\",node_name=~\"$node_name\",environment=~\"$environment\",cluster=~\"$cluster\"})"
    }
   },
   {
    "name": "autovacuum_multixact_freeze_max_age",
    "query": {
     "query": "query_result(pg_settings_autovacuum_multixact_freeze_max_age{service_name=~\"$service_name\",node_name=~\"$node_name\",environment=~\"$environment\",cluster=~\"$cluster\"})"
    }
   },
   {
    "name": "replication_set",
    "label": "Replication Set",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, replication_set)"
    }
   },
   {
    "name": "node_type",
    "label": "Type",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, node_type)"
    }
   },
   {
    "name": "service_type",
    "label": "Type",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, service_type)"
    }
   },
   {
    "name": "username",
    "label": "Username",
    "query": {
     "query": "label_values(mysql_info_schema_user_statistics_connected_time_seconds_total{service_name=\"$service_name\",node_name=~\"$node_name\",environment=~\"$environment\",cluster=~\"$cluster\"},user)"
    }
   },
   {
    "name": "schema",
    "label": "Schema",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, schema)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Transactions per Seconds",
   "type": "timeseries",
   "description": "Commit rate per second (pg_stat_database). A drop may indicate connection saturation, long-running transactions, or deadlocks — check pg_stat_activity for blocking sessions.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "(sum by (service_name) (rate(pg_stat_database_xact_commit{service_type=~\"$service_type\",node_name=~\"$node_name\",service_name=~\"$service_name\",environment=~\"$environment\",cluster=~\"$cluster\"}[$interval])) or \nsum by (service_name) (irate(pg_stat_database_xact_commit{service_type=~\"$service_type\",node_name=~\"$node_name\",service_name=~\"$service_name\",environment=~\"$environment\",cluster=~\"$cluster\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 10 Slowest Query",
   "type": "table",
   "description": "Highest average execution time per call — expensive on every run. Use QAN EXPLAIN to find sequential scans, missing indexes, or inefficient join strategies.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT   \n    service_name as \"Service Name\",\n    database as Database,\n    fingerprint AS \"Query\", \n    sum(m_query_time_sum) / nullIf(sum(m_query_time_cnt), 0) AS \"Avg Execution Time\"\nFROM pmm.\"metrics\"\nWHERE \n    period_start >= $__fromTime \n    AND period_start <= $__toTime \n    AND $__conditionalAll(service_name IN (${service_name:singlequote}), $service_name) AND $__conditionalAll(environment IN (${environment:singlequote}), $environment) AND $__conditionalAll(cluster IN (${cluster:singlequote}), $cluster) AND $__conditionalAll(node_name IN (${node_name:singlequote}), $node_name)\n    AND service_type = 'postgresql'\n    AND database NOT IN ('postgres', '<database name not available>', 'template1')\n    AND fingerprint NOT IN ('SELECT version()')\n    AND fingerprint NOT ILIKE '%pg_stat_%'\n    AND fingerprint NOT ILIKE '%pg_replication_slots%'\n    AND fingerprint NOT ILIKE '%pg_publication%'\n    AND fingerprint NOT ILIKE '%pg_last_wal_receive_lsn%'\nGROUP BY \n    service_name, \n    database, \n    fingerprint\nHAVING sum(m_query_time_cnt) > 0\nORDER BY \"Avg Execution Time\" DESC\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "Top 10 time spent",
   "type": "table",
   "description": "Most cumulative execution time overall. A fast query called thousands of times can dominate here — start here when diagnosing CPU saturation or poor throughput.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT   \n    service_name as \"Service Name\",\n    database as Database,\n    fingerprint AS \"Query\", \n    sum(m_query_time_sum) AS \"Execution Time Summary\"\nFROM pmm.\"metrics\"\nWHERE \n    period_start >= $__fromTime \n    AND period_start <= $__toTime \n    AND $__conditionalAll(service_name IN (${service_name:singlequote}), $service_name) AND $__conditionalAll(environment IN (${environment:singlequote}), $environment) AND $__conditionalAll(cluster IN (${cluster:singlequote}), $cluster) AND $__conditionalAll(node_name IN (${node_name:singlequote}), $node_name)\n    AND service_type = 'postgresql'\n    AND database NOT IN ('postgres', '<database name not available>', 'template1')\n    AND fingerprint NOT IN ('SELECT version()')\n    AND fingerprint NOT ILIKE '%pg_stat_%'\n    AND fingerprint NOT ILIKE '%pg_replication_slots%'\n    AND fingerprint NOT ILIKE '%pg_publication%'\n    AND fingerprint NOT ILIKE '%pg_last_wal_receive_lsn%'\nGROUP BY \n    service_name,  \n    database, \n    fingerprint \nORDER BY \"Execution Time Summary\" DESC\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "Top 10 Queries Executed the most",
   "type": "table",
   "description": "Most frequently called queries. Small savings here multiply into large gains — check for N+1 patterns or result caching opportunities.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "rawSql": "SELECT   \n    service_name as \"Service Name\",\n    database as Database,\n    fingerprint AS \"Query\", \n    sum(num_queries) AS \"Executed\"\nFROM pmm.\"metrics\"\nWHERE \n    period_start >= $__fromTime \n    AND period_start <= $__toTime \n    AND $__conditionalAll(service_name IN (${service_name:singlequote}), $service_name) AND $__conditionalAll(environment IN (${environment:singlequote}), $environment) AND $__conditionalAll(cluster IN (${cluster:singlequote}), $cluster) AND $__conditionalAll(node_name IN (${node_name:singlequote}), $node_name)\n    AND service_type = 'postgresql'\n    AND database NOT IN ('postgres', '<database name not available>', 'template1')\n    AND fingerprint NOT IN ('SELECT version()')\n    AND fingerprint NOT ILIKE '%pg_stat_%'\n    AND fingerprint NOT ILIKE '%pg_replication_slots%'\n    AND fingerprint NOT ILIKE '%pg_publication%'\n    AND fingerprint NOT ILIKE '%pg_last_wal_receive_lsn%'\nGROUP BY \n    service_name, \n    database, \n    fingerprint\nORDER BY \"Executed\" DESC\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "Top 10 Queries writing the most",
   "type": "table",
   "description": "INSERT/UPDATE/DELETE with the highest total rows affected. Heavy DML drives autovacuum pressure, WAL generation, and replication lag — consider batching or rate-limiting bulk operations.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "rawSql": "SELECT   \n    service_name as \"Service Name\",\n    database as Database,\n    fingerprint AS \"Query\", \n    sum(m_rows_sent_sum) AS \"Affected Rows\"\nFROM pmm.\"metrics\"\nWHERE \n    period_start >= $__fromTime \n    AND period_start <= $__toTime \n    AND $__conditionalAll(service_name IN (${service_name:singlequote}), $service_name) AND $__conditionalAll(environment IN (${environment:singlequote}), $environment) AND $__conditionalAll(cluster IN (${cluster:singlequote}), $cluster) AND $__conditionalAll(node_name IN (${node_name:singlequote}), $node_name)\n    AND service_type = 'postgresql'\n    AND database NOT IN ('postgres', '<database name not available>', 'template1')\n    AND fingerprint NOT IN ('SELECT version()')\n    AND fingerprint NOT ILIKE '%pg_stat_%'\n    AND fingerprint NOT ILIKE '%pg_replication_slots%'\n    AND fingerprint NOT ILIKE '%pg_publication%'\n    AND fingerprint NOT ILIKE '%pg_last_wal_receive_lsn%'\n    AND cmd_type not in ('SELECT','')\nGROUP BY \n    service_name, \n    database, \n    fingerprint\nORDER BY \"Affected Rows\" DESC\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "Top 10 Queries Affected the most rows",
   "type": "table",
   "description": "Total rows returned or affected across all query types, including SELECTs. Large result sets waste memory and bandwidth — check for missing pagination or absent WHERE clauses.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "rawSql": "SELECT   \n    service_name as \"Service Name\",\n    database as Database,\n    fingerprint AS \"Query\", \n    sum(m_rows_sent_sum) AS \"Rows Affected\"\nFROM pmm.\"metrics\"\nWHERE \n    period_start >= $__fromTime \n    AND period_start <= $__toTime \n    AND $__conditionalAll(service_name IN (${service_name:singlequote}), $service_name) AND $__conditionalAll(environment IN (${environment:singlequote}), $environment) AND $__conditionalAll(cluster IN (${cluster:singlequote}), $cluster) AND $__conditionalAll(node_name IN (${node_name:singlequote}), $node_name)\n    AND service_type = 'postgresql'\n    AND database NOT IN ('postgres', '<database name not available>', 'template1')\n    AND fingerprint NOT IN ('SELECT version()')\n    AND fingerprint NOT ILIKE '%pg_stat_%'\n    AND fingerprint NOT ILIKE '%pg_replication_slots%'\n    AND fingerprint NOT ILIKE '%pg_publication%'\n    AND fingerprint NOT ILIKE '%pg_last_wal_receive_lsn%'\nGROUP BY \n    service_name, \n    database, \n    fingerprint\nORDER BY \"Rows Affected\" DESC\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "Top 10 User Executed the most queries",
   "type": "table",
   "description": "Database users by query volume. A single account dominating traffic may indicate a misconfigured connection pool or a runaway batch job — consider workload isolation via a connection pooler.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {
     "rawSql": "SELECT   \n    service_name as \"Service Name\",\n    database as Database,\n    username as Username,\n    sum(num_queries) AS \"Executed Queries\"\nFROM pmm.\"metrics\"\nWHERE \n    period_start >= $__fromTime \n    AND period_start <= $__toTime \n    AND $__conditionalAll(service_name IN (${service_name:singlequote}), $service_name) AND $__conditionalAll(environment IN (${environment:singlequote}), $environment) AND $__conditionalAll(cluster IN (${cluster:singlequote}), $cluster) AND $__conditionalAll(node_name IN (${node_name:singlequote}), $node_name)\n    AND service_type = 'postgresql'\n    AND database NOT IN ('postgres', '<database name not available>', 'template1')\n    AND fingerprint NOT IN ('SELECT version()')\n    AND fingerprint NOT ILIKE '%pg_stat_%'\n    AND fingerprint NOT ILIKE '%pg_replication_slots%'\n    AND fingerprint NOT ILIKE '%pg_publication%'\n    AND fingerprint NOT ILIKE '%pg_last_wal_receive_lsn%'\nGROUP BY \n    service_name, \n    database,\n    username\nORDER BY \"Executed Queries\" DESC\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "Top 10 CPU Intensive Queries",
   "type": "table",
   "description": "Most total CPU time consumed (user + system). High values point to full-table scans, complex aggregations, or missing indexes — use QAN EXPLAIN to verify. Requires pg_stat_monitor; empty with standard pg_stat_statements.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 63 },
   "targets": [
    {
     "rawSql": "SELECT   \n    service_name as \"Service Name\",\n    database as Database,\n    fingerprint AS \"Query\", \n    sum(m_cpu_user_time_sum + m_cpu_sys_time_sum) AS \"Total CPU Time (s)\",\n    sum(m_cpu_user_time_sum + m_cpu_sys_time_sum) / nullIf(sum(num_queries), 0) AS \"Avg CPU / Query (s)\"\nFROM pmm.\"metrics\"\nWHERE \n    period_start >= $__fromTime \n    AND period_start <= $__toTime \n    AND $__conditionalAll(service_name IN (${service_name:singlequote}), $service_name) AND $__conditionalAll(environment IN (${environment:singlequote}), $environment) AND $__conditionalAll(cluster IN (${cluster:singlequote}), $cluster) AND $__conditionalAll(node_name IN (${node_name:singlequote}), $node_name)\n    AND service_type = 'postgresql'\n    AND database NOT IN ('postgres', '<database name not available>', 'template1')\n    AND fingerprint NOT IN ('SELECT version()')\n    AND fingerprint NOT ILIKE '%pg_stat_%'\n    AND fingerprint NOT ILIKE '%pg_replication_slots%'\n    AND fingerprint NOT ILIKE '%pg_publication%'\n    AND fingerprint NOT ILIKE '%pg_last_wal_receive_lsn%'\n    AND (m_cpu_user_time_sum > 0 OR m_cpu_sys_time_sum > 0)\nGROUP BY \n    service_name, \n    database, \n    fingerprint\nORDER BY \"Total CPU Time (s)\" DESC\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "Top 10 Memory Intensive Queries",
   "type": "table",
   "description": "Queries spilling sort/hash work to disk (temp blocks, 8 KB each). Disk spills are ~100x slower than memory — increase work_mem, add indexes to avoid large sorts, or reduce intermediate result sizes. Available with pg_stat_statements or pg_stat_monitor.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 71 },
   "targets": [
    {
     "rawSql": "SELECT   \n    service_name as \"Service Name\",\n    database as Database,\n    fingerprint AS \"Query\", \n    sum(m_temp_blks_written_sum + m_temp_blks_read_sum) AS \"Temp Blocks\",\n    sum(m_shared_blks_read_sum) AS \"Shared Blocks Read\",\n    sum(num_queries) AS \"Executions\"\nFROM pmm.\"metrics\"\nWHERE \n    period_start >= $__fromTime \n    AND period_start <= $__toTime \n    AND $__conditionalAll(service_name IN (${service_name:singlequote}), $service_name) AND $__conditionalAll(environment IN (${environment:singlequote}), $environment) AND $__conditionalAll(cluster IN (${cluster:singlequote}), $cluster) AND $__conditionalAll(node_name IN (${node_name:singlequote}), $node_name)\n    AND service_type = 'postgresql'\n    AND database NOT IN ('postgres', '<database name not available>', 'template1')\n    AND fingerprint NOT IN ('SELECT version()')\n    AND fingerprint NOT ILIKE '%pg_stat_%'\n    AND fingerprint NOT ILIKE '%pg_replication_slots%'\n    AND fingerprint NOT ILIKE '%pg_publication%'\n    AND fingerprint NOT ILIKE '%pg_last_wal_receive_lsn%'\n    AND (m_temp_blks_written_sum > 0 OR m_temp_blks_read_sum > 0)\nGROUP BY \n    service_name, \n    database, \n    fingerprint\nORDER BY \"Temp Blocks\" DESC\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "Top 10 Queries by I/O Wait",
   "type": "table",
   "description": "Most time waiting on block I/O (ms). High read wait signals sequential scans — add indexes. High write wait may need checkpoint tuning. I/O-bound queries hold locks longer, increasing contention. Available with pg_stat_statements or pg_stat_monitor. Requires track_io_timing = on in postgresql.conf.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 79 },
   "targets": [
    {
     "rawSql": "SELECT   \n    service_name as \"Service Name\",\n    database as Database,\n    fingerprint AS \"Query\", \n    sum(m_shared_blk_read_time_sum + m_shared_blk_write_time_sum) AS \"Total I/O Wait (ms)\",\n    sum(m_shared_blk_read_time_sum + m_shared_blk_write_time_sum) / nullIf(sum(num_queries), 0) AS \"Avg I/O Wait / Query (ms)\",\n    sum(num_queries) AS \"Executions\"\nFROM pmm.\"metrics\"\nWHERE \n    period_start >= $__fromTime \n    AND period_start <= $__toTime \n    AND $__conditionalAll(service_name IN (${service_name:singlequote}), $service_name) AND $__conditionalAll(environment IN (${environment:singlequote}), $environment) AND $__conditionalAll(cluster IN (${cluster:singlequote}), $cluster) AND $__conditionalAll(node_name IN (${node_name:singlequote}), $node_name)\n    AND service_type = 'postgresql'\n    AND database NOT IN ('postgres', '<database name not available>', 'template1')\n    AND fingerprint NOT IN ('SELECT version()')\n    AND fingerprint NOT ILIKE '%pg_stat_%'\n    AND fingerprint NOT ILIKE '%pg_replication_slots%'\n    AND fingerprint NOT ILIKE '%pg_publication%'\n    AND fingerprint NOT ILIKE '%pg_last_wal_receive_lsn%'\nGROUP BY \n    service_name, \n    database, \n    fingerprint\nORDER BY \"Total I/O Wait (ms)\" DESC\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "Top 10 Queries by Shared Block Reads (Sequential Scan Indicator)",
   "type": "table",
   "description": "SELECT queries reading the most shared blocks per execution on average. A high ratio signals a likely sequential scan — use QAN EXPLAIN to confirm, then index the most selective filter columns. Available with pg_stat_statements or pg_stat_monitor.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 87 },
   "targets": [
    {
     "rawSql": "SELECT   \n    service_name as \"Service Name\",\n    database as Database,\n    fingerprint AS \"Query\", \n    sum(m_shared_blks_read_sum) AS \"Total Shared Blocks Read\",\n    CASE WHEN sum(num_queries) > 0 THEN sum(m_shared_blks_read_sum) / sum(num_queries) ELSE 0 END AS \"Avg Blocks / Query\",\n    sum(num_queries) AS \"Executions\"\nFROM pmm.\"metrics\"\nWHERE \n    period_start >= $__fromTime \n    AND period_start <= $__toTime \n    AND $__conditionalAll(service_name IN (${service_name:singlequote}), $service_name) AND $__conditionalAll(environment IN (${environment:singlequote}), $environment) AND $__conditionalAll(cluster IN (${cluster:singlequote}), $cluster) AND $__conditionalAll(node_name IN (${node_name:singlequote}), $node_name)\n    AND service_type = 'postgresql'\n    AND database NOT IN ('postgres', '<database name not available>', 'template1')\n    AND fingerprint NOT IN ('SELECT version()')\n    AND fingerprint NOT ILIKE '%pg_stat_%'\n    AND fingerprint NOT ILIKE '%pg_replication_slots%'\n    AND fingerprint NOT ILIKE '%pg_publication%'\n    AND fingerprint NOT ILIKE '%pg_last_wal_receive_lsn%'\n    AND cmd_type = 'SELECT'\n    AND m_shared_blks_read_sum > 0\nGROUP BY \n    service_name, \n    database, \n    fingerprint\nORDER BY \"Avg Blocks / Query\" DESC\nLIMIT 10;"
    }
   ]
  }
 ]
}