{
 "title": "PostgreSQL Instances Compare",
 "tags": [
  "Percona",
  "PostgreSQL_Compare"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "work_mem",
    "query": {
     "query": "query_result(pg_settings_work_mem_bytes{service_name=~\"$service_name\",node_name=~\"$node_name\"})"
    }
   },
   { "name": "node_name", "label": "Node Name", "query": { "query": "label_values(pg_up,node_name)" } },
   {
    "name": "service_name",
    "label": "Service Name",
    "query": {
     "query": "label_values(pg_up{node_name=~\"$node_name\"}, service_name)"
    }
   },
   {
    "name": "max_connections",
    "query": {
     "query": "query_result(pg_settings_max_connections{service_name=~\"$service_name\",node_name=~\"$node_name\"})"
    }
   },
   {
    "name": "shared_buffers",
    "query": {
     "query": "query_result(pg_settings_shared_buffers_bytes{service_name=~\"$service_name\",node_name=~\"$node_name\"})"
    }
   },
   {
    "name": "wal_buffers",
    "query": {
     "query": "query_result(pg_settings_wal_buffers_bytes{service_name=~\"$service_name\",node_name=~\"$node_name\"})"
    }
   },
   {
    "name": "wal_segment_size",
    "query": {
     "query": "query_result(pg_settings_wal_segment_size_bytes{service_name=~\"$service_name\",node_name=~\"$node_name\"})"
    }
   },
   {
    "name": "maintenance_work_mem",
    "query": {
     "query": "query_result(pg_settings_maintenance_work_mem_bytes{service_name=~\"$service_name\",node_name=~\"$node_name\"})"
    }
   },
   {
    "name": "block_size",
    "query": {
     "query": "query_result(pg_settings_block_size{service_name=~\"$service_name\",node_name=~\"$node_name\"})"
    }
   },
   {
    "name": "checkpoint_segments",
    "query": {
     "query": "query_result(pg_settings_checkpoint_segments{service_name=~\"$service_name\",node_name=~\"$node_name\"})"
    }
   },
   {
    "name": "checkpoint_timeout",
    "query": {
     "query": "query_result(pg_settings_checkpoint_timeout_seconds{service_name=~\"$service_name\",node_name=~\"$node_name\"})"
    }
   },
   {
    "name": "default_statistics_target",
    "query": {
     "query": "query_result(pg_settings_default_statistics_target{service_name=~\"$service_name\",node_name=~\"$node_name\"})"
    }
   },
   {
    "name": "seq_page_cost",
    "query": {
     "query": "query_result(pg_settings_seq_page_cost{service_name=~\"$service_name\",node_name=~\"$node_name\"})"
    }
   },
   {
    "name": "random_page_cost",
    "query": {
     "query": "query_result(pg_settings_random_page_cost{service_name=~\"$service_name\",node_name=~\"$node_name\"})"
    }
   },
   {
    "name": "effective_cache_size",
    "query": {
     "query": "query_result(pg_settings_effective_cache_size_bytes{service_name=~\"$service_name\",node_name=~\"$node_name\"})"
    }
   },
   {
    "name": "effective_io_concurrency",
    "query": {
     "query": "query_result(pg_settings_effective_io_concurrency{service_name=~\"$service_name\",node_name=~\"$node_name\"})"
    }
   },
   {
    "name": "fsync",
    "query": {
     "query": "query_result(pg_settings_fsync{service_name=~\"$service_name\",node_name=~\"$node_name\"})"
    }
   },
   {
    "name": "autovacuum",
    "query": {
     "query": "query_result(pg_settings_autovacuum{service_name=~\"$service_name\",node_name=~\"$node_name\"})"
    }
   },
   {
    "name": "autovacuum_analyze_scale_factor",
    "query": {
     "query": "query_result(pg_settings_autovacuum_analyze_scale_factor{service_name=~\"$service_name\",node_name=~\"$node_name\"})"
    }
   },
   {
    "name": "autovacuum_analyze_threshold",
    "query": {
     "query": "query_result(pg_settings_autovacuum_analyze_threshold{service_name=~\"$service_name\",node_name=~\"$node_name\"})"
    }
   },
   {
    "name": "autovacuum_vacuum_scale_factor",
    "query": {
     "query": "query_result(pg_settings_autovacuum_vacuum_scale_factor{service_name=~\"$service_name\",node_name=~\"$node_name\"})"
    }
   },
   {
    "name": "autovacuum_vacuum_threshold",
    "query": {
     "query": "query_result(pg_settings_autovacuum_vacuum_threshold{service_name=~\"$service_name\",node_name=~\"$node_name\"})"
    }
   },
   {
    "name": "autovacuum_vacuum_cost_limit",
    "query": {
     "query": "query_result(pg_settings_autovacuum_vacuum_cost_limit{service_name=~\"$service_name\",node_name=~\"$node_name\"})"
    }
   },
   {
    "name": "autovacuum_vacuum_cost_delay",
    "query": {
     "query": "query_result(pg_settings_autovacuum_vacuum_cost_delay_seconds{service_name=~\"$service_name\",node_name=~\"$node_name\"})"
    }
   },
   {
    "name": "autovacuum_max_workers",
    "query": {
     "query": "query_result(pg_settings_autovacuum_max_workers{service_name=~\"$service_name\",node_name=~\"$node_name\"})"
    }
   },
   {
    "name": "autovacuum_naptime",
    "query": {
     "query": "query_result(pg_settings_autovacuum_naptime_seconds{service_name=~\"$service_name\",node_name=~\"$node_name\"})"
    }
   },
   {
    "name": "autovacuum_freeze_max_age",
    "query": {
     "query": "query_result(pg_settings_autovacuum_freeze_max_age{service_name=~\"$service_name\",node_name=~\"$node_name\"})"
    }
   },
   {
    "name": "logging_collector",
    "query": {
     "query": "query_result(pg_settings_logging_collector{service_name=~\"$service_name\",node_name=~\"$node_name\"})"
    }
   },
   {
    "name": "log_min_duration_statement",
    "query": {
     "query": "query_result(pg_settings_log_min_duration_statement_seconds{service_name=~\"$service_name\",node_name=~\"$node_name\"})"
    }
   },
   {
    "name": "log_duration",
    "query": {
     "query": "query_result(pg_settings_log_duration{service_name=~\"$service_name\",node_name=~\"$node_name\"})"
    }
   },
   {
    "name": "log_lock_waits",
    "query": {
     "query": "query_result(pg_settings_log_lock_waits{service_name=~\"$service_name\",node_name=~\"$node_name\"})"
    }
   },
   {
    "name": "max_wal_senders",
    "query": {
     "query": "query_result(pg_settings_max_wal_senders{service_name=~\"$service_name\",node_name=~\"$node_name\"})"
    }
   },
   {
    "name": "max_wal_size",
    "query": {
     "query": "query_result(pg_settings_max_wal_size_bytes{service_name=~\"$service_name\",node_name=~\"$node_name\"})"
    }
   },
   {
    "name": "min_wal_size",
    "query": {
     "query": "query_result(pg_settings_min_wal_size_bytes{service_name=~\"$service_name\",node_name=~\"$node_name\"})"
    }
   },
   {
    "name": "wal_compression",
    "query": {
     "query": "query_result(pg_settings_wal_compression{service_name=~\"$service_name\",node_name=~\"$node_name\"})"
    }
   },
   {
    "name": "max_worker_processes",
    "query": {
     "query": "query_result(pg_settings_max_worker_processes{service_name=~\"$service_name\",node_name=~\"$node_name\"})"
    }
   },
   {
    "name": "max_parallel_workers_per_gather",
    "query": {
     "query": "query_result(pg_settings_max_parallel_workers_per_gather{service_name=~\"$service_name\",node_name=~\"$node_name\"})"
    }
   },
   {
    "name": "max_parallel_workers",
    "query": {
     "query": "query_result(pg_settings_max_parallel_workers_per_gather{service_name=~\"$service_name\",node_name=~\"$node_name\"})"
    }
   },
   {
    "name": "autovacuum_work_mem",
    "query": {
     "query": "query_result(pg_settings_autovacuum_work_mem_bytes{service_name=~\"$service_name\",node_name=~\"$node_name\"})"
    }
   },
   {
    "name": "autovacuum_multixact_freeze_max_age",
    "query": {
     "query": "query_result(pg_settings_autovacuum_multixact_freeze_max_age{service_name=~\"$service_name\",node_name=~\"$node_name\"})"
    }
   },
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, environment)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, cluster)"
    }
   },
   {
    "name": "replication_set",
    "label": "Replication Set",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, replication_set)"
    }
   },
   {
    "name": "database",
    "label": "Database",
    "query": {
     "query": "label_values(pg_stat_database_tup_fetched{service_name=~\"$service_name\",datname!~\"template.*\",node_name=~\"$node_name\"},datname)"
    }
   },
   {
    "name": "node_type",
    "label": "Type",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, node_type)"
    }
   },
   {
    "name": "service_type",
    "label": "Type",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, service_type)"
    }
   },
   {
    "name": "username",
    "label": "Username",
    "query": {
     "query": "label_values(mysql_info_schema_user_statistics_connected_time_seconds_total{service_name=\"$service_name\",node_name=~\"$node_name\"},user)"
    }
   },
   {
    "name": "schema",
    "label": "Schema",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, schema)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$service_name - Service Info",
   "type": "table-old",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "repeat": "service_name",
   "targets": [
    {
     "expr": "pg_static{service_name=~\"$service_name\",node_name=~\"$node_name\"}"
    }
   ]
  },
  {
   "title": "$service_name - Shared Buffers",
   "type": "stat",
   "description": "Defines the amount of memory the database server uses for shared memory buffers.  Default is 128MB.  Guidance on tuning is 25% of RAM, but generally doesn't exceed 40%.",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 5 },
   "repeat": "service_name",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (service_name) (max_over_time(pg_settings_shared_buffers_bytes{service_name=~\"$service_name\",node_name=~\"$node_name\"}[$interval]) or max_over_time(pg_settings_shared_buffers_bytes{service_name=~\"$service_name\",node_name=~\"$node_name\"}[5m]))"
    }
   ]
  },
  {
   "title": "$service_name - Disk-Page Buffers",
   "type": "stat",
   "description": "The setting wal_buffers defines how much memory is used for caching the write-ahead log entries. Generally this value is small (3% of shared_buffers value), but it may need to be modified for heavily loaded servers.",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 8 },
   "repeat": "service_name",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (service_name) (max_over_time(pg_settings_wal_buffers_bytes{service_name=~\"$service_name\",node_name=~\"$node_name\"}[$interval]) or max_over_time(pg_settings_wal_buffers_bytes{service_name=~\"$service_name\",node_name=~\"$node_name\"}[5m]))"
    }
   ]
  },
  {
   "title": "$service_name - Memory Size for each Sort",
   "type": "stat",
   "description": "The parameter work_mem defines the amount of memory assigned for internal sort operations and hash tables before writing to temporary disk files.  The default is 4MB.",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 11 },
   "repeat": "service_name",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (service_name) (max_over_time(pg_settings_work_mem_bytes{service_name=~\"$service_name\",node_name=~\"$node_name\"}[$interval]) or\nmax_over_time(pg_settings_work_mem_bytes{service_name=~\"$service_name\",node_name=~\"$node_name\"}[5m]))"
    }
   ]
  },
  {
   "title": "$service_name - Disk Cache Size",
   "type": "stat",
   "description": "PostgreSQL's effective_cache_size variable tunes how much RAM you expect to be available for disk caching.  Generally adding Linux free+cached will give you a good idea.  This value is used by the query planner whether plans will fit in memory, and when defined too low, can lead to some plans rejecting certain indexes.",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 14 },
   "repeat": "service_name",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (service_name) (max_over_time(pg_settings_effective_cache_size_bytes{service_name=~\"$service_name\",node_name=~\"$node_name\"}[$interval]) or\nmax_over_time(pg_settings_effective_cache_size_bytes{service_name=~\"$service_name\",node_name=~\"$node_name\"}[5m]))"
    }
   ]
  },
  {
   "title": "$service_name - Autovacuum",
   "type": "stat",
   "description": "Whether autovacuum process is enabled or not.  Generally the solution is to vacuum more often, not less.",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 17 },
   "repeat": "service_name",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (service_name) (max_over_time(pg_settings_autovacuum{service_name=~\"$service_name\",node_name=~\"$node_name\"}[$interval]) or max_over_time(pg_settings_autovacuum{service_name=~\"$service_name\",node_name=~\"$node_name\"}[5m]))"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "$service_name - PostgreSQL Connections",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
     "repeat": "service_name",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(max_over_time(pg_stat_activity_count{service_name=~\"$service_name\",datname=~\"$database\",node_name=~\"$node_name\"}[$interval]) or\nmax_over_time(pg_stat_activity_count{service_name=~\"$service_name\",datname=~\"$database\",node_name=~\"$node_name\"}[5m])) by (service_name,state)",
       "legendFormat": "{{state}}"
      },
      {
       "expr": "sum by (service_name) (max_over_time(pg_stat_activity_count{service_name=~\"$service_name\",datname=~\"$database\",node_name=~\"$node_name\"}[$interval]) or\nmax_over_time(pg_stat_activity_count{service_name=~\"$service_name\",datname=~\"$database\",node_name=~\"$node_name\"}[5m]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "$service_name - Active Connections",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
     "repeat": "service_name",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg by (service_name,datname) (max_over_time(pg_stat_activity_count{service_name=~\"$service_name\",state='active',datname=~\"$database\",node_name=~\"$node_name\"}[$interval]) or\nmax_over_time(pg_stat_activity_count{service_name=~\"$service_name\",state='active',datname=~\"$database\",node_name=~\"$node_name\"}[5m]))",
       "legendFormat": "{{datname}}"
      },
      {
       "expr": "avg by (service_name) (max_over_time(pg_settings_max_connections{service_name=~\"$service_name\",datname=~\"$database\",node_name=~\"$node_name\"}[$interval]) or \nmax_over_time(pg_settings_max_connections{service_name=~\"$service_name\",datname=~\"$database\",node_name=~\"$node_name\"}[5m]))",
       "legendFormat": "Maximum connections"
      }
     ]
    }
   ]
  },
  {
   "title": "Tuples",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "$service_name - Tuples",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
     "repeat": "service_name",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (service_name) (rate(pg_stat_database_tup_fetched{service_name=~\"$service_name\",datname=~\"$database\",node_name=~\"$node_name\"}[$interval])) or \nsum by (service_name) (irate(pg_stat_database_tup_fetched{service_name=~\"$service_name\",datname=~\"$database\",node_name=~\"$node_name\"}[5m]))",
       "legendFormat": "Fetched"
      },
      {
       "expr": "sum by (service_name) (rate(pg_stat_database_tup_returned{service_name=~\"$service_name\",datname=~\"$database\",node_name=~\"$node_name\"}[$interval])) or\nsum by (service_name) (irate(pg_stat_database_tup_returned{service_name=~\"$service_name\",datname=~\"$database\",node_name=~\"$node_name\"}[5m]))",
       "legendFormat": "Returned"
      },
      {
       "expr": "sum by (service_name) (rate(pg_stat_database_tup_inserted{service_name=~\"$service_name\",datname=~\"$database\",node_name=~\"$node_name\"}[$interval])) or\nsum by (service_name) (irate(pg_stat_database_tup_inserted{service_name=~\"$service_name\",datname=~\"$database\",node_name=~\"$node_name\"}[5m]))",
       "legendFormat": "Inserted"
      },
      {
       "expr": "sum by (service_name) (rate(pg_stat_database_tup_updated{service_name=~\"$service_name\",datname=~\"$database\",node_name=~\"$node_name\"}[$interval])) or\nsum by (service_name) (irate(pg_stat_database_tup_updated{service_name=~\"$service_name\",datname=~\"$database\",node_name=~\"$node_name\"}[5m]))",
       "legendFormat": "Updated"
      },
      {
       "expr": "sum by (service_name) (rate(pg_stat_database_tup_deleted{service_name=~\"$service_name\",datname=~\"$database\",node_name=~\"$node_name\"}[$interval])) or\nsum by (service_name) (irate(pg_stat_database_tup_deleted{service_name=~\"$service_name\",datname=~\"$database\",node_name=~\"$node_name\"}[5m]))",
       "legendFormat": "Deleted"
      }
     ]
    },
    {
     "title": "$service_name - Read Tuple Activity",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
     "repeat": "service_name",
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum by (service_name) (rate(pg_stat_database_tup_returned{service_name=~\"$service_name\",datname=~\"$database\",node_name=~\"$node_name\"}[$interval])) or\nsum by (service_name) (irate(pg_stat_database_tup_returned{service_name=~\"$service_name\",datname=~\"$database\",node_name=~\"$node_name\"}[5m]))",
       "legendFormat": "Rows returned by queries"
      },
      {
       "expr": "sum by (service_name) (rate(pg_stat_database_tup_fetched{service_name=~\"$service_name\",datname=~\"$database\",node_name=~\"$node_name\"}[$interval])) or\nsum by (service_name) (irate(pg_stat_database_tup_fetched{service_name=~\"$service_name\",datname=~\"$database\",node_name=~\"$node_name\"}[5m]))",
       "legendFormat": "Rows fetched by queries"
      }
     ]
    },
    {
     "title": "$service_name - Tuples Changes by Queries",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
     "repeat": "service_name",
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum by (service_name) (rate(pg_stat_database_tup_inserted{service_name=~\"$service_name\",datname=~\"$database\",node_name=~\"$node_name\"}[$interval])) or\nsum by (service_name) (irate(pg_stat_database_tup_inserted{service_name=~\"$service_name\",datname=~\"$database\",node_name=~\"$node_name\"}[5m]))",
       "legendFormat": "Rows inserted by queries"
      },
      {
       "expr": "sum by (service_name) (rate(pg_stat_database_tup_updated{service_name=~\"$service_name\",datname=~\"$database\",node_name=~\"$node_name\"}[$interval])) or\nsum by (service_name) (irate(pg_stat_database_tup_updated{service_name=~\"$service_name\",datname=~\"$database\",node_name=~\"$node_name\"}[5m]))",
       "legendFormat": "Rows updated by queries"
      },
      {
       "expr": "sum by (service_name) (rate(pg_stat_database_tup_deleted{service_name=~\"$service_name\",datname=~\"$database\",node_name=~\"$node_name\"}[$interval])) or\nsum by (service_name) (irate(pg_stat_database_tup_deleted{service_name=~\"$service_name\",datname=~\"$database\",node_name=~\"$node_name\"}[5m]))",
       "legendFormat": "Rows deleted by queries"
      }
     ]
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "$service_name - Transactions",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
     "repeat": "service_name",
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum by (service_name) (rate(pg_stat_database_xact_commit{service_name=~\"$service_name\",datname=~\"$database\",node_name=~\"$node_name\"}[$interval])) or \nsum by (service_name) (irate(pg_stat_database_xact_commit{service_name=~\"$service_name\",datname=~\"$database\",node_name=~\"$node_name\"}[5m]))",
       "legendFormat": "Commits"
      },
      {
       "expr": "sum by (service_name) (rate(pg_stat_database_xact_rollback{service_name=~\"$service_name\",datname=~\"$database\",node_name=~\"$node_name\"}[$interval])) or\nsum by (service_name) (irate(pg_stat_database_xact_rollback{service_name=~\"$service_name\",datname=~\"$database\",node_name=~\"$node_name\"}[5m]))",
       "legendFormat": "Rollbacks"
      }
     ]
    },
    {
     "title": "$service_name - Duration of Transactions",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
     "repeat": "service_name",
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg by (service_name,state) (max_over_time(pg_stat_activity_max_tx_duration{service_name=~\"$service_name\",node_name=~\"$node_name\"}[$interval]) or\nmax_over_time(pg_stat_activity_max_tx_duration{service_name=~\"$service_name\",node_name=~\"$node_name\"}[5m]))",
       "legendFormat": "{{state}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Temp Files",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "$service_name - Number of Temp Files",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
     "repeat": "service_name",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg by (service_name,datname) (max_over_time(pg_stat_database_temp_files{service_name=~\"$service_name\",datname!~\"template.*\",datid!=\"0\",node_name=~\"$node_name\"}[$interval]) or \nmax_over_time(pg_stat_database_temp_files{service_name=~\"$service_name\",datname!~\"template.*\",datid!=\"0\",node_name=~\"$node_name\"}[5m]))",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "$service_name - Size of Temp Files",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
     "repeat": "service_name",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "avg by (service_name,datname) (max_over_time(pg_stat_database_temp_bytes{service_name=~\"$service_name\",datname!~\"template.*\",datid!=\"0\",node_name=~\"$node_name\"}[$interval]) or \nmax_over_time(pg_stat_database_temp_bytes{service_name=~\"$service_name\",datname!~\"template.*\",datid!=\"0\",node_name=~\"$node_name\"}[5m]))",
       "legendFormat": "{{datname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Conflicts & Locks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "$service_name - Conflicts/Deadlocks",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
     "repeat": "service_name",
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "alias": "conflicts",
       "expr": "sum by (service_name) (rate(pg_stat_database_deadlocks{service_name=~\"$service_name\",datname=~\"$database\",node_name=~\"$node_name\"}[$interval])) or \nsum by (service_name) (irate(pg_stat_database_deadlocks{service_name=~\"$service_name\",datname=~\"$database\",node_name=~\"$node_name\"}[5m]))",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Deadlocks",
       "measurement": "postgresql",
       "select": [
        [
         { "params": [ "conflicts" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ],
       "tags": [
        { "key": "node_name", "operator": "=~", "value": "/^$node_name$/" }
       ]
      },
      {
       "alias": "deadlocks",
       "expr": "sum by (service_name) (rate(pg_stat_database_conflicts{service_name=~\"$service_name\",datname=~\"$database\",node_name=~\"$node_name\"}[$interval])) or \nsum by (service_name) (irate(pg_stat_database_conflicts{service_name=~\"$service_name\",datname=~\"$database\",node_name=~\"$node_name\"}[5m]))",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Conflicts",
       "measurement": "postgresql",
       "select": [
        [
         { "params": [ "deadlocks" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ],
       "tags": [
        { "key": "node_name", "operator": "=~", "value": "/^$node_name$/" }
       ]
      }
     ]
    },
    {
     "title": "$service_name - Number of Locks",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
     "repeat": "service_name",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "conflicts",
       "expr": "avg by (service_name,datname,mode) (max_over_time(pg_locks_count{service_name=~\"$service_name\",datname=~\"$database\",datname!~\"template.*\",datid!=\"0\",node_name=~\"$node_name\"}[$interval]) or\nmax_over_time(pg_locks_count{service_name=~\"$service_name\",datname=~\"$database\",datname!~\"template.*\",datid!=\"0\",node_name=~\"$node_name\"}[5m]))",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{mode}} - {{datname}}",
       "measurement": "postgresql",
       "select": [
        [
         { "params": [ "conflicts" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ],
       "tags": [
        { "key": "node_name", "operator": "=~", "value": "/^$node_name$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Buffers & Blocks Operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "$service_name - Operations with Blocks",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
     "repeat": "service_name",
     "yaxes": [
      { "format": "rps" }
     ],
     "targets": [
      {
       "expr": "avg by (service_name,datname) (rate(pg_stat_database_blk_read_time{service_name=~\"$service_name\",datname!~\"template.*\",datname=~\"$database\",node_name=~\"$node_name\"}[$interval]) or\nirate(pg_stat_database_blk_read_time{service_name=~\"$service_name\",datname=~\"$database\",datname!~\"template.*\",node_name=~\"$node_name\"}[5m]))",
       "legendFormat": "Read {{datname}}"
      },
      {
       "expr": "avg by (service_name,datname) (rate(pg_stat_database_blk_write_time{service_name=~\"$service_name\",datname!~\"template.*\",datname=~\"$database\",node_name=~\"$node_name\"}[$interval]) or\nirate(pg_stat_database_blk_write_time{service_name=~\"$service_name\",datname=~\"$database\",datname!~\"template.*\",node_name=~\"$node_name\"}[5m]))",
       "legendFormat": "Write {{datname}}"
      }
     ]
    },
    {
     "title": "$service_name - Buffers",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
     "repeat": "service_name",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Buffers Allocated",
       "expr": "avg by (service_name) (rate(pg_stat_bgwriter_buffers_alloc{service_name=~\"$service_name\",node_name=~\"$node_name\"}[$interval]) or \nirate(pg_stat_bgwriter_buffers_alloc{service_name=~\"$service_name\",node_name=~\"$node_name\"}[5m]))",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Allocated",
       "measurement": "postgresql",
       "select": [
        [
         { "params": [ "buffers_alloc" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ],
       "tags": [
        { "key": "node_name", "operator": "=~", "value": "/^$node_name$/" }
       ]
      },
      {
       "alias": "Buffers Allocated",
       "expr": "avg by (service_name) (rate(pg_stat_bgwriter_buffers_backend_fsync{service_name=~\"$service_name\",node_name=~\"$node_name\"}[$interval]) or\nirate(pg_stat_bgwriter_buffers_backend_fsync{service_name=~\"$service_name\",node_name=~\"$node_name\"}[5m]))",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Fsync calls by a backend",
       "measurement": "postgresql",
       "select": [
        [
         { "params": [ "buffers_alloc" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ],
       "tags": [
        { "key": "node_name", "operator": "=~", "value": "/^$node_name$/" }
       ]
      },
      {
       "alias": "Buffers Allocated",
       "expr": "avg by (service_name) (rate(pg_stat_bgwriter_buffers_backend{service_name=~\"$service_name\",node_name=~\"$node_name\"}[$interval]) or\nirate(pg_stat_bgwriter_buffers_backend{service_name=~\"$service_name\",node_name=~\"$node_name\"}[5m]))",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Written directly by a backend",
       "measurement": "postgresql",
       "select": [
        [
         { "params": [ "buffers_alloc" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ],
       "tags": [
        { "key": "node_name", "operator": "=~", "value": "/^$node_name$/" }
       ]
      },
      {
       "alias": "Buffers Allocated",
       "expr": "avg by (service_name) (rate(pg_stat_bgwriter_buffers_clean{service_name=~\"$service_name\",node_name=~\"$node_name\"}[$interval]) or \nirate(pg_stat_bgwriter_buffers_clean{service_name=~\"$service_name\",node_name=~\"$node_name\"}[5m]))",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Written by the background writer",
       "measurement": "postgresql",
       "select": [
        [
         { "params": [ "buffers_alloc" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ],
       "tags": [
        { "key": "node_name", "operator": "=~", "value": "/^$node_name$/" }
       ]
      },
      {
       "alias": "Buffers Allocated",
       "expr": "avg by (service_name) (rate(pg_stat_bgwriter_buffers_checkpoint{service_name=~\"$service_name\",node_name=~\"$node_name\"}[5m]) or\nirate(pg_stat_bgwriter_buffers_checkpoint{service_name=~\"$service_name\",node_name=~\"$node_name\"}[5m]))",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Written during checkpoints",
       "measurement": "postgresql",
       "select": [
        [
         { "params": [ "buffers_alloc" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ],
       "tags": [
        { "key": "node_name", "operator": "=~", "value": "/^$node_name$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Others",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "$service_name - Canceled Queries",
     "type": "graph",
     "description": "Based on pg_stat_database_conflicts view",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
     "repeat": "service_name",
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum by (service_name) (rate(pg_stat_database_conflicts_confl_bufferpin{service_name=~\"$service_name\",datname!~\"template(0|1)\",node_name=~\"$node_name\"}[$interval])) or\nsum by (service_name) (irate(pg_stat_database_conflicts_confl_bufferpin{service_name=~\"$service_name\",datname!~\"template(0|1)\",node_name=~\"$node_name\"}[5m]))",
       "legendFormat": "Pinned buffers"
      },
      {
       "expr": "sum by (service_name) (rate(pg_stat_database_conflicts_confl_deadlock{service_name=~\"$service_name\",datname!~\"template(0|1)\",node_name=~\"$node_name\"}[$interval])) or\nsum by (service_name) (irate(pg_stat_database_conflicts_confl_deadlock{service_name=~\"$service_name\",datname!~\"template(0|1)\",node_name=~\"$node_name\"}[5m]))",
       "legendFormat": "Deadlocks"
      },
      {
       "expr": "sum by (service_name) (rate(pg_stat_database_conflicts_confl_lock{service_name=~\"$service_name\",datname!~\"template(0|1)\",node_name=~\"$node_name\"}[$interval])) or\nsum by (service_name) (irate(pg_stat_database_conflicts_confl_lock{service_name=~\"$service_name\",datname!~\"template(0|1)\",node_name=~\"$node_name\"}[5m]))",
       "legendFormat": "Lock timeouts"
      },
      {
       "expr": "sum by (service_name) (rate(pg_stat_database_conflicts_confl_snapshot{service_name=~\"$service_name\",datname!~\"template(0|1)\",node_name=~\"$node_name\"}[$interval])) or\nsum by (service_name) (irate(pg_stat_database_conflicts_confl_snapshot{service_name=~\"$service_name\",datname!~\"template(0|1)\",node_name=~\"$node_name\"}[5m]))",
       "legendFormat": "Old snapshots"
      },
      {
       "expr": "sum by (service_name) (rate(pg_stat_database_conflicts_confl_tablespace{service_name=~\"$service_name\",datname!~\"template(0|1)\",node_name=~\"$node_name\"}[$interval])) or\nsum by (service_name) (irate(pg_stat_database_conflicts_confl_tablespace{service_name=~\"$service_name\",datname!~\"template(0|1)\",node_name=~\"$node_name\"}[5m]))",
       "legendFormat": "Dropped tablespaces "
      }
     ]
    },
    {
     "title": "$service_name - Cache Hit Ratio",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
     "repeat": "service_name",
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum by (service_name,datname) (pg_stat_database_blks_hit{service_name=~\"$service_name\",datname!~\"template.*\",datid!=\"0\",node_name=~\"$node_name\"}) /\n(sum by (service_name,datname) (pg_stat_database_blks_hit{service_name=~\"$service_name\",datname!~\"template.*\",datid!=\"0\",node_name=~\"$node_name\"}) + \nsum by (service_name,datname) (pg_stat_database_blks_read{service_name=~\"$service_name\",datname!~\"template.*\",datid!=\"0\",node_name=~\"$node_name\"}))",
       "legendFormat": "Cache hit rate {{datname}}"
      }
     ]
    },
    {
     "title": "$service_name - Checkpoint stats",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 45 },
     "repeat": "service_name",
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "avg by (service_name) (rate(pg_stat_bgwriter_checkpoint_sync_time{service_name=~'$service_name',datname!~\"template(0|1)\",node_name=~\"$node_name\"}[$interval]) or\nirate(pg_stat_bgwriter_checkpoint_sync_time{service_name=~'$service_name', datname!~\"template(0|1)\", node_name=~\"$node_name\"}[5m]))",
       "legendFormat": "Files Synchronization to disk"
      },
      {
       "expr": "avg by (service_name) (rate(pg_stat_bgwriter_checkpoint_write_time{service_name=~'$service_name', datname!~\"template(0|1)\", node_name=~\"$node_name\"}[$interval]) or\nirate(pg_stat_bgwriter_checkpoint_write_time{service_name=~'$service_name', datname!~\"template(0|1)\", node_name=~\"$node_name\"}[5m]))",
       "legendFormat": "Written Files to disk"
      }
     ]
    }
   ]
  }
 ]
}