// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// InventoryGetNodeResponse inventory get node response
// swagger:model inventoryGetNodeResponse
type InventoryGetNodeResponse struct {

	// amazon rds
	AmazonRDS *InventoryAmazonRDSRemoteNode `json:"amazon_rds,omitempty"`

	// generic
	Generic *InventoryGenericNode `json:"generic,omitempty"`

	// remote
	Remote *InventoryRemoteNode `json:"remote,omitempty"`
}

// Validate validates this inventory get node response
func (m *InventoryGetNodeResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAmazonRDS(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateGeneric(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRemote(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *InventoryGetNodeResponse) validateAmazonRDS(formats strfmt.Registry) error {

	if swag.IsZero(m.AmazonRDS) { // not required
		return nil
	}

	if m.AmazonRDS != nil {
		if err := m.AmazonRDS.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("amazon_rds")
			}
			return err
		}
	}

	return nil
}

func (m *InventoryGetNodeResponse) validateGeneric(formats strfmt.Registry) error {

	if swag.IsZero(m.Generic) { // not required
		return nil
	}

	if m.Generic != nil {
		if err := m.Generic.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("generic")
			}
			return err
		}
	}

	return nil
}

func (m *InventoryGetNodeResponse) validateRemote(formats strfmt.Registry) error {

	if swag.IsZero(m.Remote) { // not required
		return nil
	}

	if m.Remote != nil {
		if err := m.Remote.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("remote")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *InventoryGetNodeResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *InventoryGetNodeResponse) UnmarshalBinary(b []byte) error {
	var res InventoryGetNodeResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
