CREATE TABLE queries (
  digest String,
  digest_text String,
  db_server String,
  db_schema String,
  db_username String,
  client_host String,
  `labels.key` Array(String),
  `labels.value` Array(String),
  agent_uuid String,
  period_start DateTime,
  period_length UInt8,
  example String,
  example_format Enum8('EXAMPLE' = 0, 'DIGEST' = 1),
  is_truncated UInt8,
  example_type Enum8(
    'RANDOM' = 0,
    'SLOWEST' = 1,
    'FASTEST' = 2,
    'WITH_ERROR' = 3
  ),
  example_metrics String,
  num_query_with_warnings UInt64,
  `warnings.code` Array(String),
  `warnings.count` Array(UInt64),
  num_query_with_errors UInt64,
  `errors.code` Array(String),
  `errors.count` Array(UInt64),
  num_queries UInt64,
  m_Query_time_cnt UInt32,
  m_Query_time_sum Float32,
  m_Query_time_min Float32,
  m_Query_time_max Float32,
  m_Query_time_p99 Float32,
  m_Query_time_hg Array(UInt32),
  m_Lock_time_cnt UInt32,
  m_Lock_time_sum Float32,
  m_Lock_time_min Float32,
  m_Lock_time_max Float32,
  m_Lock_time_p99 Float32,
  m_Lock_time_hg Array(Float32),
  m_Rows_sent_cnt UInt64,
  m_Rows_sent_sum UInt64,
  m_Rows_sent_min UInt64,
  m_Rows_sent_max UInt64,
  m_Rows_sent_p99 UInt64,
  m_Rows_sent_hg Array(UInt64),
  m_Rows_examined_cnt UInt64,
  m_Rows_examined_sum UInt64,
  m_Rows_examined_min UInt64,
  m_Rows_examined_max UInt64,
  m_Rows_examined_p99 UInt64,
  m_Rows_examined_hg Array(UInt64),
  m_Rows_affected_cnt UInt64,
  m_Rows_affected_sum UInt64,
  m_Rows_affected_min UInt64,
  m_Rows_affected_max UInt64,
  m_Rows_affected_p99 UInt64,
  m_Rows_affected_hg Array(UInt64),
  m_Rows_read_cnt UInt64,
  m_Rows_read_sum UInt64,
  m_Rows_read_min UInt64,
  m_Rows_read_max UInt64,
  m_Rows_read_p99 UInt64,
  m_Rows_read_hg Array(UInt64),
  m_Merge_passes_cnt UInt64,
  m_Merge_passes_sum UInt64,
  m_Merge_passes_min UInt64,
  m_Merge_passes_max UInt64,
  m_Merge_passes_p99 UInt64,
  m_Merge_passes_hg Array(UInt64),
  m_InnoDB_IO_r_ops_cnt UInt64,
  m_InnoDB_IO_r_ops_sum UInt64,
  m_InnoDB_IO_r_ops_min UInt64,
  m_InnoDB_IO_r_ops_max UInt64,
  m_InnoDB_IO_r_ops_p99 UInt64,
  m_InnoDB_IO_r_ops_hg Array(UInt64),
  m_InnoDB_IO_r_bytes_cnt UInt64,
  m_InnoDB_IO_r_bytes_sum UInt64,
  m_InnoDB_IO_r_bytes_min UInt64,
  m_InnoDB_IO_r_bytes_max UInt64,
  m_InnoDB_IO_r_bytes_p99 UInt64,
  m_InnoDB_IO_r_bytes_hg Array(UInt64),
  m_InnoDB_IO_r_wait_cnt Float32,
  m_InnoDB_IO_r_wait_sum Float32,
  m_InnoDB_IO_r_wait_min Float32,
  m_InnoDB_IO_r_wait_max Float32,
  m_InnoDB_IO_r_wait_p99 Float32,
  m_InnoDB_IO_r_wait_hg Array(Float32),
  m_InnoDB_rec_lock_wait_cnt Float32,
  m_InnoDB_rec_lock_wait_sum Float32,
  m_InnoDB_rec_lock_wait_min Float32,
  m_InnoDB_rec_lock_wait_max Float32,
  m_InnoDB_rec_lock_wait_p99 Float32,
  m_InnoDB_rec_lock_wait_hg Array(Float32),
  m_InnoDB_queue_wait_cnt Float32,
  m_InnoDB_queue_wait_sum Float32,
  m_InnoDB_queue_wait_min Float32,
  m_InnoDB_queue_wait_max Float32,
  m_InnoDB_queue_wait_p99 Float32,
  m_InnoDB_queue_wait_hg Array(Float32),
  m_InnoDB_pages_distinct_cnt UInt64,
  m_InnoDB_pages_distinct_sum UInt64,
  m_InnoDB_pages_distinct_min UInt64,
  m_InnoDB_pages_distinct_max UInt64,
  m_InnoDB_pages_distinct_p99 UInt64,
  m_InnoDB_pages_distinct_hg Array(UInt64),
  m_Query_length_cnt UInt64,
  m_Query_length_sum UInt64,
  m_Query_length_min UInt64,
  m_Query_length_max UInt64,
  m_Query_length_p99 UInt64,
  m_Query_length_hg Array(UInt64),
  m_Bytes_sent_cnt UInt64,
  m_Bytes_sent_sum UInt64,
  m_Bytes_sent_min UInt64,
  m_Bytes_sent_max UInt64,
  m_Bytes_sent_p99 UInt64,
  m_Bytes_sent_hg Array(UInt64),
  m_Tmp_tables_cnt UInt64,
  m_Tmp_tables_sum UInt64,
  m_Tmp_tables_min UInt64,
  m_Tmp_tables_max UInt64,
  m_Tmp_tables_p99 UInt64,
  m_Tmp_tables_hg Array(UInt64),
  m_Tmp_disk_tables_cnt UInt64,
  m_Tmp_disk_tables_sum UInt64,
  m_Tmp_disk_tables_min UInt64,
  m_Tmp_disk_tables_max UInt64,
  m_Tmp_disk_tables_p99 UInt64,
  m_Tmp_disk_tables_hg Array(UInt64),
  m_Tmp_table_sizes_cnt UInt64,
  m_Tmp_table_sizes_sum UInt64,
  m_Tmp_table_sizes_min UInt64,
  m_Tmp_table_sizes_max UInt64,
  m_Tmp_table_sizes_p99 UInt64,
  m_Tmp_table_sizes_hg Array(UInt64),
  m_QC_Hit_sum UInt64,
  m_Full_scan_sum UInt64,
  m_Full_join_sum UInt64,
  m_Tmp_table_sum UInt64,
  m_Tmp_table_on_disk_sum UInt64,
  m_Filesort_sum UInt64,
  m_Filesort_on_disk_sum UInt64,
  m_Select_full_range_join_sum UInt64,
  m_Select_range_sum UInt64,
  m_Select_range_check_sum UInt64,
  m_Sort_range_sum UInt64,
  m_Sort_rows_sum UInt64,
  m_Sort_scan_sum UInt64,
  m_No_index_used_sum UInt64,
  m_No_good_index_used_sum UInt64,
  grpstr String,
  grpint UInt16,
  `labint.key` Array(UInt16),
  `labint.value` Array(UInt16)
) ENGINE = MergeTree PARTITION BY toYYYYMM(period_start)
ORDER BY
  (
    digest,
    db_server,
    db_username,
    db_schema,
    client_host,
    period_start
  )
