ALTER TABLE metrics
  ADD COLUMN `m_shared_blks_hit_cnt` Float32,
  ADD COLUMN `m_shared_blks_hit_sum` Float32 COMMENT 'Total number of shared blocks cache hits by the statement',
  ADD COLUMN `m_shared_blks_read_cnt` Float32,
  ADD COLUMN `m_shared_blks_read_sum` Float32 COMMENT 'Total number of shared blocks read by the statement.',
  ADD COLUMN `m_shared_blks_dirtied_cnt` Float32,
  ADD COLUMN `m_shared_blks_dirtied_sum` Float32 COMMENT 'Total number of shared blocks dirtied by the statement.',
  ADD COLUMN `m_shared_blks_written_cnt` Float32,
  ADD COLUMN `m_shared_blks_written_sum` Float32 COMMENT 'Total number of shared blocks written by the statement.',
  ADD COLUMN `m_local_blks_hit_cnt` Float32,
  ADD COLUMN `m_local_blks_hit_sum` Float32 COMMENT 'Total number of local block cache hits by the statement',
  ADD COLUMN `m_local_blks_read_cnt` Float32,
  ADD COLUMN `m_local_blks_read_sum` Float32 COMMENT 'Total number of local blocks read by the statement.',
  ADD COLUMN `m_local_blks_dirtied_cnt` Float32,
  ADD COLUMN `m_local_blks_dirtied_sum` Float32 COMMENT 'Total number of local blocks dirtied by the statement.',
  ADD COLUMN `m_local_blks_written_cnt` Float32,
  ADD COLUMN `m_local_blks_written_sum` Float32 COMMENT 'Total number of local blocks written by the statement.',
  ADD COLUMN `m_temp_blks_read_cnt` Float32,
  ADD COLUMN `m_temp_blks_read_sum` Float32 COMMENT 'Total number of temp blocks read by the statement.',
  ADD COLUMN `m_temp_blks_written_cnt` Float32,
  ADD COLUMN `m_temp_blks_written_sum` Float32 COMMENT 'Total number of temp blocks written by the statement.',
  ADD COLUMN `m_blk_read_time_cnt` Float32,
  ADD COLUMN `m_blk_read_time_sum` Float32 COMMENT 'Total time the statement spent reading blocks, in milliseconds (if track_io_timing is enabled, otherwise zero).',
  ADD COLUMN `m_blk_write_time_cnt` Float32,
  ADD COLUMN `m_blk_write_time_sum` Float32 COMMENT 'Total time the statement spent writing blocks, in milliseconds (if track_io_timing is enabled, otherwise zero).'
  ;