---
# Restore Postgres Databases
# This playbook can be run on its own as follows:
# ansible-playbook -i localhost /usr/share/pmm-update/ansible/playbook/tasks/roles/postgres/tasks/restore.yml
# or using `include_role` from another playbook with `tasks_from: restore.yml`

- name: Check if supervisor socket exists
  stat:
    path: /run/supervisor/supervisor.sock
  register: supervisor_socket

- name: Set fact is_supervisor_running
  set_fact:
    is_supervisor_running: supervisor_socket.stat.exists

- name: Set fact is_ha
  set_fact:
    is_ha: lookup('env','GF_DATABASE_URL') == '' and lookup('env','GF_DATABASE_HOST') == ''

- name: Restore the database
  block:
  - name: Stop pmm-managed, pmm-agent and postgres before backing up
    supervisorctl:
      name: "{{ item }}"
      state: stopped
    loop:
      - pmm-managed
      - pmm-agent
      - postgresql
    become: true

  - name: Run Postgres database without supervisor
    command: /usr/pgsql-14/bin/pg_ctl start -D /srv/postgres
    become: true
    become_user: pmm
    become_method: su

  - name: Restore pmm-managed database
    postgresql_db:
      name: pmm-managed
      state: restore
      target: /srv/postgres14/pmm-managed.sql

  - name: Restore grafana database
    postgresql_db:
      name: grafana
      state: restore
      target: /srv/postgres14/grafana.sql
    when: not is_ha

  - name: Check pg_stat_statements extension
    postgresql_ext:
      db: postgres
      name: pg_stat_statements
      schema: public

  - name: Stop Postgres database without supervisor
    command: /usr/pgsql-14/bin/pg_ctl stop -D /srv/postgres14
    become: true
    become_user: pmm
    become_method: su

  - name: Start pmm-managed, pmm-agent and postgres after restoring
    supervisorctl:
      name: "{{ item }}"
      state: started
    loop:
      - postgresql
      - pmm-managed
      - pmm-agent
    become: true    

  when: is_supervisor_running
