// Code generated by go-swagger; DO NOT EDIT.

package agent_local

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewAgentLocalReloadParams creates a new AgentLocalReloadParams object
// with the default values initialized.
func NewAgentLocalReloadParams() *AgentLocalReloadParams {
	var ()
	return &AgentLocalReloadParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAgentLocalReloadParamsWithTimeout creates a new AgentLocalReloadParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAgentLocalReloadParamsWithTimeout(timeout time.Duration) *AgentLocalReloadParams {
	var ()
	return &AgentLocalReloadParams{

		timeout: timeout,
	}
}

// NewAgentLocalReloadParamsWithContext creates a new AgentLocalReloadParams object
// with the default values initialized, and the ability to set a context for a request
func NewAgentLocalReloadParamsWithContext(ctx context.Context) *AgentLocalReloadParams {
	var ()
	return &AgentLocalReloadParams{

		Context: ctx,
	}
}

// NewAgentLocalReloadParamsWithHTTPClient creates a new AgentLocalReloadParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAgentLocalReloadParamsWithHTTPClient(client *http.Client) *AgentLocalReloadParams {
	var ()
	return &AgentLocalReloadParams{
		HTTPClient: client,
	}
}

/*AgentLocalReloadParams contains all the parameters to send to the API endpoint
for the agent local reload operation typically these are written to a http.Request
*/
type AgentLocalReloadParams struct {

	/*Body*/
	Body interface{}

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the agent local reload params
func (o *AgentLocalReloadParams) WithTimeout(timeout time.Duration) *AgentLocalReloadParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the agent local reload params
func (o *AgentLocalReloadParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the agent local reload params
func (o *AgentLocalReloadParams) WithContext(ctx context.Context) *AgentLocalReloadParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the agent local reload params
func (o *AgentLocalReloadParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the agent local reload params
func (o *AgentLocalReloadParams) WithHTTPClient(client *http.Client) *AgentLocalReloadParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the agent local reload params
func (o *AgentLocalReloadParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the agent local reload params
func (o *AgentLocalReloadParams) WithBody(body interface{}) *AgentLocalReloadParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the agent local reload params
func (o *AgentLocalReloadParams) SetBody(body interface{}) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *AgentLocalReloadParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
