{
 "title": "MongoDB Instances Compare",
 "tags": [
  "MongoDB_Compare",
  "Percona"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"},environment)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(mongodb_mongod_replset_my_state{environment=~\"$environment\"},cluster)"
    }
   },
   {
    "name": "node_name",
    "label": "Node Name",
    "query": {
     "query": "label_values(mongodb_up{cluster=~\"$cluster\", environment=~\"$environment\"},node_name)"
    }
   },
   {
    "name": "replication_set",
    "label": "Replication Set",
    "query": {
     "query": "label_values(mongodb_mongod_replset_my_state{environment=~\"$environment\",cluster=~\"$cluster\"}, set)"
    }
   },
   {
    "name": "service_name",
    "label": "Node",
    "query": {
     "query": "label_values(mongodb_mongod_replset_my_state{environment=~\"$environment\",cluster=~\"$cluster\",set=~\"$replication_set\"}, service_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$service_name - Service Info",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "repeat": "service_name",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(mongodb_version_info{service_name=~\"$service_name\",environment=~\"$environment\",cluster=~\"$cluster\"} and on (service_name) group by (service_name) (mongodb_mongod_replset_my_state{environment=~\"$environment\",cluster=~\"$cluster\",set=~\"$replication_set\"}))"
    }
   ]
  },
  {
   "title": "$service_name - MongoDB Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 5 },
   "repeat": "service_name",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "avg by (service_name) ((mongodb_instance_uptime_seconds{service_name=~\"$service_name\",environment=~\"$environment\",cluster=~\"$cluster\"} and on (service_name) group by (service_name) (mongodb_mongod_replset_my_state{environment=~\"$environment\",cluster=~\"$cluster\",set=~\"$replication_set\"})))"
    }
   ]
  },
  {
   "title": "$service_name - Current QPS",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 7 },
   "repeat": "service_name",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (service_name) ((rate(mongodb_op_counters_total{service_name=~\"$service_name\",type!=\"command\",environment=~\"$environment\",cluster=~\"$cluster\"}[$interval]) and on (service_name) group by (service_name) (mongodb_mongod_replset_my_state{environment=~\"$environment\",cluster=~\"$cluster\",set=~\"$replication_set\"})) or (irate(mongodb_op_counters_total{service_name=~\"$service_name\",type!=\"command\",environment=~\"$environment\",cluster=~\"$cluster\"}[5m]) and on (service_name) group by (service_name) (mongodb_mongod_replset_my_state{environment=~\"$environment\",cluster=~\"$cluster\",set=~\"$replication_set\"})))"
    }
   ]
  },
  {
   "title": "$service_name - DB Connections",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 9 },
   "repeat": "service_name",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (service_name) ((max_over_time(mongodb_connections{service_name=~\"$service_name\",state=\"current\",environment=~\"$environment\",cluster=~\"$cluster\"}[$interval]) and on (service_name) group by (service_name) (mongodb_mongod_replset_my_state{environment=~\"$environment\",cluster=~\"$cluster\",set=~\"$replication_set\"})) or (max_over_time(mongodb_connections{service_name=~\"$service_name\",state=\"current\",environment=~\"$environment\",cluster=~\"$cluster\"}[5m]) and on (service_name) group by (service_name) (mongodb_mongod_replset_my_state{environment=~\"$environment\",cluster=~\"$cluster\",set=~\"$replication_set\"})))"
    }
   ]
  },
  {
   "title": "$service_name - Latency",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 11 },
   "repeat": "service_name",
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "avg by (service_name) ((rate(mongodb_mongod_op_latencies_latency_total{service_name=~\"$service_name\",type=\"command\",environment=~\"$environment\",cluster=~\"$cluster\"}[$interval]) and on (service_name) group by (service_name) (mongodb_mongod_replset_my_state{environment=~\"$environment\",cluster=~\"$cluster\",set=~\"$replication_set\"})) / ((rate(mongodb_mongod_op_latencies_ops_total{service_name=~\"$service_name\",type=\"command\",environment=~\"$environment\",cluster=~\"$cluster\"}[$interval]) and on (service_name) group by (service_name) (mongodb_mongod_replset_my_state{environment=~\"$environment\",cluster=~\"$cluster\",set=~\"$replication_set\"})) > 0) or (irate(mongodb_mongod_op_latencies_latency_total{service_name=~\"$service_name\",type=\"command\",environment=~\"$environment\",cluster=~\"$cluster\"}[5m]) and on (service_name) group by (service_name) (mongodb_mongod_replset_my_state{environment=~\"$environment\",cluster=~\"$cluster\",set=~\"$replication_set\"})) / ((irate(mongodb_mongod_op_latencies_ops_total{service_name=~\"$service_name\",type=\"command\",environment=~\"$environment\",cluster=~\"$cluster\"}[5m]) and on (service_name) group by (service_name) (mongodb_mongod_replset_my_state{environment=~\"$environment\",cluster=~\"$cluster\",set=~\"$replication_set\"})) > 0))"
    }
   ]
  },
  {
   "title": "$service_name - Opened Cursors",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 13 },
   "repeat": "service_name",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "sum((mongodb_mongod_metrics_cursor_open{service_name=~\"$service_name\",environment=~\"$environment\",cluster=~\"$cluster\"} and on (service_name) group by (service_name) (mongodb_mongod_replset_my_state{environment=~\"$environment\",cluster=~\"$cluster\",set=~\"$replication_set\"})) or (mongodb_mongod_cursors{service_name=~\"$service_name\",environment=~\"$environment\",cluster=~\"$cluster\"} and on (service_name) group by (service_name) (mongodb_mongod_replset_my_state{environment=~\"$environment\",cluster=~\"$cluster\",set=~\"$replication_set\"})) or (mongodb_mongos_metrics_cursor_open{service_name=~\"$service_name\",environment=~\"$environment\",cluster=~\"$cluster\"} and on (service_name) group by (service_name) (mongodb_mongod_replset_my_state{environment=~\"$environment\",cluster=~\"$cluster\",set=~\"$replication_set\"})) or (mongodb_mongos_cursors{service_name=~\"$service_name\",environment=~\"$environment\",cluster=~\"$cluster\"} and on (service_name) group by (service_name) (mongodb_mongod_replset_my_state{environment=~\"$environment\",cluster=~\"$cluster\",set=~\"$replication_set\"})))"
    }
   ]
  },
  {
   "title": "$service_name - Replica Set",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 15 },
   "repeat": "service_name",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "mongodb_mongod_replset_my_state{service_name=~\"$service_name\",environment=~\"$environment\",cluster=~\"$cluster\",set=~\"$replication_set\"}",
     "legendFormat": "{{set}}"
    }
   ]
  },
  {
   "title": "$service_name - ReplSet State",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 17 },
   "repeat": "service_name",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_mongod_replset_my_state{service_name=~\"$service_name\",environment=~\"$environment\",cluster=~\"$cluster\",set=~\"$replication_set\"}"
    }
   ]
  },
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "$service_name - Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
   "repeat": "service_name",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (service_name,state) ((max_over_time(mongodb_mongod_connections{service_name=~\"$service_name\", state=~\"current|available\", environment=~\"$environment\", cluster=~\"$cluster\"}[$interval]) and on (service_name) group by (service_name) (mongodb_mongod_replset_my_state{environment=~\"$environment\",cluster=~\"$cluster\",set=~\"$replication_set\"})) or (max_over_time(mongodb_mongod_connections{service_name=~\"$service_name\", state=~\"current|available\", environment=~\"$environment\", cluster=~\"$cluster\"}[5m]) and on (service_name) group by (service_name) (mongodb_mongod_replset_my_state{environment=~\"$environment\",cluster=~\"$cluster\",set=~\"$replication_set\"})) or (max_over_time(mongodb_mongos_connections{service_name=~\"$service_name\", state=~\"current|available\", environment=~\"$environment\", cluster=~\"$cluster\"}[$interval]) and on (service_name) group by (service_name) (mongodb_mongod_replset_my_state{environment=~\"$environment\",cluster=~\"$cluster\",set=~\"$replication_set\"})) or (max_over_time(mongodb_mongos_connections{service_name=~\"$service_name\", state=~\"current|available\", environment=~\"$environment\", cluster=~\"$cluster\"}[5m]) and on (service_name) group by (service_name) (mongodb_mongod_replset_my_state{environment=~\"$environment\",cluster=~\"$cluster\",set=~\"$replication_set\"})) or \n(max_over_time(mongodb_connections{service_name=~\"$service_name\", state=~\"current|available\", environment=~\"$environment\", cluster=~\"$cluster\"}[$interval]) and on (service_name) group by (service_name) (mongodb_mongod_replset_my_state{environment=~\"$environment\",cluster=~\"$cluster\",set=~\"$replication_set\"})) or \n(max_over_time(mongodb_connections{service_name=~\"$service_name\", state=~\"current|available\", environment=~\"$environment\", cluster=~\"$cluster\"}[5m]) and on (service_name) group by (service_name) (mongodb_mongod_replset_my_state{environment=~\"$environment\",cluster=~\"$cluster\",set=~\"$replication_set\"})))",
     "legendFormat": "{{state}}"
    }
   ]
  },
  { "title": "Cursors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "$service_name - Cursors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 29 },
   "repeat": "service_name",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (service_name,state) ((mongodb_mongod_metrics_cursor_open{service_name=~\"$service_name\",environment=~\"$environment\",cluster=~\"$cluster\"} and on (service_name) group by (service_name) (mongodb_mongod_replset_my_state{environment=~\"$environment\",cluster=~\"$cluster\",set=~\"$replication_set\"})) or \n(mongodb_mongod_cursors{service_name=~\"$service_name\",environment=~\"$environment\",cluster=~\"$cluster\"} and on (service_name) group by (service_name) (mongodb_mongod_replset_my_state{environment=~\"$environment\",cluster=~\"$cluster\",set=~\"$replication_set\"})) or \n(mongodb_mongos_metrics_cursor_open{service_name=~\"$service_name\",environment=~\"$environment\",cluster=~\"$cluster\"} and on (service_name) group by (service_name) (mongodb_mongod_replset_my_state{environment=~\"$environment\",cluster=~\"$cluster\",set=~\"$replication_set\"})) or \n(mongodb_mongos_cursors{service_name=~\"$service_name\",environment=~\"$environment\",cluster=~\"$cluster\"} and on (service_name) group by (service_name) (mongodb_mongod_replset_my_state{environment=~\"$environment\",cluster=~\"$cluster\",set=~\"$replication_set\"})))",
     "legendFormat": "{{state}}"
    }
   ]
  },
  { "title": "Query Efficiency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "$service_name - Latency",
   "type": "timeseries",
   "description": "Average latency of operations (classified by read, write, or (other) command)",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 38 },
   "repeat": "service_name",
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (service_name,type) ((rate(mongodb_mongod_op_latencies_latency_total{service_name=~\"$service_name\",environment=~\"$environment\",cluster=~\"$cluster\"}[$interval]) and on (service_name) group by (service_name) (mongodb_mongod_replset_my_state{environment=~\"$environment\",cluster=~\"$cluster\",set=~\"$replication_set\"})) / ((rate(mongodb_mongod_op_latencies_ops_total{service_name=~\"$service_name\",environment=~\"$environment\",cluster=~\"$cluster\"}[$interval]) and on (service_name) group by (service_name) (mongodb_mongod_replset_my_state{environment=~\"$environment\",cluster=~\"$cluster\",set=~\"$replication_set\"})) > 0) or\n(irate(mongodb_mongod_op_latencies_latency_total{service_name=~\"$service_name\",environment=~\"$environment\",cluster=~\"$cluster\"}[5m]) and on (service_name) group by (service_name) (mongodb_mongod_replset_my_state{environment=~\"$environment\",cluster=~\"$cluster\",set=~\"$replication_set\"})) / \n((irate(mongodb_mongod_op_latencies_ops_total{service_name=~\"$service_name\",environment=~\"$environment\",cluster=~\"$cluster\"}[5m]) and on (service_name) group by (service_name) (mongodb_mongod_replset_my_state{environment=~\"$environment\",cluster=~\"$cluster\",set=~\"$replication_set\"})) > 0))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "$service_name - Scan Ratios",
   "type": "timeseries",
   "description": "Ratio of index entries scanned or whole docs scanned / number of documents returned",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 46 },
   "repeat": "service_name",
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (service_name) ((rate(mongodb_mongod_metrics_query_executor_total{service_name=~\"$service_name\", state=\"scanned\", environment=~\"$environment\", cluster=~\"$cluster\"}[$interval]) and on (service_name) group by (service_name) (mongodb_mongod_replset_my_state{environment=~\"$environment\",cluster=~\"$cluster\",set=~\"$replication_set\"})) / ignoring(state) (rate(mongodb_mongod_metrics_document_total{service_name=~\"$service_name\", state=\"returned\", environment=~\"$environment\", cluster=~\"$cluster\"}[$interval]) and on (service_name) group by (service_name) (mongodb_mongod_replset_my_state{environment=~\"$environment\",cluster=~\"$cluster\",set=~\"$replication_set\"})) or ((irate(mongodb_mongod_metrics_query_executor_total{service_name=~\"$service_name\", state=\"scanned\", environment=~\"$environment\", cluster=~\"$cluster\"}[5m]) and on (service_name) group by (service_name) (mongodb_mongod_replset_my_state{environment=~\"$environment\",cluster=~\"$cluster\",set=~\"$replication_set\"})) / ignoring(state) (irate(mongodb_mongod_metrics_document_total{service_name=~\"$service_name\", state=\"returned\", environment=~\"$environment\", cluster=~\"$cluster\"}[5m]) and on (service_name) group by (service_name) (mongodb_mongod_replset_my_state{environment=~\"$environment\",cluster=~\"$cluster\",set=~\"$replication_set\"}))))",
     "legendFormat": "Index"
    },
    {
     "expr": "avg by (service_name) ((rate(mongodb_mongod_metrics_document_total{service_name=~\"$service_name\", state=\"returned\", environment=~\"$environment\", cluster=~\"$cluster\"}[$interval]) and on (service_name) group by (service_name) (mongodb_mongod_replset_my_state{environment=~\"$environment\",cluster=~\"$cluster\",set=~\"$replication_set\"})) / ignoring(state)(rate(mongodb_mongod_metrics_query_executor_total{service_name=~\"$service_name\", state=\"scanned_objects\", environment=~\"$environment\", cluster=~\"$cluster\"}[$interval]) and on (service_name) group by (service_name) (mongodb_mongod_replset_my_state{environment=~\"$environment\",cluster=~\"$cluster\",set=~\"$replication_set\"})) or\n(irate(mongodb_mongod_metrics_document_total{service_name=~\"$service_name\", state=\"returned\", environment=~\"$environment\", cluster=~\"$cluster\"}[5m]) and on (service_name) group by (service_name) (mongodb_mongod_replset_my_state{environment=~\"$environment\",cluster=~\"$cluster\",set=~\"$replication_set\"})) / ignoring(state)(irate(mongodb_mongod_metrics_query_executor_total{service_name=~\"$service_name\", state=\"scanned_objects\", environment=~\"$environment\", cluster=~\"$cluster\"}[5m]) and on (service_name) group by (service_name) (mongodb_mongod_replset_my_state{environment=~\"$environment\",cluster=~\"$cluster\",set=~\"$replication_set\"})))",
     "legendFormat": "Document"
    }
   ]
  },
  {
   "title": "$service_name - Index Filtering Effectiveness",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 54 },
   "repeat": "service_name",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum by (service_name) ((mongodb_mongod_metrics_query_executor_total{service_name=~\"$service_name\", state=~\"scanned_objects\", environment=~\"$environment\", cluster=~\"$cluster\"} and on (service_name) group by (service_name) (mongodb_mongod_replset_my_state{environment=~\"$environment\",cluster=~\"$cluster\",set=~\"$replication_set\"}))) / ignoring(state)sum by (service_name) ((mongodb_mongod_metrics_query_executor_total{service_name=~\"$service_name\", state=~\"scanned_objects|scanned\", environment=~\"$environment\", cluster=~\"$cluster\"} and on (service_name) group by (service_name) (mongodb_mongod_replset_my_state{environment=~\"$environment\",cluster=~\"$cluster\",set=~\"$replication_set\"})))",
     "legendFormat": "Index"
    }
   ]
  },
  { "title": "Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "$service_name - Requests",
   "type": "timeseries",
   "description": "Ops/sec (classified by (legacy) wire protocol request type)",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 63 },
   "repeat": "service_name",
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (service_name,type) ((rate(mongodb_mongod_op_counters_total{service_name=~\"$service_name\",environment=~\"$environment\",cluster=~\"$cluster\"}[$interval]) and on (service_name) group by (service_name) (mongodb_mongod_replset_my_state{environment=~\"$environment\",cluster=~\"$cluster\",set=~\"$replication_set\"})) or \n(irate(mongodb_mongod_op_counters_total{service_name=~\"$service_name\",environment=~\"$environment\",cluster=~\"$cluster\"}[5m]) and on (service_name) group by (service_name) (mongodb_mongod_replset_my_state{environment=~\"$environment\",cluster=~\"$cluster\",set=~\"$replication_set\"})) or \n(rate(mongodb_mongos_op_counters_total{service_name=~\"$service_name\",environment=~\"$environment\",cluster=~\"$cluster\"}[$interval]) and on (service_name) group by (service_name) (mongodb_mongod_replset_my_state{environment=~\"$environment\",cluster=~\"$cluster\",set=~\"$replication_set\"})) or \n(irate(mongodb_mongos_op_counters_total{service_name=~\"$service_name\",environment=~\"$environment\",cluster=~\"$cluster\"}[5m]) and on (service_name) group by (service_name) (mongodb_mongod_replset_my_state{environment=~\"$environment\",cluster=~\"$cluster\",set=~\"$replication_set\"})) or \n(rate(mongodb_op_counters_total{service_name=~\"$service_name\",environment=~\"$environment\",cluster=~\"$cluster\"}[$interval]) and on (service_name) group by (service_name) (mongodb_mongod_replset_my_state{environment=~\"$environment\",cluster=~\"$cluster\",set=~\"$replication_set\"})) or \n(irate(mongodb_op_counters_total{service_name=~\"$service_name\",environment=~\"$environment\",cluster=~\"$cluster\"}[5m]) and on (service_name) group by (service_name) (mongodb_mongod_replset_my_state{environment=~\"$environment\",cluster=~\"$cluster\",set=~\"$replication_set\"})))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "$service_name - Document Operations",
   "type": "timeseries",
   "description": "Documents inserted/updated/deleted or returned per sec",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 71 },
   "repeat": "service_name",
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (service_name,state) ((rate(mongodb_mongod_metrics_document_total{service_name=~\"$service_name\",environment=~\"$environment\",cluster=~\"$cluster\"}[$interval]) and on (service_name) group by (service_name) (mongodb_mongod_replset_my_state{environment=~\"$environment\",cluster=~\"$cluster\",set=~\"$replication_set\"})) or \n(irate(mongodb_mongod_metrics_document_total{service_name=~\"$service_name\",environment=~\"$environment\",cluster=~\"$cluster\"}[5m]) and on (service_name) group by (service_name) (mongodb_mongod_replset_my_state{environment=~\"$environment\",cluster=~\"$cluster\",set=~\"$replication_set\"})))\n",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "$service_name - Queued Operations",
   "type": "timeseries",
   "description": "The number of operations that are currently queued and waiting for a lock",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 79 },
   "repeat": "service_name",
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (service_name,type) ((max_over_time(mongodb_mongod_global_lock_current_queue{service_name=~\"$service_name\",environment=~\"$environment\",cluster=~\"$cluster\"}[$interval]) and on (service_name) group by (service_name) (mongodb_mongod_replset_my_state{environment=~\"$environment\",cluster=~\"$cluster\",set=~\"$replication_set\"})) or (max_over_time(mongodb_mongod_global_lock_current_queue{service_name=~\"$service_name\",environment=~\"$environment\",cluster=~\"$cluster\"}[5m]) and on (service_name) group by (service_name) (mongodb_mongod_replset_my_state{environment=~\"$environment\",cluster=~\"$cluster\",set=~\"$replication_set\"})))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 } },
  {
   "title": "$service_name - Used Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 88 },
   "repeat": "service_name",
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "avg by (service_name,type) ((max_over_time(mongodb_memory{service_name=~\"$service_name\",environment=~\"$environment\",cluster=~\"$cluster\"}[$interval]) and on (service_name) group by (service_name) (mongodb_mongod_replset_my_state{environment=~\"$environment\",cluster=~\"$cluster\",set=~\"$replication_set\"})) or\n(max_over_time(mongodb_memory{service_name=~\"$service_name\",environment=~\"$environment\",cluster=~\"$cluster\"}[5m]) and on (service_name) group by (service_name) (mongodb_mongod_replset_my_state{environment=~\"$environment\",cluster=~\"$cluster\",set=~\"$replication_set\"})))",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}