{
 "title": "MongoDB Collections Overview",
 "tags": [
  "Percona",
  "MongoDB"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values({__name__=~\"mongodb_up\"}, environment)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(mongodb_up{environment=~\"$environment\"},cluster)"
    }
   },
   {
    "name": "replication_set",
    "label": "Replication Set",
    "query": {
     "query": "label_values(mongodb_mongod_replset_my_state{cluster=~\"$cluster\"}, set)"
    }
   },
   {
    "name": "node_name",
    "label": "Node Name",
    "query": {
     "query": "label_values(mongodb_mongod_replset_my_state{environment=~\"$environment\",cluster=~\"$cluster\",set=~\"$replication_set\"}, node_name)"
    }
   },
   {
    "name": "service_name",
    "label": "MongoDB Node",
    "query": {
     "query": "label_values(mongodb_mongod_replset_my_state{environment=~\"$environment\",cluster=~\"$cluster\",node_name=~\"$node_name\",set=~\"$replication_set\"}, service_name)"
    }
   },
   {
    "name": "database",
    "label": "Database",
    "query": {
     "query": "label_values(mongodb_top_commands_count{cluster=~\"$cluster\",service_name=~\"$service_name\"}, database)"
    }
   },
   {
    "name": "collection",
    "query": {
     "query": "label_values(mongodb_top_commands_count{database=~\"$database\"}, collection)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Datasize", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Top 5 Databases By Size",
   "type": "timeseries",
   "description": "Provides the names and sizes of the 5 largest databases in an instance/cluster. Data showing only from Primary node in replica set.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by(database) (topk(5, mongodb_dbstats_dataSize{cluster=~\"$cluster\", rs_nm=~\"$replication_set\", service_name=~\"$service_name\"}))",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "Collections in Database ($database)",
   "type": "stat",
   "description": "Provides the number of collections in the selected databases",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(mongodb_top_commands_time{database=~\"$database\",service_name=~\"$service_name\"})"
    }
   ]
  },
  {
   "title": "Indexes in Database ($database)",
   "type": "stat",
   "description": "Provides the number of indexes in the selected databases",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mongodb_dbstats_indexes{database=~\"$database\",service_name=~\"$service_name\"})"
    }
   ]
  },
  {
   "title": "Avg Object Size in Database ($database)",
   "type": "timeseries",
   "description": "Average size of each document in bytes. dataSize divided by number of documents",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (database)(mongodb_dbstats_avgObjSize{ service_name=~\"$service_name\", database=~\"$database\"})",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "Index Size in Database ($database)",
   "type": "timeseries",
   "description": "Total size of all indexes in a given database",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (database)(mongodb_dbstats_indexSize{database=~\"$database\", service_name=~\"$service_name\"})",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "Data Size for Database ($database)",
   "type": "timeseries",
   "description": "Total size of uncompressed data in a database in bytes. May be larger than storageSize due to WT compression. ",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (database)(mongodb_dbstats_dataSize{database=~\"$database\",service_name=~\"$service_name\"})",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "Instance Level",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Top 5 Hottest Collections by Read  (Total)",
   "type": "table",
   "description": "Show summary information on the top 5 collections that are most frequently read.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk (5,sum by (database, collection) (mongodb_top_queries_count{database =~ \"$database\",service_name=~\"$service_name\"}))"
    }
   ]
  },
  {
   "title": "Top 5 Hottest Collections by Write (Total)",
   "type": "table",
   "description": "Show summary information on the top 5 collections that are most frequently written to (insert, update, delete, etc.).",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(5, sum by (database, collection) (mongodb_top_insert_count{database =~ \"$database\", service_name=~\"$service_name\"}) + sum by (database, collection) (mongodb_top_remove_count{database =~ \"$database\", service_name=~\"$service_name\"}) + sum by (database, collection) (mongodb_top_update_count{database =~ \"$database\", service_name=~\"$service_name\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 5 Hottest Collections by Read (Rate)",
   "type": "bargauge",
   "description": "Show the 5 collections that are most frequently read.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "ops/s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, sum by (environment, cluster, database, collection) (rate(mongodb_top_queries_count{database =~ \"$database\", service_name=~\"$service_name\"}[$__rate_interval])))",
     "legendFormat": "{{ database }}.{{ collection }}"
    }
   ]
  },
  {
   "title": "Top 5 Hottest Collections by Write (Rate)",
   "type": "bargauge",
   "description": "Show the 5 collections that are most frequently written to (insert, update, delete, etc.).",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "ops/s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, sum by (environment, cluster, database, collection) (rate(mongodb_top_insert_count{database =~ \"$database\", service_name=~\"$service_name\"}[$__rate_interval]) + rate(mongodb_top_remove_count{database =~ \"$database\", service_name=~\"$service_name\"}[$__rate_interval]) + rate(mongodb_top_update_count{database =~ \"$database\", service_name=~\"$service_name\"}[$__rate_interval])))",
     "legendFormat": "{{ database }}.{{ collection }}"
    }
   ]
  },
  {
   "title": "Database Level",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Collections statistics  for $database (rate)",
   "type": "timeseries",
   "description": "Provides information on the rate of activity against the database then breaks down into activity type over the selected time period",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(sum by (database) (mongodb_top_commands_count{database=~\"$database\",service_name=~\"$service_name\"}[$interval]))",
     "legendFormat": "Commands - {{database}}"
    },
    {
     "expr": "rate(sum by (database) (mongodb_top_insert_count {database=~\"$database\",service_name=~\"$service_name\"}[$interval]))",
     "legendFormat": "Insert - {{database}}"
    },
    {
     "expr": "rate(sum by (database) (mongodb_top_update_count {database=~\"$database\", service_name=~\"$service_name\"}[$interval]))",
     "legendFormat": "Update - {{database}}"
    },
    {
     "expr": "rate(sum by (database) (mongodb_top_remove_count {database=~\"$database\", service_name=~\"$service_name\"}[$interval]))",
     "legendFormat": "Remove - {{database}}"
    },
    {
     "expr": "rate(sum by (database) (mongodb_top_getmore_count {database=~\"$database\",service_name=~\"$service_name\"}[$interval]))",
     "legendFormat": "Getmore - {{database}}"
    },
    {
     "expr": "rate(sum by (database) (mongodb_top_queries_count {environment=~\"$environment\", cluster=~\"$cluster\", rs_nm=~\"$replication_set\", database=~\"$database\", service_name=~\"$service_name\"}[$interval]))",
     "legendFormat": "Queries - {{database}}"
    }
   ]
  },
  {
   "title": "Collections statistics  for $database (summary)",
   "type": "timeseries",
   "description": "Provides summary information on the activity running against the database then breaks down into activity type over the selected time period",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (database) (mongodb_top_commands_count {environment=~\"$environment\", cluster=~\"$cluster\", rs_nm=~\"$replication_set\", database=~\"$database\", service_name=~\"$service_name\"}[$interval])",
     "legendFormat": "Commands - {{database}}"
    },
    {
     "expr": "sum by (database) (mongodb_top_insert_count {environment=~\"$environment\", cluster=~\"$cluster\", rs_nm=~\"$replication_set\", database=~\"$database\", service_name=~\"$service_name\"}[$interval])",
     "legendFormat": "Insert - {{database}}"
    },
    {
     "expr": "sum by (database) (mongodb_top_update_count {environment=~\"$environment\", cluster=~\"$cluster\", rs_nm=~\"$replication_set\", database=~\"$database\", service_name=~\"$service_name\"}[$interval])",
     "legendFormat": "Update - {{database}}"
    },
    {
     "expr": "sum by (database) (mongodb_top_remove_count {environment=~\"$environment\", cluster=~\"$cluster\", rs_nm=~\"$replication_set\", database=~\"$database\", service_name=~\"$service_name\"}[$interval])",
     "legendFormat": "Remove - {{database}}"
    },
    {
     "expr": "sum by (database) (mongodb_top_getmore_count {environment=~\"$environment\", cluster=~\"$cluster\", rs_nm=~\"$replication_set\", database=~\"$database\", service_name=~\"$service_name\"}[$interval])",
     "legendFormat": "Getmore - {{database}}"
    },
    {
     "expr": "sum by (database) (mongodb_top_queries_count {environment=~\"$environment\", cluster=~\"$cluster\", rs_nm=~\"$replication_set\", database=~\"$database\", service_name=~\"$service_name\"}[$interval])",
     "legendFormat": "Queries - {{database}}"
    }
   ]
  },
  {
   "title": "Collections statistics  $database",
   "type": "table",
   "description": "Provides totals for each activity type hitting a database for collections",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 68 },
   "repeat": "database",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (collection) (mongodb_top_queries_count {environment=~\"$environment\", cluster=~\"$cluster\", rs_nm=~\"$replication_set\", database=~\"$database\", service_name=~\"$service_name\"})"
    },
    {
     "expr": "sum by (collection) (mongodb_top_insert_count {environment=~\"$environment\", cluster=~\"$cluster\", rs_nm=~\"$replication_set\", database=~\"$database\", service_name=~\"$service_name\"})"
    },
    {
     "expr": "sum by (collection) (mongodb_top_remove_count {environment=~\"$environment\", cluster=~\"$cluster\", rs_nm=~\"$replication_set\", database=~\"$database\", service_name=~\"$service_name\"})"
    },
    {
     "expr": "sum by (collection) (mongodb_top_update_count{environment=~\"$environment\", cluster=~\"$cluster\", rs_nm=~\"$replication_set\", database=~\"$database\", service_name=~\"$service_name\"})"
    },
    {
     "expr": "sum by (collection) (mongodb_top_getmore_count {environment=~\"$environment\", cluster=~\"$cluster\", rs_nm=~\"$replication_set\", database=~\"$database\", service_name=~\"$service_name\"})"
    }
   ]
  }
 ]
}