{
 "title": "MongoDB Unused Indexes",
 "tags": [
  "Percona",
  "MongoDB"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values({__name__=~\"mongodb_up\"}, environment)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(mongodb_up{environment=~\"$environment\"},cluster)"
    }
   },
   {
    "name": "replication_set",
    "label": "Replication Set",
    "query": {
     "query": "label_values(mongodb_mongod_replset_my_state{cluster=~\"$cluster\"}, set)"
    }
   },
   {
    "name": "node_name",
    "label": "Node Name",
    "query": {
     "query": "label_values(mongodb_mongod_replset_my_state{environment=~\"$environment\",cluster=~\"$cluster\",set=~\"$replication_set\"}, node_name)"
    }
   },
   {
    "name": "service_name",
    "label": "MongoDB Node",
    "query": {
     "query": "label_values(mongodb_mongod_replset_my_state{environment=~\"$environment\",cluster=~\"$cluster\",node_name=~\"$node_name\",set=~\"$replication_set\"}, service_name)"
    }
   },
   {
    "name": "database",
    "label": "Database",
    "query": {
     "query": "label_values(mongodb_indexstats_accesses_ops{cluster=~\"$cluster\",service_name=~\"$service_name\",environment=~\"$environment\",node_name=~\"$node_name\"}, database)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "About Unused Indexes",
   "type": "text",
   "description": "Indexes with zero accesses since the last mongod restart are candidates for review. The indexstats collector must be enabled on the MongoDB exporter. Index usage is recorded only on the node that executes the query, so review all replica set members before dropping an index.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "<p>This dashboard lists MongoDB indexes with <b>zero accesses</b> since the last <code>mongod</code> service restart. These indexes are candidates for dropping after validation with your application team.</p><p><b>Requirements:</b> enable the <code>indexstats</code> collector on the MongoDB exporter. On replica sets, check every member before dropping an index because usage is recorded only on the node that runs the query.</p>"
   }
  },
  {
   "title": "Instance Uptime",
   "type": "stat",
   "description": "Minimum uptime across the selected MongoDB node(s) (time since the most recent restart).",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min((mongodb_instance_uptime_seconds{environment=~\"$environment\", cluster=~\"$cluster\", service_name=~\"$service_name\", node_name=~\"$node_name\"} and on (service_name) group by (service_name) (mongodb_mongod_replset_my_state{environment=~\"$environment\",cluster=~\"$cluster\",node_name=~\"$node_name\",set=~\"$replication_set\"}))) / 86400"
    }
   ]
  },
  {
   "title": "Unused Indexes",
   "type": "stat",
   "description": "Number of indexes with zero accesses since the last mongod restart. The default _id_ index is excluded.",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(avg by (cluster, collection, database, key_name, service_name, node_name) ((mongodb_indexstats_accesses_ops{environment=~\"$environment\", cluster=~\"$cluster\", service_name=~\"$service_name\", database=~\"$database\", node_name=~\"$node_name\", key_name!=\"_id_\"} and on (service_name) group by (service_name) (mongodb_mongod_replset_my_state{environment=~\"$environment\",cluster=~\"$cluster\",node_name=~\"$node_name\",set=~\"$replication_set\"}))) == 0)"
    }
   ]
  },
  {
   "title": "Indexes Monitored",
   "type": "stat",
   "description": "Total number of indexes reported by the indexstats collector for the selected filters.",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(avg by (cluster, collection, database, key_name, service_name, node_name) ((mongodb_indexstats_accesses_ops{environment=~\"$environment\", cluster=~\"$cluster\", service_name=~\"$service_name\", database=~\"$database\", node_name=~\"$node_name\", key_name!=\"_id_\"} and on (service_name) group by (service_name) (mongodb_mongod_replset_my_state{environment=~\"$environment\",cluster=~\"$cluster\",node_name=~\"$node_name\",set=~\"$replication_set\"}))))"
    }
   ]
  },
  { "title": "Unused Index Candidates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Unused Indexes by Collection",
   "type": "table",
   "description": "Indexes with zero accesses since the last mongod restart. Review with your application team before dropping any index.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by (cluster, collection, database, key_name, service_name, node_name) ((mongodb_indexstats_accesses_ops{environment=~\"$environment\", cluster=~\"$cluster\", service_name=~\"$service_name\", database=~\"$database\", node_name=~\"$node_name\", key_name!=\"_id_\"} and on (service_name) group by (service_name) (mongodb_mongod_replset_my_state{environment=~\"$environment\",cluster=~\"$cluster\",node_name=~\"$node_name\",set=~\"$replication_set\"}))) == 0"
    }
   ]
  },
  { "title": "Index Access Activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Index Accesses Since Restart",
   "type": "timeseries",
   "description": "Index access count since the last mongod restart. Flat lines at zero indicate unused indexes.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (cluster, database, collection, key_name, service_name, node_name) ((mongodb_indexstats_accesses_ops{environment=~\"$environment\", cluster=~\"$cluster\", service_name=~\"$service_name\", database=~\"$database\", node_name=~\"$node_name\", key_name!=\"_id_\"} and on (service_name) group by (service_name) (mongodb_mongod_replset_my_state{environment=~\"$environment\",cluster=~\"$cluster\",node_name=~\"$node_name\",set=~\"$replication_set\"})))",
     "legendFormat": "{{cluster}} | {{service_name}} | {{node_name}} | {{database}}.{{collection}} | {{key_name}}"
    }
   ]
  },
  {
   "title": "Least Used Indexes",
   "type": "table",
   "description": "Indexes with the lowest access counts since restart. Useful for spotting rarely used indexes that are not yet at zero.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "bottomk(20, avg by (cluster, database, collection, key_name, service_name, node_name) ((mongodb_indexstats_accesses_ops{environment=~\"$environment\", cluster=~\"$cluster\", service_name=~\"$service_name\", database=~\"$database\", node_name=~\"$node_name\", key_name!=\"_id_\"} and on (service_name) group by (service_name) (mongodb_mongod_replset_my_state{environment=~\"$environment\",cluster=~\"$cluster\",node_name=~\"$node_name\",set=~\"$replication_set\"}))))"
    }
   ]
  }
 ]
}