#!/bin/bash
#
# Change password for default admin user in PMM

if grafana cli --config=/etc/grafana/grafana.ini --homepath /usr/share/grafana admin reset-admin-password "$1"; then
    echo "Admin password successfully reset."
    echo "logger=administration t=$(date -u +"%Y-%m-%dT%H:%M:%S.%N"Z) level=info msg=\"Admin password has been reset.\"" >> /srv/logs/grafana.log
else
    echo "logger=administration t=$(date -u +"%Y-%m-%dT%H:%M:%S.%N"Z) level=error msg=\"Failed to reset admin password.\"" >> /srv/logs/grafana.log
    exit 1
fi
