# Grafana data source configuration for ClickHouse
# This should be added to your Grafana provisioning/datasources directory

apiVersion: 1

datasources:
  # https://github.com/grafana/clickhouse-datasource?tab=readme-ov-file#with-a-configuration-file
  - name: ClickHouse-Logs
    uid: clickhouse-logs
    orgId: 1
    version: 2
    type: grafana-clickhouse-datasource
    jsonData:
      defaultDatabase: pmm
      defaultTable: metrics  
      username: ${PMM_CLICKHOUSE_USER}
      port: ${PMM_CLICKHOUSE_PORT}
      host: ${PMM_CLICKHOUSE_HOST}
      tlsSkipVerify: false
      logs:
        defaultDatabase: otel
        defaultTable: logs
        otelEnabled: true
    secureJsonData:
      password: ${PMM_CLICKHOUSE_PASSWORD}
