# Grafana contact points configuration (modern alerting)
# This should be added to your Grafana provisioning/alerting directory

apiVersion: 1

contactPoints:
  - orgId: 1
    name: email-log-alerts
    receivers:
      - uid: email-log-alerts-receiver
        type: email
        settings:
          addresses: "admin@yourcompany.com;security@yourcompany.com"
          subject: "PMM Log Alert: {{ .GroupLabels.alertname }}"
          message: |
            PMM Security Alert
            
            Alert: {{ .GroupLabels.alertname }}
            Severity: {{ .GroupLabels.severity }}
            Team: {{ .GroupLabels.team }}
            Status: {{ .Status }}
            
            Alert Details:
            {{ range .Alerts }}
            - Description: {{ .Annotations.description }}
            - Summary: {{ .Annotations.summary }}
            - Alert Time: {{ .StartsAt }}
            {{ if .Labels.service }}  - Service: {{ .Labels.service }}{{ end }}
            {{ if .Labels.message }}  - Message: {{ .Labels.message }}{{ end }}
            {{ if .Labels.user }}  - User: {{ .Labels.user }}{{ end }}
            
            {{ end }}
            Please investigate this security event immediately.
            
            Generated by PMM OpenTelemetry Logging System
        disableResolveMessage: false
