# Grafana contact points configuration (modern alerting)
# This should be added to your Grafana provisioning/alerting directory

apiVersion: 1

contactPoints:
  - orgId: 1
    name: email-log-alerts
    receivers:
      - uid: email-log-alerts-receiver
        type: email
        settings:
          # Multiple addresses can be specified, separated by semicolons
          addresses: "security@yourcompany.com"
          subject: "PMM Log Alert: {{ .GroupLabels.alertname }}"
          message: |
            PMM Security Alert
            
            Alert: {{ .GroupLabels.alertname }}
            Status: {{ .Status }}
            
            Alert Details:
            {{ range .Alerts }}
            - Summary: {{ .Annotations.summary }}
            - Description: {{ .Annotations.description }}
            - Severity: {{ .Labels.severity }}
            - Team: {{ .Labels.team }}
            - Service: {{ .Labels.service }}
            - Alert Time: {{ .StartsAt }}
            {{ if .Labels.message }}  - Log message: {{ .Labels.message }}{{ end }}
            {{ if .Labels.user }}  - User: {{ .Labels.user }}{{ end }}
            
            {{ end }}
            Please investigate this security event immediately.
            
            Generated by PMM OpenTelemetry Logging System
        # We don't want to resolve the message automatically, as it is not relevant for this type of alert
        disableResolveMessage: true
