// Code generated by go-swagger; DO NOT EDIT.

package gmodels

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// AlertManagerNotReady alert manager not ready
//
// swagger:model AlertManagerNotReady
type AlertManagerNotReady interface{}
