// Code generated by go-swagger; DO NOT EDIT.

package gmodels

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// DataRowValues data row values
//
// swagger:model DataRowValues
type DataRowValues []interface{}

// Validate validates this data row values
func (m DataRowValues) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this data row values based on context it is used
func (m DataRowValues) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
