# This is the top-level configuration file for mockery.
disable-version-string: True
with-expecter: False
resolve-type-alias: False
issue-845-fix: True
inpackage: True
dir: "{{.InterfaceDir}}"
filename: "mock_{{ .InterfaceName | snakecase }}_test.go"
mockname: "mock{{ .InterfaceName | camelcase | firstUpper }}"
packages:
  github.com/percona/pmm/agent/agentlocal:
    interfaces:
      client:
      supervisor:
  github.com/percona/pmm/agent/client:
    interfaces:
      connectionChecker:
      serviceInfoBroker:
      supervisor:
  github.com/percona/pmm/agent/versioner:
    interfaces:
      ExecFunctions:
        config:
          mockname: "Mock{{ .InterfaceName | camelcase | firstUpper }}"
