
* Exporters

** mysqld_exporter

#+begin-table: mysqld-exporter collector-flag
+mysqld-exporter.collector-flag+

=======================================================  ==============  ===================================================================================   
Name                                                     MySQL Version   Description
=======================================================  ==============  ===================================================================================   
collect.auto_increment.columns                           5.1             Collect auto_increment columns and max values from information_schema.
collect.binlog_size                                      5.1             Collect the current size of all registered binlog files
collect.engine_innodb_status                             5.1             Collect from SHOW ENGINE INNODB STATUS.
collect.engine_tokudb_status                             5.6             Collect from SHOW ENGINE TOKUDB STATUS.
collect.global_status                                    5.1             Collect from SHOW GLOBAL STATUS (Enabled by default)
collect.global_variables                                 5.1             Collect from SHOW GLOBAL VARIABLES (Enabled by default)
collect.info_schema.clientstats                          5.5             If running with userstat=1, set to true to collect client statistics.
collect.info_schema.innodb_metrics                       5.6             Collect metrics from information_schema.innodb_metrics.
collect.info_schema.innodb_tablespaces                   5.7             Collect metrics from information_schema.innodb_sys_tablespaces.
collect.info_schema.processlist                          5.1             Collect thread state counts from information_schema.processlist.
collect.info_schema.processlist.min_time                 5.1             Minimum time a thread must be in each state to be counted. (default: 0)
collect.info_schema.query_response_time                  5.5             Collect query response time distribution if query_response_time_stats is ON.
collect.info_schema.tables                               5.1             Collect metrics from information_schema.tables (Enabled by default)
collect.info_schema.tables.databases                     5.1             The list of databases to collect table stats for, or '`*`' for all.
collect.info_schema.tablestats                           5.1             If running with userstat=1, set to true to collect table statistics.
collect.info_schema.userstats                            5.1             If running with userstat=1, set to true to collect user statistics.
collect.perf_schema.eventsstatements                     5.6             Collect metrics from performance_schema.events_statements_summary_by_digest.
collect.perf_schema.eventsstatements.digest_text_limit   5.6             Maximum length of the normalized statement text. (default: 120)
collect.perf_schema.eventsstatements.limit               5.6             Limit the number of events statements digests by response time. (default: 250)
collect.perf_schema.eventsstatements.timelimit           5.6             Limit how old the 'last_seen' events statements can be, in seconds. (default: 86400)
collect.perf_schema.eventswaits                          5.5             Collect metrics from performance_schema.events_waits_summary_global_by_event_name.
collect.perf_schema.file_events                          5.6             Collect metrics from performance_schema.file_summary_by_event_name.
collect.perf_schema.file_instances                       5.5             Collect metrics from performance_schema.file_summary_by_instance.
collect.perf_schema.indexiowaits                         5.6             Collect metrics from performance_schema.table_io_waits_summary_by_index_usage.
collect.perf_schema.tableiowaits                         5.6             Collect metrics from performance_schema.table_io_waits_summary_by_table.
collect.perf_schema.tablelocks                           5.6             Collect metrics from performance_schema.table_lock_waits_summary_by_table.
collect.slave_status                                     5.1             Collect from SHOW SLAVE STATUS (Enabled by default)
collect.heartbeat                                        5.1             Collect from [heartbeat](#heartbeat).
collect.heartbeat.database                               5.1             Database from where to collect heartbeat data. (default: heartbeat)
collect.heartbeat.table                                  5.1             Table from where to collect heartbeat data. (default: heartbeat)
=======================================================  ==============  ===================================================================================   

#+end-table
#+begin-table: mysqld-exporter general-flag
+mysqld-exporter.general-flag+

===========================================  =================================================================================================
Name                                         Description
===========================================  =================================================================================================
config.my-cnf                                Path to .my.cnf file to read MySQL credentials from. (default: `~/.my.cnf`)
log.level                                    Logging verbosity (default: info)
log_slow_filter                              Add a log_slow_filter to avoid exessive MySQL slow logging.  NOTE: Not supported by Oracle MySQL.
web.listen-address                           Address to listen on for web interface and telemetry.
web.telemetry-path                           Path under which to expose metrics.
version                                      Print the version information.
===========================================  =================================================================================================

#+end-table

** node_exporter

#+begin-table: node_exporter flag
+node-exporter.flag+

=============  =================  ====================================================================================================================      
Name           Enaled by Default  Description 
=============  =================  ====================================================================================================================      
conntrack      Yes                Shows conntrack statistics (does nothing if no `/proc/sys/net/netfilter/` present). 
diskstats      Yes                Disk I/O statistics from `/proc/diskstats`. 
edac           Yes                Error detection and correction statistics. 
entropy        Yes                Available entropy. 
filefd         Yes                File descriptor statistics from `/proc/sys/fs/file-nr`. 
filesystem     Yes                Filesystem statistics, such as disk space used. , Dragonfly, FreeBSD, Linux, OpenBSD
hwmon          Yes                Hardware monitoring and sensor data from `/sys/class/hwmon/`. 
infiniband     Yes                Network statistics specific to InfiniBand configurations. 
loadavg        Yes                Load average. , Dragonfly, FreeBSD, Linux, NetBSD, OpenBSD, Solaris
mdadm          Yes                Statistics about devices in `/proc/mdstat` (does nothing if no `/proc/mdstat` present). 
meminfo        Yes                Memory statistics. , Dragonfly, FreeBSD, Linux
netdev         Yes                Network interface statistics such as bytes transferred. , Dragonfly, FreeBSD, Linux, OpenBSD
netstat        Yes                Network statistics from `/proc/net/netstat`. This is the same information as `netstat -s`. 
sockstat       Yes                Various statistics from `/proc/net/sockstat`. 
stat           Yes                Various statistics from `/proc/stat`. This includes CPU usage, boot time, forks and interrupts. 
textfile       Yes                Statistics read from local disk. The `--collector.textfile.directory` flag must be set. 
time           Yes                The current system time. 
uname          Yes                System information as provided by the uname system call. 
vmstat         Yes                Statistics from `/proc/vmstat`. 
wifi           Yes                WiFi device and station statistics. 
zfs            Yes                [ZFS](http://open-zfs.org/) performance statistics.
bonding        No                 The number of configured and active slaves of Linux bonding interfaces. 
buddyinfo      No                 Statistics of memory fragments as reported by /proc/buddyinfo. 
drbd           No                 Distributed Replicated Block Device statistics 
interrupts     No                 Detailed interrupts statistics. , OpenBSD
ipvs           No                 IPVS status from `/proc/net/ip_vs` and stats from `/proc/net/ip_vs_stats`. 
ksmd           No                 Kernel and system statistics from `/sys/kernel/mm/ksm`. 
logind         No                 Session counts from [logind](http://www.freedesktop.org/wiki/Software/systemd/logind/). 
meminfo\_numa  No                 Memory statistics from `/proc/meminfo_numa`. 
mountstats     No                 Filesystem statistics from `/proc/self/mountstats`. Exposes detailed NFS client statistics. 
nfs            No                 NFS client statistics from `/proc/net/rpc/nfs`. This is the same information as `nfsstat -c`. 
runit          No                 Service status from [runit](http://smarden.org/runit/). 
supervisord    No                 Service status from [supervisord](http://supervisord.org/).
systemd        No                 Service and system status from [systemd](http://www.freedesktop.org/wiki/Software/systemd/). 
tcpstat        No                 TCP connection status information from `/proc/net/tcp` and `/proc/net/tcp6`. (Warning: the current version has 
                                  potential performance issues in high load situations.) 
gmond          Deprecated         Statistics from Ganglia
megacli        Deprecated         RAID statistics from MegaCLI
ntp            Deprecated         Time drift from an NTP server
=============  =================  ====================================================================================================================      

#+end-table

** mongodb_exporter
#+begin-table: mongodb_exporter flag
+mongodb-exporter.flag+


===========================================  =================================================================================================
Name                                         Description
===========================================  =================================================================================================
-collect.collection                          Enable collection of Collection metrics
-collect.database                            Enable collection of Database metrics
-groups.enabled string                       Comma-separated list of groups to use, 
                                             (default "asserts,durability,background_flushing,connections,extra_info,global_lock,
                                             index_counters,network,op_counters,op_counters_repl,memory,locks,metrics")
-mongodb.max-connections int                 Max number of pooled connections to the database. (default 1)
-mongodb.tls                                 Enable tls connection with mongo server
-mongodb.tls-ca string                       Path to PEM file that contains the CAs that are trusted for server connections.
                                             If provided: MongoDB servers connecting to should present a certificate signed by one of this 
                                             CAs.
                                             If not provided: System default CAs are used.
-mongodb.tls-cert string                     Path to PEM file that contains the certificate (and optionally also the decrypted private key in 
                                             PEM format). This should include the whole certificate chain.
                                             If provided: The connection will be opened via TLS to the MongoDB server.
-mongodb.tls-disable-hostname-validation     Do hostname validation for server connection.
-mongodb.tls-private-key string              Path to PEM file that contains the decrypted private key 
                                             (if not contained in mongodb.tls-cert file).
-mongodb.uri string                          MongoDB URI, 
                                             format: [mongodb://][user:pass@]host1[:port1][,host2[:port2],...][/database][?options] 
                                             (default "mongodb://localhost:27017")
-version                                     Print version information and exit.
-web.auth-file string                        Path to YAML file with server_user, server_password options for http basic auth 
                                             (overrides HTTP_AUTH env var).
-web.listen-address string                   Address to listen on for web interface and telemetry. (default ":9216")
-web.metrics-path string                     Path under which to expose metrics. (default "/metrics")
-web.ssl-cert-file string                    Path to SSL certificate file.
-web.ssl-key-file string                     Path to SSL key file.
===========================================  =================================================================================================

#+end-table

** proxysql_exporter

#+begin-table: proxysql_exporter collector-flag
+proxysql-exporter.collector-flag+

==============================  ==========================================================
Name                            Description
==============================  ==========================================================
collect.mysql_connection_pool   Collect from stats_mysql_connection_pool.
collect.mysql_status            Collect from stats_mysql_global (SHOW MYSQL STATUS).
==============================  ==========================================================

#+end-table
#+begin-table: proxysql_exporter general-flag
+proxysql-exporter.general-flag+

==============================  ==========================================================
Name                            Description
==============================  ==========================================================
log.format                      Set the log target and format. 
                                Example: "logger:syslog?appname=bob&local=7" or 
                                "logger:stdout?json=true" (default "logger:stderr")
log.level                       Only log messages with the given severity or above. 
                                Valid levels: [debug, info, warn, error, fatal]
version                         Print version information and exit.
web.auth-file                   Path to YAML file with server_user, server_password 
                                options for http basic auth (overrides HTTP_AUTH env var).
web.listen-address              Address to listen on for web interface and telemetry. 
                                (default ":42004")
web.ssl-cert-file               Path to SSL certificate file.
web.ssl-key-file                Path to SSL key file.
web.telemetry-path              Path under which to expose metrics. (default "/metrics")
==============================  ==========================================================


#+end-table
