doc-check-images:   ## Check if all images are used in documentation
	@documentation/resources/bin/check-images.sh

doc-remove-images:  ## Remove unused images from documentation
	@ACTION=remove documentation/resources/bin/check-images.sh
