---
name: API Tests Static

on:
  pull_request:
    paths:
      - '.github/workflows/main.yml'
      - '.github/actions/setup-go-release/**'
      - "api/**"
      - "api-tests/**"
      - "utils/**"
      - "go.*"
      - "!**/*.md"

permissions:
  contents: read

env:
  GOPRIVATE: 'github.com/percona,github.com/Percona-Lab'

jobs:
  check:
    name: Static checks
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}/api-tests

    steps:
      - name: Check out code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup Go release
        uses: ./.github/actions/setup-go-release

      - name: Check files are formatted and no source code changes
        run: |
          make format
          go mod tidy -v
          git status
          git diff --exit-code

      - name: Run debug commands on failure
        if: ${{ failure() }}
        run: |
          env | sort
          go env | sort
          git status

  build:
    name: Build
    runs-on: ubuntu-latest
    continue-on-error: false
    defaults:
      run:
        working-directory: ${{ github.workspace }}/api-tests

    steps:
      - name: Check out code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup Go release
        uses: ./.github/actions/setup-go-release

      - name: Build PMM Agent
        run: make init
