name: 'API Tests'

on:
  # NOTE: no action on `push` and `pull_request` since the API tests need to be run
  # against a container that has the latest changes from your code. Therefore, the
  # PMM_SERVER_IMAGE should either be the one from your feature build or the local
  # devcontainer. One more scenario is when we want to run the API tests on dev-latest
  # to see if the tests are in a good shape.
  # That said, this workflow is mostly a convenience if you prefer Github to Jenkins.
  # https://github.com/Percona-Lab/jenkins-pipelines/blob/master/pmm/pmm3-api-tests.groovy

  workflow_dispatch:
    inputs:
      PMM_SERVER_IMAGE:
        description: "PMM Server image version"
        default: "ghcr.io/percona/pmm:3-dev-container"
        required: true
        type: string

  workflow_call:
    inputs:
      BRANCH:
        description: "The branch to pull API tests from"
        default: "v3"
        required: true
        type: string      
      PMM_SERVER_IMAGE:
        description: "PMM Server image version"
        default: "ghcr.io/percona/pmm:3-dev-container"
        required: true
        type: string

permissions:
  contents: read

jobs:
  test:
    name: Tests
    runs-on: ubuntu-22.04
    env:
      PMM_URL: https://admin:admin@127.0.0.1
      BRANCH: ${{ github.event.inputs.BRANCH || 'v3' }}
      PMM_SERVER_IMAGE: ${{ github.event.inputs.PMM_SERVER_IMAGE }}

    steps:
      - name: Check out code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ env.BRANCH }}        

      - name: Login to docker.io registry
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Run PMM Server
        run: |
          cat <<-EOF > compose.yml
          services:
            pmm-server:
              image: ${{ env.PMM_SERVER_IMAGE }}
              container_name: pmm-server
              environment:
                - PMM_DEBUG=1
                - PMM_DEV_PERCONA_PLATFORM_ADDRESS=https://check-dev.percona.com
              ports:
                - 443:8443
              volumes:
                - pmm-data:/srv
                - ./managed/testdata/checks:/srv/checks
          volumes:
            pmm-data:
              name: pmm-data
          EOF

          # Run it and wait until it's healthy
          docker compose -f compose.yml up -d --wait --wait-timeout=100

      - name: Build the test image
        shell: bash
        run: |
          echo "Make sure to set the context to the root of the repository."
          docker buildx build -f api-tests/Dockerfile -t percona/pmm-api-tests .

      - name: Run compose up for test DBs
        shell: bash
        run: |
          pushd api-tests
          docker compose up test_db # no daemon mode
          popd

      - name: Check connectivity to PMM Server
        shell: bash
        run: curl -kf ${{env.PMM_URL}}/ping

      - name: Run API tests
        shell: bash
        run: |
          docker run \
            -e PMM_SERVER_URL=${{env.PMM_URL}} \
            -e PMM_RUN_UPDATE_TEST=0 \
            -e PMM_RUN_ADVISOR_TESTS=0 \
            -e PMM_SERVER_INSECURE_TLS=1 \
            --name pmm-api-tests \
            --network host \
            percona/pmm-api-tests

      - name: Get PMM logs
        if: ${{ failure() }}
        run: curl -k ${{env.PMM_URL}}/logs.zip --output ${{ github.workspace }}/logs.zip || true

      - name: Upload the logs on failure
        if: ${{ failure() }}
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: "logs.zip"
          path: ${{ github.workspace }}/logs.zip

      - name: Run debug commands on failure
        if: ${{ failure() }}
        run: |
          echo "----- ENVIRONMENT VARIABLES -----"
          env | sort
