---
name: 'API Tests'

on:
  # NOTE: no action on `push` and `pull_request` since the API tests need to be run
  # against a container that has the latest changes from your code. Therefore, the
  # PMM_SERVER_IMAGE should either be the one from your feature build or the local
  # devcontainer. One more scenario is when we want to run the API tests on dev-latest
  # to see if the tests are in a good shape.
  # That said, this workflow is mostly a convenience if you prefer Github to Jenkins.
  # https://github.com/Percona-Lab/jenkins-pipelines/blob/master/pmm/pmm3-api-tests.groovy

  workflow_dispatch:
    inputs:
      PMM_SERVER_IMAGE:
        description: "PMM Server image version"
        default: "ghcr.io/percona/pmm:3-dev-container"
        required: true
        type: string

  workflow_call:
    inputs:
      BRANCH:
        description: "The branch to pull API tests from"
        default: "main"
        required: true
        type: string
      PMM_SERVER_IMAGE:
        description: "PMM Server image version"
        default: "ghcr.io/percona/pmm:3-dev-container"
        required: true
        type: string

permissions:
  contents: read

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    env:
      PMM_URL: https://admin:admin@127.0.0.1
      BRANCH: ${{ github.event.inputs.BRANCH || 'main' }}
      PMM_SERVER_IMAGE: ${{ github.event.inputs.PMM_SERVER_IMAGE }}

    steps:
      - name: Check out code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ref: ${{ env.BRANCH }}

      - name: Login to docker.io registry
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Run PMM Server
        run: |
          cat <<-EOF > compose.yml
          services:
            pmm-server:
              image: ${{ env.PMM_SERVER_IMAGE }}
              container_name: pmm-server
              environment:
                - PMM_DEBUG=1
              ports:
                - 443:8443
              volumes:
                - pmm-data:/srv
                - ./managed/testdata/checks:/srv/checks
          volumes:
            pmm-data:
              name: pmm-data
          EOF

          # Run it and wait until it's healthy
          docker compose -f compose.yml up -d --wait --wait-timeout=100

      - name: Build the test image
        shell: bash
        run: |
          make docker-build-image

      - name: Run compose up for test DBs
        shell: bash
        run: |
          pushd api-tests
          docker compose up test_db # no daemon mode
          popd

      - name: Check connectivity to PMM Server
        shell: bash
        run: curl -kf ${{env.PMM_URL}}/ping

      - name: Run API tests
        shell: bash
        run: |
          PMM_SERVER_URL=${{env.PMM_URL}} make docker-run-tests

      - name: Get PMM logs
        if: ${{ failure() }}
        run: curl -k ${{env.PMM_URL}}/logs.zip --output ${{ github.workspace }}/logs.zip || true

      - name: Upload the logs on failure
        if: ${{ failure() }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: "logs.zip"
          path: ${{ github.workspace }}/logs.zip

      - name: Run debug commands on failure
        if: ${{ failure() }}
        run: |
          echo "----- ENVIRONMENT VARIABLES -----"
          env | sort
