---
name: API

on:
  pull_request:
    paths:
      - '.github/workflows/api.yml'
      - '.github/actions/setup-go-release/**'
      - "api/**"
      - "go.*"
      - "!**/*.md"

permissions:
  contents: read

jobs:
  check:
    name: Static checks
    runs-on: ubuntu-latest
    continue-on-error: false
    defaults:
      run:
        working-directory: ${{ github.workspace }}/api

    steps:
      - name: Check out code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup Go release
        uses: ./.github/actions/setup-go-release

      - name: Check files formatting
        run: |
          make gen
          git status
          git diff --exit-code

      - name: Check API compatibility descriptors
        run: |
          # log if descriptors changed, useful for "update descriptors" PRs
          make descriptors
          git diff --exit-code

      - name: Run API linter
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if out=$(go tool buf lint -v .); code="$?"; test "$code" -eq 0; then
            echo "$out"
            exit 0
          fi

          echo "API linter exited with code: $code"
          echo "$out"
          ## buf uses exit code 100 for linter warnings
          if [ "$code" -ne 100 ] || ${{ github.event.pull_request == null }}; then
            exit $code
          fi

          # One may need to suppress passing to reviewdog because of https://github.com/reviewdog/reviewdog/issues/1696
          echo "$out" | go tool reviewdog -f=buf -reporter=github-pr-review -fail-level=error

      - name: Run debug commands on failure
        if: ${{ failure() }}
        run: |
          env | sort
          git status

  test:
    name: Tests
    runs-on: ubuntu-latest
    continue-on-error: false
    defaults:
      run:
        working-directory: ${{ github.workspace }}/api

    steps:
      - name: Check out code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup Go release
        uses: ./.github/actions/setup-go-release

      - name: Test
        run: make test

      - name: Run debug commands on failure
        if: ${{ failure() }}
        run: |
          env | sort
          go env | sort
          git status
