name: merge-gatekeeper CI

on:
  pull_request:

jobs:
  merge:
    runs-on: ubuntu-22.04
    steps:
      - name: Run Merge Gatekeeper
        uses: percona-platform/merge-gatekeeper@v1.0.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          interval: 45
          timeout: 1200