name: merge-gatekeeper CI

on:
  push:
    branches:
      - main
      - release-*
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*

jobs:
  merge:
    runs-on: ubuntu-22.04
    steps:
        - name: Set GO_VERSION environment variable
          run: |
            go version
            echo "GO_VERSION=$(go version)" >> $GITHUB_ENV