---
name: Cleanup Go caches
on:
  schedule:
    # run every Saturday
    - cron: "0 12 * * 6"

permissions:
  contents: read

jobs:
  clean:
    name: Clean caches
    timeout-minutes: 5

    continue-on-error: false
    runs-on: ubuntu-latest

    env:
      GOFLAGS: -v -mod=readonly

    steps:
      - name: Configure git for private modules
        env:
          ROBOT_TOKEN: ${{ secrets.ROBOT_TOKEN }}
        run: echo "machine github.com login percona-robot password ${{ secrets.ROBOT_TOKEN }}" > $HOME/.netrc

      - name: Check out code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup Go release
        uses: ./.github/actions/setup-go-release

      - name: Clean Go modules cache
        run: go clean -modcache

      - name: Clean Go build cache
        run: go clean -cache
