---
name: GH Actions

on:
  pull_request:
    paths:
      - '.github/workflows/*.yml'

jobs:
  lint:
    name: Workflows checks
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Run actionlint
        uses: reviewdog/action-actionlint@6fb7acc99f4a1008869fa8a0f09cfca740837d9d # v1.72.0
        with:
          github_token: ${{ secrets.ROBOT_TOKEN || secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          fail_level: error
          cache: false
