name: Linkspector
on:
  pull_request:
    paths:
      - "documentation/**"
  workflow_dispatch:
    inputs:
      ref:
        description: "Git ref (branch, tag, or SHA) to check links in."
        required: false
        default: ""

permissions:
  contents: read

jobs:
  check-links:
    name: linkspector
    runs-on: ubuntu-22.04
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - name: Check out code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.event.inputs.ref || github.ref }}

      - name: Run linkspector
        uses: umbrelladocs/action-linkspector@652f85bc57bb1e7d4327260decc10aa68f7694c3 # v1.4.0
        with:
          github_token: ${{ secrets.ROBOT_TOKEN || secrets.GITHUB_TOKEN }}
          reporter: ${{ github.event_name == 'pull_request' && 'github-pr-review' || 'github-check' }}
          fail_level: error
          filter_mode: nofilter
          config_file: documentation/.linkspector.yml
