name: Merge Gatekeeper

on:
  pull_request_target:

permissions:
  checks: read
  statuses: read
  packages: read

jobs:
  merge-gatekeeper:
    name: Merge Gatekeeper
    runs-on: ubuntu-latest
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Merge Gatekeeper
        uses: docker://ghcr.io/percona/pmm/merge-gatekeeper:2.0
        with:
          self: Merge Gatekeeper
          token: ${{ secrets.GITHUB_TOKEN }}
          interval: 45
          timeout: 1200
          ignored: "linkspector"
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
