---
name: 'Percona Intelligence'
on:
  pull_request:
    paths:
      - 'managed/data/alerting-templates/**'
      - 'managed/data/advisors/**'
      - 'managed/data/checks/**'

permissions:
  contents: read

env:
  GONOPROXY: 'github.com/percona,github.com/Percona-Lab'
  GONOSUMDB: 'github.com/percona,github.com/Percona-Lab'
  GOPRIVATE: 'github.com/percona,github.com/Percona-Lab'

jobs:
  validate:
    name: Validate PI files
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Set up Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: ${{ github.workspace }}/go.mod
      - name: Validate PI files
        run: make -C managed pi-validate
