name: 'Percona Intelligence'
on:
  push:
    branches:
      - v3
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*
    paths:
      - 'managed/data/alerting-templates/**'
      - 'managed/data/advisors/**'
      - 'managed/data/checks/**'
  pull_request:
    paths:
      - 'managed/data/alerting-templates/**'
      - 'managed/data/advisors/**'
      - 'managed/data/checks/**'

permissions:
  contents: read

jobs:
  validate:
    name: Validate PI files
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - name: Check out code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Set up Go
        uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        with:
          go-version-file: ${{ github.workspace }}/go.mod
      - name: Validate PI files
        run: make -C managed pi-validate
