name: QAN

on:
  push:
    branches:
      - main
      - v3
      - pmm-*
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*
    paths-ignore:
      - "documentation/**"

  pull_request:
    paths-ignore:
      - "admin/**"
      - "agent/**"
      - "api-tests/**"
      - "docs/**"
      - "documentation/**"
      - "managed/**"
      - "update/**"
      - "vmproxy/**"
      - "ui/**"

permissions:
  contents: read

jobs:
  test:
    name: Tests
    runs-on: ubuntu-22.04

    defaults:
      run:
        working-directory: ${{ github.workspace }}/qan-api2

    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Set up Go
        uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        with:
          go-version-file: ${{ github.workspace }}/go.mod
          cache: false

      - name: Enable Go build cache
        uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
        with:
          path: ~/.cache/go-build
          key: ${{ runner.os }}-go-build-${{ github.ref }}-${{ hashFiles('**') }}
          restore-keys: |
            ${{ runner.os }}-go-build-${{ github.ref }}-
            ${{ runner.os }}-go-build-

      - name: Enable Go modules cache
        uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-modules-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-modules-

      - name: Download Go modules
        run: go mod download -x

      - name: Build and install
        run: make install

      - name: Initialize CI environment
        run: make test-env-up

      - name: Run Tests
        run: |
          make test-race
          make test-cover

      - name: Run debug commands on failure
        if: ${{ failure() }}
        run: |
          env | sort
          go env | sort
          git status
