---
name: SBOM

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*

permissions:
  contents: read

jobs:
  sbom:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Create SBOM for PMM
        uses: anchore/sbom-action@3ad7283483fc7af8ff2b4ea19663c2d5ca935e26 # v0.24.2
        with:
          file: go.mod
          artifact-name: pmm.spdx.json

      - name: Publish SBOM for PMM
        uses: anchore/sbom-action/publish-sbom@3ad7283483fc7af8ff2b4ea19663c2d5ca935e26 # v0.24.2
        with:
          sbom-artifact-match: ".*\\.spdx\\.json$"

  vmproxy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Create SBOM for vmproxy
        uses: anchore/sbom-action@3ad7283483fc7af8ff2b4ea19663c2d5ca935e26 # v0.24.2
        with:
          path: ./vmproxy
          artifact-name: vmproxy.spdx.json

      - name: Publish SBOM for vmproxy
        uses: anchore/sbom-action/publish-sbom@3ad7283483fc7af8ff2b4ea19663c2d5ca935e26 # v0.24.2
        with:
          sbom-artifact-match: ".*\\.spdx\\.json$"
