name: SBOM

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*

permissions:
  contents: read

jobs:
  sbom:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Create SBOM for PMM
        uses: anchore/sbom-action@28d71544de8eaf1b958d335707167c5f783590ad # v0.22.2
        with:
          file: go.mod
          artifact-name: pmm.spdx.json

      - name: Publish SBOM for PMM
        uses: anchore/sbom-action/publish-sbom@28d71544de8eaf1b958d335707167c5f783590ad # v0.22.2
        with:
          sbom-artifact-match: ".*\\.spdx\\.json$"

  vmproxy:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Create SBOM for vmproxy
        uses: anchore/sbom-action@28d71544de8eaf1b958d335707167c5f783590ad # v0.22.2
        with:
          path: ./vmproxy
          artifact-name: vmproxy.spdx.json

      - name: Publish SBOM for vmproxy
        uses: anchore/sbom-action/publish-sbom@28d71544de8eaf1b958d335707167c5f783590ad # v0.22.2
        with:
          sbom-artifact-match: ".*\\.spdx\\.json$"
