name: SBOM

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*

jobs:
  sbom:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: Create SBOM for PMM
        uses: anchore/sbom-action@fbfd9c6c189226748411491745178e0c2017392d # v0.20.10
        with:
          file: go.mod
          artifact-name: pmm.spdx.json

      - name: Publish SBOM for PMM
        uses: anchore/sbom-action/publish-sbom@fbfd9c6c189226748411491745178e0c2017392d # v0.20.10
        with:
          sbom-artifact-match: ".*\\.spdx\\.json$"

  vmproxy:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: Create SBOM for vmproxy
        uses: anchore/sbom-action@fbfd9c6c189226748411491745178e0c2017392d # v0.20.10
        with:
          path: ./vmproxy
          artifact-name: vmproxy.spdx.json

      - name: Publish SBOM for vmproxy
        uses: anchore/sbom-action/publish-sbom@fbfd9c6c189226748411491745178e0c2017392d # v0.20.10
        with:
          sbom-artifact-match: ".*\\.spdx\\.json$"
