name: UI

on:
  push:
    branches:
      - main
      - pmm-*
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*
    paths-ignore:
      - "documentation/**"
      - "dashboards/**"

  pull_request:
    paths-ignore:
      - "admin/**"
      - "agent/**"
      - "api-tests/**"
      - "dev/docs/**"
      - "documentation/**"
      - "dashboards/**"
      - "managed/**"
      - "qan-api2/**"
      - "vmproxy/**"
      - "update/**"

permissions:
  contents: read

jobs:
  ci:
    name: CI
    runs-on: ubuntu-22.04

    defaults:
      run:
        working-directory: ${{ github.workspace }}/ui

    steps:
      - name: Check out code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup nodejs
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version-file: ui/.nvmrc
          cache: yarn
          cache-dependency-path: ui/yarn.lock

      - name: Run lint
        run: make lint

      - name: Run unit tests
        run: make test

      - name: Build application
        run: make build
