---
name: VM Proxy

on:
  pull_request:
    paths:
      - '.github/workflows/vmproxy.yml'
      - '.github/actions/setup-go-release/**'
      - "version/**"
      - "vmproxy/**"
      - 'go.*'
      - '!**/*.md'

permissions:
  contents: read

env:
  GOPRIVATE: 'github.com/percona,github.com/Percona-Lab'

jobs:
  check:
    name: Static checks
    runs-on: ubuntu-latest
    continue-on-error: false
    defaults:
      run:
        working-directory: ${{ github.workspace }}/vmproxy

    steps:
      - name: Check out code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup Go release
        uses: ./.github/actions/setup-go-release

      - name: Check files formatting
        run: |
          make format
          git status
          git diff --exit-code

      - name: Run debug commands on failure
        if: ${{ failure() }}
        run: |
          env | sort
          git status

  build:
    name: Build
    runs-on: ubuntu-latest
    continue-on-error: false
    defaults:
      run:
        working-directory: ${{ github.workspace }}/vmproxy

    steps:
      - name: Check out code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup Go release
        uses: ./.github/actions/setup-go-release

      - name: Build VMProxy
        run: make release

  test:
    name: Tests
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ github.workspace }}/vmproxy

    steps:
      - name: Check out code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup Go release
        uses: ./.github/actions/setup-go-release

      - name: Run tests
        run: make test-cover

      - name: Upload coverage results
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          files: cover.out
          flags: vmproxy
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Run debug commands on failure
        if: ${{ failure() }}
        run: |
          env | sort
          go env | sort
          git status
